GetStream/stream-chat-android

- library/src/main/java/com/getstream/sdk/chat/model/User.java
- library/src/main/java/com/getstream/sdk/chat/rest/controller/RestController.java
- library/src/main/java/com/getstream/sdk/chat/rest/controller/RetrofitClient.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/StreamChat.java
- library/src/main/java/com/getstream/sdk/chat/view/activity/ChatActivity.java
move all optional fields for user to extra data and "promote" name and image fields to avoid hitting the HashMap each time
> Fix set user data

- library/src/main/java/com/getstream/sdk/chat/model/Channel.java
- library/src/main/java/com/getstream/sdk/chat/rest/controller/APIService.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
Remove hard-coded channel type. Fixes #25
> remove hard-coded messaging type

- .idea/misc.xml
- library/src/main/java/com/getstream/sdk/chat/model/Channel.java
- library/src/main/java/com/getstream/sdk/chat/rest/codecs/GsonConverter.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
- library/src/main/java/com/getstream/sdk/chat/rest/interfaces/FlagCallback.java
- library/src/main/java/com/getstream/sdk/chat/rest/response/ErrorGsonAdapter.java
- library/src/main/java/com/getstream/sdk/chat/rest/response/ErrorResponse.java
- library/src/main/java/com/getstream/sdk/chat/view/Dialog/MoreActionDialog.java
- library/src/main/res/values/styles.xml
- sample/src/main/AndroidManifest.xml
- sample/src/main/res/values/styles.xml
> copy and flag for message

- library/src/main/java/com/getstream/sdk/chat/model/Channel.java
- library/src/main/java/com/getstream/sdk/chat/rest/controller/APIService.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java
> Fix Thread Issue
(When received new message(regular) on Thread mode, it was added to thread messages after loadMore)
> fix thread loadMore issue.

- library/src/main/java/com/getstream/sdk/chat/adapter/AttachmentViewHolderMedia.java
- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/utils/Utils.java
- library/src/main/java/com/getstream/sdk/chat/view/activity/AttachmentActivity.java
When add(delete) reaction, the layout has an issue.
- Before:
- After:
> fix readstateview layout issue

- library/src/main/java/com/getstream/sdk/chat/enums/MessageInputType.java
- library/src/main/java/com/getstream/sdk/chat/utils/MessageInputClient.java
- library/src/main/java/com/getstream/sdk/chat/utils/Utils.java
> fix mention issue.

- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemAdapter.java
- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/view/Dialog/MoreActionDialog.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageListViewStyle.java
- library/src/main/res/values/attrs.xml
- **Check threadable and reactionable from channel config**
> check thread and reaction from channel config

- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/model/Config.java
- library/src/main/java/com/getstream/sdk/chat/view/Dialog/MoreActionDialog.java
> renamed reactions and replies to reactionEnabled and repliesEnabled

- library/src/main/java/com/getstream/sdk/chat/view/ReadStateView.java
> fix readStateColor and textStyle

- docs/ChannelList.md
- library/src/main/java/com/getstream/sdk/chat/rest/request/SendMessageRequest.java
- library/src/main/res/values/dimens.xml
- sample/src/main/java/io/getstream/chat/example/BaseApplication.java
- sample/src/main/java/io/getstream/chat/example/MainActivity.java
- **Fix Video attachment from Camera**
> fix video uploading from camera

- library/src/main/java/com/getstream/sdk/chat/utils/MessageInputClient.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java
> fix take photo from camera.

- build.gradle
- library/build.gradle
- Added dependency for jUnit5 gradle plugin in application gradle
- Apply jUnit5 gradle plugin in library module gradle
- Added dependencies for *jupiter* in library module gradle module
> setup gradle tests

- library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModelFactory.java
- sample/src/main/java/io/getstream/chat/example/ChannelActivity.java
- sample/src/main/java/io/getstream/chat/example/CustomChannelListViewModel.java
- sample/src/main/java/io/getstream/chat/example/CustomChannelViewModel.java
Make it easy to subclass our viewModel and make changes the the behaviour
In the future we should have an interface for the viewModels so you can use the components and write your own viewModel
> Viewmodel customizability

- library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelListViewModel.java
More traditional listener setup for #92
> add the ability to set a listener for channel query success and failure

- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java
- Invalid commands don’t show an error message
> invalid command

- library/src/main/java/com/getstream/sdk/chat/rest/Message.java
- library/src/main/java/com/getstream/sdk/chat/utils/MessageListItemLiveData.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java
- Fixed Reply Count displaying issue on main channel.
- Hidden Reply count of Thread Top message
> fix issue for  thread message count displying

- library/build.gradle
- library/src/main/java/com/getstream/sdk/chat/utils/StringUtility.java
- gradle update of Markwon(4.1.1)
- fix  newline issues
> fix newline

- library/src/main/java/com/getstream/sdk/chat/utils/Utils.java
- Fixed Toast background issue.
> fix toast background issue.

- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java
- prevent to send null gif from keyboard
> privent to send giphy from null

- library/src/main/java/com/getstream/sdk/chat/rest/response/ChannelStateGsonAdapter.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java
> fix loardMore issue

- library/src/main/java/com/getstream/sdk/chat/adapter/ReactionDialogAdapter.java
- library/src/main/java/com/getstream/sdk/chat/model/Channel.java
- library/src/main/java/com/getstream/sdk/chat/model/Reaction.java
- library/src/main/java/com/getstream/sdk/chat/rest/adapter/ReactionGsonAdapter.java
- library/src/main/java/com/getstream/sdk/chat/rest/codecs/GsonConverter.java
- library/src/main/java/com/getstream/sdk/chat/rest/controller/APIService.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
- library/src/main/java/com/getstream/sdk/chat/rest/request/ReactionRequest.java
- library/src/test/java/com/getstream/sdk/chat/ReactionGsonAdapterTest.java
- Cleanup Reaction type
- Add support for `extraData` for reactions
- Update some Javadocs to match the correct signature and format
> add support for reaction.extra_data + clean up some javadocs

- library/src/main/java/com/getstream/sdk/chat/model/Channel.java
- library/src/main/java/com/getstream/sdk/chat/rest/Message.java
- library/src/main/java/com/getstream/sdk/chat/rest/adapter/MessageGsonAdapter.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
- library/src/main/java/com/getstream/sdk/chat/rest/request/ChannelQueryRequest.java
- library/src/main/java/com/getstream/sdk/chat/rest/request/QueryChannelsRequest.java
- library/src/main/java/com/getstream/sdk/chat/rest/request/SendMessageRequest.java
- library/src/main/java/com/getstream/sdk/chat/storage/Storage.java
- library/src/main/java/com/getstream/sdk/chat/storage/Sync.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java
- sample/src/main/java/io/getstream/chat/example/MainActivity.java
First of many cleanups that make the low level APIs easier to use
> cleanup send message flow

- library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java
> Feature/Fixed App crashes when attachment is not sent correctly

- library/src/main/java/com/getstream/sdk/chat/model/Channel.java
- library/src/main/java/com/getstream/sdk/chat/rest/response/ChannelState.java
> countUnreadMentions

- library/src/main/java/com/getstream/sdk/chat/model/Channel.java
- library/src/main/java/com/getstream/sdk/chat/rest/controller/APIService.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
- add API method to `Client` to stop watching a channel
- add the method to `Channel` to stop watching this channel
> Feature: stop watching channel

- library/src/main/java/com/getstream/sdk/chat/model/Channel.java
- library/src/main/java/com/getstream/sdk/chat/rest/controller/APIService.java
- library/src/main/java/com/getstream/sdk/chat/rest/response/CompletableResponse.java
- library/src/main/java/com/getstream/sdk/chat/rest/storage/BaseStorage.java
- library/src/main/java/com/getstream/sdk/chat/rest/storage/StreamPublicStorage.java
- add API methods to `APIService` to delete file/image
- add abstract methods to `BaseStorage` to delete file/image
- add realization of methods to `StreamPublicStorage` to delete file/image
- add methods to `Channel` o delete file/image of this channel
> Feature: remove file/image

- library/src/main/java/com/getstream/sdk/chat/rest/request/ChannelQueryRequest.java
> expose members and watchers pagination options for query channel

- library/src/main/java/com/getstream/sdk/chat/rest/response/ChannelState.java
> Fix empty no message in channel case

- sample/build.gradle
- sample/readme.md
- sample/src/main/java/io/getstream/chat/example/MainActivity.java
Makes it easier to config custom user for testing and development.
> Add custom user config

- docs/ChannelHeader.md
- Update ReadMe for ChannelHeader
> Fix/Update ReadMe for ChannelHeader

- docs/ChannelList.md
- Update ReadMe for ChannelList
> Fix/Update ReadMe for ChannelList

- library/src/main/java/com/getstream/sdk/chat/StreamChat.java
- library/src/main/java/com/getstream/sdk/chat/rest/User.java
- removed `RuntimeException`. So it doesn't force developers to put initialisation into `Application`, making it easier to develop a POC. And not all apps actually has application, although most of them.
- replace `HashMap` with map to allow usage Kotlin builtin utility functions.
> Add StreamChat developer friendly improvements

- docs/ChannelHeader.md
- docs/MessageList.md
- added PermissionRequestListener to ChannelActivity
> Fix/Update ReadMe

- library/src/main/java/com/getstream/sdk/chat/enums/ClientErrorCode.java
- library/src/main/java/com/getstream/sdk/chat/interfaces/ClientConnectionCallback.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
- library/src/main/java/com/getstream/sdk/chat/utils/StringUtility.java
> Encode user image url

- library/src/main/java/com/getstream/sdk/chat/rest/storage/StreamPublicStorage.java
> Fix/Null check for signGlideURL

- library/src/main/java/com/getstream/sdk/chat/view/AvatarGroupView.java
> Fix/AvatarView Black Corner

- library/src/main/java/com/getstream/sdk/chat/adapter/DateSeparatorViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/rest/Message.java
- library/src/main/res/layout/stream_item_date_separator.xml
- library/src/main/res/values/strings.xml
> Fix/"0 minutes ago" for message date separator

- library/src/main/java/com/getstream/sdk/chat/rest/adapter/UserGsonAdapter.java
If user name or image is null, set empty string.
> Fix/Set Empty String  if user name or image is null

- library/src/main/java/com/getstream/sdk/chat/utils/MessageInputController.java
> Fix/Disable commands list view if there're no commands

- library/src/main/java/com/getstream/sdk/chat/rest/response/ChannelState.java
> Fix/AvatarGroupView for getOtherUsers

- library/src/main/java/com/getstream/sdk/chat/view/ChannelHeaderView.java
- library/src/main/res/values/strings.xml
> Add channel header to strings.xml

- library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
- set created by user when creating new channel
> Fix/Set created-by user when creating new channel

- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/res/values/strings.xml
- replace hardcoded reply count
- support pluralization for reply count
> Replace hardcoded reply count

- library/src/main/java/com/getstream/sdk/chat/rest/core/ChatEventHandler.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
- library/src/main/java/com/getstream/sdk/chat/rest/response/ChannelState.java
- close #273 
- fix updates of the channel for other members
- fix handling new messages
> Fix/New channel's data

- CHANGELOG.md
- library/src/main/java/com/getstream/sdk/chat/utils/MessageInputController.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java
> Feature/File upload 2.0

- library/src/main/java/com/getstream/sdk/chat/rest/adapter/MessageGsonAdapter.java
> Fix/Null check for Message

- library/src/main/java/com/getstream/sdk/chat/rest/StreamWebSocketService.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/providers/StreamWebSocketServiceProvider.java
- library/src/test/java/com/getstream/sdk/chat/StreamWebSocketServiceProviderTest.java
Use GSON to encode connect payload
> make sure JSON encoding is consistent on .connect

- library/src/main/java/com/getstream/sdk/chat/adapter/DateSeparatorViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/enums/Dates.java
- library/src/main/java/com/getstream/sdk/chat/enums/MessageInputType.java
- library/src/main/java/com/getstream/sdk/chat/rest/Message.java
- library/src/main/java/com/getstream/sdk/chat/utils/MessageInputController.java
Avoids retaining localized strings across configuration changes, otherwise these strings won't update to a different language after the user changes the default system language.
> Avoid retaining localized strings across configuration changes

- library/src/main/java/com/getstream/sdk/chat/StreamChat.java
- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/enums/Dates.java
- library/src/main/java/com/getstream/sdk/chat/rest/response/ChannelState.java
- library/src/main/java/com/getstream/sdk/chat/utils/strings/StringsProvider.java
- library/src/main/java/com/getstream/sdk/chat/utils/strings/StringsProviderImpl.java
- library/src/test/java/com/getstream/sdk/chat/rest/core/ClientTest.java
- library/src/test/java/com/getstream/sdk/chat/utils/strings/StubStringsProvider.java
- sample/src/main/java/io/getstream/chat/example/MainActivity.java
Fix: https://stream-io.atlassian.net/browse/CAS-42
> CAS-42 Remove channels view model creates, fix last message update

- library/src/main/java/com/getstream/sdk/chat/DefaultBubbleHelper.java
> Fix/Message item view corner radius When it has multi attachments

- README.md
- Result
https://github.com/GetStream/stream-chat-android/tree/update/ReadMe-reusable#setup-custom-font
> Update ReadMe for setting Custom font

- library/src/main/res/layout/stream_item_attach_media.xml
- library/src/main/res/values/strings.xml
- fix: https://stream-io.atlassian.net/secure/RapidBoard.jspa?rapidView=49&modal=detail&selectedIssue=CAS-44
> CAS-44: Giphy buttons alignment (not bottom space)

- CHANGELOG.md
- library/src/main/java/com/getstream/sdk/chat/style/FontsManagerImpl.java
- library/src/main/java/com/getstream/sdk/chat/view/ChannelListViewStyle.java
> CAS-50 Fix/Setting textStyle without custom font

- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/utils/StringUtility.java
- sample/src/main/java/io/getstream/chat/example/MainActivity.java
Add checking with regular for message list holder.
> CAS-6 Feature/parse markdown

- CHANGELOG.md
- docs/MessageList.md
- library/src/main/java/com/getstream/sdk/chat/DefaultBubbleHelper.java
- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageListViewStyle.java
- library/src/main/res/values/attrs.xml
| Properties                                            | Type                 | Default                            |
| ----------------------------------------------------- | -------------------- | ---------------------------------- |
| `app:streamAttachmentBorderColorMine`                 | color                | streamMessageBorderColorMine       |
| `app:streamAttachmentBorderColorTheirs`               | color                | streamMessageBorderColorTheirs     |
| `app:streamMessageLinkTextColorMine`            | color                | -         |
| `app:streamMessageLinkTextColorTheirs`          | color                | -         |
> Update/Attachment Attrs: Border/LinkText Colors

- library/src/main/java/com/getstream/sdk/chat/rest/core/providers/StreamWebSocketServiceProvider.java
> CAS-59 Fix/URLEncoder of Get WS URL

- README.md
- close #237 
- [Result](https://github.com/GetStream/stream-chat-android/tree/update/faq-localization#localize-the-ui-with-translations)
> Update/ReadMe: add localization to FAQ

- README.md
- update `README` about FAQ of `Localize the UI with Translations`
> update ReadMe for FAQ

- library/src/main/java/com/getstream/sdk/chat/rest/core/providers/StreamUploadStorageProvider.java
Fix problem with loading attachments.
> Fix public storage provider

- library/src/main/java/com/getstream/sdk/chat/view/ChannelHeaderView.java
- library/src/main/res/layout/stream_view_channel_header.xml
- library/src/main/res/values/dimens.xml
- update headerview layout
- fix title, header option, active badge issues.
> CAS-66 Fix/channel header UI issues

- docs/MessageInput.md
- library/src/main/java/com/getstream/sdk/chat/DefaultBubbleHelper.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java
- sample/src/main/java/io/getstream/chat/example/CustomMessageInputView.java
- Fix regression `DefaultBubbleHelper`
- Fix regression `prepareNewMessage` for pending message in `MessageInputView`
- Fix ReadMe for `CustomMessageInputView`
> Fix/Regression of DefaultBubbleHelper

- CHANGELOG.md
- README.md
- build.gradle
- library/src/main/java/com/getstream/sdk/chat/StreamChat.java
- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/navigation/ChatNavigationHandler.java
- library/src/main/java/com/getstream/sdk/chat/navigation/StreamChatNavigator.java
- library/src/main/java/com/getstream/sdk/chat/navigation/StreamChatNavigatorImpl.java
- library/src/main/java/com/getstream/sdk/chat/navigation/destinations/AppSettingsDestination.java
- library/src/main/java/com/getstream/sdk/chat/navigation/destinations/AttachmentDestination.java
- library/src/main/java/com/getstream/sdk/chat/navigation/destinations/CameraDestination.java
- library/src/main/java/com/getstream/sdk/chat/navigation/destinations/ChatDestination.java
- library/src/main/java/com/getstream/sdk/chat/navigation/destinations/WebLinkDestination.java
- library/src/main/java/com/getstream/sdk/chat/utils/PermissionChecker.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java
- sample/src/main/java/io/getstream/chat/example/BaseApplication.java
- sample/src/main/java/io/getstream/chat/example/ChannelActivity.java
- sample/src/main/java/io/getstream/chat/example/LoginActivity.java
- sample/src/main/java/io/getstream/chat/example/navigation/ChannelDestination.java
- sample/src/main/java/io/getstream/chat/example/navigation/HomeDestination.java
- sample/src/main/java/io/getstream/chat/example/navigation/LoginDestination.java
- sample/src/main/java/io/getstream/chat/example/navigation/SearchDestination.java
- sample/src/main/java/io/getstream/chat/example/search/MessageSearchActivity.java
- sample/src/main/java/io/getstream/chat/example/view/fragment/ChannelListFragment.java
- sample/src/main/java/io/getstream/chat/example/view/fragment/ProfileFragment.java
Navigation is extracted into separate module `StreamChatNavigator`. Each navigation action is extracted into particular class of `ChatDestination`.
- allows to integrate your own navigation framework in a single place without passing multiple callbacks
- has familiar [Google Navigation concepts](https://developer.android.com/guide/navigation/navigation-getting-started)
- makes it possible to test navigation
```java
Config config = new Config(this, "key");
config.navigationHandler(destination -> {
String url = "";
if (destination instanceof WebLinkDestination) {
url = ((WebLinkDestination) destination).url;
} else if (destination instanceof AttachmentDestination) {
url = ((AttachmentDestination) destination).url;
}
if (url.startsWith("https://your.domain.com")) {
// handle/change/update …
```
> Navigation and custom handler to override default navigation behviour

- library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java
Reverts changes of https://github.com/GetStream/stream-chat-android/commit/2ff9720eff4432096440f918c5865a04a045a062
> CAS-75: Disable autoscroll when list is scrolled

- sample/build.gradle
Fix release sample default hardcoded users
> Fix release sdk duplicate for sample app

- sample/src/main/AndroidManifest.xml
- sample/src/main/java/io/getstream/chat/example/CCFirebaseMessagingService.java
- sample/src/main/java/io/getstream/chat/example/LoginActivity.java
- sample/src/main/java/io/getstream/chat/example/view/fragment/ChannelListFragment.java
- sample/src/main/java/io/getstream/chat/example/view/fragment/ProfileFragment.java
Fixed crash on opening notifications
> CAS-73 Fix/Crash on opening notification

- library/build.gradle
- library/src/main/java/com/getstream/sdk/chat/rest/controller/RetrofitClient.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/ApiClientOptions.java
- library/src/test/java/com/getstream/sdk/chat/rest/RetrofitClientTest.java
- library/src/test/java/com/getstream/sdk/chat/rest/utils/TestApiClientOptions.java
- keepAlive 45 seconds
- timeout 45 seconds
- Add tests for checking timeout
> CAS-83 fix/Change okHttp settings

- CHANGELOG.md
- library/src/main/java/com/getstream/sdk/chat/adapter/BaseChannelListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/adapter/ChannelViewHolderFactory.java
- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelListViewModel.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java
Small fixes to resolve issues that blocked me during tutorial writing:
- Our docs tell you to customize the ViewModel and ViewHolder. Unfortunately, most of those methods are marked private instead of protected.
- Fixed mistakes in the documentation (on master already))
- Two way data binding for the message input makes the tutorial a lot easier to write. 
- Cleaned up viewHolderFactory code
> Tutorial fixes, first 2 bits

- CHANGELOG.md
- build.gradle
- library/src/main/java/com/getstream/sdk/chat/model/Reaction.java
- library/src/main/java/com/getstream/sdk/chat/rest/adapter/ReactionGsonAdapter.java
- sample/build.gradle
> add reaction score field

- build.gradle
- sample/build.gradle
> Update AGP and clean up build

- build.gradle
- library/build.gradle
- library/src/main/java/com/getstream/sdk/chat/rest/controller/TokenAuthInterceptor.java
- library/src/main/java/com/getstream/sdk/chat/rest/core/providers/StreamWebSocketServiceProvider.java
- library/src/main/java/com/getstream/sdk/chat/utils/Constant.java
- library/src/main/java/com/getstream/sdk/chat/utils/Utils.java
- library/src/test/java/com/getstream/sdk/chat/rest/providers/StreamWebSocketServiceProviderTest.java
- add version to header and socket json
> Update version: 3.6.8 with header

- library/build.gradle
- update client to 1.0.12 with version header
> Update version: 4.0.14. Update llc to 1.0.12

- library/build.gradle
Add Kotlin plugins to the library and Kotlin depency
> Add kotlin support

- build.gradle
- library/build.gradle
Upgrade `RedirectGlide` and `Glide` version and fix #468
> Upgrade Glide and RedirectGlide dependencies version

- CHANGELOG.md
- library/build.gradle
> Update livedata to 0.6.0.

- library/build.gradle
- library/src/main/java/com/getstream/sdk/chat/adapter/CommandsAdapter.kt
- library/src/main/java/com/getstream/sdk/chat/adapter/MentionsAdapter.kt
- library/src/main/java/com/getstream/sdk/chat/utils/MessageInputController.kt
- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.kt
- library/src/main/res/layout/stream_view_message_input.xml
Improve suggestions when user wants to use a commands or create a mention to anyone else
> Refactor commands and mentions behavior

- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItem.java
- library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemDiffCallback.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.kt
- library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
- library/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
- library/src/main/res/layout/stream_view_message_input.xml
- library/src/test/java/com/getstream/sdk/chat/Mother.kt
- library/src/test/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModelTest.kt
- sample/src/main/AndroidManifest.xml
- sample/src/main/kotlin/io/getstream/chat/sample/feature/channel/ChannelFragment.kt
This PR refactored legacy "messages thread" feature:
* Decoupled MessageListView from the data layer
* Reimplemented thread data loading logic into Kotlin
Note: Message sending logic should be further refactored in MessageInputViewModel.
> Feature / Message list: thread support

- library/src/main/java/com/getstream/sdk/chat/utils/MessageInputController.kt
- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.kt
- library/src/main/java/com/getstream/sdk/chat/view/ReplyToView.kt
- library/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
- library/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModelBinding.kt
- library/src/main/res/layout/stream_reply_to_view.xml
- library/src/main/res/layout/stream_view_message_input.xml
A new View has been created to show the message which the user wants to reply to.
This view has been added to our `MessageInputView` and it visibility is handled depending on wheter there is a message to reply to or not
> Feature ReplyTo message

- docs/ChannelList.md
- library/src/main/java/com/getstream/sdk/chat/adapter/BaseChannelListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemAdapter.java
- library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/adapter/ChannelViewHolderFactory.java
- library/src/main/java/com/getstream/sdk/chat/view/channels/ChannelListView.java
- library/src/main/java/com/getstream/sdk/chat/view/channels/ChannelListViewStyle.java
- library/src/main/java/com/getstream/sdk/chat/view/channels/ChannelsView.kt
- library/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModel.kt
- library/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModelBinding.kt
- library/src/main/res/values/ids.xml
- library/src/main/res/values/strings.xml
- library/src/test/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModelTest.kt
- sample/src/main/kotlin/io/getstream/chat/sample/feature/channels/ChannelsFragment.kt
- sample/src/main/res/layout/fragment_channels.xml
- sample/src/main/res/values/strings.xml
This PR:
* Displays empty state view when there are no channels available
Issue: https://github.com/GetStream/stream-chat-android/issues/521
> Display empty state label when there are no channels available

- library/src/main/java/com/getstream/sdk/chat/utils/MessageInputController.kt
- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.kt
- library/src/main/java/com/getstream/sdk/chat/view/PreviewMessageView.kt
- library/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
- library/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModelBinding.kt
- library/src/main/res/layout/stream_reply_to_view.xml
- library/src/main/res/layout/stream_view_message_input.xml
- library/src/test/java/com/getstream/sdk/chat/Mother.kt
- library/src/test/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModelTest.kt
- sample/src/main/kotlin/io/getstream/chat/sample/feature/channel/ChannelFragment.kt
Implement EditMessage behavior from `MessageInputView`
The coupled ViewModel has been removed from the View as well
> Feature Edit Message

- library/build.gradle
- library/src/main/java/com/getstream/sdk/chat/utils/MessageInputController.kt
- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.kt
- library/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
- library/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModelBinding.kt
- library/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
- library/src/main/res/layout/stream_view_message_input.xml
- library/src/main/res/values/strings.xml
- sample/src/main/kotlin/io/getstream/chat/sample/feature/channel/ChannelFragment.kt
Implement Reply on a Thread behavior on `MessageInputView`
Thread Mode has been handled on the sample app as well
> Reply on a thread

- .travis.yml
- CHANGELOG.md
- build.gradle
- library/src/main/java/com/getstream/sdk/chat/utils/CaptureController.java
- library/src/main/java/com/getstream/sdk/chat/utils/MessageInputController.java
- library/src/main/java/com/getstream/sdk/chat/utils/UploadManager.java
- library/src/main/java/com/getstream/sdk/chat/utils/Utils.java
- library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java
- sample/build.gradle
> Update target SDK version to 29. Update files uploading.

- library/build.gradle
- library/src/test/java/com/getstream/sdk/chat/Mother.kt
- library/src/test/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModelTest.kt
Upgrade Stream Livedata to version 0.6.7.
On this version thread support has been improved.
This version use a newer LLC version that introduced some changes on the business models, so some tests needed to be updated as well
> Upgrade Stream Livedata to 0.6.7

- library/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModel.kt
- library/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModelBinding.kt
Loading indicator was not being hidden on a `Loading.isLoading = false` event
> [Fix] Loading indicator

- library/src/main/java/com/getstream/sdk/chat/Chat.kt
- library/src/main/java/com/getstream/sdk/chat/ChatImpl.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModel.kt
- sample/src/main/kotlin/io/getstream/chat/sample/application/App.kt
- sample/src/main/kotlin/io/getstream/chat/sample/feature/channels/ChannelsFragment.kt
- sample/src/main/kotlin/io/getstream/chat/sample/feature/create_channel/CreateChannelFragment.kt
- sample/src/main/res/layout/fragment_channels.xml
- sample/src/main/res/menu/menu_channels.xml
- sample/src/main/res/navigation/main_navigation.xml
- sample/src/main/res/values/strings.xml
1. Fix log out / switch user logic:
* Add missing call to ChatClient.disconnect()
2. Implement log-out feature
Fixes: https://github.com/GetStream/stream-chat-android/issues/524
> Allow to switch user / logout

- build.gradle
- sample/build.gradle
Add Crashlytics to the sample App
> Add Crashlytics to sample app

- library/build.gradle
> Update livedata to 0.6.8

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- library/build.gradle
- sample/build.gradle
- versions.gradle
- [ x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x ] The code changes follow best practices
- [ x] Code changes are tested (add some information if not applicable)
> Create a separate file to manage libraries versions.

- sample/src/debug/kotlin/io/getstream/chat/sample/application/AppConfig.kt
Switching to old app config (apiKey and user data)
> Switch to old app config

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/getstream/sdk/chat/Dependencies.kt
- library/src/main/java/com/getstream/sdk/chat/ChatImpl.java
- library/src/main/java/com/getstream/sdk/chat/ChatSocketListener.kt
- library/src/main/java/com/getstream/sdk/chat/utils/LlcMigrationUtils.java
ChatEvent has been refactored on LLC.
Now we have a sealed class with different events. Every Event has only the required fields, so no more nullable values.
> Update ChatEvent structure

- sample/src/debug/kotlin/io/getstream/chat/sample/application/AppConfig.kt
- sample/src/main/kotlin/io/getstream/chat/sample/data/user/User.kt
- sample/src/release/kotlin/io/getstream/chat/sample/application/AppConfig.kt
> [CAS-254] Update app data

- CHANGELOG.md
- library/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModel.kt
- library/src/test/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModelTest.kt
> [CAS-255] Fix default filter

- buildSrc/src/main/kotlin/com/getstream/sdk/chat/Dependencies.kt
- sample/build.gradle
Upload Stream Livedata version
Fixes #631
> Update Stream-Livedata to version 0.7.6

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/getstream/sdk/chat/Dependencies.kt
Upgrade Offline Support Version to 0.8.2
Fix #644
> Upgrade Offline Support Version to 0.8.2

- library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java
Describe what this PR changes, why we're making the change, how it should be tested...
> Fix NPE when attachments type is null

- library/src/main/java/com/getstream/sdk/chat/utils/DataBuffer.kt
- library/src/main/java/com/getstream/sdk/chat/utils/StartStopBuffer.kt
- library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java
- library/src/test/java/com/getstream/sdk/chat/utils/StartStopBufferTest.kt
[CAS-288](https://stream-io.atlassian.net/browse/CAS-288)
Fixing typing icon. The MessageListView wasn't scrolling when it should to show this icon. 
Take a look: 
_Now it scrolls automatically_
> [CAS-288] fixing typing icon

- .editorconfig
- library/src/main/java/com/getstream/sdk/chat/utils/StartStopBuffer.kt
- library/src/test/java/com/getstream/sdk/chat/utils/StartStopBufferTest.kt
Fixing unit tests for Coroutines in `StartStopBufferTest`.
> [CAS-288] Fixing coroutines test

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/getstream/sdk/chat/Dependencies.kt
- library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java
- library/src/main/java/com/getstream/sdk/chat/adapter/viewholder/message/configurators/IndicatorConfigurator.kt
- library/src/main/java/com/getstream/sdk/chat/adapter/viewholder/message/configurators/UsernameAndDateConfigurator.kt
- library/src/main/java/com/getstream/sdk/chat/utils/LlcMigrationUtils.java
- library/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.java
Update Offline Support Version
> Update offline support version

- library/src/main/java/com/getstream/sdk/chat/utils/StartStopBuffer.kt
- library/src/main/java/com/getstream/sdk/chat/view/MessageListView.kt
- library/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputView.kt
- library/src/main/res/values/attrs.xml
- library/src/test/java/com/getstream/sdk/chat/utils/StartStopBufferTest.kt
- sample/src/main/res/layout/fragment_channel.xml
[CAS-270](https://stream-io.atlassian.net/browse/CAS-270)
StartStopBuffer wasn't working properly so the scroll wasn't working as it should. Now I'm fixing it and adding more unit tests. 
Also, this PR substitute #688
> CAS-270/fixing start top buffer

- CHANGELOG.md
- library/src/main/java/com/getstream/sdk/chat/utils/LlcMigrationUtils.java
- library/src/main/java/com/getstream/sdk/chat/utils/Primitives.kt
- library/src/main/java/com/getstream/sdk/chat/view/AvatarView.kt
- library/src/test/java/com/getstream/sdk/chat/Mother.kt
- library/src/test/java/com/getstream/sdk/chat/utils/LlcMigrationUtilsTest.kt
Previous implementation of those method didn't cover the case where the String only contained spaces
> [CAS-302] Fix methods that obtain initial of an user or Channel

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventBatchUpdate.kt
Changes for review notes according to [this PR](https://github.com/GetStream/stream-chat-android-livedata/pull/85)
> Fix review notes

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
Fix ConcurrentModificationExceptions
> Fix ConcurrentModificationExceptions

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
Fix unhandled exception when query for events
> Fix unhandled exception

- README.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-offline-README.md
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
- stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/feature/login/LoginViewModel.kt
- stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/feature/users/UsersViewModel.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/Chat.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java
- stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/viewholder/attachment/AttachmentViewHolder.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/viewholder/message/configurators/MessageTextConfigurator.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/enums/Dates.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/enums/MessageInputType.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/navigation/destinations/WebLinkDestination.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/style/TextStyle.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/utils/StringUtility.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/utils/Utils.java
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/MessageListView.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/ReadStateView.java
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/activity/AttachmentActivity.java
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/activity/AttachmentMediaActivity.java
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
unify how we get the instance, same across all 3 now.
> standardize the naming

- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/factory/ChannelsViewModelFactory.kt
Fix ChannelsViewModelFactory factory crash
> Fix ChannelsViewModelFactory factory crash

- stream-chat-android-client/src/debug/java/io/getstream/chat/android/client/di/ChatModule.kt
- stream-chat-android-client/src/release/java/io.getstream.chat.android.client.di/ChatModule.kt
Fix release version of `ChatModule` after https://github.com/GetStream/stream-chat-android/pull/773 broke it
> Fix release version of ChatModule, add reminder comments

- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/factory/ChannelsViewModelFactory.kt
Fix for requiring all parameters when calling this constructor from Java code.
> Add @JvmOverloads to ChannelsViewModelFactory constructor

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/ChannelHeaderView.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelHeaderViewModel.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelHeaderViewModelBinding.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModelBinding.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModelBinding.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModelBinding.kt
- Add ChatClient KDoc
- Add ChannelsView and ChannelsViewModel KDoc
- Add MessageInputView and MessageInputViewModel KDoc
- Add ChannelHeaderView and ChannelHeaderViewModel KDoc
- Add MessageListView and MessageListViewModel KDoc
> [CAS-349] Add KDoc comments for classes and methods used in tutorial:

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImpl.kt
> attempt at fixing #698

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
See commit messages & inline comments
> Fix some issues in ChatDomainImpl

- .github/workflows/pr-checks.yml
Use `push` event for PR Checks Workflow
> Use `push` event for PR Checks Workflow

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt
- stream-chat-android-ui-components-sample/src/main/res/layout/nav_header.xml
Utilized `AvatarView` instead of `ImageView` in navigation drawer.
> Integrate avatar view into navigation drawer

- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_channels.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/textinput/StreamMessageInputView.kt
> Compilation errors fix

- .github/workflows/pr-checks.yml
This PR adds the missing GitHub actions PR check for `ui-components` and `ui-components-sample` module.
> GitHub actions config update

- .gitignore
- Explicitly allow the files within `.idea` that we _do_ want in VCS instead of ignoring the rest one by one, this prevents us accidentally adding random files to commits
- Removes some paths that don't exist in the project anyway
> Update project level .gitignore

- stream-chat-android/src/main/java/com/getstream/sdk/chat/navigation/destinations/AttachmentDestination.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/utils/Utils.java
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/activity/AttachmentActivity.java
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/activity/AttachmentDocumentActivity.java
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputView.kt
Remove unneeded methods on `Utils` class
Fixes #842 
> Remove unneeded methods on `Utils` class

- .gitignore
- .idea/misc.xml
Apparently this file does change sometimes, for example due to plugins, and it's annoying to have to ignore it while commiting changes. We don't need it in VCS for any reason, so, it shouldn't be in the repo.
> Remove .idea/misc.xml file from repo

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QuerySort.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Extensions.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatFirebaseMessagingService.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/EventsParser.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/SocketFactory.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/entity/ReactionEntity.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/service/sync/OfflineSyncFirebaseMessagingService.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDomainTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDomainTest2.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/utils/TestDataHelper.kt
- stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/application/ChatInitializer.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragmentViewModel.kt
- stream-chat-android-ui-components-sample/src/main/res/values/styles.xml
- stream-chat-android-ui-components/src/main/res/values/strings.xml
- stream-chat-android/src/main/java/com/getstream/sdk/chat/Chat.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/ChatSocketListener.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/ChatUI.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/activity/AttachmentActivity.java
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelHeaderViewModel.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
Clean up some compilation warnings and lint errors, fix some typos
> General code cleanup

- .github/workflows/pr-checks.yml
This PR changes our github actions so we only run unit tests for the debug build type.
> Adding unit tests only for debug build type

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ErrorCall.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/call/CoroutineCall.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/call/ZipCall.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/core/internal/coroutines/DispatcherProvider.kt
- stream-chat-android-offline/build.gradle
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/extensions/LiveDataExtensions.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/service/sync/OfflineSyncFirebaseMessagingService.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/MarkAllReadImpl.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/utils/TestCoroutineExtension.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/utils/TestCoroutineRule.kt
- stream-chat-android-ui-components/build.gradle
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarView.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/ImageLoader.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/utils/StartStopBuffer.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/AvatarView.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messageinput/AttachmentsController.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/CreateChannelViewModel.kt
- stream-chat-android/src/test/java/com/getstream/sdk/chat/utils/TestCoroutineExtension.kt
Moved DispatcherProvider to `stream-chat-android-core` module
> Move DispatcherProvider to core module

- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelHeaderViewModel.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModelBinding.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModelBinding.kt
- stream-chat-android/src/test/java/com/getstream/sdk/chat/viewmodel/ChannelHeaderViewModelTest.kt
- stream-chat-android/src/test/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModelTest.kt
- stream-chat-android/src/test/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModelTest.kt
- stream-chat-android/src/test/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModelTest.kt
> [CAS-443] Remove direct invoke into our vm

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/ClientStateService.kt
- stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/application/ChatInitializer.kt
- stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/feature/user_login/UserLoginViewModel.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/user_login/UserLoginViewModel.kt
Update the FSM to handle status where the 
> [CAS-393] Allow set user without network connection

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/BaseMessageItemViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewHolderFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewType.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewTypeMapper.kt
[CAS-410](https://stream-io.atlassian.net/browse/CAS-410?atlOrigin=eyJpIjoiNWUwYTVlZjc3Njc1NGNhNzlhYzdkYmI5NTIzMTg1OGUiLCJwIjoiaiJ9)
Message list item view holder factory
> Message list item view holder factory

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt
This small PR integrates channels header with navigation drawer:
- A click on avatar view in channels header opens the drawer
> Open navigation drawer on avatar click in channels header

- CHANGELOG.md
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryHelper.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java
- stream-chat-android/src/main/java/com/getstream/sdk/chat/utils/LlcMigrationUtils.java
ChannelList weren't using the proper data to be rendered when it was loaded from offline storage
> [CAS-445] Hotfix/channels view render offline

- .github/workflows/app-distribute.yml
Add workflow to distribute ui components sample app
> Add workflow to distribute ui components sample app

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
< Jira issue link, if applicable >
Update Version pattern used by our API Headers
> [CAS-449] Update Version pattern used by our API Headers

- settings.gradle
- stream-chat-android-docs/build.gradle
- stream-chat-android-docs/src/main/AndroidManifest.xml
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ClientAndUsers.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/StaticInstances.kt
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ClientAndUsers.kt
Create a new module to keep documentation up-to-date
> Create a new module to keep documentation up-to-date

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ClientAndUsers.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Messages.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ClientAndUsers.kt
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Messages.kt
[Messages](https://getstream.io/chat/docs/send_message/?language=kotlin) code-snippet from web documentation. 
> Messages Code Snippet Docs

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ClientAndUsers.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ClientAndUsers.kt
* Add a nested class for each section
* Add KDoc link to the docs web page
> Restructure Client & Users Code Snippet Docs

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Messages.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Messages.kt
* Add a nested class for each section
* Add KDoc link to the docs web page
> Restructure Messages Code Snippet Docs

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mentions/MentionsListViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchResultListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchViewModelBinding.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/EndlessScrollListener.kt
https://stream-io.atlassian.net/browse/CAS-369
Integrate the new search result list with the backend APIs, adding paging to the results.
Displaying errors and loading state will be on a separate PR.
> Integrate search API in SearchViewModel

- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_delete_channel_dialog_fragment.xml
- stream-chat-android-ui-components-sample/src/main/res/values/strings.xml
> Fix the wording / name of a couple string resources

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/ListenerContainerImpl.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/Extensions.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/ListenerContainerImpl.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/utils/ListenerDelegate.kt
- stream-chat-android/src/test/java/com/getstream/sdk/chat/utils/ListenerDelegateTest.kt
Simple cleanup PR to remove some accidentally exposed public API, and to make some utilities easier to reuse within our modules
> Util fixes

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/add/group/select_name/AddGroupChannelSelectNameViewModel.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatViewModelFactory.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/GroupChatInfoFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/users/GroupChatInfoAddUsersAdapter.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/users/GroupChatInfoAddUsersDialogFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/users/GroupChatInfoAddUsersViewModel.kt
- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_group_add_users_dialog_fragment.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_group_add_users_item.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_group_chat_info.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchResultListView.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/EndlessScrollListener.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/MessageListView.kt
This PR also adds missing channel id when creating group channel.
Creating channel without id results in a distinct channel being created (based on members) and that channel type doesn't allow to change members.
> [CAS-468] Add possibility to add users to group channel

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/ChannelInfo.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Message.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/home/ComponentBrowserHomeFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messagepreview/ComponentBrowserMessagePreviewFragment.kt
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_component_browser_message_preview.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mentions/MentionsListAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mentions/MentionsListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messagepreview/MessagePreviewView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchResultListAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchResultListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Channel.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_preview_item.xml
- stream-chat-android-ui-components/src/main/res/values/strings.xml
Updates the formatting of the sender and the message itself in `MessagePreviewView` to match the design.
<p float=left>
</p>
> Message preview formatting

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/common/Extensions.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt
Close navigation drawer when drawer item is clicked so that the drawer is closed when we go back to the home screen.
> Close navigation drawer when action item is selected

- stream-chat-android-ui-components-sample/src/main/res/layout/add_group_channel_select_name_action_layout.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/add_group_channel_select_name_member_item.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_add_group_channel_select_name.xml
Small amendments to "Name of Group Chat" screen
| --- | --- |
| ![photo_2020-12-14 11 43 37](https://user-images.githubusercontent.com/9600921/102059216-a0499b80-3e01-11eb-8420-9a6e6c13860d.jpeg) | ![photo_2020-12-14 11 41 06](https://user-images.githubusercontent.com/9600921/102058925-4b0d8a00-3e01-11eb-937f-d4741a6c189e.jpeg)|
|![photo_2020-12-14 11 43 41](https://user-images.githubusercontent.com/9600921/102059392-ebfc4500-3e01-11eb-82e9-ca1919cfe2e1.jpeg) | ![photo_2020-12-14 11 41 13](https://user-images.githubusercontent.com/9600921/102058929-4e087a80-3e01-11eb-958e-dc1fba55f7a0.jpeg) |
> Name of Group Chat screen amendments

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/GroupChatInfoFragment.kt
> Add back button click listener to GroupChatInfo header

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/User.kt
This PR fixes the display of channel avatars in component browser.
> Fix channel AvatarViews in component browser 

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoSharedGroupsFragment.kt
> Add missing binging import to ChatInfoSharedGroupsFragment

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/observable/ChatEventsObservable.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/observable/ChatEventsObservableTest.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImpl.kt
See the google doc about the 3 BIT issues
> Bit fix fork

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messagepreview/MessagePreviewView.kt
> Filter for only File attachments when displaying file names preview

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/textinput/MessageInputView.kt
- stream-chat-android-ui-components/src/main/res/values/colors.xml
A small improvement to send button animation
> Improve send button animation

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/CancelMessage.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/CreateChannelImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/DeleteMessageImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/DeleteReactionImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/EditMessageImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/GetChannelControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/GetThreadImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/GetTotalUnreadCountImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/GetUnreadChannelCountImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/HideChannelImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/KeystrokeImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/LoadMessageByIdImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/LoadNewerMessagesImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/LoadOlderMessagesImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/MarkReadImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/QueryChannelsImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/QueryChannelsLoadMoreImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/ReplayEventsForActiveChannelsImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/SendGiphyImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/SendMessageImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/SendReactionImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/ShowChannelImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/ShuffleGiphyImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/StopTypingImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/ThreadLoadMoreImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/WatchChannelImpl.kt
Some of these docs were incorrect, some of them just unnecessary.
> Remove some unnecessary documentation from use cases classes

- .github/workflows/build-and-test.yml
- stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveDataBenchmark.kt
Release tests are no different from debug tests, there's no need to run them separately. We already have another job that checks if release builds are successful.
> Run debug tests only in build and test workflow

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt
> Fix crash when updating last seen message

- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_input.xml
[CAS-229](https://stream-io.atlassian.net/browse/CAS-229)
A small fix for the DarkTheme colours. That field passed me by.
> [CAS-229] Small color fix

- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_file_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_media_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_file_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_media_attachments.xml
This PR changes the style of message list avatars (correct size, without border)
> Fix message list avatar style

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/user_login/UserLoginFragment.kt
- stream-chat-android-ui-components-sample/src/main/res/drawable/shape_bottom_navigation_background.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/add_channel_header_view.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/add_channel_user_item.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/add_group_channel_select_name_member_item.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_delete_channel_dialog_fragment.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_group_member_item.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_group_name_item.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_member_item.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_option_item.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_shared_file_item.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_stateful_option_item.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_home.xml
- stream-chat-android-ui-components/src/main/res/drawable/stream_ui_divider.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_header_view.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_item_foreground_view.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_input.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_options_view.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_messages_header_view.xml
- stream-chat-android-ui-components/src/main/res/values-night/colors.xml
- stream-chat-android-ui-components/src/main/res/values/colors.xml
- stream-chat-android-ui-components/src/main/res/values/dimens.xml
Small divider related fixes:
- Added divider to `BottomNavigationView` instead of elevation shadow
- Ensured that dividers on the login screen are of correct color
- Added divider to message input
- Add divider to message list header
| --- | --- |
| ![photo_2020-12-23 04 39 08](https://user-images.githubusercontent.com/9600921/102949232-d4474f80-44d8-11eb-9543-4e88bdad761f.jpeg)| ![photo_2020-12-23 04 39 40](https://user-images.githubusercontent.com/9600921/102949252-e1643e80-44d8-11eb-8071-d3a54a5c71ee.jpeg) |
| ![photo_2020-12-23 04 39 12](https://user-images.githubusercontent.com/9600921/102949226-d14c5f00-44d8-11eb-9ae6-ebdf9ecd3c0e.jpeg)|![photo_2020-12-23 04 41 31](https://user-images.githubusercontent.com/9600921/102949362-2b4d2480-44d9-11eb-934a-d531bd63ba1d.jpeg …
> Fix dividers

- stream-chat-android-ui-components-sample/src/main/res/drawable/shape_bottom_navigation_background.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_input.xml
Fixing some colours. 
| --- | --- |
| ![Screenshot_20201223-125820](https://user-images.githubusercontent.com/10619102/102994233-f9f74780-451e-11eb-869b-069881433e0b.png) |![Screenshot_20201223-125722](https://user-images.githubusercontent.com/10619102/102994250-024f8280-451f-11eb-8eaa-2e06fe6234e3.png) |
|![Screenshot_20201223-125825](https://user-images.githubusercontent.com/10619102/102994236-fb287480-451e-11eb-8421-8dcd248d83fe.png)  |  ![Screenshot_20201223-125726](https://user-images.githubusercontent.com/10619102/102994251-0380af80-451f-11eb-80e6-3706600e09eb.png)|
> Fixing some colours

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/attachments/media/MediaAttachmentAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/attachments/selected/SelectedMediaAttachmentAdapter.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_selected_attachment_media.xml
[CAS-482]( https://stream-io.atlassian.net/browse/CAS-482?atlOrigin=eyJpIjoiOTVjNWM3OTk4M2EyNDM3NGIwNzhjYzY4NTI4MzliYjAiLCJwIjoiaiJ9)
This PR add video support in MessageInputView by showing thumbnails
https://user-images.githubusercontent.com/11807573/103005990-24f39280-4543-11eb-9183-4bfcdda1b5d7.mov
> Video support in message input view

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/OnlyMediaAttachmentsMessagesComponentBrowserFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/PlainTextMessagesComponentBrowserFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/PlainTextWithFileAttachmentsMessagesComponentBrowserFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/PlainTextWithMediaAttachmentsMessagesComponentBrowserFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/utils/DataProvider.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/BaseMessageItemViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewHolderFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewTypeMapper.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/LinkAttachmentView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/MediaAttachmentView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/MessagePlainTextViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithFileAttachmentsViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithMediaAttachmentsViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/BackgroundDecorator.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/GravityDecorator.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/LinkAttachmentDecorator.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/ReactionsDecorator.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Attachment.kt
- stream-chat-android-ui-components/src/main/res/drawable/stream_ui_attachment_link_label_background.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_link_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_file_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_media_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_link_attachments_view.xml
> [CAS-491] Add link decorator

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/ChannelListItemAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListListenerContainer.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewHolderFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListListenerContainer.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListListenerContainerImpl.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/GiphyViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/MessagePlainTextViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyFileAttachmentsViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyMediaAttachmentsViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithFileAttachmentsViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithMediaAttachmentsViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt
General code cleanup, decreasing visibility, renaming `ListenerContainer` to `MessageListListenerContainer` as we now have multiple ones
> Clean up code around ListenerContainers

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchInputView.kt
- stream-chat-android-ui-components/src/main/res/drawable/stream_ui_shape_search_view_background.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_search_result_list_view.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_search_view.xml
- stream-chat-android-ui-components/src/main/res/values-night/colors.xml
- stream-chat-android-ui-components/src/main/res/values/colors.xml
Fixes some theming, alignment, and minor behaviour around Search
| --- | --- |
| ![Screenshot_20201229_141238](https://user-images.githubusercontent.com/12054216/103286227-28be6380-49e0-11eb-9d84-8031028ba41b.png) | ![Screenshot_20201229_141053](https://user-images.githubusercontent.com/12054216/103286175-18a68400-49e0-11eb-9fe4-13c19b53ac17.png) | 
| ![Screenshot_20201229_141246](https://user-images.githubusercontent.com/12054216/103286225-28be6380-49e0-11eb-864d-c76fce829e3b.png) | ![Screenshot_20201229_141102](https://user-images.githubusercontent.com/12054216/103286174-18a68400-49e0-11eb-81da-227596bbef2e.png) | 
| ![Screenshot_20201229_141257](https://user-images.githubusercontent.com/12054216/103286218-26f4a000-49e0-11eb-8152-3ccb232cca0e.png) | …
> Fix SearchView theming

- UNRELEASED_CHANGELOG.md
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryHelper.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/LeaveChannelImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/UseCaseHelper.kt
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/ChannelListFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/GroupChatInfoViewModel.kt
> Add leaving channel

- UNRELEASED_CHANGELOG.md
- buildSrc/src/main/kotlin/com/getstream/sdk/chat/Dependencies.kt
- stream-chat-android/build.gradle
Updates from the beta version to the RC, and hopefully a fix for #925
> AndroidX Activity and Fragment dependency updates

- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_date_divider.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_deleted.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_list_view.xml
https://stream-io.atlassian.net/browse/CAS-503
- Fixes horizontal margin for deleted messages
- Added small bottom margin to the message list according to the design
| --- | --- |
|![photo_2021-01-05 22 56 01](https://user-images.githubusercontent.com/9600921/103692692-35772480-4fa9-11eb-8f4f-9145a3a87096.jpeg) |![photo_2021-01-05 22 56 04](https://user-images.githubusercontent.com/9600921/103692685-327c3400-4fa9-11eb-97a6-c41beeab5be2.jpeg) |
> CAS-503 Fix deleted message margins

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoViewModel.kt
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat_info.xml
| With member | Without member |
| --- | --- |
|<img width="366" alt="Screenshot 2021-01-06 at 12 12 20" src="https://user-images.githubusercontent.com/17440581/103762402-84a86e00-5018-11eb-95ac-dea6a6d3d6cb.png">|<img width="365" alt="Screenshot 2021-01-06 at 12 12 44" src="https://user-images.githubusercontent.com/17440581/103762404-86723180-5018-11eb-9fdf-059dd3d054df.png">|
Multiple improvements for chat info:
- Make Chat Member nullable (can be null when the channel has only one member or when we don't have Internet connection)
- Improve building options (don't show member related options when it doesn't exist)
- Add showing loading indicator when entering the screen (we are getting channel member from the backend)
> [CAS-507] Improve chat info view model

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/actions/ChannelActionsViewModel.kt
> Improve observing members in ChannelActionsViewModel

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/images/AttachmentGallery.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/images/menu/ImagesMenuAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/images/menu/ImagesMenuDialogFragment.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_image_menu_dialog.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_attachment_image.xml
- stream-chat-android-ui-components/src/main/res/values/attrs.xml
- stream-chat-android-ui-components/src/main/res/values/dimens.xml
- stream-chat-android-ui-components/src/main/res/values/strings.xml
[CAS-419](https://stream-io.atlassian.net/browse/CAS-419)
Making a image menu for the attachment gallery. 
> [CAS-419] Attachment images menu

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoItem.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoViewHolders.kt
> [CAS-514] Change delete conversation text color to red

- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/navigation/destinations/AttachmentDestination.kt
> [CAS-519] Open html attachments

- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/ChannelListFragment.kt
> Replace hiding with deleting channel when clicking on delete option

- stream-chat-android-ui-components/src/main/res/layout/stream_ui_messages_header_view.xml
Increase back arrow icon size
| --- | --- |
|  ![photo_2021-01-08_17-53-11](https://user-images.githubusercontent.com/4047514/104042307-9e91ae80-51da-11eb-9c54-0d70e71fcf4b.jpg)  |  ![photo_2021-01-08_17-53-08](https://user-images.githubusercontent.com/4047514/104042322-a2bdcc00-51da-11eb-845c-dc7d41b43318.jpg) |
> [CAS-527] Increase back arrow icon size

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
Quick fix of channels visibility changed logic
> Channel list visibility changed fix

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messagepreview/MessagePreviewView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Channel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/String.kt
Bold mentions ignoring case
| --- | --- |
| ![photo_2021-01-08_13-07-24](https://user-images.githubusercontent.com/4047514/104013992-94f45080-51b2-11eb-8114-883a44795d17.jpg) | ![photo_2021-01-08_13-07-26](https://user-images.githubusercontent.com/4047514/104014003-9b82c800-51b2-11eb-8742-6f4e25c82b72.jpg) |
> Bold mentions ignoring case

- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_group_edit_name_view.xml
Increase button size
| --- | --- |
|  ![photo_2021-01-13_12-58-28](https://user-images.githubusercontent.com/4047514/104449801-75d53480-559f-11eb-9cd8-1d5792221469.jpg)  |  ![photo_2021-01-13_12-58-30](https://user-images.githubusercontent.com/4047514/104449812-7a015200-559f-11eb-9781-97e685ae77f8.jpg) |
> [CAS-540] Increase buttons size

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/helpers/QueryChannelsPostponeHelper.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/helpers/QueryChannelsPostponeHelperTests.kt
Handle attempts limit reached exception that is thrown if the `setUser` is not completed in time 
> [CAS-539] Handle attempts limit reached

- stream-chat-android-ui-components-sample/src/main/res/values/styles.xml
Use proper style for hint
| --- | --- |
| ![photo_2021-01-13_15-08-58](https://user-images.githubusercontent.com/4047514/104462804-4c250900-55b1-11eb-8647-b68f31fb1872.jpg)  | ![photo_2021-01-13_15-09-01](https://user-images.githubusercontent.com/4047514/104462821-50e9bd00-55b1-11eb-9a16-d4657babd366.jpg)  |
- ~[ ] Changelog updated with client-facing changes
- ~[ ] New code is covered by unit tests
> Use proper style for hint

- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/BaseMessageItemViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/AnimationUtils.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_deleted.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_file_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_media_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_file_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_media_attachments.xml
- stream-chat-android-ui-components/src/main/res/values-night/colors.xml
- stream-chat-android-ui-components/src/main/res/values/colors.xml
https://stream-io.atlassian.net/browse/CAS-521
When we navigate to a conversation from a mention the corresponding message is highlighted for 3 seconds
Can be improved:
- support for mentions in threads (not possible with our API)
- starting animation via payloads /changed state
- better error handling
https://user-images.githubusercontent.com/9600921/104461875-f48e9980-55c0-11eb-807c-46d796bdf163.mov
> [CAS-521] Highlight message with mention

- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/StorageHelper.kt
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/StringUtils.kt
- stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/utils/StringUtilsTest.kt
The correct prefix that we would like to remove is **STREAM_** and not **prefix_**
> [CAS-512] Fixing prefix

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/add/group/select_name/AddGroupChannelSelectNameFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/shared/ChatInfoSharedGroupsFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/shared/ChatInfoSharedGroupsViewHolderFactory.kt
- stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_shared_groups_item.xml
- stream-chat-android-ui-components-sample/src/main/res/values/strings.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelsView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/SimpleVerticalListDivider.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Channel.kt
> [CAS-532] Add different channel item layout for shared groups screen

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Messages.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Messages.kt
https://getstream.io/chat/docs/pinned_messages/?language=kotlin
> Add pinned messages docs

- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/factory/ChannelViewModelFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/ChannelListItemAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/ChannelListItemType.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListItemViewHolderFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/BaseMessageItemViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewHolderFactory.kt
Some updates to support integrating the new ui-components with our tutorial.
> UI component tutorial integration updates

- stream-chat-android-ui-components-sample/build.gradle
- stream-chat-android-ui-components-sample/src/debug/kotlin/io/getstream/chat/ui/sample/application/ApplicationConfigurator.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt
- stream-chat-android-ui-components-sample/src/release/kotlin/io/getstream/chat/ui/sample/application/ApplicationConfigurator.kt
Enable Flipper for the new app
> Enable Flipper for debug new components app

- stream-chat-android-sample/src/demo/kotlin/io/getstream/chat/sample/application/AppConfig.kt
- stream-chat-android-ui-components-sample/src/demo/kotlin/io/getstream/chat/ui/sample/application/AppConfig.kt
> Add QA Test Users

- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/ReactionRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/controllers/ChannelController.kt
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Messages.java
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDatabase.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/dao/ReactionDao.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/entity/ReactionEntity.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/extensions/ClientExtensions.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/ReactionRepository.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/mapper/ReactionMapper.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/SendReactionImpl.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDomainTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDomainTest2.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplInsertDomainTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplReactionsTest.kt
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListViewModelBinding.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/ReactionDialogAdapter.java
https://stream-io.atlassian.net/browse/CAS-471
> Add support for sending unique reactions

- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_thread_divider.xml
Add Background to Thread Divider
> [CAS-577] Add Background to Thread Divider

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchInputView.kt
> [CAS-580] Increase search tappable area

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Messages.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Messages.kt
https://getstream.io/chat/docs/send_reaction/?preview=1&language=kotlin
> Update reactions doc

- stream-chat-android-ui-components-sample/src/main/res/drawable/shape_circle_grey_whisper.xml
- stream-chat-android-ui-components-sample/src/main/res/drawable/shape_circle_white_snow.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/add_group_channel_member_item.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_custom_login.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/item_options.xml
- stream-chat-android-ui-components-sample/src/main/res/values/colors.xml
- stream-chat-android-ui-components-sample/src/main/res/values/styles.xml
https://stream-io.atlassian.net/browse/CAS-581
| --- | --- |
|<img width="306" alt="Screenshot 2021-01-22 at 10 06 14" src="https://user-images.githubusercontent.com/17440581/105471546-22e43700-5c9b-11eb-987f-98a9ab1f5599.png">|<img width="306" alt="Screenshot 2021-01-22 at 10 11 37" src="https://user-images.githubusercontent.com/17440581/105471551-24156400-5c9b-11eb-8628-263d7e6adab8.png">|
|<img width="306" alt="Screenshot 2021-01-22 at 10 09 32" src="https://user-images.githubusercontent.com/17440581/105471550-24156400-5c9b-11eb-8faa-3ff8b3dafd55.png">|<img width="306" alt="Screenshot 2021-01-22 at 10 11 56" src="https://user-images.githubusercontent.com/17440581/105471553-24adfa80-5c9b-11eb-9162-c81af312218c.png">|
> [CAS-581] Fix colors on select user screens

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/FootnoteDecorator.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_deleted.xml
https://stream-io.atlassian.net/browse/CAS-573
| --- | --- |
|<img width="324" alt="Screenshot 2021-01-22 at 15 08 12" src="https://user-images.githubusercontent.com/17440581/105501143-25a75200-5cc4-11eb-9fe8-cc7c0f510c3e.png">|<img width="322" alt="Screenshot 2021-01-22 at 15 07 12" src="https://user-images.githubusercontent.com/17440581/105501138-23dd8e80-5cc4-11eb-8e72-c8d96b47a0ba.png">|
> [CAS-573] Add footnote view to deleted message view holder

- README.md
- stream-chat-android-client/README.md
- stream-chat-android-offline/README.md
Removes some outdated doc examples, unnecessary things from our READMEs, especially simplifies the module level READMEs. Also fixes a bunch of links.
> Fix various things in our READMEs, remove old docs

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Reaction.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/ReactionRepository.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryFactory.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryHelper.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/mapper/ReactionMapper.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/Mother.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplInsertDomainTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplReactionsTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/ReactionRepositoryTest.kt
Remove ReactionEntity usage in ChatDomain
> [CAS-641] Isolate ReactionEntity

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/MessageReplyView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/options/MessageOptionsView.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_input.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_options_view.xml
1) Enable reply feature
2) Fix in dynamic view setup in ReplyView
> [CAS-501] Enable reply feature

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/extensions/ClientExtensions.kt
Fix Attachment Type when a video is sent
> Set proper type to video attachments

- stream-chat-android-ui-components/src/main/res/drawable/stream_ui_base_channel_list_item.xml
- stream-chat-android-ui-components/src/main/res/drawable/stream_ui_foreground_channel_list.xml
- stream-chat-android-ui-components/src/main/res/drawable/stream_ui_shape_message_options_background.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_attachment_gallery.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_attachment_options_view.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_item_foreground_view.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_input.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_options_view.xml
- stream-chat-android-ui-components/src/main/res/values/dimens.xml
https://stream-io.atlassian.net/browse/CAS-630
1. Ripple added to channel list items
2. Ripple added to attachment gallery bottom buttons (share, and photos)
3. Ripple added to message input buttons (attachment, command)
4. Fixed ripple overlapping round corners of message options and attachment options menus
~- [ ] Changelog updated with client-facing changes~
~- [ ] Comparison screenshots added for visual changes~
> CAS-630 Ripple effect

- stream-chat-android/src/main/res/layout/stream_dialog_message_moreaction.xml
- stream-chat-android/src/main/res/values/strings.xml
`Message more action dialog` hardcoded texts were updated for localizing support.
> Message more action hardcoded strings

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/common/Extensions.kt
- stream-chat-android-ui-components-sample/src/main/res/color/bottom_nav_item_color.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_home.xml
- stream-chat-android-ui-components-sample/src/main/res/values/colors.xml
- stream-chat-android-ui-components-sample/src/main/res/values/styles.xml
This PR aligns colors and text styles in bottom navigation with the design.
| --- | --- |
| ![device-2021-02-01-031717](https://user-images.githubusercontent.com/9600921/106402856-b7d5f580-643c-11eb-8eb9-1f838a30d20e.png) | ![device-2021-02-01-031609](https://user-images.githubusercontent.com/9600921/106402861-bad0e600-643c-11eb-94ef-9c6d91269ce9.png) |
| ![device-2021-02-01-031743](https://user-images.githubusercontent.com/9600921/106402851-b3a9d800-643c-11eb-9d33-a679407b54ca.png) | ![device-2021-02-01-031524](https://user-images.githubusercontent.com/9600921/106402863-bd334000-643c-11eb-80f4-c94551d21e0f.png) |
> Fix bottom navigation style

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
Just handling some warnings pointed by Android Studio. 
- Comparison screenshots added for visual changes. **no need**
> Removing warnnings from ChannelsControllerImpl

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelController.kt
> Add some missing docs, remove outdated "repo" terminology from domain

- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt
- stream-chat-android-offline/api/stream-chat-android-offline.api
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/KeystrokeImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/StopTypingImpl.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/utils/TestDataHelper.kt
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
- stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModelTest.kt
https://stream-io.atlassian.net/browse/CAS-436
> [CAS-436] Add support for typing events in threads

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/TypingIndicators.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/TypingIndicators.kt
https://getstream.io/chat/docs/android/typing_indicators/
> Update typing indicators docs

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Channels.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Channels.kt
Adds documentation snippets for https://getstream.io/chat/docs/android/slow_mode/?language=kotlin
> Add docs snippets for slow mode

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/FirebaseMessageParserImpl.kt
Fix incorrect Firabase field names
> Fix notifications

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryHelper.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/PerformanceTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplInsertDomainTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/QueryChannelsImplRepositoryTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/HideChannelImplTest.kt
https://stream-io.atlassian.net/browse/CAS-559
Changing the visibility for `RepositoryHelper.messageRepository` and creating the necessary methods
> [CAS-559] query channels repository visibility

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Channels.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Channels.kt
Lots of readability / style improvements for Channel doc snippets, including the completion of https://stream-io.atlassian.net/browse/CAS-645
> Improve Channel doc snippets

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventBatchUpdate.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryHelper.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/RepositoryHelperTests.kt
[CAS-555](https://stream-io.atlassian.net/browse/CAS-555)
> [CAS-555] Agregating metods to store channels state

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventBatchUpdate.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryHelper.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/ChatDomainEventDomainImplTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/PerformanceTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplInsertDomainTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplReactionsTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/SendMessagesTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/MessageRepositoryTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/ReactionRepositoryTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/HideChannelImplTest.kt
https://stream-io.atlassian.net/browse/CAS-560
Changing the visibility for `RepositoryHelper.messageRepository` and creating the necessary methods
> [CAS-560] Messages repository visibility

- .github/workflows/apk-s3-distribute.yml
Create Workflow to upload apk to AWS S3
The workflow has been tested [here](https://github.com/GetStream/stream-chat-android/runs/1822776499?check_suite_focus=true)
> [CAS-652] Create Workflow to upload apk to AWS S3

- stream-chat-android-offline/api/stream-chat-android-offline.api
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/dao/ChannelDao.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/ChannelRepository.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryHelper.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/UserRepository.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDomainTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDomainTest2.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/ChatDomainEventDomainImplTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/SendMessagesTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/ChannelRepositoryTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/MessageRepositoryTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/HideChannelImplTest.kt
Make `channelRepository` the private field in `RepositoryHelper`
> [CAS-558] Hide channel repository

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/FileUploader.kt
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Messages.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/helpers/MyFileUploader.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Messages.kt
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/helpers/MyFileUploader.kt
Minor documentation updates for FileUploader. See changes on https://getstream.io/chat/docs/android/file_uploads/?language=kotlin
> Update doc comments for FileUploader, add docs samples

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventBatchUpdate.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/ChannelRepository.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryFactory.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryHelper.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/BaseRepositoryHelperTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/RepositoryHelperTests.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/WhenUpdateLastMessage.kt
1) Provide `selectMessage`, `selectUser` funs into a constructor of the `ChannelsRepository`
2) Cover ChannelRepository by new interface
3) Remove some wrapped functions from `RepositoryHelper`
4) Rename some methods of the `ChannelRepository` interface
> [CAS-555] Repo facade2

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ClientAndUsers.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ClientAndUsers.kt
Doc updates, doc updates, get your doc updateeees heeeeree
> Update client and user docs snippets

- stream-chat-android-offline/api/stream-chat-android-offline.api
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/dao/ReactionDao.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/MessageRepository.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/ReactionRepository.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryFactory.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryHelper.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplInsertDomainTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/MessageRepositoryTests.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/ReactionRepositoryTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/BaseRepositoryHelperTest.kt
1) MessageRepository, ReactionRepository covered by new interfaces
2) RepositoryHelper implements those by the interface delegate mechanism
3) Removed some redundant, test-only methods
> [CAS-555] Repo facade3

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsSpec.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/ChannelConfigRepository.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/QueryChannelsRepository.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryFactory.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryHelper.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/SyncStateRepository.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseConnectedIntegrationTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDisconnectedIntegrationTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDomainTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDomainTest2.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/IdGenerationDomainTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/PerformanceTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplInsertDomainTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/ChannelConfigRepositoryTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/QueryChannelsImplRepositoryTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/RepositoryHelperTests.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/WhenEnrichChannel.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/HideChannelImplTest.kt
1) Add interfaces for the left repositories
2) Apply delegation pattern to `RepositoryHelper`
3) Rename some methods to be clear for their usage
> [CAS-555] Repo facade4

- build.gradle
- buildSrc/build.gradle.kts
Isolate JCenter Dependencies
It will help us to complete https://stream-io.atlassian.net/browse/CAS-666
Majority of the dependencies already have an opened issue
> Isolate JCenter Dependencies

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Android.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt
[CAS-662](https://stream-io.atlassian.net/browse/CAS-662)
Documentation for [AttachmentGalleryActivity](https://getstream.io/nessy/docs/chat_docs/android_chat_ux/attachmentgallery)
> [CAS-662] Attachment gallery documentation

- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/HiddenMessageListItemFilter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/HiddenMessageListItemPredicate.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt
> Invert filter condition

- stream-chat-android-ui-components-sample/src/main/res/values/themes.xml
Inherit Material Theme for pre 23 API
> Inherit Material Theme for pre 23 API

- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModelBinding.kt
- stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModelTest.kt
> [CAS-705] Convert ChannelListViewModel state to data class

- build.gradle
`KeyboardVisibilityEvent` dependency is already published to Maven Central
https://github.com/yshrsmz/KeyboardVisibilityEvent/issues/64#issuecomment-777326803
> Use Maven Repository for `keyboardvisibilityevent` Dependency

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Push.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Push.kt
> Fix/add some snippets in Push notification docs

- UNRELEASED_CHANGELOG.md
- stream-chat-android/api/stream-chat-android.api
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/MessageListViewStyle.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/dialog/MessageMoreActionDialog.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputStyle.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputView.kt
- stream-chat-android/src/main/res/layout/stream_view_message_input.xml
- stream-chat-android/src/main/res/values/attrs.xml
closes #1399 
This PR adds attributes that allow configuring:
- Action buttons background (in MessageListView)
- Attachments menu background (in MessageInputView)
- Suggestions background (in MessageInputView)
> [CAS-707] Add additional attributes to MessageInputView and MessageListView

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/service/sync/OfflineSyncFirebaseMessagingService.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/service/sync/PushMessageSyncHandler.kt
* Fix the place we stop foreground execution of sync. 
* Run the sync operation synchronously
* A bunch of improvements for docs
> CAS-670 Fix for sync foreground execution end

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Android.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt
https://getstream.io/nessy/docs/chat_docs/android_chat_ux/combining_view_models
> [CAS-722] Update Combining Views and View Models docs

- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/ClientStateService.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/clientstate/ClientStateServiceTests.kt
Handle disconect event during pending token
Fixes #1405 
> Handle disconect event during pending token

- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/Setup.kt
https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#setup
> [CAS-715] Add Cookbook's setup section

- UNRELEASED_CHANGELOG.md
- stream-chat-android-test/src/main/java/io/getstream/chat/android/test/Mother.kt
- stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemDiffCallback.kt
- stream-chat-android/src/test/java/com/getstream/sdk/chat/Mother.kt
- stream-chat-android/src/test/java/com/getstream/sdk/chat/adapter/MessageListItemDiffCallbackTest.kt
Fix ReadIndicator State
Fixes #1411 
- ~[ ] Changelog updated with client-facing changes
- ~[ ] Comparison screenshots added for visual changes
> Fix ReadIndicator State

- stream-chat-android-docs/build.gradle
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/ChannelList.kt
- stream-chat-android-docs/src/main/res/drawable/shape_shimmer.xml
- stream-chat-android-docs/src/main/res/layout/channel_list_loading_view.xml
- stream-chat-android-docs/src/main/res/layout/custom_channel_list_item.xml
- stream-chat-android-docs/src/main/res/layout/item_loading_view.xml
- stream-chat-android-docs/src/main/res/values/strings.xml
https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#channel-list
> [CAS-716] Add Channel List section to cookbook

- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/SuggestionListView_.kt
https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#suggestion-list-view
> [CAS-719] Add Suggestion List View section to cookbook

- stream-chat-android-docs/build.gradle
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/ChatView.kt
- stream-chat-android-docs/src/main/res/layout/custom_plain_text_item.xml
https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#chat-view
> [CAS-717] Add Chat View section to cookbook

- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/MentionList.kt
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/SuggestionListView_.kt
https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#mention-list-view
> [CAS-718] Add Mention List View section to cookbook

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/UnreadCounts.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/UnreadCounts.kt
> Update unread count snippets

- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/SearchView.kt
https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#search-view
> [CAS-720] Add Search View section to cookbook

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Channels.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Channels.kt
> Update channel mute snippets

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Android.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt
https://getstream.io/nessy/docs/chat_docs/android_chat_ux/suggestion_list_view
Feel free to publish docs and trigger a build after review.
> [CAS-728] Add suggestion list view docs

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/FootnoteDecorator.kt
- stream-chat-android-ui-components/src/main/res/drawable/stream_ui_attachment_link_label_background.xml
- stream-chat-android-ui-components/src/main/res/drawable/stream_ui_white_shape_8dp_corners.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_file_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_media_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_link_attachments_view.xml
Redesign link rendering
1) Link content goes upper, above text in message VH
2) Link content gets background with the `stream_ui_white` color
| --- | --- |
|  ![Screenshot_1613757778](https://user-images.githubusercontent.com/11807573/108543520-77ec8a80-72e5-11eb-90b4-105f6c5028a7.png)  | ![Screenshot_1613757464](https://user-images.githubusercontent.com/11807573/108543524-791db780-72e5-11eb-876e-0d71dfc0e547.png) |
> [CAS-697] link redesign

- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/SocketFactory.kt
Remove unneeded user data when creating WS Connection
> [CAS-742] Remove unneeded user data when creating WS Connection

- README.md
> Update README.md - wiki link

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/shared/media/ChatInfoSharedMediaFragment.kt
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_add_channel.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_add_group_channel.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_add_group_channel_select_name.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat_info.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat_info_shared_files.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat_info_shared_groups.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat_info_shared_media.xml
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_custom_login.xml
https://stream-io.atlassian.net/browse/CAS-730
Replaced toolbar elevation (which looks differently on different API levels) with a single pixel separator.
> [CAS-730] Fix toolbar shadows

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
Fix create channel with extras
> Fix create channel with extras

- stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/AttachmentExtension.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/overview/internal/MediaAttachmentAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/LinkAttachmentView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/MediaAttachmentView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/MessageReplyView.kt
This PR ensures that our UI components work well with our generated data (image attachments without populated `imageUrl` field). 
https://user-images.githubusercontent.com/9600921/108839440-221a2a00-75e6-11eb-8f52-561ae8392227.mov
> Fix image urls

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImpl.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImplTest.kt
[CAS-738](https://stream-io.atlassian.net/browse/CAS-738)
In this PR the the channel list is updated if a new message come from a new channel.
https://user-images.githubusercontent.com/10619102/109013560-14ba7980-7692-11eb-950b-7d8337695f3c.mov
> [CAS-738] - Fix - New messages dont update UI

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/GsonChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/DeviceApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MessageApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/DeviceMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/DeviceDto.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/AddDeviceRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/ReactionRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/CompletableResponse.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/DevicesResponse.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/ReactionResponse.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/ReactionsResponse.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
Adds reaction and device related API calls to the Moshi based impl.
> Add reaction and device API calls to Moshi impl

- UNRELEASED_CHANGELOG.md
Add new sections to our CHANGELOG
> Update CHANGELOG Formatting

- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/Setup.kt
Sort ChatDomain.Builder paramters
> Apply Martons comment

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/HeadersInterceptor.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/SocketFactory.kt
Use Train-Case format for Stream Client Header
> [CAS-763] Use Train-Case format for Stream Client Header

- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/utils/LiveDataTestUtil.kt
This improvement is required for https://github.com/GetStream/stream-chat-android/pull/1502
Decreased unnecessary delay in `waitForSetUser` which is used in integration tests. `client.connectUser` is a method which is executed in 2 steps: 
1. First event loop run: connection to WS is established
2. Second event loop run: `Connected` is received
Therefore calling `client.connectUser(user, token).execute()` in a test will never complete and we have to use the `enqueue()` method.
> Increase integration tests speed

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Messages.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Messages.kt
Add docs to CMS with an example for custom attachments
https://getstream.io/nessy/docs/chat_docs/android_chat_ux/message_list_view
> [CAS-736] Docs for custom attachments 

- stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/Date.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/actions/internal/ChannelActionsDialogFragment.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/User.kt
- stream-chat-android-ui-components/src/main/res/values/strings.xml
- stream-chat-android/src/main/java/com/getstream/sdk/chat/utils/extensions/Date.kt
Replaced "Last see 0 minutes ago" with "Last seen just now"
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/110034651-c4a37d00-7d4b-11eb-9c68-9d376d2746da.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/110034636-c1a88c80-7d4b-11eb-9e17-e262cd21bc15.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
> Fix last seen text

- README.md
> Update Stream Chat links in the README

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
> Fix ChannelListView::setViewHolderFactory KDoc

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsView.kt
- stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml
https://stream-io.atlassian.net/browse/CAS-797
> [CAS-797] Add possibility to enable/disable delete message option

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
- stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml
> Update delete message option methods and attribute names

- stream-chat-android-ui-components-sample/src/main/res/values-v29/themes.xml
- stream-chat-android-ui-components-sample/src/main/res/values/themes.xml
[CAS-787](https://stream-io.atlassian.net/browse/CAS-787)
Fixing navigation icons. Making then easier to see.
By changing the style for the 29 API the system adapt itself. Source: https://developer.android.com/training/gestures/gesturenav
| Old navigation | New 3 buttons | New gesture |
| --- | --- | --- |
|![Screenshot_20210317-163743](https://user-images.githubusercontent.com/10619102/111533892-14b81180-8746-11eb-9b56-d457bb253e14.png)| ![Screenshot_20210317-172339](https://user-images.githubusercontent.com/10619102/111533917-200b3d00-8746-11eb-844f-f8b1dcf1a2a2.png) | ![Screenshot_20210317-172257](https://user-images.githubusercontent.com/10619102/111533934-24cff100-8746-11eb-9425-2a1f38130eef.png) |
- ~[ ] New code is covered by …
> [CAS-787] Fix - Navigation bar

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_home.xml
Add version name to the drawer layout of our sample app 
> Show version on drawer layout of the sample app

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/SuggestionListController.kt
- stream-chat-android-ui-components/src/main/res/values/attrs_message_input_view.xml
https://stream-io.atlassian.net/browse/CAS-794
> [CAS-794] Add possibility to enable/disable commands

- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListItemStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/ScrollButtonViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/edit/EditReactionsViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/view/ViewReactionsViewStyle.kt
Convert ViewStyles to data class
> Convert ViewStyles to data class

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ThreadControllerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/thread/ThreadController.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ThreadControllerImplTest.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- New `ThreadController` based on StateFlow
- All code from `ThreadControllerImpl` moved to new `ThreadController`
- The old `ThreadControllerImpl` is a wrapper for the StateFlow `ThreadController`. The old one exposes live data
> [CAS-767] Thread controller flow

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/GsonChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/QueryParams.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitAnonymousApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitCdnApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/ApiKeyInterceptor.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/HeadersInterceptor.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/HttpLoggingInterceptor.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/TokenAuthInterceptor.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/ChannelApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/DeviceApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/GeneralApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/GuestApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MessageApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/ModerationApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/UserApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/StreamFileUploader.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChannelsApiCallsTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/DevicesApiCallsTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MessageIdGenerationTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MessagesApiCallsTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/UsersApiCallsTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/TokenAuthInterceptorTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/interceptor/TokenAuthInterceptorTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/uploader/StreamFileUploaderTest.kt
Introduced an interceptor to append `api_key` query parameter to every request URL.
> API key interceptor

- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/GsonChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/helpers/QueryChannelsPostponeHelper.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/ChatSocketImpl.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/ChatSocketServiceImpl.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MessageIdGenerationTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/helpers/QueryChannelsPostponeHelperTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/ChatSocketServiceImplTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/DevTokenTest.kt
Run postponed queries as non-blocking
> Run postponed queries as non-blocking

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/ChannelResponse.kt
> Make ChannelResponse::watcher_count optional

- DEPRECATIONS.md
- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/ChatFonts.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/ChatFontsImpl.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/TextStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListItemStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/MessageListItemViewHolderFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/internal/MessageListItemDecoratorProvider.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/FootnoteView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/LinkAttachmentView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/attachment/AttachmentViewFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/BackgroundDecorator.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/FootnoteDecorator.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/ReactionsDecorator.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/TextDecorator.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/DateDividerViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/MessageDeletedViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsDialogFragment.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/edit/EditReactionsViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/edit/internal/EditReactionsView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/view/ViewReactionsViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/view/internal/ViewReactionsView.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_date_divider.xml
- stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml
- stream-chat-android-ui-components/src/main/res/values/strings.xml
New style attributes for MessageListView customization
> [CAS-814] Message list view attributes

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/src/main/AndroidManifest.xml
Add attachment activites to manifest
> Add attachment acitivites to manifest file

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputFieldView.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_input_field.xml
- stream-chat-android-ui-components/src/main/res/values/attrs_message_input_view.xml
[CAS-813](https://stream-io.atlassian.net/browse/CAS-813)
Adding configuration for: 
- TextStyle for the Input Text 
- Posibility to custom the cursor color/drawable 
- Background EditText
- Background MessageInputView itself
> [CAS-813] Feature - New configuration for message input view

- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/ChatUI.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/ChatUI.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/header/ChannelListHeaderView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/ChatFonts.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/ChatFontsImpl.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/ChatStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/TextStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListItemStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/header/MessageListHeaderView.kt
- Refactored `TextStyle` to data class, to simplify its usage in `TransformStyle`
- Changed package names of `ChatStyle` and `TextStyle` classes to match directory structure
- Changed the default text style in `TextStyle` to `Typeface.NORMAL` as there were warnings that "-1" is an incorrect value for `textView.setTypeface(textStyle.font, textStyle.style)`
```
TransformStyle.channelListStyleTransformer = StyleTransformer {
it.copy(
optionsIcon = getDrawable(R.drawable.stream_ui_arrow_left_rounded)!!,
deleteIcon = getDrawable(R.drawable.stream_ui_arrow_right_rounded)!!,
deleteEnabled = true,
optionsEnabled = true,
swipeEnabled = true,
backgroundLayoutColor = ContextCompat.getColor(this, R.color.stream_ui_avatar_gradient_yellow),
indicatorSentIcon = …
```
> Convert TextStyle to data class

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/CommandsAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/MentionsAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/list/SuggestionListView.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_mention.xml
- stream-chat-android-ui-components/src/main/res/values/attrs_message_input_view.xml
[CAS-813](https://stream-io.atlassian.net/browse/CAS-813)
Adding configuration for: 
- Background Commands List
- TextStyle Command Name
- TextStyle Command Description
- TextStyle Commands Title
- Background Mentions List
- TextStyle User Name
- TextStyle User Nick
- Drawable "mention icon" 
> [CAS-813] Feature - missing attributes for message input view

- stream-chat-android-client/src/debug/java/io/getstream/chat/android/client/di/ChatModule.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitCallAdapterFactory.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/helpers/QueryChannelsPostponeHelper.kt
- stream-chat-android-client/src/release/java/io/getstream/chat/android/client/di/ChatModule.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/helpers/QueryChannelsPostponeHelperTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/RetroError.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/RetroSuccess.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/Call.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/CoroutineCall.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseConnectedIntegrationTest.kt
Fixes some coroutine handling issues, see inline comments for details
Supercedes #1618
> Coroutine fixes

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/domain/channelconfig/ChannelConfigRepository.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/Mother.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/ChannelConfigRepositoryTest.kt
Rewrote test for channel config repo. Just simple unit tests instead of integration ones
> [CAS-566] channel config repo test decouple

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/utils/CustomObjectFiltering.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/utils/CustomObjectFilteringTest.kt
Improve our filtering process to filter over the members id as Backend does
> [CAS-828] Filter members

- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/ReactionRepositoryTest.kt
https://stream-io.atlassian.net/browse/CAS-570
* Decouple test from `BaseDomainTest` class
* Refactor it to be a unit test
> Refactor `ReactionRepositoryTest`

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarStyle.kt
Quickfix for `AvatarView` to fix color annotations
> `AvatarView`: fix color annotations

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Context.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/TextStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListItemStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/ScrollButtonViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/edit/EditReactionsViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/view/ViewReactionsViewStyle.kt
Proper annotate View Styles Properties
> Proper annotate View Styles Properties

- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/MarkAllReadImplTest.kt
https://stream-io.atlassian.net/browse/CAS-597
Refactored `MarkAllReadImplTest` to unit test. The `ChannelController::markRead` method can be tested as a part of [CAS-598 Refactor MarkReadImplTest ](https://stream-io.atlassian.net/browse/CAS-598), as under the hood the `MarkAllReadImpl` use case just invokes the `ChannelController::markRead` method for each active channel controller.
> [CAS-597] Refactor MarkAllReadImplTest

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/utils/CustomObjectFiltering.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/controller/QueryChannelsController.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImplTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerTest.kt
- stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModelTest.kt
Filter channels into our `QueryChannelsController` depend on the given `FilterObject`
> [CAS-811] [CAS-788] Filter channels into our `QueryChannelsController` depend on the given `FilterObject`

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml
Fixes a small problem pointed in issue #1656. No need to create a ticket for that, it is just t tiny fix in the Attr.
> fixing attr for streamUiCopyMessageActionEnabled

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Android.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/ChannelList.kt
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListViewStyle.kt
https://stream-io.atlassian.net/browse/CAS-816
Improve _ChannelListViewStyle_ documentation
Check:
- [Docs](https://getstream.io/chat/docs/android/channel_list_view/?language=kotlin#other-customizations)
- [Cookbook](https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#changing-channel-list-view-style)
> [CAS-816] Add docs for ChannelListView style

- UNRELEASED_CHANGELOG.md
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Android.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/MessagePlainTextViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/TextAndAttachmentsViewHolder.kt
https://github.com/GetStream/stream-chat-android/issues/1662
https://stream-io.atlassian.net/browse/CAS-850
Fix the `MessageListView::setUserClickListener` method.
> [CAS-850] Fix user click listener

- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/GlobalCustomization.kt
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/SuggestionListView.kt
https://stream-io.atlassian.net/browse/CAS-815
Add docs for `TransformStyle` class
- [Docs](https://getstream.io/chat/docs/android/global_customization/?language=kotlin)
- [Cookbook](https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#global-customization)
> [CAS-815] Document TransformStyle class

- UNRELEASED_CHANGELOG.md
- stream-chat-android/api/stream-chat-android.api
- stream-chat-android/src/main/java/com/getstream/sdk/chat/view/AvatarView.kt
Open AvatarView class to be used outside of the SDK
- [z] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
> Open AvatarView on the old UI

- build.gradle
> Including kotlinx-html-jvm

- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/GsonChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/UpdateChannelPartialRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/ChannelApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/UpdateChannelPartialRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/controllers/ChannelController.kt
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Channels.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Channels.kt
Feature request on Github: https://github.com/GetStream/stream-chat-android/issues/1676
https://stream-io.atlassian.net/browse/CAS-862
Add support for partial updates of channel data
Documentation updates:
- [CMS](https://getstream.io/chat/docs/android/channel_update/?language=kotlin#partial-update) 
- [Cookbook](https://github.com/GetStream/stream-chat-android/wiki/Client-Cookbook#partial-update)
Tested with `Moshi` and `Gson` serialization
> [CAS-862] Partial update for channel

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Android.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/ChatView.kt
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListItemStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/ScrollButtonViewStyle.kt
Improve MessageListView docs
- [Cookbook](https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#changing-messages-style-programmatically)
- [Docs](https://getstream.io/chat/docs/android/message_list_view/?language=kotlin#using-transform-style)
> [CAS-818] Add message list view style docs

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/SuggestionListPopupWindow.kt
> Fix popup over inout

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/header/ComponentBrowserMessagesHeaderViewFragment.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/header/MessageListHeaderView.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_list_header_view.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_typing_indicator_view.xml
https://stream-io.atlassian.net/browse/CAS-854
Fix the alignment of the title when no subtitle is present
`MessageListHeaderView` has not very mature API with a bunch of random methods, but I hope I made it less fragile.
| --- | --- |
| ![photo_2021-04-14 14 12 58](https://user-images.githubusercontent.com/9600921/114701648-c0e01e80-9d2b-11eb-8cc2-4bf5ee9eada8.jpeg) |  ![photo_2021-04-14 14 16 40](https://user-images.githubusercontent.com/9600921/114701948-1e746b00-9d2c-11eb-91b5-1cb575217427.jpeg) |
| ![photo_2021-04-14 14 13 01](https://user-images.githubusercontent.com/9600921/114701647-c0478800-9d2b-11eb-93ee-d638c180e0ee.jpeg) | ![photo_2021-04-14 14 16 44](https://user-images.githubusercontent.com/9600921/114701944-1ddbd480-9d2c-11eb-9b50-b8ae76d8596c.jpeg) |
| …
> [CAS-854] Fix title alignment

- build.gradle
- scripts/sample-app-versioner.gradle
- stream-chat-android-sample/build.gradle
- stream-chat-android-ui-components-sample/build.gradle
Skip GitVersioner if git is not installed on the current machine
> Skip GitVersioner if git is not installed on the current machine

- scripts/sample-app-versioner.gradle
Disable GitVersioner while compile process is done on local machines but run it on CI
Fix #1745 
> Disable GitVersioner locally

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsDialogFragment.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/edit/EditReactionsViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/user/internal/UserReactionsView.kt
- stream-chat-android-ui-components/src/main/res/drawable/stream_ui_shape_user_reactions_background.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_options_view.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_user_reactions_view.xml
- stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml
https://stream-io.atlassian.net/browse/CAS-875
Add possibility to customize message options overlay
| Message options | Reaction options |
| --- | --- |
| ![device-2021-04-19-200735](https://user-images.githubusercontent.com/9600921/115275806-f0879000-a14a-11eb-8c15-3c8efaa25477.png) | ![device-2021-04-19-200708](https://user-images.githubusercontent.com/9600921/115275812-f2515380-a14a-11eb-937c-01dd58855771.png) |
> [CAS-875] Custom styles for message options

- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_group_chat_info.xml
Fix add user positioning in ChatGroupInfoFragment
Open ChatInfoGroupFragment
> [CAS-952] Fix add user button positioning

- documentation/docs/client/sdk.md
[CAS-905](https://stream-io.atlassian.net/browse/CAS-905)
Create the docs of section: Calling SDK methods. 
I created the `.md` and docusaurus does its magic =P
to install docusaurus run: 
```
yarn install
```
Then:
3. Go to **Calling SDK Methods** section
> [CAS-905] Adding documentation for Calling SDK methods

- documentation/docs/client/querying_channels.md
[CAS-922](https://stream-io.atlassian.net/browse/CAS-922)
Documentation for querying channels
.md Added
```
yarn install
```
Then:
> [CAS-922] Docs - querying channels docusaurus

- documentation/docs/client/user_presence.md
https://stream-io.atlassian.net/browse/CAS-920
Move Client User Presence docs
1. Go to `documentation` folder
3. Go to Client -> User Presence section
> [CAS-920] Add user presence docs

- documentation/docs/client/creating_channels.md
[CAS-921](https://stream-io.atlassian.net/browse/CAS-921)
Documentation for creating
.md Added
```
yarn install
```
Then:
> [CAS-921] Docs - Creating channels docusaurus

- documentation/docs/client/updating_a_channel.md
[CAS-924](https://stream-io.atlassian.net/browse/CAS-924)
Documentation for updating a channel
.md Added
```
yarn install
```
Then:
> [CAS-924] Docs - Updating a channel docusaurus

- documentation/docs/client/watching_channel.md
https://stream-io.atlassian.net/browse/CAS-923
Move Client Watching a Channel docs
1. Go to `documentation` folder
3. Go to Client -> Watching Channel section
> [CAS-923] Add watching channel docs

- documentation/docs/client/querying_users/_category_.json
- documentation/docs/client/querying_users/querying_banned_users.md
- documentation/docs/client/querying_users/querying_regular_users.md
- documentation/docs/client/querying_users/querying_users_by_search_term.md
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
https://stream-io.atlassian.net/browse/CAS-919
Move Query User docs to docusaurus
3. Check out Client -> Query User section
> CAS-919 Docs/client/querying_user

- documentation/docs/client/muting_channels.md
[CAS-927](https://stream-io.atlassian.net/browse/CAS-927)
Documentation for updating a channel
.md Added
```
yarn install
```
Then:
> [CAS-927] Docs - muting channels docusaurus

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChannelData.kt
Add members_count value when converting from `ChannelData` to `Channel`
> Add memberCount value when converting from `ChannelData` to `Channel`

- documentation/docs/client/deleting_and_hiding_channel.md
[CAS-928](https://stream-io.atlassian.net/browse/CAS-928)
Documentation for deleting and hiding channel
.md Added
```
yarn install
```
Then:
> [CAS-928] Docs - Deleting and hiding channel docusaurus

- documentation/docs/client/slow_mode.md
[CAS-930](https://stream-io.atlassian.net/browse/CAS-930)
Documentation for Slow Mode
.md Added
```
yarn install
```
Then:
> [CAS-930] Docs - Slow mode docusaurus

- documentation/docs/client/messages.md
[CAS-930](https://stream-io.atlassian.net/browse/CAS-930)
Documentation for messages section
.md Added
```
yarn install
```
Then:
> [CAS-931] Docs - Messages Docusaurus

- documentation/docs/client/reactions.md
https://stream-io.atlassian.net/browse/CAS-933
Create Documentation for `Client > Reactions` section
Apart from the content from our LLC cookbook, added some more information from the CMS
3. Check out Client -> Reactions section
> [CAS-933] Create documentation for Client > Reactions section

- documentation/docs/client/silent_messages.md
https://stream-io.atlassian.net/browse/CAS-936
Create Documentation for "Client > Silent Message" section
3. Check out Client -> Silent Message Messages
> [CAS-936] Create documentation for Client > Silent Message section

- documentation/docs/client/pinned_messages.md
https://stream-io.atlassian.net/browse/CAS-937
Create Documentation for "Client > Pinned Messages" section
Apart from using our LLC cookbook, added some more details from the CMS
3. Check out Client -> Pinned Messages section
> [CAS-937] Create documentation for Client > Pinned Messages section

- documentation/docs/client/typing_indicators.md
https://stream-io.atlassian.net/browse/CAS-939
Create Documentation for "Client > Typing Indicators" section
3. Check out Client -> Typing Indicators section
> [CAS-939] Create documentation for Client > Typing Indicators section

- documentation/docs/client/searching_messages.md
https://stream-io.atlassian.net/browse/CAS-935
Create Documentation for "Client > Searching Messages" section
3. Check out Client -> Searching Messages
> [CAS-935] Create documentation for Client > Searching Messages section

- documentation/docs/client/uploading_files.md
[CAS-932](https://stream-io.atlassian.net/browse/CAS-932)
Documentation for uploading files
.md Added
```
yarn install
```
Then:
> [CAS-932] Docs - Uploading files

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/QueryChannelsRequest.kt
Align query channel request made with Moshi serialization with what we had previously:
- Rename `querySort` to `sort` in query channels payload.
> Fix channel list sorting with Moshi serialization

- DEPRECATIONS.md
- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
https://stream-io.atlassian.net/browse/CAS-989
Moshi by default
Makes Moshi the default, adds warnings and explanation everywhere
> [CAS-989] Use Moshi serialization in the client by default

- documentation/docs/ui/channel_list/binding_view_models.md
- documentation/docs/ui/chat_view/binding_chat_view_models.md
- documentation/docs/ui/mention_list_view.md
- documentation/docs/ui/search_view.md
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/header/viewmodel/ChannelListHeaderViewModelBinding.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModelBinding.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mention/list/viewmodel/MentionListViewModelBinding.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/viewmodel/MessageInputViewModelBinding.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/header/viewmodel/MessageListHeaderViewBinding.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/viewmodel/MessageListViewModelBinding.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/list/viewmodel/SearchViewModelBinding.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/typing/viewmodel/TypingIndicatorViewModelBinding.kt
Clarify that `bindView` should be called before setting other listeners to avoid listeners being overridden.
> bindView doc improvements

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventHandlerImpl.kt
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/ChatSocketListener.kt
Removing some warnings form the code.
Just removing some `?`
> Removing warnings for onUnreadChannels and onTotalUnreadCountListener

- stream-chat-android-offline/api/stream-chat-android-offline.api
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/attachment/AttachmentMapper.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/attachment/AttachmentToUploadDao.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/attachment/AttachmentUploadRepository.kt
Use Attachments as model not entity in AttachmentUploadRepository
We shouldn't expose DB entities in any part of business logic
Use domain model in repo interface API
> Fix attachment to upload repo interface

- .github/workflows/docusaurus.yml
> Move to separate gh action

- .github/workflows/docusaurus.yml
[CAS-1007](https://stream-io.atlassian.net/browse/CAS-1007)
Adding a name of the docusaurus action. 
Just inserted a line in the YAML.
The name should appear in the action. 
> [CAS-1007] Ci - Adding name to docusaurus doc

- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatNotifications.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/PushTokenUpdateHandler.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/ChatNotificationHandler.kt
After upgrading Firebase dependency we were using wrong API to obtain token.
> Quick fix: Fix getting Firebase token

- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatNotifications.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/ChatNotificationHandler.kt
https://stream-io.atlassian.net/browse/CAS-1013
Improve showing notifications after receiving `NewMessageEvent`.
1. Change `ChatNoficationHandler::onChatEvent` signature and default return value
2. Add checking if the event comes from the current user 
3. Remove `isForeground()` check while handling event internally
4. Remove unnecessary call to server for message data (it's now obtained from the event)
1. Change `ChatNotificationHandler::onChatEvent` return value to false
2. Send message from another device
3. You should see a notification
> [CAS-1013] Refactor handling push notifications after receiving event

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/LoadNotificationDataWorker.kt
Decrease "Loading data" notification priority
1. Send message from another device
2. You should receive push notification
> Decrease loading data notifications priority

- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatNotifications.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/ChatNotificationHandler.kt
Improve notifications customization
Changed method parameters and return type in order to make notifications more customizable.
1. Check that push notification are working as expected
> Change ChatNotificationHandler::buildNotification signature

- docusaurus/docs/Android/client/invites.md
- docusaurus/docs/Android/client/moderation_tools.md
- docusaurus/docs/Android/client/typing_indicators.md
- docusaurus/docs/Android/ui/channel_list/binding_view_models.md
- docusaurus/docs/Android/ui/channel_list/handling_channel_actions.md
- docusaurus/docs/Android/ui/chat_view/handling_chat_actions.md
- docusaurus/docs/Android/ui/chat_view/sample_chat_customizations/changing_message_input_view.md
- docusaurus/docs/Android/ui/chat_view/sample_chat_customizations/changing_messages_style.md
- docusaurus/docs/Android/ui/global_customizations/chat_ui_customizations/navigator.md
- docusaurus/docs/Android/ui/global_customizations/transform_style.md
- docusaurus/docs/Android/ui/search_view.md
- docusaurus/docs/Android/ui/setup.md
Fixing some typos in Docusaurus docs
> Fix typos in docusaurus docs

- .github/workflows/docusaurus.yml
- build.gradle
- scripts/merge-dokkasaurus-outputs.sh
- stream-chat-android-client/build.gradle
- stream-chat-android-offline/build.gradle
- stream-chat-android-ui-components/build.gradle
Be able to use dokkasaurus and Dokka with HTML. 
Adding Dokka with many separated single new tasks and moving all the outputs with a `.sh` script 
Run the action.
- ~[] New code is covered by unit tests~
> Dokkasaurus as a separate task

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/TokenUtils.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ConnectUserTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/BaseChatClientTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenConnectUser.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/TokenUtilsTest.kt
Be sure the userId into the JWT and the user that want to be connect are the same
The JWT contains the userId on the payload that is sent to the server.
A new class has been created to obtain this userId and check that it matches with the user provided.
In other case it is notified to the developer and the connectUser process is stopped
> [CAS-1061] Feature/check user id from token

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt
Close AttachmentGalleryActivity in case no attachment are received.
Fix #1959 
> Close Gallery if the list of pictures to show is empty

- stream-chat-android-sample/build.gradle
- stream-chat-android-ui-components-sample/build.gradle
> Remove unused ndkVersion from sample app configs

- CHANGELOG.md
Changelog of the latest release contained typos. This PR fixes them.
Fixes #1969
> Quickfix: Changelog typos

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/build.gradle
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/factory/ChannelListViewModelFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/FilterUtils.kt
- stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModelTest.kt
https://stream-io.atlassian.net/browse/CAS-972
Subscribe to user instead of using currentUser.
I closed the PR #1900 as it became too large and now I'm starting with small parts (and the ones that makes changes in the API)
Changing implementation of `ChannelListViewModel`. 
The list of Channels should be correctly requested.
_Fighting this monster!_
> [CAS-972] Refactor - Channel list view model

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/TransformStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/FileAttachmentsViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/FileAttachmentsView.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_file_attachment.xml
- stream-chat-android-ui-components/src/main/res/values/attrs_file_attachment_view.xml
https://stream-io.atlassian.net/browse/CAS-1035
Allow `FileAttachmentView` customization using `TransformStyle` API.
* Created FileAttachmentsViewStyle class allowing customization via TransformStyle
* Added XML attrs allowing customization
> CAS-1035 file attachments view style

- docusaurus/docs/Android/01-basics/01-introduction.md
- docusaurus/docs/Android/01-basics/01-overview.md
- docusaurus/docs/Android/01-basics/02-dependencies.md
- docusaurus/docs/Android/01-basics/03-initializing-sdk.md
- docusaurus/docs/Android/01-basics/04-calling-sdk-methods.md
- docusaurus/docs/Android/03-ui/01-getting-started.md
- docusaurus/docs/Android/03-ui/04-components/03-message-list.md
> Improve docs intros

- docusaurus/docs/Android/03-ui/04-components/01-channel-list.md
Small updates to this documentation page
> Make some quick edits to the ChannelListView doc page

- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/StreamFileProvider.java
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/StreamFileProvider.kt
Fix nonsense Samsung crashes.
The trivial class being implemented in Java will produce even simpler bytecode, with no references to `kotlin.Metadata`.
Nobody knows
> Convert StreamFileProvider to Java in an attempt to make Samsung devices happy

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/usecase/SearchUsersByName.kt
FIxing a bug in the user search. The filter was wrong so the search was returning a failure result. 
Don't using a list in the NE filter, using a String instead.
Go to "New Group" and check that is doesn't work in `develop`. Then check that it work in this branch.
_Sorry... my fault_
> Fix - Fixing bug in user search

- docusaurus/docs/Android/04-guides/05-push-notifications.md
https://stream-io.atlassian.net/browse/CAS-1103
> [CAS-1103] Move Push Notification docs to Guides section

- DEPRECATIONS.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
> Deprecate logLevel method with String parameter

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/images/CoilStreamImageLoader.kt
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/images/ImageHeadersProvider.kt
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/images/StreamImageLoader.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/ChatUI.kt
- stream-chat-android/api/stream-chat-android.api
- stream-chat-android/src/main/java/com/getstream/sdk/chat/ChatUI.kt
Allow adding custom HTTP headers to image requests
Add custom image request header and check if it's included in the image request
> [CAS-1110] Allow adding custom HTTP headers to image requests

- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/GsonChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/UpdateCooldownRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/ChannelApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/UpdateCooldownRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
https://stream-io.atlassian.net/browse/CAS-1111
Use partial channel update when enabling/disabling cooldown
The API remains the same
> [CAS-1111] Use partial channel update when enabling/disabling cooldown

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components-sample/src/main/res/layout/fragment_home.xml
- stream-chat-android-ui-components-sample/src/main/res/values-v23/themes.xml
- stream-chat-android-ui-components-sample/src/main/res/values-v29/themes.xml
- stream-chat-android-ui-components-sample/src/main/res/values/themes.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/header/ChannelListHeaderView.kt
- stream-chat-android-ui-components/src/main/res/values/attrs.xml
- stream-chat-android-ui-components/src/main/res/values/styles.xml
[CAS-992](https://stream-io.atlassian.net/browse/CAS-992)
Add theme for ChannelListHeader.
Adding the attr and style. 
Change some parts of the theme and see it reflected in the UI
> [CAS-992] Refac - Theming for channel list header

- docusaurus/docs/Android/01-basics/01-overview.md
- docusaurus/docs/Android/01-basics/02-dependencies.md
- docusaurus/docs/Android/01-basics/03-getting-started.md
- docusaurus/docs/Android/01-basics/04-core-concepts.md
- docusaurus/docs/Android/01-basics/05-logging.md
- docusaurus/docs/Android/03-ui/01-getting-started.md
- docusaurus/docs/Android/03-ui/02-chatui.md
- docusaurus/docs/Android/03-ui/03-components/01-channel-list.md
- docusaurus/docs/Android/03-ui/03-components/02-channel-list-header.md
- docusaurus/docs/Android/03-ui/03-components/03-message-list.md
- docusaurus/docs/Android/03-ui/03-components/04-message-list-header.md
- docusaurus/docs/Android/03-ui/03-components/05-message-input.md
- docusaurus/docs/Android/03-ui/03-components/06-mention-list-view.md
- docusaurus/docs/Android/03-ui/03-components/07-search-view.md
- docusaurus/docs/Android/03-ui/03-components/08-attachment-gallery.md
- docusaurus/docs/Android/03-ui/04-guides/01-building-channel-list-screen.md
- docusaurus/docs/Android/03-ui/04-guides/02-building-message-list-screen.md
- docusaurus/docs/Android/03-ui/04-guides/03-custom-message-input.md
- docusaurus/docs/Android/03-ui/04-guides/04-theming.md
Perform an edit pass on the docs, clean up any typos, wording and formatting issues, etc. Make documentation pages as consistent as possible.
Run `npx stream-chat-docusaurus -i -s`.
> Clean up documentation

- .github/workflows/docusaurus-prod.yml
- .github/workflows/docusaurus-staging.yml
Set up Docusaurus workflows for prod use
> Update Docusaurus workflows

- stream-chat-android-ui-components-sample/src/main/res/values-v23/themes.xml
- stream-chat-android-ui-components-sample/src/main/res/values-v29/themes.xml
- stream-chat-android-ui-components-sample/src/main/res/values/themes.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_header_view.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_channel_member.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_media_attachment.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_search_result.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_list_header_view.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_threads_footnote.xml
- stream-chat-android-ui-components/src/main/res/values/dimens.xml
- stream-chat-android-ui-components/src/main/res/values/styles.xml
[CAS-991](https://stream-io.atlassian.net/browse/CAS-991)
Fixes for avatar theme.
Many fixes, mostly layout_width and layoyt_height that were not removed from the view and the style was applied.
Make the changes in the style and check if they are applied. 
> [CAS-991] Fixes for avatar theming

- README.md
- stream-chat-android-client/README.md
- stream-chat-android-offline/README.md
- stream-chat-android-ui-components/README.md
Update old links in the README, remove irrelevant info
See [the README on the branch](https://github.com/GetStream/stream-chat-android/tree/readme-updates). Also check the module level READMEs here.
> Readme rework

- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
Expose style of appropriate MessageListView :-)
> Expose style of MessageListView

- stream-chat-android-ui-components/src/main/res/values/styles.xml
Fix `ChannelListHeader` crash
1. Try to upload attachments
> Remove streamUiOfflineTitleTextFont fron ChannelListHeader style

- stream-chat-android-ui-components/src/main/res/values/styles.xml
Fix icon's tint color
| --- | --- |
| <img width="267" alt="Screenshot 2021-07-19 at 11 27 57" src="https://user-images.githubusercontent.com/17440581/126138224-ae53cee1-a6c9-4047-8d5d-7c173c1fdc83.png">|<img width="267" alt="Screenshot 2021-07-19 at 11 28 21" src="https://user-images.githubusercontent.com/17440581/126138228-a4b43c63-94af-4d53-9a1e-96c0c376c845.png">|
> Remove streamUiActionButtonTint from ChannelListHeader style

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomain.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/usecase/QueryMembers.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/usecase/SearchUsersByName.kt
https://stream-io.atlassian.net/browse/CAS-1135
Usability improvement: warn users if they don't use the return type of methods that return `Call` objects.
Try using these methods incorrectly.
- [#] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [#] PR targets the `develop` branch
> [CAS-1135] Add missing @CheckResult annotations

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components-sample/src/main/AndroidManifest.xml
- stream-chat-android-ui-components/src/main/AndroidManifest.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_activity_attachment.xml
- stream-chat-android-ui-components/src/main/res/values/attrs_attachment_activity.xml
- stream-chat-android-ui-components/src/main/res/values/styles.xml
[CAS-996](https://stream-io.atlassian.net/browse/CAS-996)
Create theme for AttachmentActivity
Use the theme and check the applied changes
_Fashion_
> [CAS-996] Feature - Theme for attachment activity

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/TransformStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mention/list/MentionListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mention/list/MentionListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mention/list/internal/MentionListAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/preview/MessagePreviewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/preview/internal/MessagePreviewView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/internal/SearchResultListAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/list/SearchResultListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/list/SearchResultListViewStyle.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_search_result_list_view.xml
- stream-chat-android-ui-components/src/main/res/values/attrs.xml
- stream-chat-android-ui-components/src/main/res/values/attrs_search_result_list_view.xml
- stream-chat-android-ui-components/src/main/res/values/styles.xml
https://stream-io.atlassian.net/browse/CAS-1006
Add possibility to customize `SearchResultListView`
1. Add `MentionListViewStyle` and missing transformer
2. Add `MessagePreviewStyle` which is reused in both `MentionListViewStyle` and `SearchResultListViewStyle`
3. Add `SearchResultListViewStyle`
| --- | --- |
| <img width="322" alt="Screenshot 2021-07-21 at 18 12 49" src="https://user-images.githubusercontent.com/17440581/126596015-b25e9c0a-abe6-4b61-b1d2-67f09c3758c7.png">|<img width="322" alt="Screenshot 2021-07-21 at 18 18 44" src="https://user-images.githubusercontent.com/17440581/126596017-fdd30337-cdc4-4612-b5b8-920bed7fce40.png">|
Play with new attributes
> [CAS-1006] Add possibility to customize `SearchResultListView`

- stream-chat-android-compose-sample/build.gradle
Make work
Set the signing configs correctly for this module
> Fix signing config setup for Compose sample app

- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChannelActivity.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatApp.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/ChannelsScreen.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/list/ChannelItem.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/list/ChannelList.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channel/ChannelListViewModel.kt
- stream-chat-android-compose/src/main/res/values/strings.xml
Improve behaviour when data (avatar, name, message) is missing.
Also some minor other fixes.
| --- | --- |
| ![Screenshot_1627491170](https://user-images.githubusercontent.com/12054216/127364089-d20beb9f-c3ca-4546-a1af-969a05ca2d1c.png) | ![Screenshot_1627491126](https://user-images.githubusercontent.com/12054216/127364099-0ca78244-bdcb-49c4-a1ac-ef7c339a9e2d.png)|
> Compose channel list improvements

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/MediaAttachmentView.kt
- Fix crash while sending Giphy messages
- Fix the typo in `streamUiMessagesStart`
> Fix giphy messages

- stream-chat-android-client/src/main/res/values-en/strings.xml
- stream-chat-android-ui-common/src/main/res/values-en/strings.xml
- stream-chat-android-ui-components/src/main/res/values-en/strings_attachment_gallery.xml
- stream-chat-android-ui-components/src/main/res/values-en/strings_channel_list.xml
- stream-chat-android-ui-components/src/main/res/values-en/strings_channel_list_header.xml
- stream-chat-android-ui-components/src/main/res/values-en/strings_common.xml
- stream-chat-android-ui-components/src/main/res/values-en/strings_mention_list.xml
- stream-chat-android-ui-components/src/main/res/values-en/strings_message_input.xml
- stream-chat-android-ui-components/src/main/res/values-en/strings_message_list.xml
- stream-chat-android-ui-components/src/main/res/values-en/strings_message_list_header.xml
- stream-chat-android-ui-components/src/main/res/values-en/strings_search.xml
https://stream-io.atlassian.net/browse/CAS-1178
Add English translations to values-en folder so it's possible to override default translations
> [CAS-1178] Add English translations to values-en folder

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputFieldView.kt
[CAS-1161](https://stream-io.atlassian.net/browse/CAS-1161)
Fix the attachments from camera. 
Adding more attachments instead of overriding it.
Selected many pictures and videos from camera. 
- ~[ ] Comparison screenshots added for visual changes.~
> [CAS-1161] Adding more attachments instead of overriding then

- stream-chat-android-docs/src/main/res/layout/custom_channel_list_item.xml
- stream-chat-android-ui-components-sample/src/main/res/values/styles.xml
- stream-chat-android-ui-components/src/main/res/values/styles.xml
[CAS-1132](https://stream-io.atlassian.net/browse/CAS-1132)
Code clean for styles. 
Moving some styles to sample app, as they are used only there and removing some others as they are not used.
The CI is enough in this case.
- ~[] Changelog is updated with client-facing changes~
> [CAS-1132] Refactor - Cleaning styles of SDK

- UNRELEASED_CHANGELOG.md
- stream-chat-android-client/src/main/res/values-es/strings.xml
- stream-chat-android-ui-common/src/main/res/values-es/strings.xml
- stream-chat-android-ui-components/src/main/res/values-es/strings_attachment_gallery.xml
- stream-chat-android-ui-components/src/main/res/values-es/strings_channel_list.xml
- stream-chat-android-ui-components/src/main/res/values-es/strings_channel_list_header.xml
- stream-chat-android-ui-components/src/main/res/values-es/strings_common.xml
- stream-chat-android-ui-components/src/main/res/values-es/strings_mention_list.xml
- stream-chat-android-ui-components/src/main/res/values-es/strings_message_input.xml
- stream-chat-android-ui-components/src/main/res/values-es/strings_message_list.xml
- stream-chat-android-ui-components/src/main/res/values-es/strings_message_list_header.xml
- stream-chat-android-ui-components/src/main/res/values-es/strings_search.xml
> [CAS-1171] Add Spanish translations

- stream-chat-android-ui-components/src/main/res/values-es/strings_message_list.xml
- stream-chat-android-ui-components/src/main/res/values-es/strings_pinned_message_list.xml
Spanish translations for the following strings:
```xml
<string name="stream_ui_message_list_pinned_message">Pinned by %s</string>
<string name="stream_ui_message_list_pinned_message_you">You</string>
<string name="stream_ui_message_list_pin_message">Pin to Conversation</string>
<string name="stream_ui_message_list_unpin_message">Unpin from Conversation</string>
<string name="stream_ui_message_list_error_pin_message">Failed to pin message</string>
<string name="stream_ui_message_list_error_unpin_message">Failed to unpin message</string>
<string name="stream_ui_pinned_message_list_empty_title">No pinned messages</string>
<string name="stream_ui_pinned_message_list_empty_description"><![CDATA[Long-press an important message and choose <b>Pin to conversation</b>]]></string>
<string …
```
> [CAS-895] Spanish translation

- stream-chat-android-client/src/main/res/values-ja/strings.xml
- stream-chat-android-ui-common/src/main/res/values-ja/strings.xml
- stream-chat-android-ui-components/src/main/res/values-ja/strings_channel_list.xml
- stream-chat-android-ui-components/src/main/res/values-ja/strings_common.xml
- stream-chat-android-ui-components/src/main/res/values-ja/strings_message_input.xml
- stream-chat-android-ui-components/src/main/res/values-ja/strings_message_list.xml
- stream-chat-android-ui-components/src/main/res/values-ja/strings_message_list_header.xml
- stream-chat-android-ui-components/src/main/res/values-ja/strings_search.xml
> docs(Japanese Translations): Minor edits to Japanese translations made

- stream-chat-android-ui-components/src/main/res/values-hi/strings_message_list.xml
- stream-chat-android-ui-components/src/main/res/values-hi/strings_pinned_message_list.xml
Hindi translations for the following strings:
```xml
<string name="stream_ui_message_list_pinned_message">Pinned by %s</string>
<string name="stream_ui_message_list_pinned_message_you">You</string>
<string name="stream_ui_message_list_pin_message">Pin to Conversation</string>
<string name="stream_ui_message_list_unpin_message">Unpin from Conversation</string>
<string name="stream_ui_message_list_error_pin_message">Failed to pin message</string>
<string name="stream_ui_message_list_error_unpin_message">Failed to unpin message</string>
<string name="stream_ui_pinned_message_list_empty_title">No pinned messages</string>
<string name="stream_ui_pinned_message_list_empty_description"><![CDATA[Long-press an important message and choose <b>Pin to conversation</b>]]></string>
<string …
```
> [CAS-895] Hindi translation

- docusaurus/docs/Android/03-ui/05-guides/04-custom-translations.md
Apply Niko's [suggestion](https://github.com/GetStream/stream-chat-android/pull/2196#discussion_r687018283) from the previous PR
> Add section explaining auto-translation

- docusaurus/docs/Android/02-client/06-guides/01-push-notifications.md
Edited the push notification docs.
> Push notification docs edit

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventHandlerImpl.kt
Fix #2197 
Store updated data from the current user when it is updated
Check if the UpdateUserEvent is for the currentUser and update it. CurrentUser is updated with an especial key ("me") into our database and doesn't follow the same way the rest of users are updated from our `EventBatchUpdate`
> Update current user data when an UpdateUserEvent arrives

- stream-chat-android-compose-sample/build.gradle
Catch any bugs related to obfuscation during testing
Copied the configuration from the UI Components sample module
> Update Compose sample app minification settings

- stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/ChatDomainImplCreateChannelTest.kt
[CAS-1225](https://stream-io.atlassian.net/browse/CAS-1225)
Fixing flaky test.
Chaging `verifyZeroInteractions` to check that `insertChannel`. By the description of the test, the real goal is to check if no channel is inserted in the DB instead of checking if no interaction was made in RepositoryFacade.
You can run this test multiple times in a row and check that it is not flaky anymore. 
> [CAS-1225] Fix - Fixing unit test

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/compose_task.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Updates the available issue types in the repository.
Will only take effect once merged to `main`, but not an urgent change.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/12054216/129792899-70ba687f-9722-4ead-96c4-c43349ed5a4b.png) | ![image](https://user-images.githubusercontent.com/12054216/129792942-8d867732-0a4f-42d9-af08-75b1ed9c9fe5.png) |
> Update issue templates

- stream-chat-android-compose-sample/build.gradle
- stream-chat-android-compose-sample/google-services.json
#2243
Integrate Firebase into our Compose Sample
> Add Firebase to Compose Sample

- .gitignore
Ignore Release keystore in our git repository
> Ignore release keystore

- docusaurus/docs/Android/02-client/06-guides/01-push-notifications.mdx
> Fix intro in push notification docs

- docusaurus/docs/Android/03-ui/04-components/01-channel-list-screen.mdx
- docusaurus/docs/Android/03-ui/04-components/04-message-list-screen.mdx
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/ChannelListFragment.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/MessageListFragment.kt
https://stream-io.atlassian.net/browse/CAS-1222
Add small amendments to the docs according to Marton's comments
> [CAS-1222] Small amendments to higher-level component docs

- UNRELEASED_CHANGELOG.md
- stream-chat-android-ui-components/src/main/res/values/styles.xml
Applying the correct theme to AttachmentActivity.
Go to AttachmentActivity... the sample app breaks.
> Applying correct fix for AttachmentActivity

- UNRELEASED_CHANGELOG.md
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
Log channel delete error. If a user does an illegal error, we don't log the cause, which makes it super hard to understand why it failed. 
Logging channel delete error. 
Make an illegal deletion and check the logs
> Log channel delete error

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/network/NetworkStateProvider.kt
Fix IllegalArgumeentException when a NetworkCallback was already unregistered:
<details>
<summary>Click to expand the full stacktrace!</summary>
```
Fatal Exception: java.lang.IllegalArgumentException: NetworkCallback was already unregistered
at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:47)
at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:3602)
at io.getstream.chat.android.client.network.NetworkStateProvider.unsubscribe(NetworkStateProvider.java:67)
at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$special$$inlined$observable$1.afterChange(ChatSocketServiceImpl.java:100)
at kotlin.properties.ObservableProperty.setValue(ObservableProperty.java:41)
at …
```
> Add lock to subscribe/unsubscribe methods

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/build.gradle
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/internal/toggle/ToggleService.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/internal/toggle/dialog/ToggleAdapter.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/internal/toggle/dialog/ToggleDialogController.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/internal/toggle/dialog/ToggleDialogFragment.kt
- stream-chat-android-client/src/main/res/drawable-night/stream_text_color_selector.xml
- stream-chat-android-client/src/main/res/drawable/stream_text_color_selector.xml
- stream-chat-android-client/src/main/res/layout/stream_toggle_dialog_fragment.xml
- stream-chat-android-client/src/main/res/layout/stream_toggle_list_item.xml
- stream-chat-android-ui-components-sample/src/debug/kotlin/io/getstream/chat/ui/sample/application/ApplicationConfigurator.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/ChannelListFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/header/ChannelListHeaderView.kt
In order to make new refactorings and test its' impact on SDK and sample this PR brings `ToggleService` and `ToggleDIalogFragment`
1. ToggleService can be used as singleton instance in every point of SDK (since it's included in LLC) when you want to check some toggle.
```kotlin
if (ToggleService.instance().isEnabled("myToggle") {
// do new logic here
} else {
// keep old logic here
}
```
https://user-images.githubusercontent.com/11807573/130959671-46341a6b-8eb8-4a3d-acf0-40a94f2be7dc.mov
Long click on the avatar in the channel list screen and you'll observe `ToggleDialogFragment` 
_P.S. Enabled only for DEBUG version_
- ~[ ] Affected documentation updated (docusaurus, tutorial, CMS (task …
> [CAS-1063] Toggle service

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/UploadFileResponse.kt
Fix the issue with broken uploading
> Fix UploadFileResponse serialization with Moshi

- docusaurus/docs/Android/01-basics/02-dependencies.mdx
https://stream-io.atlassian.net/browse/CAS-1228
To tell our clients about our versioning & snapshot builds.
Run Docusaurus with `npx stream-chat-docusaurus -i -s`
> [CAS-1228] Add versioning docs

- docusaurus/docs/Android/01-basics/02-dependencies.mdx
> Improve instructions and wording on the Dependencies page

- docusaurus/docs/Android/03-ui/04-components/05-message-list.mdx
Improve Messages Start Position docs
Check mentioned docs
> Improve Messages Start Position docs

- docusaurus/docs/Android/03-ui/04-components/07-message-input.mdx
Small fix for docs of `MessageInputView`. 
> Small fix for message input documentation

- build.gradle
This library is now available from MavenCentral 🎉
> Remove ok2curl entry from Jitpack modules

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/ConfigMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/ConfigDto.kt
Fix `com.squareup.moshi.JsonDataException: com.squareup.moshi.JsonDataException: Required value 'name' missing at $.config at $.channel` error
> Make Config::name optional

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/MockChatClientBuilder.kt
- stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModelTest.kt
Be able to create some mock ChatClient instance for test purpose  
> Chat client builder

- DEPRECATIONS.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatNotifications.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/DeviceRegisteredListener.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/PushTokenUpdateHandler.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/ChatNotificationHandler.kt
Deprecated an unusefull listener
> Deprecated class `DeviceRegisteredListener`

- .gitignore
- .idea/inspectionProfiles/ktlint.xml
- .idea/scopes/Library_modules.xml
Show warning on all undocumented APIs
> Show warnings on missing public kdoc

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
Fix Curl request strings which lack user tokens and therefore fail. This will help us with customer requests as we will be able ask them for Curl requests and execute them on our side. 
Moved token interceptor up the chain so that user token is included in the request before the request is dumped with Curl.
As @zsmb13 noticed, there is a small downside: we'll log requests twice if the token interceptor has to load a new token and retry.
> Fix curl requests

- CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/ScrollButtonViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/internal/ScrollButtonView.kt
- stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml
- stream-chat-android-ui-components/src/main/res/values/styles.xml
[CAS-1367](https://stream-io.atlassian.net/browse/CAS-1367)
Add customizable elevation for scroll button
Set the elevation for scroll button and check that it takes effect. 
- ~[ ] Affected documentation updated (docusaurus, tutorial, CMS (task created))~~
> [CAS-1367] Customize scroll button elevation

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/MessageRepository.kt
[CAS-1324](https://stream-io.atlassian.net/browse/CAS-1324)
Add more information about issue #2333. We need more information to be able to investigate it.
> [CAS-1324] Adding more information about error of null Message.cid

- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/handlers/LoadMoreHandler.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/list/ChannelList.kt
Move `LoadMoreHanlder` from the `common` package  to `handler` package.
> [Compose] - Move load more handler to the correct package

- docusaurus/docs/Android/04-compose/03-channel-components/02-channel-list-header.mdx
- docusaurus/docs/Android/04-compose/04-message-components/02-message-list-header.mdx
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChannelActivity.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/header/ChannelListHeader.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/header/MessageListHeader.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/model/ConnectionState.kt
Update the docs for `ConnectionState` parameter.
> [Compose] Document ConnetionState class

- docusaurus/docs/Android/03-ui/05-guides/04-custom-translations.mdx
Add Indonesian to Adding Localization docs
> Add Indonesian to Adding Localization docs

- CHANGELOG.md
- stream-chat-android-offline/api/stream-chat-android-offline.api
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/add/AddChannelViewModel.kt
https://stream-io.atlassian.net/browse/CAS-1295
The goal is to make it easy to search for users without ChatDomain for clients.
Added an extension function ChatClient::searchUsersByName
Run sample app and be sure the search is working fine when adding members to create a new channel.
> [CAS-1295] Add searchUsersByName extension to ChatClient

- CHANGELOG.md
- stream-chat-android/api/stream-chat-android.api
- stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemAdapter.java
https://stream-io.atlassian.net/browse/CAS-1444
Add `ChannelListItemAdapter::getChannels` for getting a list of channels in Old SDK module
Check If the method works correctly
> [CAS-1444] Add ChannelListItemAdapter::getChannels for getting a list of channels

- CHANGELOG.md
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/common/TypingIndicator.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/header/MessageListHeader.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
- stream-chat-android-compose/src/main/res/values-en/strings.xml
- stream-chat-android-compose/src/main/res/values-es/strings.xml
- stream-chat-android-compose/src/main/res/values-fr/strings.xml
- stream-chat-android-compose/src/main/res/values-hi/strings.xml
- stream-chat-android-compose/src/main/res/values-it/strings.xml
- stream-chat-android-compose/src/main/res/values-ja/strings.xml
- stream-chat-android-compose/src/main/res/values-ko/strings.xml
- stream-chat-android-compose/src/main/res/values/strings.xml
Add typing indicator component
https://user-images.githubusercontent.com/9600921/142380655-38cfe02e-6248-415c-8ecb-9169d52acfac.mov
> [Compose] Add typing indicator component

- CHANGELOG.md
- README.md
Update README with old UI module deprecation info
Check README
> Update README with old UI module deprecation info

- CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarView.kt
- stream-chat-android-ui-components/src/main/res/values/attrs_avatar_view.xml
- stream-chat-android-ui-components/src/main/res/values/styles.xml
[CAS-1421](https://stream-io.atlassian.net/browse/CAS-1421)
Improve customization of avatar. Add more possibilities for customization. Now it is possible: 
- Change shape of avatar. Rounded square was added. 
New options added in AvatarStyle
| Before - images from BE | After - avatar tye = color |
| --- | --- |
| ![Screenshot_20211119-165851](https://user-images.githubusercontent.com/10619102/142684256-befd849f-d481-4dc6-9f56-f4a25f3dee2d.png) | ![Screenshot_20211122-132154](https://user-images.githubusercontent.com/10619102/142897533-3bcdbd2b-e7fd-4dcf-871c-b49260bad30c.png) |
Customize avatar in many different ways. 
> [CAS-1421] Improvement - Avatar Customization

- CHANGELOG.md
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/handlers/ClipboardHandler.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/ChannelNameFormatter.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/MessagePreviewFormatter.kt
https://github.com/orgs/GetStream/projects/6/views/4
Make interfaces functional where possible
- Made ChannelNameFormatter interface is functional
- Made ClipboardHandler interface is functional
- Made MessagePreviewFormatter interface is functional
> [Compose] - 2658 - Make interfaces functional

- stream-chat-android-ui-components/src/main/res/values/styles.xml
Removing borders for avatar by default
Setting original width for borders
Check that borders are removed and check if some border should be there and it is not. 
> using avatar borders as 0dp

- CHANGELOG.md
- docusaurus/docs/Android/04-compose/03-channel-components/03-channel-list.mdx
- docusaurus/docs/Android/04-compose/03-channel-components/04-default-channel-item.mdx
- docusaurus/docs/Android/04-compose/03-channel-components/05-channel-info.mdx
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChannelActivity.kt
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/channel/list/ChannelItem.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/channel/list/ChannelsState.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/ChannelsScreen.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/info/ChannelInfo.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/list/ChannelItem.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/list/ChannelList.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/ChannelUtils.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channel/ChannelListViewModel.kt
https://github.com/GetStream/stream-chat-android/issues/2669
Introduce `ChannelItem` class that represents an item on the channel list screen.
> [2669] Introduce ChannelItem class

- .github/ISSUE_TEMPLATE/compose_task.md
Updated the template so it's easier & faster to create tickets.
> Made the compose task template simpler

- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/ChannelsScreen.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/header/ChannelListHeader.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/list/ChannelItem.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/header/MessageListHeader.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt
A PR with tiny UI fixes.
Channel list screen:
- Used the `Scaffold` component on the channel list screen so that the toolbar shadow is not slipped
- Proper 54dp toolbar height
- Aligned the content with 8dp guideline
- Increased the padding below unread count indicator
Message list screen: 
- Increased the size of channel avatar
- Removed user name for own message
| --- | --- |
| ![ui-before](https://user-images.githubusercontent.com/9600921/143883948-b82fe25c-b264-430b-ad81-ea520fbe5b2f.png) | ![ui-after](https://user-images.githubusercontent.com/9600921/143883960-eae2fe63-410c-410d-b390-6adc8cec7a3f.png) |
> Minor UI improvements

- .github/pull_request_template.md
I added a bit more structure to the PR template (I think in the correct place) to feature what we discussed.
Now we have 2 checklists:
- Contributor
- Reviewer
I also re-structured the Contributor checklist in two groups:
- General checklist (for setting up the PR)
- Code & documentation
> Update PR checklist for better review process

- CHANGELOG.md
- stream-chat-android-ui-components/src/main/res/values-ko/strings_attachment_gallery.xml
- stream-chat-android-ui-components/src/main/res/values-ko/strings_message_list.xml
- stream-chat-android-ui-components/src/main/res/values-ko/strings_message_list_header.xml
Improved and resolved warnings for Korean 🇰🇷  translations.
> Improve Korean translations

- README.md
- stream-chat-android-compose/README.md
Fixes #2636 
Added links and mentions of the Jetpack Compose project planning board.
> Update readme to feature Compose project management board

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/internal/AttachmentGalleryPageFragment.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/attachment/internal/AttachmentOptionsDialogFragment.kt
refer to https://developer.android.com/topic/libraries/view-binding
| --- | --- |
| img | img |
> Fix potential memory leaks in fragments

- CHANGELOG.md
- stream-chat-android-ui-components/src/main/res/values-ja/strings_common.xml
- stream-chat-android-ui-components/src/main/res/values-ko/strings_common.xml
Improve Korean and Japanese translation.
> Improve Korean and Japanese translation

- CHANGELOG.md
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventHandlerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/ChannelRepository.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/integration/ChatDomainEventDomainImplTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/utils/TestDataHelper.kt
https://stream-io.atlassian.net/browse/CAS-1491
Completely remove hard deleted messages from our persistent storage, cache and the UI.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/145586533-24153bb4-a2e3-42db-9949-f4ad411a638e.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/145584814-056e948a-8a31-4d0f-b679-4276343efcca.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
- Hard delete a message from another client
- Observe that the message is completely wiped out from the channel
> [CAS-1491] Fix hard delete message

- CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/navigation/destinations/AttachmentDestination.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentMediaActivity.kt
- stream-chat-android-ui-components/src/main/res/drawable/stream_ui_arrow_left_white.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_activity_attachment_media.xml
- stream-chat-android-ui-components/src/main/res/values/attrs_media_activity.xml
- stream-chat-android-ui-components/src/main/res/values/styles.xml
https://stream-io.atlassian.net/browse/CAS-1473
Add header to `AttachmentMediaActivity`
Added header and attributes for customization
| --- | --- |
|![Screenshot_1639385732](https://user-images.githubusercontent.com/17440581/145786219-cb73f424-2ac8-4a79-8e26-31a23108ff77.png)|![Screenshot_1639385155](https://user-images.githubusercontent.com/17440581/145786214-4a617181-9746-4650-b97f-286ae7dd6e41.png)|
Open playable content (for example video) and check the header.
Play with newly added attrs.
> [CAS-1473] Add header to AttachmentMediaActivity

- CHANGELOG.md
- docusaurus/docs/Android/03-ui/04-components/02-channel-list.mdx
- stream-chat-android-offline/api/stream-chat-android-offline.api
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/ChannelFilterRequest.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/ChatEventHandler.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/ChatEventHandlerFactory.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/DefaultChatEventHandler.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/NonMemberChatEventHandler.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/QueryChannelsController.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/integration/ChatDomainEventDomainImplTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/querychannels/NonMemberChatEventHandlerTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/querychannels/QueryChannelsControllerIntegrationTest.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/querychannels/QueryChannelsControllerTest.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/ChannelListFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/CustomEventHandler.kt
Add cached channel to chat event handler
- Added cached channel to chat event handler so it's possible to handle `MemberAdded` and `MemberRemoved` events.
- Added custom chat event handler for the sample app
| --- | --- |
|https://user-images.githubusercontent.com/17440581/147118319-14576561-f788-4233-aea8-42e59867c700.mp4| https://user-images.githubusercontent.com/17440581/147118302-90b5b472-e468-4bda-8b5c-71855901c44e.mp4|
Try to create, leave, join channels. Check if channels` list is updated properly
> Add cached channel to chat event handler

- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/previewdata/PreviewMembersData.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/DateFormatType.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/imagepreview/ImagePreviewResult.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/messages/NewMessageState.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/messages/attachments/AttachmentsPickerMode.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/ChannelsScreen.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/composer/MessageInput.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/imagepreview/ImagePreviewContract.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamDimens.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamShapes.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamTypography.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channel/ChannelViewModelFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/imagepreview/ImagePreviewViewModel.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/imagepreview/ImagePreviewViewModelFactory.kt
https://github.com/GetStream/stream-chat-android/issues/2805
Did some maintenance and resolved most of the warning shown in the IDE. 
~~- [ ] Changelog is updated with client-facing changes~~
~~- [ ] New code is covered by unit tests~~
~~- [ ] Comparison screenshots added for visual changes~~
~~- [ ] Affected documentation updated (KDocs, docusaurus, tutorial)~~
> Address warnings in the Compose codebase

- CHANGELOG.md
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
#2858 
Mentions should work in multiline.
> Added multiline pattern to mentions

- CHANGELOG.md
- DEPRECATIONS.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/MemberMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/MemberDtos.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Member.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/ChannelDtoTestData.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/ChatDatabase.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/member/MemberEntity.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/member/MemberMapper.kt
Add Member::banned and Member::channelRole properties
- Added `Member::banned` and `Member::channelRole`
- Added `MemberEntity::banned` and `MemberEntity::channelRole`
- Deprecated `Member::role`
1. Check if `Member::channelRole` contains proper data
2. Check if `Member:banned` contains proper data - try to ban/unban user in the channel
> Add Member::banned and Member::channelRole properties

- docusaurus/docs/Android/02-client/06-guides/01-push-notifications/01-overview.mdx
Fix docs style 
| --- | --- |
| ![Screenshot from 2022-01-17 16-29-47](https://user-images.githubusercontent.com/4047514/149798559-a66006d5-8ed4-436f-9481-70a8ea440cef.png) | ![Screenshot from 2022-01-17 16-30-00](https://user-images.githubusercontent.com/4047514/149798618-81cea2c9-3d87-452b-8a6d-9c95ea9e3962.png) |
- ~~[ ] Changelog is updated with client-facing changes~~
- ~~[ ] New code is covered by unit tests~~
- ~~[ ] UI Components sample runs & works~~
- ~~[ ] Compose sample runs & works~~
- ~~[ ] UI Changes correct (before & after images)~~
- ~~[ ] Bugs validated (bugfixes)~~
- ~~[ ] New feature tested and works~~
- ~~[ ] All code we touched has new or updated KDocs~~
> Fix docs style

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
follow up of PR: #2962
Remove unused code
Removing the code
> [ISSUE-2962] Removing unused method

- hooks/pre-commit
Just fixing a commit hook to use spotless instead of ktlint
> Fix commit hook to use spotless

- CHANGELOG.md
- docusaurus/docs/Android/03-ui/05-components/02-channel-list.mdx
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/ChannelExtension.kt
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/ChannelList.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/shared/ChatInfoSharedGroupsViewHolderFactory.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/ChatUI.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/ChannelNameFormatter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/Channel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/header/viewmodel/MessageListHeaderViewBinding.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/LazyVarDelegate.kt
Create `ChannelNameFormatter` interface, expose it via `ChatUI` and implement the `DefaultChannelNameFormatter` class based on `Channel.getDisplayName` implementation.
There should be now changes:
| --- | --- |
| ![photo_2022-02-10 14 14 36](https://user-images.githubusercontent.com/9600921/153396068-c4bb7377-ed01-4edc-a1b6-95c2bcaa3dcc.jpeg) | ![photo_2022-02-10 14 15 28](https://user-images.githubusercontent.com/9600921/153396156-ecfcb63f-197c-4db3-95eb-ad65f7030ccc.jpeg)|
| ![photo_2022-02-10 14 14 41](https://user-images.githubusercontent.com/9600921/153396063-891dcea4-f929-4c89-99c0-f5079d50a615.jpeg) | ![photo_2022-02-10 14 15 31](https://user-images.githubusercontent.com/9600921/153396150-31f7e270-e463-4e84-beeb-f6d4458a73f9.jpeg)  |
1. Implement a custom …
> [3047] Add ChannelNameFormatter

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/errorhandler/ErrorHandler.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/errorhandler/factory/ErrorHandlerFactory.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/errorhandler/factory/NoOpErrorHandlerFactory.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/errorhandler/listeners/DeleteReactionErrorHandler.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/factory/PluginFactory.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/listeners/DeleteReactionListener.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ConnectUserTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/BaseChatClientTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/DevTokenTest.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
- stream-chat-android-offline/api/stream-chat-android-offline.api
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/errorhandler/OfflineErrorHandler.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/errorhandler/factory/OfflineErrorHandlerFactory.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/errorhandler/listener/DeleteReactionErrorHandlerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/DeleteReactionListenerImpl.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
Introduce an error handler for handling errors produced by `OfflinePlugin`
Add `ErrorHandler` interface and `OfflineErrorHandler` implementation.
Run the app, try to delete the reaction offline.
> Introduce error handler

- CHANGELOG.md
- docusaurus/docs/Android/03-ui/03-chatui.mdx
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/DateFormatter.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/ChatUI.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mention/list/MentionListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mention/list/internal/MentionListAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/preview/internal/MessagePreviewView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/pinned/list/PinnedMessageListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/pinned/list/internal/PinnedMessageListAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/internal/SearchResultListAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/list/SearchResultListView.kt
Closes #2883 
Add a way to customize date/time formatters.
Should be no difference:
| --- | --- |
| ![photo_2022-02-16 13 05 31](https://user-images.githubusercontent.com/9600921/154241953-78c01c12-a4b7-4d07-8595-74391eb32f3f.jpeg) | ![photo_2022-02-16 13 06 28](https://user-images.githubusercontent.com/9600921/154242078-a1b0834a-33ec-426e-8c88-d46c4a48d18f.jpeg) |
| ![photo_2022-02-16 13 05 29](https://user-images.githubusercontent.com/9600921/154241947-f5ff15a5-6e8a-4b5e-8fba-bf9c36a09d69.jpeg) | ![photo_2022-02-16 13 06 25](https://user-images.githubusercontent.com/9600921/154242072-89478c48-c7e3-47f1-bb65-d8904d820f72.jpeg) |
1. Apply the patch below:
2. Observe custom channel name and date formatters
<details>
<summary>Patch file to …
> [2883] Add possibility to customizae date formatters

- CHANGELOG.md
- build.gradle
- buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/build.gradle
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/navigation/destinations/AttachmentDestination.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentMediaActivity.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_activity_attachment_media.xml
Removed `ExoPlayer` dependency from the project.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/154756619-925718b9-0b4a-4dbb-ac86-973776c205ac.mp4" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/154756647-23e73b18-2c5e-45fb-a0c7-fa090a102ff8.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
1. Launch the UI Components sample app
2. Open a video or audio attachment
> [2880] Remove ExoPlayer from UI components

- stream-chat-android-offline/api/stream-chat-android-offline.api
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/extensions/ChatClient.kt
> Expose GlobalState

- buildSrc/build.gradle.kts
Bump Moshi to 1.13.0 in buildSrc following #3104. Related to #1856.
> Bump Moshi to 1.13.0 in buildSrc

- .github/workflows/release-automation.yaml
Change release automation trigger
> Change release automation trigger

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
- stream-chat-android-offline/api/stream-chat-android-offline.api
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/state/ChannelState.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/errorhandler/factory/OfflineErrorHandlerFactories.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/extensions/ChatClient.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/interceptor/DefaultInterceptor.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/configuration/Config.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/factory/StreamOfflinePluginFactory.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/state/StateRegistry.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/querychannels/state/QueryChannelsState.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
closes #2909 
Cleanup Offline Plugin related code.
1. Remove unused `*Internal` methods
2. Add a few missing KDocs
3. Make state-related things public 
4. Simplify OfflinePlugin initialization by initializing `OfflineErrorHandlers` inside `StreamOfflinePluginFactory `.
Run sample apps.
> Cleanup Offline Plugin related code

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
Improve the message of a problem in MoshiChatApi. Based on question in Zendesk.
Just changing the message
> Adding hint of problem in MoshiChatApi

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/AndroidIntroduction.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ClientAndUsers.java
Very trivial refactor to use `setUser` and `setImage` methods for Java docs.
> Refactor to setUser and setImage methods for Java docs

- CHANGELOG.md
- DEPRECATIONS.md
Update DEPRECATIONS and CHANGELOG.
Take a look at DEPRECATIONS.md and CHANGELOG.md
> Update DEPRECATIONS and CHANGELOG

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_file_attachments.xml
Smaller fixes and improvements. 
Added padding to file items.
Fixed the way commands dismiss works.
> Minor fixes for UI

- stream-chat-android-compose/build.gradle
Update maven version for Jetpack Compose module. Now we can use the `rootVersionName`.
> Update maven version for Jetpack Compose module

- docusaurus/docs/Android/02-client/06-guides/01-push-notifications/01-overview.mdx
Remove outdated info from Push Notifications docs
Run ```npx stream-chat-docusaurus -i -s```, go to the push notifications page and make sure the info is not there.
> Update Push Notifications docs

- CHANGELOG.md
- README.md
- stream-chat-android-compose/GUIDELINES.md
Summarize and write down our Compose SDK guidelines for internal and external contributors.
> [2917] Write Compose SDK Guidelines

- stream-chat-android-markdown-transformer/detekt-baseline.xml
- stream-chat-android-markdown-transformer/src/main/kotlin/io/getstream/chat/android/markdown/ItalicFix.kt
Fix issues we had on Markdown Transformer Module 
Fixes https://github.com/GetStream/android-internal-board/issues/21
- ~[ ] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui)~
> Fix Detekt Issues on markdown-transformer module

- README.md
Add an API level badge below on README:
<p>
<a href="https://android-arsenal.com/api?level=21"><img alt="API" src="https://img.shields.io/badge/API-21%2B-brightgreen.svg?style=flat"/></a>
</p>
> Add an API level badge on README

- .github/workflows/apk-s3-distribute.yml
- .github/workflows/publish.yml
> Fix publish actions trigger

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/ChannelMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/EventMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/ChannelDtos.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/EventDtos.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/ChannelResponse.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Channel.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/ChannelDtoTestData.kt
- stream-chat-android-compose-sample/src/main/AndroidManifest.xml
- stream-chat-android-compose-sample/src/main/res/xml/network_security_config.xml
- stream-chat-android-offline/api/stream-chat-android-offline.api
- stream-chat-android-offline/detekt-baseline.xml
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/internal/Channel.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/model/channel/ChannelData.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/converter/internal/MemberConverter.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/ChatDatabase.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/ChannelEntity.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/ChannelMapper.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/Mother.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/utils/TestDataHelper.kt
- stream-chat-android-ui-components-sample/src/main/AndroidManifest.xml
- stream-chat-android-ui-components-sample/src/main/res/xml/network_security_config.xml
Support `Channel.membership` property
[Channel membership property lifecycle](https://www.notion.so/stream-wiki/Android-Channel-membership-property-lifecycle-fc01903e4c7a4c7cae2498a061aa1375)
Check databases, table `stream_chat_channel_state`, column `membership` 
> [3320] support membership property

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/state/StateRegistry.kt
Fix checking if the channel is active.
1. Sign in as User1 and stay on the channels list
2. Send some messages from another device
3. Channel list on device 1 should be updated properly
> Fix checking if the channel is active

- .github/workflows/publish-v4.yml
Add action for publishing v4.X.X.
> Add action for publishing v4.X.X

- CHANGELOG.md
- buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/LongClickFriendlyLinkMovementMethod.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/Manufacturer.kt
Release 4.30.2 version.
Contains following PRs:
- #3491 
- #3499 
Run sample apps.
> Update to version 4.30.2 

- .github/workflows/publish-v4.yml
Chane Publish_v4 action trigger.
> Chane Publish_v4 action trigger

- .github/workflows/publish-v4.yml
Add workflow_dispatch to Publish_v4 script
> Add workflow_dispatch to Publish_v4 script

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaPreviewActivity.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_activity_attachment_media.xml
Closes #3497
Fix an issue with video scaling.
| --- | --- |
| ![photo_2022-05-23 10 12 03](https://user-images.githubusercontent.com/9600921/169763696-6c89ac1b-d754-41d4-be48-78e3432a2bf0.jpeg) | ![photo_2022-05-23 09 58 21](https://user-images.githubusercontent.com/9600921/169761555-5253d8fa-422b-436d-9f4b-ea80fd2dc514.jpeg) |
| --- | --- |
| ![photo_2022-05-23 10 11 38](https://user-images.githubusercontent.com/9600921/169763580-87632e9f-998d-45e5-9fd0-b143fa928d37.jpeg) | ![photo_2022-05-23 09 58 39](https://user-images.githubusercontent.com/9600921/169761609-00c3187f-887a-4480-8905-51f4d1472406.jpeg) |
1. Send this video to a channel: https://user-images.githubusercontent.com/9600921/169764400-95a8625f-e832-4cf2-99bb-6cade5507fdc.mp4
2. Enable …
> [3497] Fix video scaling

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QuerySort.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/errorhandler/internal/QueryMembersErrorHandlerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/internal/Channel.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/state/querychannels/internal/QueryChannelsMutableState.kt
issue: https://github.com/GetStream/stream-chat-android/issues/3571
Adding logs for QuerySort.
Take a looks at the logs.
> Logging query sort

- .github/workflows/clean-detekt-baseline.yaml
- .github/workflows/no-response.yml
- .github/workflows/snapshot-record.yaml
- .github/workflows/snapshot-tests.yaml
Closes #3579
Use develop branch for snapshot tests
> [3579] Use develop branch for snapshot tests

- .github/workflows/release-start.yaml
Adding branch to tag creation
It was tested in a fork of this repo.
-~ [ ] Comparison screenshots added for visual changes~
> Adding branch for tag creation

- spotless/spotless.gradle
- stream-chat-android-compose-sample/detekt-baseline.xml
- stream-chat-android-compose/detekt-baseline.xml
- stream-chat-android-core/detekt-baseline.xml
- stream-chat-android-offline/detekt-baseline.xml
- stream-chat-android-ui-common/detekt-baseline.xml
- stream-chat-android-ui-components-sample/detekt-baseline.xml
- stream-chat-android-ui-components/detekt-baseline.xml
- stream-chat-android-ui-uitests/detekt-baseline.xml
Remove spotless header from detekt baseline files
> Remove spotless header from detekt baseline files

- .github/workflows/apk-s3-distribute.yml
- .github/workflows/publish-hotfix.yml
Add an action for publishing hotfixes
> Add an action for publishing hotfixes

- CHANGELOG.md
- buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/FieldSearcher.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QuerySort.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/internal/CompositeComparator.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/StringExtensions.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/extensions/StringExtensionsKtTest.kt
Prepare 5.3.1 release.
Releasing #3608.
Check if sample apps work correctly.
> Prepare 5.3.1 release

- CHANGELOG.md
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
Log when an increment happens in channel unread count.
Check the logs
> Logging unread count change

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerSequential.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/sync/internal/SyncManager.kt
Add logs & decompose `SyncManager.connectionRecovered` method
Just run any sample app and make sure you can send/receive new messages.
> [3555] add uncaught exceptions for coroutine & more logging

- stream-chat-android-core/detekt-baseline.xml
- stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/Call.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/client/utils/Result.kt
Fix Detekt Issues on Core Module
> Fix Detekt Issues on Core Module

- CHANGELOG.md
- stream-chat-android-offline/detekt-baseline.xml
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerImpl.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerSequential.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/model/SelfUser.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/utils/SelfUserUtils.kt
- stream-chat-android-ui-components/detekt-baseline.xml
Fix mutes drop on user-related events
<details>
```
Index: stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt
<+>UTF-8
diff --git a/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt b/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt
--- a/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt	(revision …
```
> [3628] Updating the current user resets channel mutes

- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/ChatUIInitializer.kt
Closes #3740 
Fix video thumbnails in the attachments picker
> [3740] Fix video thumbs

- CHANGELOG.md
- docusaurus/docs/Android/01-basics/04-getting-started.mdx
Add more information about `ChatClient::connectUser` behavior
Check `CHANGELOG` and docs.
> Add more information about ChatClient::connectUser behavior

- CHANGELOG.md
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
Fix `app:streamUiMessageInputHintText` not getting applied.
Apply hint from styles to `MessageInputView`.
<details>
```
Index: stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat.xml
<+>UTF-8
diff --git a/stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat.xml b/stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat.xml
--- a/stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat.xml	(revision 3bf4ab1ae1894b48c5240781f0fe66e409bdcc66)
+++ …
```
> Fix streamUiMessageInputHintText property not getting applied properly

- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/images/CoilStreamImageLoader.kt
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/images/RoundedCornersTransformation.kt
Detailed description can be found in the original issue here: https://github.com/GetStream/stream-chat-android/issues/3750
Created a duplicate `RoundedCornersTransformation` rolled back to the previous version of determining destination width and height.
| --- | --- |
| ![before_coil_duplicate](https://user-images.githubusercontent.com/37080097/175290082-0ba880d6-7f03-4924-926c-60e0899aeb90.png) | ![after_coil_duplicate](https://user-images.githubusercontent.com/37080097/175290090-87a1f879-e3b3-4b91-8c2e-322d463c873d.png) |
Apply the patch that turns on rounded corner avatars and test everything with a rounded corner shape that you can find.
Note: **Both Compose and UI Components samples should be tested as this affects both**
<details> …
> [3750] Fix link attachment previews

- .github/pull_request_template.md
Update the PR template so that it includes the proper patch formatting.
Reasoning is that it's easier to delete if not needed than write if needed.
> Update the PR template so that it includes patch formatting

- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/MessagesActivity.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/ChannelsScreen.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerImpl.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/message/attachments/internal/UploadAttachmentsWorker.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/EditMessageListenerImpl.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryDestination.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/overview/MediaAttachmentGridView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
Refactor codes to remove IDE warnings.
> Refactor codes to remove IDE warnings

- stream-chat-android-ui-common/detekt-baseline.xml
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/Linkify.kt
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/MessageFooterVisibility.kt
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.kt
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/MessageOptionsUserReactionAlignment.kt
Resolve ui-common detekt issues.
Resolve ui-common detekt issues.
> Resolve ui-common detekt issues

- .github/CODEOWNERS
> Add state module to CODEOWNERS

- .github/pull_request_template.md
Add video section to PR template.
> Add video section to PR template

- .github/workflows/app-distribute.yml
- .github/workflows/publish.yml
- .github/workflows/release-docs.yaml
- .github/workflows/release-post.yaml
- .github/workflows/release-start.yaml
Create a release process that uses a release branch instead of doing the work in the `develop` and `main` branches.
Now this can happen in the `release-post.yml`, because the success of this step is not mandatory for the release to happen. If it fails, the release can happen and this can be fixed manually. 
The automation bumps version and changes changelog in the `release` branch. Then it syncs with main branch and then creates a PR to develop. The process is:
1 - Developer creates the `release` branch from `develop`
2 - Developer triggers ReleaseStart in `release` branch
3 - Automation bump the version, updates changelog and does the release in github.
4 - Automation publishes the artifact. 
5 - Automation publishes documentations, syncs release with main, creates the PR to develop from …
> Adding new flows

- scripts/sample-app-versioner.gradle
Adding release to branches of App Test release.
- ~[ ] PR targets the `develop` branch~
> Adding release to branches

- .github/workflows/release-start.yaml
Fix `ReleaseStart` Action.
Change ref branch from `develop` to `release`.
> Fix ReleaseStart Action

- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/DateFormatter.kt
> Fix DateFormaterTests

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QueryChannelRequest.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
- stream-chat-android-state/api/stream-chat-android-state.api
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/SearchLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/channel/internal/ChannelMutableStateImpl.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/internal/ChatClientStateCalls.kt
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatViewModel.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoViewModel.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/GroupChatInfoViewModel.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/users/GroupChatInfoAddUsersViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/actions/internal/ChannelActionsViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/header/viewmodel/MessageListHeaderViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/typing/viewmodel/TypingIndicatorViewModel.kt
> Fixing message preview

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ShuffleGiphyListenerComposite.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ShuffleGiphyListenerDatabase.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/ShuffleGiphyListenerDatabaseTest.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ShuffleGiphyListenerState.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
- stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/ShuffleGiphyListenerStateTest.kt
Separate ShuffleGiphyListenerImpl into state and database
Created 2 new classes and an aggregation class. 
Shuffle some giphys =P
_Shuffling!! \o| \o/ \o| |o/ \o/_
> [ISSUE-3709] Shuffle giphy listener impl separation

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/AddDeviceRequest.kt
Rename field of name of optional provider. Conforming with documentation: https://getstream.io/chat/docs/react/push_devices/?language=kotlin#register-a-device
_Just a little push..._
> [ISSUE-4007] Field rename for AddDeviceRequest

- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatApp.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt
The new socket implementation is not working correctly when switching users.
Disabling new implementation in debug until we merge #3996 
> Disable new socket implementation

- docusaurus/docs/Android/02-client/06-guides/03-channel-list-updates.mdx
Minor formatting fix for docusaurus.
Before:
After:
Here's a tortoise:
> Minor formatting fix

- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/sync/internal/SyncManager.kt
Fix the retry logic.
- run any Sample app
- send a message
- turn on the Airplane mode
- delete the message
- turn off the Airplane mode
**Actual**: Delete request is NOT being fired to BE
**Expected**: Delete request is being fired to BE
> [3879] move retryFailedEntities invocation before the syncing

- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamColors.kt
- stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/CatalogActivity.kt
> Guides color fix

- CHANGELOG.md
- buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
Closes #4087
Fix `useSequentialEventHandler` config parameter.
***Test new event handler**
1. Run UI Components sample app
2. Verify that there are entries with `Chat::EventHandlerSeq` tag in logcat
**Test old events handler:** 
1. Pass `useSequentialEventHandler = false`
2. Run UI Components sample app
3. Verify that there are entries with Chat:EventHandlerOld tag in logcat
> [4087] Fix event handler config parameter

- CHANGELOG.md
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt
Fix online count
| --- | --- |
| img | img |
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<details>
```
```
</details>
> [4072] Fix online count

- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatApp.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt
Enable Experimental Websocket implementation on sample apps
> Enable Experimental Websocket implementation on sample apps

- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/AndroidIntroduction.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/AndroidIntroduction.kt
closes #4118 
Update Android Introduction snippets.
Changed the way we pass `image` and `name`.
Check the snippets [here](https://getstream.io/chat/docs/android/?language=kotlin) after they are published.
> Update Android Introduction snippets

- README.md
https://github.com/GetStream/android-internal-board/issues/50
Reference Android-Samples repo in the main readme.
> [50] Add link to Android-Samples repo

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/ChatDatabase.kt
Room DAOs were updated but the DB version wasn't. Room throws an exception because the data structure has changed:
```
Room cannot verify the data integrity. Looks like you've changed the schema but forgot to update the version number. You can simply fix this by increasing the version number.
```
Use the sample app without this code change. After that compile this new code change and install it on the same device without clear data of the app. The Sample App should work as normal.
> Update db version

- .github/workflows/check-entities.yml
Whenever an `@Entity` of our DB is updated, we need to update the structure of our DB. To do that on Room, we need to upgrade the Version number (And process any migration on the case it is needed).
If we don't upgrade it, a runtime exception is thrown when Room is instanciated
Fix #4150
A comment like this one is posted on every PR that contains any `@Entity` update
> GH-Action to check DB Entities

- buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
Prepare V6 Config on `develop` branch
> Update Configuration Version to be prepared for V6

- docusaurus/docs/Android/02-client/06-guides/03-channel-list-updates.mdx
> Fix Broken Link

- docusaurus/docs/Android/03-ui/06-guides/10-customizing-message-list-scroll-behavior.mdx
Added a guide for customizing the default scrolling behavior of the MessageListView.
Related to #4215 
- Docusaurus should render properly and show this page in the list in UI Component guides
- The docs should make sense and be accurate
> Add docs for customizing scrolling behavior of MessageListView

- stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/ui/BaseUiTest.kt
- stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/util/FakeImageLoader.kt
https://github.com/GetStream/android-internal-board/issues/56
After refactoring avatars to ShapeableImageView, something happened to avatar backgrounds (and probably backgrounds of all the ImageViews clipped by clip path). Happens only when running snapshots tests.
| --- | --- |
| ![io getstream chat android uitests snapshot uicomponents components ChannelAvatarTest_channelAvatarForChannelWithFiveMembers](https://user-images.githubusercontent.com/9600921/194847889-8b8761b9-1c12-4cd3-9104-efb2c1127c27.png) | ![io getstream chat android uitests snapshot uicomponents components ChannelAvatarTest_channelAvatarForChannelWithFiveMembers](https://user-images.githubusercontent.com/9600921/194848634-8d3631d8-b5da-4841-915a-b669f037bf62.png) |
Execute …
> [56] Fix avatar snapshot tests

- stream-chat-android-compose-sample/build.gradle
- stream-chat-android-docs/build.gradle
- stream-chat-android-ui-common/build.gradle
- stream-chat-android-ui-components-sample/build.gradle
- stream-chat-android-ui-guides/build.gradle
- stream-chat-android-ui-uitests/build.gradle
Separate offline module from UI module. 
Remove offline module from ui-common in gradle.
> Removing offline from ui common module in gradle

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Make events work again in the SDK.
- Moving `plugins.forEach { it.onUserSet(user) }`  in a later stage of the SDK initialization. 
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/194939491-18dd6580-2a0e-40a8-85ce-a54262aaf833.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/194939527-c6dc9bbd-2253-4a72-84a4-d895ef3974aa.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Send messages to the sample app and check that they are arriving. 
_Ops D=_
> [ISSUE-4264] Moving plugins.forEach { it.onUserSet(user) } after plugins are created

- CHANGELOG.md
- stream-chat-android-ui-components/src/main/res/values-night/colors.xml
- stream-chat-android-ui-components/src/main/res/values-v23/themes.xml
- stream-chat-android-ui-components/src/main/res/values-v29/themes.xml
- stream-chat-android-ui-components/src/main/res/values/colors.xml
- stream-chat-android-ui-components/src/main/res/values/styles.xml
- stream-chat-android-ui-components/src/main/res/values/themes.xml
https://github.com/GetStream/stream-chat-android/issues/4091
Improves how embedded Activities handle status bar and navigation bar colors.
There are several main Activities shipped with UI Components SDK:
**Attachment gallery screen**
```xml
<activity
android:name=".gallery.AttachmentGalleryActivity"
android:theme="@style/StreamUi.AttachmentGallery"
android:exported="false" />
```
**Media preview screen**
```xml
<activity
android:name=".gallery.AttachmentMediaActivity"
android:theme="@style/StreamUi.MediaActivity"
android:exported="false" />
```
**Websites, youtube and giphy preview screen**
```xml
<activity
android:name=".gallery.AttachmentActivity"
android:theme="@style/StreamUi.AttachmentActivity"
android:exported="false" />
```     
All the Activities have explicitly defined themes. …
> [4091] Fix status bar colors in XML

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
Remove unneeded cache on factories
> Remove cache from factories

- .github/actions/gradle-cache/action.yml
- .github/workflows/apk-s3-distribute.yml
- .github/workflows/app-distribute.yml
- .github/workflows/build-and-test.yml
- .github/workflows/check-entities.yml
- .github/workflows/clean-detekt-baseline.yaml
- .github/workflows/docusaurus-staging.yml
- .github/workflows/localazy-download.yml
- .github/workflows/localazy-upload.yml
- .github/workflows/no-response.yml
- .github/workflows/pr-checks.yml
- .github/workflows/publish-hotfix.yml
- .github/workflows/publish-snapshot.yml
- .github/workflows/publish.yml
- .github/workflows/release-docs.yaml
- .github/workflows/release-post.yaml
- .github/workflows/release-start-test.yaml
- .github/workflows/release-start.yaml
- .github/workflows/snapshot-record.yaml
- .github/workflows/snapshot-tests.yaml
Update Ubuntu Runners Version to 22.04, previous one will be deprecated at the end of this year.
Actions has been upgraded as well to the last version to avoid some Warning Messages:
-. actions/cache@v3.0.11
-. actions/setup-java@v3.5.1
-. actions/checkout@v3.1.0
-. actions/upload-artifact@v3.1.0
> Update Ubuntu Runners Version to 22.04

- stream-chat-android-core/api/stream-chat-android-core.api
- stream-chat-android-core/src/main/java/io/getstream/chat/android/client/Result.kt
The first part of the `Result` class refactor.
Added a new `Result` class definition which will replace the old one.
Check the new `Result` class definition.
> Add new Result class definition

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Improve `ChatClient::connectGuestUser` readability.
Remove unnecessary wrapping with the `Result` class
> Improve ChatClient::connectGuestUser readability

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/state/ClientMutableState.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/state/ClientState.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/Mother.kt
Remove ClientState.clearState 
The CI is enough in this case.
> Removing ClientState.clearState

- .github/workflows/publish-beta.yml
Add action for publishing the beta version.
Publish will be triggered on `vX.Y.Z-betaN` tag, where `X, Y, Z, N = [0,9]+`
> Add publish beta action

- CHANGELOG.md
- buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
Prep for v6 beta release for our blog post
> v6 beta1 preparation

- docusaurus/docs/Android/03-ui/04-message-components/01-message-list-screen.mdx
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ui/messages/MessageListScreen.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageListScreen.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/MessageListActivity.kt
Small improvement for https://github.com/GetStream/stream-chat-android/pull/4390
> [4385] Improve message list screen docs

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-core/api/stream-chat-android-core.api
- stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/WithPreconditionCall.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/client/utils/Result.kt
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/AndroidIntroduction.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Channels.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/ClientAndUsers.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Events.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Messages.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Moderation.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/UnreadCounts.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/UserPermissions.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/UserPresence.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/docusaurus/CoreConcepts.java
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/listener/internal/QueryChannelListenerState.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/sync/internal/SyncManager.kt
Add `Result::getOrNull`, `Result::getOrThrow` and `Result::chatErrorOrNull`.
1. Added two properties to the `Result` class to simplify getting `value` for Java users
2. Converted `onSuccess` and `onError` from extension functions to methods
3. Removed `@JvmSynthetic` from some result's method
Just check the implementation of the methods.
> Add properties for getting Result's value

- stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/messages/MessageContainerTest.kt
- stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/messages/MessageItemTest.kt
Fix compilation error in android test source set.
> Fix compilation error

- docusaurus/docs/Android/03-ui/06-guides/05-app-startup-initializers.mdx
Closes https://github.com/GetStream/stream-chat-android/issues/4431
Update app startup initializes guide
Launch docusaurus with `npx stream-chat-docusaurus -i -s`, and ensure that the changes look good.
> [4431] Update app startup initialiers guide

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
Fixing mistake of postponeCall. 
Check the loading of channels when no data is available in database.
> Reverting sugar syntax for postponeCall

- CHANGELOG.md
- buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/configuration/Config.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/interceptor/internal/SendMessageInterceptorImpl.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/message/attachments/internal/AttachmentUploader.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/message/attachments/internal/UploadAttachmentsAndroidWorker.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/message/attachments/internal/UploadAttachmentsWorker.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/sync/messages/internal/SyncMessagesWork.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/configuration/StatePluginConfig.kt
Add more logs to sending messages with attachments.
> Add more logs to sending message with attachments

- docusaurus/docs/Android/02-client/06-guides/02-handling-user-connection.mdx
- docusaurus/docs/Android/02-client/06-guides/05-channel-list-updates.mdx
- docusaurus/docs/Android/02-client/06-guides/08-optimizations.mdx
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Update `HandlingUserConnection`, `Optimizations` and `ChannelListUpdates` pages.
Made small changes to the pages mentioned above.
Check the changes.
> Update core docs

- buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/HttpLoggingInterceptor.kt
Upgrade StreamLog dependency to version 1.0.2
> Upgrade StreamLog dependency to version 1.0.2

- CHANGELOG.md
- buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
Prep for release - changelog and versions
> Prep for release

- docusaurus/android_versioned_docs/version-5.x.x/03-ui/02-general-customization/02-chatui.mdx
- docusaurus/docs/Android/03-ui/02-general-customization/02-chatui.mdx
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ui/general/Configuration.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/general/Configuration.kt
Closes https://github.com/GetStream/stream-chat-android/issues/4315
Mutate Drawables in the docs where necessary.
> [4315] Update reactions docs

- CHANGELOG.md
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/Attachment.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/extensions/ChatClient.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/extensions/internal/Attachment.kt
Merge `main` into `develop` after publishing a v5 release.
Validate changes and launch both apps to check that they are working properly
> [After v5 release procedure] Merge `main` to `develop`

- CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/viewmodel/factory/MessageListViewModelFactory.kt
Give the users the ability to define page size.
Added `messageLimit` parameter to `MessageListViewModel` and `MessageListViewModelFactory`.
1. Apply the patch
2. Run the XML sample
3. Enter a channel and page
4. Try to change the page size and retest to see if everything is working correct.
<details>
<summary>Page patch</summary>
```
Index: stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
<+>UTF-8
diff --git a/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt …
```
> Add MessageListViewModel message limit

- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/DatabaseChannelRepository.kt
Include forgotten last commit for PR #4633
Sorry I thought I added this commit before merging =|
> [ISSUE-4625] Forgotten commit

- CHANGELOG.md
- buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
Release `v5.12.0`.
Updated the version and cleaned up the changelog.
> [v5] Prepare `v5.12.0` for release

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/state/ChannelState.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/channel/internal/ChannelMutableState.kt
- stream-chat-android-state/src/test/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogicTest.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListItem.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListItemPayloadDiff.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/internal/MessageListItemAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/internal/MessageListItemDiffCallback.kt
Make changes for messages reflect in all replies. 
The PR adds a map to keep all quoting messages in order to get a reference of then without search all messages at once. 
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/214630549-2b108604-b172-4ecc-af9c-f4722f1bb041.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/214630523-35277881-1476-4d24-b5f0-57548fc43c70.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Edit a message that is quoted by other messages and check that all the messages are updates, not only the original one. 
_I mean, "Quotes", right??_
> [ISSUE-4644] Reflecting edit to quoting messages

- .github/workflows/app-distribute.yml
Add triggering app-distribute workflow on push to v5
> Add triggering app-distribute workflow on push to v5

- buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
V5 new version.
Bump the minor version number.
> v5 version bump

- CHANGELOG.md
Prepare changelog for release.
Prepare changelog for release.
> v5 changelog cleanup

- buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
Update the version prior to release.
> - Bump version in preparation for a release

- CHANGELOG.md
Update the changelog prior to releasing.
> - Update the changelog prior to releasing v5.14.0

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/RepositoryFacade.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/QueryChannelListenerDatabase.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventBatchUpdate.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/querychannels/internal/QueryChannelsDatabaseLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/querychannels/internal/QueryChannelsLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/sync/internal/SyncManager.kt
- stream-chat-android-state/src/test/java/io/getstream/chat/android/state/facade/RepositoryFacadeTests.kt
> Remove duplicate logic storing channels state

- docusaurus/docs/Android/02-migration-guides/01-client/01-push-notifications.mdx
Add Migration guides for PN
Close: #4763
> Add Migration guides for PN

- CHANGELOG.md
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/list/ChannelItem.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/channels/MessageReadStatusIcon.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageFooter.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
- stream-chat-android-core/api/stream-chat-android-core.api
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/Message.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/ChannelListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/internal/ChannelViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListViewStyle.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListItem.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/internal/MessageListItemDecoratorProvider.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/FootnoteView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/decorator/internal/FootnoteDecorator.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Channel.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_item_foreground_view.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_footnote.xml
- stream-chat-android-ui-components/src/main/res/values/attrs_channel_list_view.xml
- stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml
- stream-chat-android-ui-components/src/main/res/values/styles.xml
Add count of read messages. 
| --- | --- |
| ![Screenshot 2023-02-16 at 15 48 06](https://user-images.githubusercontent.com/10619102/219397776-ba7860fb-b054-4e20-9a25-6af711c43d1d.png) | ![Screenshot 2023-02-16 at 15 45 52](https://user-images.githubusercontent.com/10619102/219397102-9d0568d1-6e79-4c49-b421-ccd411062910.png) |
| ![Screenshot 2023-02-16 at 15 48 12](https://user-images.githubusercontent.com/10619102/219397781-39b57a57-bc6b-4ad2-b9f3-c8f3a4475bf2.png) | ![Screenshot 2023-02-16 at 15 46 03](https://user-images.githubusercontent.com/10619102/219397106-ebff7a1f-8c47-4658-b5a8-0130f784dd40.png) |
Send a message and read it with other users and check that the count increments. 
- ~[ ] New code is covered …
> [ISSUE-4677] Count for read messages

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/UserStateService.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatNotifications.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/experimental/ChatSocketStateService.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/experimental/ChatSocketStateServiceTest.kt
Create a method to clear local data even if the user is not connected.
> Clear persistence (V5)

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/UserStateService.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatNotifications.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/ChatSocketStateService.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/experimental/ChatSocketStateServiceTest.kt
Create a method to clear local data even if the user is not connected.
> Clear persistence v6

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
Allow "unselect a message" if null is passed
Fix: #4726
> Allow "unselect a message" if null is passed

- CHANGELOG.md
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
Allow "unselect a message" if null is passed
> Unselect message (V6)

- CHANGELOG.md
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ui/general/Configuration.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/general/Configuration.kt
- stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
- stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/DateFormatter.kt
Closes: https://github.com/GetStream/android-internal-board/issues/64
| --- | --- |
| img | img |
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<details>
```
```
</details>
> [64] allow format messages with date & time

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/AddMembersRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Channels.java
Closes: https://github.com/GetStream/android-internal-board/issues/68
> [i68] Add hide_history flag support while adding members

- CHANGELOG.md
- docusaurus/docs/Android/02-client/02-channels.mdx
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/querysort/QuerySortByField.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/ChannelApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/InviteMembersRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Channels.java
Closes: https://github.com/GetStream/android-internal-board/issues/69
> [i69] Add members invitation functionality

- CHANGELOG.md
- docusaurus/android_versioned_docs/version-5.x.x/02-client/02-channels.mdx
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/ChannelApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/InviteMembersRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/querysort/QuerySortByField.kt
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Channels.java
Closes: https://github.com/GetStream/android-internal-board/issues/69
>  [i69] Add members invitation functionality

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/StreamLifecycleObserver.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/UserStateService.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/network/NetworkStateProvider.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/ChatSocket.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/ChatSocketStateService.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/HealthMonitor.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/internal/toggle/dialog/ToggleDialogController.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/internal/toggle/dialog/ToggleDialogFragment.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ConnectUserTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/BaseChatClientTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/clientstate/UserStateServiceTests.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/debugger/ChatClientDebuggerTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/FakeChatSocket.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/experimental/ChatSocketStateServiceTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/observable/ChatEventsObservableTest.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/StartupActivity.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/login/CustomLoginActivity.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/login/UserLoginActivity.kt
- stream-chat-android-core/api/stream-chat-android-core.api
- stream-chat-android-core/src/main/java/io/getstream/chat/android/core/internal/fsm/FiniteStateMachine.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/InitializationState.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/user_login/UserLoginViewModel.kt
Improve how our connectUser logic works to allow offline connections without waiting the connection result
> Improve connect user logic

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/TextUtils.kt
- stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/Linkify.kt
- stream-chat-android-ui-utils/src/main/kotlin/io/getstream/chat/android/uiutils/extension/String.kt
Make emails clickable in messages
Closes: https://github.com/GetStream/android-internal-board/issues/72
| --- | --- |
| ![email_before](https://github.com/GetStream/stream-chat-android/assets/1286516/d8a69f6f-05b3-4522-847e-cf91aed4c877) | ![email_after](https://github.com/GetStream/stream-chat-android/assets/1286516/22438203-1922-4c86-a620-72d4bf13011f) |
- open Compose or XML app
- go to any Channel
- post a message with email
- make sure email is highlighted 
- tap on email
- make sure you're redirected to an email app
> [i72] make emails clickable in messages

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/ChannelExtension.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogic.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Channel.kt
Notify member changes on channel list
> Notify member changes on channel list

- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/viewmodel/MessageListViewModelBinding.kt
Consume target message after scroll to it
> Consume target message after scroll to it

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/ChatSocket.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/HealthMonitor.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/experimental/ChatSocket.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/ChatSocketTest.kt
Closes: https://github.com/GetStream/android-internal-board/issues/87
> [i87] WS gets connected while App in background

- CHANGELOG.md
- stream-chat-android-state/detekt-baseline.xml
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/sync/internal/SyncManager.kt
- stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/sync/internal/SyncManagerTest.kt
Closes: https://github.com/GetStream/android-internal-board/issues/83
> [i83] Unable to receive missed messages after reconnection

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/attachment/AttachmentsSender.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/attachment/AttachmentsVerifier.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/attachment/AttachmentsVerifierTests.kt
Relates to:
- https://github.com/GetStream/android-internal-board/issues/70
- https://github.com/GetStream/android-internal-board/issues/80
> [i70_&_i80] Add attachment verifier

- stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.kt
Fix: https://github.com/GetStream/android-internal-board/issues/78
> Filter null `lastRead`

- docusaurus/docs/Android/02-migration-guides/01-client/03-plugins.mdx
Add Migration guide related to changes introduced by the State and Offline Plugin separation.
Close: https://github.com/GetStream/stream-chat-android/issues/4762
> [4762] Migration guide for State/Offline plugins

- docusaurus/docs/Android/02-migration-guides/02-ui-components/02-media-gallery.mdx
Add Migration Guides for Media Gallery
Close: #4759
> Add Migration Guides for Media Gallery

- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/internal/LogicRegistry.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/StateRegistry.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/channel/internal/ChannelMutableState.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/channel/thread/internal/ThreadMutableState.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/global/internal/MutableGlobalState.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/querychannels/internal/QueryChannelsMutableState.kt
- stream-chat-android-state/src/test/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogicTest.kt
Our "States" shouldn't be updated anymore after the current user logout. To ensure it a new `destroy()` method has been created.
> Create a `destroy()` method for our States

- docusaurus/docs/Android/02-migration-guides/03-ui-components/04-avatar-view.mdx
Closes: https://github.com/GetStream/stream-chat-android/issues/4761
> [4761] add migration guide for AvatarView

- docusaurus/docs/Android/02-migration-guides/01-client/04-logging.mdx
Closes: https://github.com/GetStream/stream-chat-android/issues/4885
> [4885] migration guide for StreamLog

- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
Closes: https://github.com/GetStream/android-internal-board/issues/99
> [i99] fix crash on notification click

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/UserUtils.kt
Fix Partial User Update by Keeping immutable user after merging it
> Fix Partial User Update

- docusaurus/docs/Android/02-migration-guides/04-compose-ui-components/01-message-list-viewmodel.mdx
- docusaurus/docs/Android/02-migration-guides/04-compose-ui-components/02-messages-screen.mdx
> [4889] Migration guide for MessagesScreen

- docusaurus/docs/Android/02-migration-guides/04-compose-ui-components/03-channels-screen.mdx
Closes: https://github.com/GetStream/stream-chat-android/issues/4891
> [4891] migration guide for ChannelsScreen

- docusaurus/docs/Android/01-basics/01-overview.mdx
- docusaurus/docs/Android/03-client/06-guides/01-push-notifications/02-setup.mdx
- docusaurus/docs/Android/03-client/06-guides/03-offline-support.mdx
- docusaurus/docs/Android/03-client/06-guides/04-state-plugin.mdx
- docusaurus/docs/Android/04-ui/02-general-customization/02-chatui.mdx
- docusaurus/docs/Android/04-ui/04-message-components/04-message-composer.mdx
> Fix docs links

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Dispose lifecycleHandler after an unrecoverable Error
> Dispose lifecycleHandler after an unrecoverable Error

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/attachment/UnsupportedAttachmentFactory.kt
It's a side-effect of https://github.com/GetStream/stream-chat-android/pull/4271
> [4042] fix issue of link attachment not being shown

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/DependencyResolverTest.kt
- stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModelTest.kt
- stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/messages/MessageComposerViewModelTest.kt
- stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModelTest.kt
- stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListControllerTests.kt
- stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/channels/ChannelListViewModelTest.kt
- stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/messages/MessageComposerViewModelTest.kt
- stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/messages/MessageListViewModelTest.kt
Better exception message when a dependency can't be resolved because user is not connected
> Better exception message when a dependency can't be resolved because user is not connected

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
Fix crash accessing position 0 of an empty list
> Fix crash accessing position 0 of an empty list

- CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListView.kt
Closes: https://github.com/GetStream/android-internal-board/issues/108
> [i108] Expose itemAnimator for MessageListView

- CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/detekt-baseline.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/ChannelListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/ChannelListIconProviderContainer.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/ChannelListIconProviderContainerImpl.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/ChannelListItemViewHolderFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/internal/ChannelViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/internal/SimpleChannelListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/ListenerDelegate.kt
Closes: https://github.com/GetStream/android-internal-board/issues/110
> [i110] control options icon for each channel

- CHANGELOG.md
- buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
- docusaurus/android-docusaurus-dontent-docs.plugin.js
> Prepare for v6 release

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/detekt-baseline.xml
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/PushMessage.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/parser/StreamPayloadParser.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/notifications/parser/StreamPayloadParserTest.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
- stream-chat-android-pushprovider-firebase/src/main/java/io/getstream/chat/android/pushprovider/firebase/FirebaseMessagingDelegate.kt
- stream-chat-android-pushprovider-huawei/src/main/java/io/getstream/chat/android/pushprovider/huawei/HuaweiMessagingDelegate.kt
- stream-chat-android-pushprovider-xiaomi/src/main/java/io/getstream/chat/android/pushprovider/xiaomi/XiaomiMessagingDelegate.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
Closes: https://github.com/GetStream/android-internal-board/issues/116
> [i116] Extend PushMessage to access extra data

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QueryChannelRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/identifier/Identifiers.kt
- stream-chat-android-core/api/stream-chat-android-core.api
- stream-chat-android-core/src/main/java/io/getstream/chat/android/core/utils/Debouncer.kt
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
- stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListControllerTests.kt
- stream-chat-android-ui-components/detekt-baseline.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/internal/MessageListScrollHelper.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/Debouncer.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/messages/MessageListViewModel.kt
Closes: https://github.com/GetStream/android-internal-board/issues/120
> [i120] fix duplicate read requests

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/detekt-baseline.xml
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/audio/AudioPlayer.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/audio/NativeMediaPlayer.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/audio/StreamAudioPlayer.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/audio/NativeMediaPlayerMock.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/audio/StreamMediaPlayerTest.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/AudioRecordAttachmentContent.kt
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/AudioRecordingController.kt
- stream-chat-android-ui-components/detekt-baseline.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/preview/factory/AudioRecordAttachmentPreviewFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/AudioRecordPlayerView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/AudioRecordingAttachmentsGroupView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/AudioWavesSeekBar.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/FileAttachmentsView.kt
Closes: https://github.com/GetStream/android-internal-board/issues/119
> [i119] fix crash on playing async voice message

- CHANGELOG.md
- docusaurus/docs/Android/01-basics/07-debugging.mdx
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/debugger/ChatClientDebugger.kt
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/docusaurus/Debugging.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/Debugging.kt
- stream-chat-android-ui-components-sample/detekt-baseline.xml
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/debugger/CustomChatClientDebugger.kt
Closes: https://github.com/GetStream/android-internal-board/issues/129
> [i129] provide non-fatal error handling mechanism

- CHANGELOG.md
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
Closes: https://github.com/GetStream/android-internal-board/issues/126
> [i126] fix user avatar click on channel list view

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/StreamLifecycleObserver.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/network/NetworkStateProvider.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/internal/ChatClientStateCalls.kt
Relates to https://github.com/GetStream/stream-chat-android/pull/4954
> [i127] align with changes made for v5

- CHANGELOG.md
- README.md
- stream-chat-android-client/consumer-proguard-rules.pro
- stream-chat-android-ui-common/consumer-proguard-rules.pro
Closes: https://github.com/GetStream/stream-chat-android/issues/4953
> [4953] prevent ChatPushDelegate from obfuscation

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/ChannelRepository.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/noop/NoOpChannelRepository.kt
- stream-chat-android-core/api/stream-chat-android-core.api
- stream-chat-android-core/src/main/java/io/getstream/chat/android/core/internal/lazy/ParameterizedLazy.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/core/utils/MutableValue.kt
- stream-chat-android-core/src/test/java/io/getstream/chat/android/core/internal/lazy/ParameterizedLazyTest.kt
- stream-chat-android-core/src/test/java/io/getstream/chat/android/core/utils/MutableValueTest.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/DatabaseChannelRepository.kt
- stream-chat-android-state/detekt-baseline.xml
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventHandlerSequential.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/batch/SocketEventCollector.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/utils/ChatEventUtils.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/utils/SelfUserUtils.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/thread/internal/ThreadLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/querychannels/internal/QueryChannelsDatabaseLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/querychannels/internal/QueryChannelsLogic.kt
- stream-chat-android-state/src/test/java/io/getstream/chat/android/state/event/TotalUnreadCountTest.kt
- stream-chat-android-state/src/test/java/io/getstream/chat/android/state/event/handler/internal/batch/SocketEventCollectorTest.kt
Expand batching mechanism, to all events except these 3:
- Connecting
- Connected
- Disconnected
> (core): process events as a batch event (v6)

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/UserRepository.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/noop/NoOpUserRepository.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/user/internal/DatabaseUserRepository.kt
Remove unused methods on UserRepository
> Remove unused methods on UserRepository

- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaGalleryPreviewActivity.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/ChannelsScreen.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/list/ChannelList.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
Closes: https://github.com/GetStream/android-internal-board/issues/195
Use `remember()` whenever we use a ViewModel into our anonymous lambdas
> Use `remember()` whenever we use a ViewModel into our anonymous lambdas

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/StreamLifecycleObserver.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/ChatSocket.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/FakeChatSocket.kt
Closes: https://github.com/GetStream/android-internal-board/issues/197
> [i197] handle unrecoverable error properly

- stream-chat-android-ui-components-sample/build.gradle
Disable minify in our UI-Component Sample App until we provide rules to not fail on compilation process.
Related PR: https://github.com/GetStream/stream-chat-android/pull/5007
> Disable minify on our UI-Component sample app

- .github/workflows/clean-detekt-baseline.yaml
- .github/workflows/localazy-download.yml
- .github/workflows/localazy-upload.yml
- .github/workflows/release-post.yaml
- .github/workflows/release-start.yaml
Configure Java 17 on all Github Workflows
> Configure Java 17 on all Github Workflows

- .github/workflows/publish-snapshot.yml
- .github/workflows/publish.yml
- buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
> Bump Nexus Plugin to 1.3.0

- stream-chat-android-core/build.gradle
Forze to build sources jar for "Pure Java/Kotlin" modules
> Forze to build sources jar for "Pure Java/Kotlin" modules

- CHANGELOG.md
Related PR: https://github.com/GetStream/stream-chat-android/pull/5020
Related Ticket: https://github.com/GetStream/android-internal-board/issues/196
> [i196] add CHANGELOG for auto-translation

- CHANGELOG.md
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageContainer.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/MessageDateSeparatorTheme.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamColors.kt
- stream-chat-android-compose/src/main/res/values/colors.xml
Closes https://github.com/GetStream/android-internal-board/issues/200
> [i200] add MessageDateSeparatorTheme

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/ChatNotificationHandler.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/MessagingStyleNotificationHandler.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/NotificationConfig.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/NotificationHandlerFactory.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatApp.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/data/PredefinedUserCredentials.kt
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/detekt-baseline.xml
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/handlers/ClipboardHandler.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageFooter.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageText.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageTranslatedLabel.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/QuotedMessageText.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessagesViewModelFactory.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
Related PR: #5020 
- Reply to auto-translated message :white_check_mark:
- Copy-paste auto-translated message :white_check_mark:
- Delete auto-translated message :white_check_mark:
- PN with auto-translated message :white_check_mark:
- Giphy with auto-translated message :white_check_mark:
> [i196] auto-translation fixes

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
> [i196] auto-translation setup fix

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Closes: https://github.com/GetStream/android-internal-board/issues/201
> [i201] make addDevice and deleteDevice public

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/StreamFileUploader.kt
Closes: https://github.com/GetStream/android-internal-board/issues/202
> [i202] encode filename before uploading

- CHANGELOG.md
> [i196] add missing CHANGELOG

- CHANGELOG.md
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageComposerViewModel.kt
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerController.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/messages/MessageComposerViewModel.kt
Closes: https://github.com/GetStream/android-internal-board/issues/206
> [i206] Add callback to sendMessage in composer VM

- CHANGELOG.md
- docusaurus/docs/Android/01-basics/07-debugging.mdx
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/debugger/SendMessageDebugger.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/debugger/ChatClientDebuggerTest.kt
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/docusaurus/Debugging.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/Debugging.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/debugger/CustomChatClientDebugger.kt
Closes: https://github.com/GetStream/android-internal-board/issues/207
> [i207] pass message with result in SendMessageDebugger

- .github/workflows/publish.yml
- .github/workflows/release-post.yaml
- .github/workflows/release-start.yaml
- build.gradle
- buildSrc/src/main/kotlin/io/getstream/chat/android/command/release/task/ReleaseTask.kt
- buildSrc/src/main/kotlin/io/getstream/chat/android/command/unittest/task/UnitTestsTask.kt
- buildSrc/src/main/kotlin/io/getstream/chat/android/command/utils/Markdown.kt
- buildSrc/src/main/kotlin/io/getstream/chat/android/command/version/task/VersionPrintTask.kt
- scripts/ci-unit-tests.sh
> Improve release process

- CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/MessageReplyView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/ReplyDecorator.kt
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_custom_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_file_attachments.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_giphy_attachment.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_image_attachment.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_link_attachment.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_composer_default_center_content.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_input_field.xml
Closes: https://github.com/GetStream/android-internal-board/issues/213
> [i213] Expose MessageReplyView

- .github/workflows/app-distribute.yml
- .github/workflows/build-and-test.yml
> Remove old workflow triggers

- stream-chat-android-ui-components/detekt-baseline.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
Related ticket: https://github.com/GetStream/android-internal-board/issues/208
Related PR: https://github.com/GetStream/stream-chat-android/pull/5040
> [i208] fix channel title position when typing

- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/data/PredefinedUserCredentials.kt
- stream-chat-android-ui-components-sample/src/demo/kotlin/io/getstream/chat/ui/sample/application/AppConfig.kt
Add two new users to the sample apps.
> Add sample users to the sample apps.

- CHANGELOG.md
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/MessagePlainTextViewHolder.kt
Closes: https://github.com/GetStream/stream-chat-android/issues/4936
> [4936] message click listener is not working

- CHANGELOG.md
- stream-chat-android-client/src/androidTest/java/io/getstream/chat/android/client/poc/ClientInstrumentationTests.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/StreamFileUploader.kt
Closes: https://github.com/GetStream/android-internal-board/issues/216
> [i216] fix audio recording uploading

- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventHandlerSequential.kt
Extra fix for https://github.com/GetStream/stream-chat-android/pull/5094
> Remove unnecessary user updates

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/UserMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/User.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/SocketFactory.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/SocketFactoryTest.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/user/internal/DatabaseUserRepository.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerSequential.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/utils/SelfUserUtils.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/222
> [i222] allow connect user with user_id only

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/Messages.kt
- stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/state/messages/list/MessageListItemState.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/226
> [i226] fix unread count not being cleared

- CHANGELOG.md
- stream-chat-android-core/src/main/java/io/getstream/chat/android/core/utils/date/DateUtils.kt
- stream-chat-android-ui-common/detekt-baseline.xml
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/231
> [i231] Old messages are read by newly added member

- CHANGELOG.md
- stream-chat-android-client/detekt-baseline.xml
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/identifier/Identifiers.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/PushTokenUpdateHandler.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/224
Similar PR for `v5`:
- https://github.com/GetStream/stream-chat-android/pull/5110
> [i224] Protect deleteDevice from repeated usage

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/audio/StreamAudioPlayer.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/audio/NativeMediaPlayerMock.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/audio/StreamMediaPlayerTest.kt
Relates to:
- https://github.com/GetStream/android-internal-board/issues/227
> [i227] fix crash when playing completed audio

- CHANGELOG.md
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/BannedUsersSort.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/Channel.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/Member.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/Message.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/User.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/querysort/QuerySortByField.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/235
> [i235] remove notation restriction in QuerySort

- docusaurus/docs/Android/03-client/02-channels.mdx
> (docs-channels) fix function names & links

- .github/workflows/pr-checks.yml
Fixes GH workflow.
Related change in iOS:
- https://github.com/GetStream/stream-chat-swift/pull/2966/commits/0f8bf876f5efc0f43c02de28be22ada64dba6b9c
> (github) fix vale step in GitHub workflow

- CHANGELOG.md
- stream-chat-android-core/src/testFixtures/kotlin/io/getstream/chat/android/Mother.kt
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
- stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListControllerTests.kt
Related ticket:
- https://github.com/GetStream/android-internal-board/issues/226
Related PR:
- https://github.com/GetStream/stream-chat-android/pull/5116
> [i226] fix unread count not cleared inside channel

- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListItem.kt
Add some changes to the "Blinking message list" PR
> Add some changes to the "Blinking message list" PR

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/AddMembersRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/InviteMembersRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/RemoveMembersRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/UsersApiCallsTests.kt
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Channels.java
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/channels/ChannelListViewModel.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/239
> [i239] Support skipPush flag in add/remove members

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatNotifications.kt
Only require PN Permission if it is not handled by our customers
> Only require PN Permission if it is not handled by our customers

- CHANGELOG.md
- docusaurus/docs/Android/03-client/06-guides/10-video-integrations/01-video-100ms.mdx
- docusaurus/docs/Android/03-client/06-guides/10-video-integrations/02-video-agora.mdx
- docusaurus/docs/Android/04-ui/04-message-components/02-message-list.mdx
- docusaurus/docs/Android/04-ui/06-guides/09-adding-custom-attachments.mdx
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ui/guides/AddingCustomAttachments.java
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ui/messages/MessageList.java
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/guides/AddingCustomAttachments.kt
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageList.kt
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/detekt-baseline.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListItemViewHolderFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListListenerContainer.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListListenerContainerImpl.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/attachment/AttachmentFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/attachment/AttachmentFactoryManager.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/attachment/BaseAttachmentFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/attachment/InnerAttachmentViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/attachment/UnsupportedAttachmentFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/impl/CustomAttachmentsViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/impl/FileAttachmentsViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/impl/GiphyAttachmentViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/impl/GiphyViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/impl/LinkAttachmentsViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/impl/MediaAttachmentsViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/impl/MessagePlainTextViewHolder.kt
Closes: 
- https://github.com/GetStream/android-internal-board/issues/240
> [i240] use default listener if custom returns false

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/detekt-baseline.xml
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/RepositoryFacade.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugin/Plugin.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugin/listeners/DeleteChannelListener.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugin/listeners/SendReactionListener.kt
- stream-chat-android-offline/detekt-baseline.xml
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/internal/OfflinePlugin.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/DeleteChannelListenerDatabase.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/SendReactionListenerDatabase.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/debug/CurrentThreadExecutor.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/debug/RoomQueryLogger.kt
- stream-chat-android-state/detekt-baseline.xml
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventHandlerSequential.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/internal/StatePlugin.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/listener/internal/DeleteChannelListenerState.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/listener/internal/SendReactionListenerState.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/StateRegistry.kt
- stream-chat-android-state/src/test/java/io/getstream/chat/android/state/facade/RepositoryFacadeTests.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/243
> [i243] fix crash on reacting to a non-existing msg

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/ChannelRepository.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/RepositoryFacade.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/noop/NoOpChannelRepository.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/DatabaseChannelRepository.kt
Resolves:
- https://github.com/GetStream/stream-chat-android/issues/5151
> [5151] fix Giphy cancellation

- CHANGELOG.md
- DEPRECATIONS.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/MessageComposerView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/picker/AttachmentSelectionListener.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/picker/AttachmentsPickerDialogFragment.kt
Improve customization over attachments picker.
Fix: https://github.com/GetStream/android-internal-board/issues/254
> Improve customization over attachments picker

- CHANGELOG.md
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/MessagesActivity.kt
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/CancelIcon.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/MessageComposerTheme.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/256
> [i256] add message composer theme (compose)

- CHANGELOG.md
- docusaurus/docs/Android/05-compose/07-guides/08-composer-link-preview.mdx
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/QueryParams.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/OpenGraphApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatApp.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/MessagesActivity.kt
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/composer/ComposerLinkPreview.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/composer/InputField.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ComponentSize.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/MessageComposerTheme.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/TextComponentStyle.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageComposerViewModel.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessagesViewModelFactory.kt
- stream-chat-android-core/api/stream-chat-android-core.api
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/LinkPreview.kt
- stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ui/guides/ImplementingOwnCapabilities.java
- stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerController.kt
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/state/messages/composer/MessageComposerState.kt
- stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerControllerTests.kt
Resolves (Compose Only):
- https://github.com/GetStream/android-internal-board/issues/112
<table>
<thead>
<tr>
<th>Composer Link Preview</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/GetStream/stream-chat-android/assets/1286516/dfb1f99e-f288-4e4e-bfcb-7013252e4c97" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
> [i112] composer link preview (Compose)

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/MessageRepository.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/RepositoryFacade.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/noop/NoOpMessageRepository.kt
- stream-chat-android-offline/api/stream-chat-android-offline.api
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/DatabaseMessageRepository.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageDao.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventBatchUpdate.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventHandlerSequential.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/internal/LogicRegistry.kt
- stream-chat-android-state/src/test/java/io/getstream/chat/android/state/channel/controller/attachment/UploadAttachmentsIntegrationTests.kt
Ensure  channel and its messages are removed on case to receive a RemoveChannel Events
> Clean cached channel

- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerController.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/255
> [i255] align user mention with other SDKs

- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogic.kt
Filter messages that has been already processed to increase unread counter
> Filter messages that has been already processed to increase unread counter

- stream-chat-android-ui-utils/src/main/kotlin/io/getstream/chat/android/uiutils/extension/String.kt
- stream-chat-android-ui-utils/src/test/kotlin/io/getstream/chat/android/uiutils/extension/StringKtTest.kt
Fix `String.containsLinks()` extension function
> Fix `String.containsLinks()` extension function

- docusaurus/docs/Android/04-compose-cookbook/02-custom-channel-list.mdx
- docusaurus/docs/Android/04-compose-cookbook/03-custom-message-list.mdx
Improve _Custom Channel List_ and _Custom Message List_ cookbook pages.
> Improve cookbook pages

- docusaurus/docs/Android/client/overview.mdx
- docusaurus/docs/Android/compose/channel-components/channel-list-header.mdx
- docusaurus/docs/Android/ui/channel-components/channel-list.mdx
- docusaurus/docs/Android/ui/guides/building-channel-list-screen.mdx
- docusaurus/sidebars-android.js
Related thread:
- https://getstream.slack.com/archives/C058XHQ1M99/p1711006060217969?thread_ts=1711005315.593919&cid=C058XHQ1M99
Describe the ChatClient usage and lifecycle
> (docs) describe the LLC lifecycle + samples of usage

- CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/detekt-baseline.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/BaseMessageItemViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListItemViewHolderFactory.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListItemViewType.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/internal/MessageListItemAdapter.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/internal/EmptyViewHolder.kt
Related thread:
- https://getstream.slack.com/archives/C058XHQ1M99/p1711128811955059
Starck Trace:
```
13:20:38.644 Chat:MessageListAdapter       I  (main:2) <init> no args
13:20:38.692 Chat:MessageListAdapter       W  (main:2) [submitList] list: [DateSeparatorItem(0), MessageItem(1), MessageItem(2), MessageItem(3), MessageItem(4), MessageItem(5), MessageItem(6), MessageItem(7), MessageItem(8), MessageItem(9), MessageItem(10), MessageItem(11), MessageItem(12), MessageItem(13), MessageItem(14), DateSeparatorItem(15), MessageItem(16)]
13:20:38.698 Chat:MessageListAdapter       I  (main:2) [getItemViewType] position: 16, viewType: FILE_ATTACHMENTS, item: MessageItem
13:20:38.714 Chat:MessageListAdapter       D  (main:2) [onCreateViewHolder] viewType: FILE_ATTACHMENTS, viewHolder: …
```
> (crash) fix message list crash

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/errors/cause/StreamChannelNotFoundException.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/278
> [i278] Add getChannel function to the ChatClient

- docusaurus/android_versioned_docs/version-5.x.x/02-client/01-users.mdx
- docusaurus/android_versioned_docs/version-6.x.x-before-refactoring/03-client/01-users.mdx
- docusaurus/docs/Android/client/overview.mdx
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/token/TokenProvider.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/285
> (docs) outline the TokenProvider impl requirements

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModel.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/284
> [i284] ChannelsState.isLoadingMore is being stuck

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/MessageMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/ReactionMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/MessageDtos.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/ReactionDtos.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/MessageDtoTestData.kt
- stream-chat-android-core/api/stream-chat-android-core.api
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/Message.kt
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/ReactionGroup.kt
- stream-chat-android-core/src/testFixtures/kotlin/io/getstream/chat/android/Mother.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/converter/internal/ReactionGroupConverter.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/ChatDatabase.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageEntity.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/ReactionGroupEntity.kt
- stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/ReactionGroupMapper.kt
- stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/database/converter/ReactionGroupConverterTest.kt
Add Reaction Group field to the Message Entity.
The UI Changes will be achieve in a different PR
> Reaction Group

- CHANGELOG.md
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/UserDtos.kt
Fix crash when parsing users from query user endpoint.
Close: https://github.com/GetStream/stream-chat-android/issues/5252
> Fix crash when parsing users from query user endpoint

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/UserApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/UserMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/UserDtos.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/BlockUserRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/UnblockUserRequest.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/BlockUserResponse.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/QueryBlockedUsersResponse.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/UnblockUserResponse.kt
- stream-chat-android-core/api/stream-chat-android-core.api
- stream-chat-android-core/src/main/java/io/getstream/chat/android/models/UserBlock.kt
Add API to block/unblock users.
Added API to the `UserApi`
> [PBE-3847] Add the API to block/unblock users and expose it via chat client

- buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
> Remove unused dependency

- stream-chat-android-core/api/stream-chat-android-core.api
- stream-chat-android-core/src/main/java/io/getstream/chat/android/extensions/FloatExtensions.kt
Use InternalStreamChatApi annotation for internal extensions.
Added `InternalStreamChatApi` annotations.
- [ x PR targets the `develop` branch
> Use InternalStreamChatApi annotation for internal extensions

- build.gradle
- buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
Upgrade Stream-Android-Push dependency to version 1.1.8
> Upgrade Stream-Android-Push dependency to version 1.1.8

- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/QuotedMessageText.kt
Small PR to fix an issue where the quoted message doesn't have the correct style.
> Update quoted messages composable to use the quoted text style instead.

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
Closes:
- https://stream-io.atlassian.net/browse/PBE-5154
> [PBE-5154] fix checkbox visibility in dark mode

- stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/channels/ChannelItemTest.kt
- stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/channels/ChannelListTest.kt
- stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/messages/MessageContainerTest.kt
- stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/messages/MessageItemTest.kt
- stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/messages/MessageListTest.kt
> Fix UI Tests

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/EventMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/EventDtos.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/ChatEvent.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventHandlerSequential.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogic.kt
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/channel/internal/ChannelMutableState.kt
Refactor poll events
The DB implementation for Poll event/data will be covered on #5283
> Refactor poll events

- stream-chat-android-client/src/main/resources/META-INF/io/getstream/stream-chat-android-client/verification.properties
Add verification.properties to verify google platform SDK.
> Add verification.properties to verify google platform SDK

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageFooter.kt
Closes:
- https://stream-io.atlassian.net/browse/PBE-5463
> [PBE-5463] edited label is not displayed

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/PollMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/PollsDtos.kt
Mark as optional some poll related fields
> Mark as optional some poll related fields

- docusaurus/docs/Android/basics/overview.mdx
Remove outdated snpashot maven repository guidelines.
> Remove outdated snpashot maven repository guidelines

- README.md
- stream-chat-android-previewdata/build.gradle.kts
- stream-chat-android-previewdata/consumer-rules.pro
Add consumer rules for previewdata module
> Add consumer rules for previewdata module

- stream-chat-android-previewdata/build.gradle.kts
Fix wrong previewdata maven package name.
> Fix wrong previewdata maven package name

- CHANGELOG.md
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
Ensure message list is cleared after events remove all messages
> [PBE-5596] Ensure message list is cleared after events remove all messages

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerPollTabFactory.kt
The number of max allowed votes wasn't updated properly according to the number of available options.
> [PBE-5618] Fix max allowed votes on a poll regarding to the number of available options

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/PollMessageContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
Use poll description instead of show question twice
> [PBE-5622] Use poll description instead of show question twice

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/PollMessageContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/poll/PollViewResultDialog.kt
The anonymous polls don't provide the list of votes but only the total number of votes per options.
> [PBE-5626] Show proper votes count for anonymous polls

- CHANGELOG.md
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/options/message/MessageOptionsDialogFragment.kt
**Closes**:
- https://stream-io.atlassian.net/browse/PBE-3971
> [PBE-3971] make options overlay render custom view

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/QuotedMessageTextFormatter.kt
Closes:
- https://stream-io.atlassian.net/browse/PBE-5700
- https://github.com/GetStream/stream-chat-android/issues/5307
Related PR:
- https://github.com/GetStream/stream-chat-android/pull/5310
> [PBE-5700] Quoted text style has no effect

- CHANGELOG.md
- stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/querychannels/internal/QueryChannelsStateLogic.kt
Keep members updated on QueryChannelsState
> [PBE-5799] Keep members updated on QueryChannelsState

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
Closes:
- https://github.com/GetStream/stream-chat-android/issues/5304
| --- | --- |
| <img src="https://github.com/user-attachments/assets/04388582-661c-4bca-8df0-cd7c88290e45" width="250"/> | <img src="https://github.com/user-attachments/assets/165ab95b-aa12-4c99-9a8a-b0d4e1c97c25" width="250"/> |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/1fd0a2bd-0029-40ab-8fa0-c789dbc979c8" width="250"/> | <img src="https://github.com/user-attachments/assets/45f4e741-1a2b-4be9-b62d-0072dd0cfe17" width="250"/> |
> [5304] enableEdgeToEdge hides EditText/TextField

- CHANGELOG.md
- stream-chat-android-compose/src/main/AndroidManifest.xml
- stream-chat-android-compose/src/main/res/values-v23/themes.xml
- stream-chat-android-compose/src/main/res/values/themes.xml
Provide default theme for the different activities our SDK provides
> [PBE-5854] Provide default theme for the different activities our SDK provides

- CHANGELOG.md
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/channels/list/ItemState.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/list/ChannelItem.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/list/ChannelList.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModel.kt
- stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModelTest.kt
Add Typing Indicator to the Channel List
> [PBE-5927] Typing indicator on channel list

- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/AttachmentFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/StreamAttachmentFactories.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/AudioRecordAttachmentFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/FileAttachmentFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/GiphyAttachmentFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/LinkAttachmentFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/MediaAttachmentFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/QuotedAttachmentFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/UnsupportedAttachmentFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/UploadAttachmentFactory.kt
- stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/compose/guides/CustomizingImageAndVideoPreviews.kt
- stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/compose/customizingimageandvideoattachments/MessagesActivity.kt
Keep class extensions as classes instead of functions returning an anonymous class simplify our development, helping to the IDE where this clas is being extended and/or used.
> Refactor attachment factories

- stream-chat-android-compose/src/main/resources/META-INF/io/getstream/stream-chat-android-compose/verification.properties
- stream-chat-android-ui-components/src/main/resources/META-INF/io/getstream/stream-chat-android-ui-components/verification.properties
Add SDK verifications for ui and compose packages
> Add SDK verifications for ui and compose packages

- CHANGELOG.md
- stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/PollView.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/internal/PollResultsDialogFragment.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/internal/poll/PollResultsDialogFragment.kt
- stream-chat-android-ui-components/src/main/res/drawable/stream_ui_ic_award.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_fragment_poll_results.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_result.xml
- stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_result_user.xml
- stream-chat-android-ui-components/src/main/res/values/strings.xml
Implement a view to show the poll results
> Implement Poll Result view

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/MessageMapping.kt
Backend reponse, by some unknown reason, is returning reactions that don't belong to the current message, what could cause inconsinstence data within our db/state data. To avoid it, we are filtering out reactions don't belong to the current message.
> [PBE-5380] Add workaround to filter reactions don't belong to the current message

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/debug/java/io/getstream/chat/android/client/di/ChatModule.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/FileTransformer.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/NoOpFileTransformer.kt
- stream-chat-android-client/src/release/java/io/getstream/chat/android/client/di/ChatModule.kt
Provide a way to transform files before they are uploaded to the CDN.
It can be used by our customers to compress video/pictures, add watermarks, or whatever local process they would like to apply to the files before they are uploaded to the CDN (Even if they are using our CDN or their own CDN)
> [PBE-6115] File transformer

- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/HeadersInterceptor.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
Include a custom User-Agent to any HTTP Call our SDK does. The User-Agent will looks like:
```
"User-Agent:Chat Sample Android / 6.5.0-DEBUG(1); StandAloneInstall; (Google; sdk_gphone64_x86_64; SDK 32; Android 12)"
```
> Add User-Agent with the App Data

- CHANGELOG.md
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/ChannelsActivity.kt
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModel.kt
Closes:
- https://stream-io.atlassian.net/browse/PBE-6188
> [PBE-6188] support PTR for Channels VM in Compose

- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/QuotedMessageTextFormatter.kt
- stream-chat-android-ui-common/src/main/res/values-en/strings.xml
- stream-chat-android-ui-common/src/main/res/values-es/strings.xml
- stream-chat-android-ui-common/src/main/res/values-fr/strings.xml
- stream-chat-android-ui-common/src/main/res/values-id/strings.xml
- stream-chat-android-ui-common/src/main/res/values-it/strings.xml
- stream-chat-android-ui-common/src/main/res/values-ko/strings.xml
- stream-chat-android-ui-common/src/main/res/values/strings.xml
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/MessageReplyView.kt
Closes:
- https://stream-io.atlassian.net/browse/PBE-6029
> [PBE-6029] bug in updating quoted message content

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
The option to allow multiple votes on a poll wasn't handle properly when the poll is created.
> [PBE-6183] Fix multianswer option on poll

- stream-chat-android-ui-components-sample/src/demo/kotlin/io/getstream/chat/ui/sample/application/AppConfig.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/MessageTranslator.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatViewModel.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/messagelist/options/CustomMessageOptionItemsFactory.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/messagelist/options/CustomMessageOptions.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/util/extensions/Drawable.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/util/extensions/MessageListView.kt
- stream-chat-android-ui-components-sample/src/main/res/drawable/ic_translate.xml
- stream-chat-android-ui-components-sample/src/main/res/values/strings.xml
Closes: #5349
Add message action `Translate` to the **SampleApp**
<table>
<thead>
<tr>
<th>Manual Translation to User's language</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/f013f871-0ba3-4fa6-93f3-a0044b20ca52" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
> [5349] demonstrate translation usage

- docusaurus/android_versioned_docs/version-5.x.x/02-client/02-channels.mdx
| --- | --- |
| img | img |
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<details>
```
```
</details>
> Fix broken link in V5 docs

- .github/workflows/build-and-test.yml
The apk file name was updated by #5464 but it wasn't updated on the workflow that used it.
> Fix build-and-test.yml workflow

- .github/workflows/app-distribute.yml
> Fix app-distrubute.yml action

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/EventMapping.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/EventDtos.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt
Update with new AI events formats.
> Update with new AI events formats

- CHANGELOG.md
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messageoptions/MessageOptionItemVisibility.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messageoptions/MessageOptions.kt
Add an option to show/hide block user action on the MessageOptions
> [AND-169] Add an option to show/hide block user action on the MessageOptions

- CHANGELOG.md
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageContainer.kt
- stream-chat-android-compose/src/main/res/values/strings.xml
- stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/state/messages/list/MessageListItemState.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/internal/ErrorMessageViewHolder.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/MessageListItem.kt
- stream-chat-android-ui-components/src/main/res/values/strings_message_list.xml
Block messages with moderated images
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/21a22569-149e-4942-a64b-0b3b22b239b5" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/1a0f9bea-4b05-4514-9f2d-26b116e69ff8" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
> [AND-178] Block messages with moderated images

- .github/workflows/sdk-size-updates.yml
Make the SDK size updates workflow run one at a time
> Run one sdk size updates workflow at the time

- .github/workflows/sdk-size-updates.yml
- metrics/size.json
Add label to the commit to avoid rerun unnecessary workflows
> Add label to the commit to avoid rerun unnecessary workflows

- .github/workflows/app-distribute.yml
- .github/workflows/build-and-test.yml
- .github/workflows/pr-checks.yml
| --- | --- |
| img | img |
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<details>
```
```
</details>
> [AND-0] Update deprecated action upload-artifact to v4.4.3.

- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/StringExtensions.kt
- stream-chat-android-client/src/test/java/io/getstream/chat/android/client/extensions/BaseUrlTest.kt
Expose a method to update the CDN Url
> Expose a method to update the CDN Url

- Gemfile
- Gemfile.lock
- fastlane/Fastfile
✅ [Tests passed](https://github.com/GetStream/stream-chat-android/actions/runs/13409661210?pr=5641)
> [CI] Implement stream-chat dependency for e2e mock server

- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/util/extensions/MessageOptionItemVisibility.kt
- stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/internal/MessageListViewExtensions.kt
Clean the code by importing methods
> Clean the code by importing methods

- .github/workflows/e2e-test-cron.yml
- fastlane/Fastfile
- stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobotMessageListAsserts.kt
Relates to https://github.com/GetStream/stream-chat-android/pull/5646
> [CI] Resolve some e2e tests issues

- .github/workflows/e2e-test-cron.yml
https://getstream.slack.com/archives/C08E4DPVA69
> [CI] Route nightly checks fail reports to a dedicated Slack channel

- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/ImageUtils.kt
Applying changes from GH PR Feedback
> Applying changes from GH PR Feedback

- CHANGELOG.md
- stream-chat-android-client/api/stream-chat-android-client.api
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/NotificationConfig.kt
Complete: [AND-341](https://linear.app/stream/issue/AND-341)
Add a way to inject a TokenProvider from PN on the case an expired token needs to be refreshed
> Custom TokenProvider when PN is received

- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
- stream-chat-android-ui-components-sample/build.gradle.kts
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
Use a more descriptive token provider name.
> [AND-359] Use a more descriptive token provider name

- stream-chat-android-client/src/androidTest/java/io/getstream/chat/android/client/poc/ClientInstrumentationTests.kt
- stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Allow override http and ws urls for local testing.
> [AND-369] add forceHttpUrl and forceWsUrl params

- CHANGELOG.md
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/messages/attachments/AttachmentState.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/FileAttachmentContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/FileAttachmentPreviewContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/FileUploadContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/GiphyAttachmentContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/LinkAttachmentContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/MediaAttachmentContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/MessageAttachmentsContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/QuotedMessageAttachmentContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/GiphyMessageContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/QuotedMessageContent.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/factory/MessageContentFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatComponentFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/MessageTheme.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/messages/attachments/FileAttachmentTheme.kt
Create a new Theme `FileAttachmentTheme` used to customize FileAttachments.
This theme could have different values for sent messages from the current user and for sent messages for other users.
> [AND-370] Provide FileAttachment Theme

- gradle/libs.versions.toml
- stream-chat-android-client/build.gradle.kts
Remove unused dependency.
Fix: #5700
> Remove unused log dependency

- CHANGELOG.md
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/feature/channel/add/component/SearchUserResultsContent.kt
- stream-chat-android-compose/api/stream-chat-android-compose.api
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/handlers/LoadMoreHandler.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/pinned/PinnedMessageList.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/threads/ThreadList.kt
- stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/handlers/LoadMoreHandlerTest.kt
Make the `LoadMoreHandler` logic testable and reuse it in `PinnedMessageList`, `ThreadList`, and `SearchUserResultList`
> Review and reuse LoadMoreHandler

- README.md
Fix worklfow badge link 
Fix: AND-476
> Fix worklfow badge link

- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
Keep updated `backAction` lambda
Complete: AND-599
> Keep updated `backAction` lambda

- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/service/SharedLocationService.kt
- stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/component/CustomChatComponentFactory.kt
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/info/DirectChannelInfoScreen.kt
- stream-chat-android-previewdata/src/main/kotlin/io/getstream/chat/android/previewdata/PreviewPollData.kt
- stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeViewModel.kt
> 6.20.0 testing findings

- CHANGELOG.md
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/Messages.kt
Scroll to the bottom when the current user sends a new message.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/13affff8-2d0d-4d7e-83ce-abf90a7c0dec" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/7be2a912-fd59-422f-a891-2d393d3d3fc4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
> Scroll to bottom when current user send a new message

- .github/workflows/build-and-test.yml
- .github/workflows/pr-checks.yml
- build.gradle.kts
- scripts/ci-unit-tests.sh
- scripts/coverage.gradle
- scripts/sonar.gradle
- stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaGalleryPreviewActivity.kt
- stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/ui/attachments/preview/MediaGalleryPreviewActivityTest.kt
- stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/ui/attachments/preview/MediaPreviewActivityTest.kt
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/threads/ThreadListController.kt
- stream-chat-android-ui-common/src/main/kotlin/io/getstream/sdk/chat/audio/recording/DefaultStreamMediaRecorder.kt
- stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/channel/header/ChannelHeaderViewControllerTest.kt
- stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/documents/AttachmentDocumentActivityTest.kt
- stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/threads/ThreadListControllerTest.kt
- stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/images/StreamImageLoaderFactoryTest.kt
- stream-chat-android-ui-common/src/test/kotlin/io/getstream/sdk/chat/audio/recording/DefaultStreamMediaRecorderTest.kt
Some of the changes here modified components to be testable. Those changes should not impact any functionality.
However, it is worth testing the functionality of `DefaultStreamMediaRecorder` to ensure that no regression issues are introduced. Test sending an audio record from the message composer of both XML and Compose SDKs.
> Improve testing coverage
