GetStream/stream-chat-android

CHANGELOG.md, docusaurus/docs/Android/04-compose/02-general-customization/01-chat-theme.mdx, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/MessageAlignmentProvider.kt
https://github.com/GetStream/stream-chat-android/issues/2461
Provide a way to customize message alignment.
The resulting UI after applying the patch below:
<details>
```
Index: stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/MessagesActivity.kt
<+>UTF-8
diff --git a/stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/MessagesActivity.kt b/stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/MessagesActivity.kt
--- …
```
=> [Compose] - 2461 - Add support for message alignment customization

CHANGELOG.md, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/attachment/AttachmentUploader.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/attachment/AttachmentUploaderTests.kt
Other SDKs use title property instead of name to show the display name.
Set title when file was uploaded
=> Provide title for attachment with file name if it is empty

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/messages/composer/MessageInputState.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/components/ComposerIntegrations.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/components/MessageInput.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageComposerViewModel.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessagesViewModelFactory.kt, stream-chat-android-offline/api/stream-chat-android-offline.api, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/state/ValidationError.kt
https://github.com/GetStream/stream-chat-android/issues/2621
Add message length limitation.
This PR only introduces message length limitation. The rest of the limitation will be covered in different PRs.
| --- | --- |
| ![device-2021-11-19-182347](https://user-images.githubusercontent.com/9600921/142647394-8a06dc2e-a4b4-4b20-8b4e-2057e563e9e8.png) | ![device-2021-11-19-182238](https://user-images.githubusercontent.com/9600921/142647293-ce751d23-6b0b-4467-8bf6-bf7929d86146.png) |
| ![device-2021-11-19-181733](https://user-images.githubusercontent.com/9600921/142646847-75a1f666-0caf-4771-a69a-22851e6c66ff.png) | ![device-2021-11-19-181921](https://user-images.githubusercontent.com/9600921/142646834-f2f4e0da-3656-4f2c-b591-067772c5b9a2.png) |
Modify the message limitation …
=> [Compose] - 2621 - Add message length limitation

docusaurus/docs/Android/01-basics/05-logging.mdx, docusaurus/docs/Android/02-client/06-guides/06-working-with-offline.mdx, docusaurus/docs/Android/03-ui/04-components/02-channel-list.mdx, docusaurus/docs/Android/03-ui/04-components/05-message-list.mdx, docusaurus/docs/Android/03-ui/04-components/08-mention-list-view.mdx, docusaurus/docs/Android/03-ui/04-components/09-pinned-message-list-view.mdx, docusaurus/docs/Android/03-ui/04-components/10-search-view.mdx
Fix a bunch of broken links in our documentation, caused by Dokka changing its generated URLs.
Open the new links.
=> Fix broken Dokka links in our documentation

stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/list/ChannelItem.kt
Make icon color dynamic (adapt to dark mode, use colors from `ChatTheme` when they're customized)
| --- | --- |
| ![Screenshot_1637751183](https://user-images.githubusercontent.com/12054216/143225630-d7b83915-00cf-41fd-9105-66c3eaa4a7ec.png) |  ![Screenshot_1637751193](https://user-images.githubusercontent.com/12054216/143225667-b49827cb-a05d-4f04-8b23-31d60e4eb77b.png) |
=> [Compose] Add tint to mute icon

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/list/ChannelItem.kt
https://github.com/GetStream/stream-chat-android/issues/2677
Fix the bug where the channel icon doesn't appear because of a lengthy title.
=> [2677] Fix muted channel icon with long title

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/common/NetworkLoadingView.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/header/MessageListHeader.kt
https://github.com/GetStream/stream-chat-android/issues/2674)](https://github.com/GetStream/stream-chat-android/issues/2674
Expose the `textStyle` and `textSize` params in the `NetworkLoadingView` component. Set them to the correct values for `ChannelListHeader` and `MessageListHeader`.
| --- | --- |
| ![device-2021-11-25-084320](https://user-images.githubusercontent.com/9600921/143386458-c75787c6-6d5a-47a2-a601-c62bd2a1f9f3.png) | ![device-2021-11-25-084209](https://user-images.githubusercontent.com/9600921/143386207-c2cf1f4a-e8b5-4363-9b2b-d90834d6996d.png) |
| ![device-2021-11-25-084341](https://user-images.githubusercontent.com/9600921/143386456-378cfda6-0b64-41e0-977d-4d96df49fc48.png) | ![device-2021-11-25-084235](https://user-images.githubusercontent.com/9600921/1 …
=> [2674] Make NetworkLoadingView more customizable

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/StorageHelperWrapper.kt, stream-chat-android-compose/src/main/res/values-en/strings.xml, stream-chat-android-compose/src/main/res/values-es/strings.xml, stream-chat-android-compose/src/main/res/values-fr/strings.xml, stream-chat-android-compose/src/main/res/values-hi/strings.xml, stream-chat-android-compose/src/main/res/values-it/strings.xml, stream-chat-android-compose/src/main/res/values-ja/strings.xml, stream-chat-android-compose/src/main/res/values-ko/strings.xml, stream-chat-android-compose/src/main/res/values/strings.xml, stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/MediaStringUtil.kt, stream-chat-android/src/test/java/com/getstream/sdk/chat/GetDeletedOrMentionedTextTest.kt
https://github.com/GetStream/stream-chat-android/issues/2653
Give users visual feedback when a validation error happens.
For now, adding a simple to`Toast` to display validation errors as in Compose it is impossible to show a `Snackbar` above an achor.
https://user-images.githubusercontent.com/9600921/143227759-bc122e40-d1b8-494f-bca2-c4152dd23ef3.mp4
=> [2653] Implement input validation errors in the message composer

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/background/MessageBackgroundFactory.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsDialogFragment.kt
Fix crash related to serialization of `MessageBackgroundFactoryImpl`
Using only the static instance of `messageViewHolderFactory` inside `MessageOptionsDialogFragment`
Change the background of messages and check that it is still applied an not crashes occur.
=> Crash fix for message options dialog fragment

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsView.kt
The block user textview was never visible even if developer has enabled `blockEnabled` property.
Simply, removed the line which was changing its visibility.
- Enable block user either with the help of style attribute `blockEnabled`.
- Block user options should be visible when tapping long on any message.
=> Fix block user textview behvaviour

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/GiphyViewHolder.kt
https://stream-io.atlassian.net/browse/CAS-1480
Fix the style attribute not being applied correctly
Replaced the `setCardBackgroundColor` call with setting the `backgroundTintList` of the `MaterialCardView` instead. Not sure why exactly `setCardBackgroundColor` doesn't work, it works in three other places in our codebase just fine.
<details>
<summary>Here's the patch to update the other three places too, in case we want to (or just for testing)</summary>
```
Index: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsView.kt
<+>UTF-8
diff --git …
```
=> [CAS-1480] Fix background color setting in GiphyViewHolder

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/messages/composer/MessageInputState.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageComposerViewModel.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
https://github.com/GetStream/stream-chat-android/issues/2704
Add support for slow mode.
https://user-images.githubusercontent.com/9600921/144101293-3454bba2-506e-4541-b0c6-9e6d8985e7a7.mov
1. Enable slow mode for a specific channel
2. Send a message
3. Observe cooldown countdown timer
=> [2704] Add support for slow mode

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/AttachmentsPicker.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/AttachmentsPickerViewModel.kt
Preemptive loading of attachment data was done before permission `READ_EXTERNAL_STORAGE` was given leading to crashes on certain Android APIs (confirmed crashes on APIs 23,24,26 and 28) when `MessagesActivity` was open in the Compose Sample app. This PR aims to rectify said crashes.
Preemptive loading was removed from the init block of `AttachmentsPickerViewModel` and inside of the function body of `changeAttachmentState(showAttachments: Boolean)` inside `AttachmentsPickerViewModel`. 
`storagePermissionState.permissionRequested` was removed from the condition check because it would always return `false` even if permission had been previously requested.
Testing can be done manually by opening the sample app on emulators/ physical devices that had crashes occurring (APIs 23,24,26 and 28), …
=> [2720] Removed preemptive attachment loading that resulted in crashes

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/Channel.kt
https://stream-io.atlassian.net/browse/CAS-1481
SDK crashes when a channel watcher is not found in a local database.
Added channel watchers to save into the database.
=> Add watchers to channel users

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/overlay/SelectedMessageOverlay.kt
Enable scrolling behavior in `SelectedMessageOverlay` in order to avoid clipping the message or clipping or fully excluding `MessageOptions` from the screen resulting in an inability to perform any actions over messages.
Enabled vertical Scrolling in `SelectedMessageOverlay` by applying `.verticalScroll(ScrollState)` to the `Box` `Modifier` inside `SelectedMessageOverlay`. 
Switched from implementing a `LazyColumn` for displaying `MessageOptionItem`s to using a `Column` so that nested scrolling would be avoided. Used key utility Composable to optimize recomposition since the Composables were called from the same call site.
Enabled vertical scrolling in `SelectedMessageOverlay`
| --- | --- |
| ![before](https://user-images.githubusercontent.com/37080097/144443377-a55b75a1 …
=> [2733] Enable scrolling behavior in SelectedMessageOverlay

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputFieldView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/TextValidator.kt, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/message/input/internal/TextValidatorTest.kt
[CAS-1457](https://stream-io.atlassian.net/browse/CAS-1457)
Fix a simple bug where is it possible to send giphys with empty screen. The check for valid message text is now outside of `MessageInputFieldView` and has unit tests for it, as it can grow in complexity as more logic is added in the SDK.
Created method to validate message text
| --- | --- |
|![Screenshot_20211130-112900](https://user-images.githubusercontent.com/10619102/144067026-dd702e06-27ab-40a8-9fdc-fd59282f76c6.png) |  ![Screenshot_20211130-112820](https://user-images.githubusercontent.com/10619102/144067020-1d19df13-6ca8-42ca-896a-4b4c6f944997.png) |
Send giphys and messages with different data and don't forget to try to send a giphy with no text
- ~[ ] Affected documentation updated (docusaurus, …
=> [CAS-1457] Fix - Disallowing empty giphys

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/EventMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/EventDtos.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventHandlerImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/ChatEventHandler.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/DefaultChatEventHandler.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/QueryChannelsController.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/utils/TestDataHelper.kt
[CAS-1482](https://stream-io.atlassian.net/browse/CAS-1482)
Fix of channels not being updated when the filter is requesting channels that the user is **not** a member. 
Removing or adding the user depends on the filter, not the event that arrived. If the channel fails if the filter, it must be removed, if it passes, it must be added. 
Left side - Normal filtering. 
Right side - Displaying only channels where the user is not a member
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/144480750-5b3ce670-815f-4752-adef-e8e4b0b6d5e9.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/144480611-b859b562-1d86-41d5-b767-0bdbbaf16919.mov" …
=> [CAS-1482] Fix - Query controller

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/common/SimpleDialog.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/AttachmentsPicker.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/overlay/SelectedMessageOverlay.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-compose/src/main/res/drawable/stream_compose_ic_flag.xml, stream-chat-android-compose/src/main/res/values-en/strings.xml, stream-chat-android-compose/src/main/res/values-es/strings.xml, stream-chat-android-compose/src/main/res/values-fr/strings.xml, stream-chat-android-compose/src/main/res/values-hi/strings.xml, stream-chat-android-compose/src/main/res/values-it/strings.xml, stream-chat-android-compose/src/main/res/values-ja/strings.xml, stream-chat-android-compose/src/main/res/values-ko/strings.xml, stream-chat-android-compose/src/main/res/values/strings.xml
https://github.com/GetStream/stream-chat-android/issues/2707
Add an option to flag messages to the message options overlay.
https://user-images.githubusercontent.com/9600921/144581828-a9288fe8-7db9-4638-a2c5-036d6c080e15.mov
=> [2707] Add support for message flagging

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputFieldView.kt
https://stream-io.atlassian.net/browse/CAS-1489
`MessageInputFieldView#mode` was not reset after custom attachments were cleared
Add custom attachment, and remove it. Debug the `MessageInputField#mode` value.
=> Bug: `MessageInputFieldView#mode` not being reset after clearing custom attachments

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventHandlerImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/Reaction.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/extensions/ReactionExtensionsTest.kt
Update `Message::ownReactions` for current user when WS event arrives
Set field as merge of lates reactions for this user and own cached reactions
UI Comp Sample App:
1. Enter channel X
2. Open message overlay and leave a reaction (everything is fine)
3. After that open the message overlay and react using a different reaction without removing the previous one. 
4. Reactions should be shown accordingly
=> Preprocess ownReactions for currentUser when event arrives

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/Mother.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/user/UserRepository.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/MessageListItemPayloadDiff.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/internal/MessageListItemAdapter.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/internal/MessageListItemDiffCallback.kt
When users' updates happen in runtime it's not reflected in `MessageListView`. Because we don't calculate `Message::user` in diff callback.
Also, we keep the outdated users in LLC
1. Consider `Message::user` field when calculate diff for `MessageListView`
2. Update user in LLC when an event with current user arrives.
Open some conversation
Change name (login from another device with a different name e.g. Dashboard update doesn't trigger event, can't be used here) of some user
Be sure the new name is shown in the conversation
=> Propagate current user updates to `MessageListView`

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageFooter.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageThreadFooter.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/ThreadParticipants.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamDimens.kt
Fixes #2687.
Fixed the logic around MessageFooter and the ThreadParticipants components.
| --- | --- |
| ![before](https://user-images.githubusercontent.com/17215808/145860969-0206a6d2-342f-4e9a-be8f-75d38e159dde.png) | ![after](https://user-images.githubusercontent.com/17215808/145860991-f6f2b9a9-1311-4703-a811-631c71faa313.png) |
Start a thread or observe existing threads - the message should have both a thread participants footer and a timestamp, if it's at the end.
Also fixed the orientation of the participants component and made it more design-friendly.
~~- [ ] New code is covered by unit tests~~
=> Cleaned up base message UI around footers

.idea/inspectionProfiles/ktlint.xml, CHANGELOG.md, docusaurus/docs/Android/04-compose/04-message-components/06-selected-message-overlay.mdx, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messageoptions/MessageOptions.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-compose/src/main/res/values-en/strings.xml, stream-chat-android-compose/src/main/res/values-es/strings.xml, stream-chat-android-compose/src/main/res/values-fr/strings.xml, stream-chat-android-compose/src/main/res/values-hi/strings.xml, stream-chat-android-compose/src/main/res/values-it/strings.xml, stream-chat-android-compose/src/main/res/values-ja/strings.xml, stream-chat-android-compose/src/main/res/values-ko/strings.xml, stream-chat-android-compose/src/main/res/values/strings.xml, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/state/MessageAction.kt
https://github.com/GetStream/stream-chat-android/issues/2745
The goal is to add a message option to unmute the user that sent the message. Also, to properly reflect the muted state of the user in the UI.
https://user-images.githubusercontent.com/9600921/146725813-49ba9945-3280-4bb4-81fe-63b641d6c4c3.mov
Monday
=> [2745] Fix user mute/unmute behavior

DEPRECATIONS.md, stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomain.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/Mother.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/integration/ChatDomainEventDomainImplTest.kt
In order to merge ChatDomain into ChatClient we need to eliminate direct usage of ChatDomain and substitute it with the usage of ChatClient. 
This PR deprecates usage of `ChatDomain::showChannel`
1. Deprecate `ChatDomain::showChannel`
2. Remove side effects from `ChannelController::showChannel` (it should be handled via events)
3. Write a test that checks that event handling updates required data
=> [CAS-1292] Deprecate ChatDomain::showChannel, remove side effects

CHANGELOG.md, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventBatchUpdate.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventHandlerImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/logic/ChannelLogic.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/state/ChannelMutableState.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/querychannels/logic/QueryChannelsLogic.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/RepositoryFacade.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/builder/RepositoryFacadeBuilder.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/ChannelRepository.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/MessageRepository.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/ChannelControllerReactionsTest.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/event/TotalUnreadCountTest.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/extensions/MemberExtensionsTest.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/querychannels/WhenQuery.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/facade/RepositoryFacadeTests.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/usecase/DeleteReactionTest.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/usecase/SendReactionTest.kt, stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/BaseMessageListHeaderViewModel.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/ChannelListPayloadDiff.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/internal/ChannelListItemAdapter.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Channel.kt, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/message/list/header/viewmodel/MessageListHeaderViewModelTest.kt, stream-chat-android/src/test/java/com/getstream/sdk/chat/viewmodel/ChannelHeaderViewModelTest.kt
We need to propagate user updates received in runtime. We had several bugs that lead to inconsistent behavior. This PR fixes them
1. Eliminate two instances of `UserRepository`. Each had a different in-memory cache that lead to inconsistent data.
2. In `EventBatchUpdate` when we fetch channels and messages we need to take data directly from DB, because some cached values can be outdated
3. Eliminate doubling of `ChannelController::toChannel` and `ChannelState::toChannel`
4. Some minor improvements
Have two samples running. Log in from the second device with changed name and observer on first device updates. Try to do some actions and be sure the updated value doesn't get reset to the previous.
=> [CAS-1503] Fix/user updates

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/TextAndAttachmentsViewHolder.kt
Fixing a little bug with borders of attachments when position change. 
The setup is redone when positions change. This allows the attachments to redraw their borders and change them accordingly. 
| --- | --- |
| ![Screenshot_20211222-170441](https://user-images.githubusercontent.com/10619102/147149534-a9cf58ea-6c2d-4c4d-9223-51e849e7ff5a.png) | ![Screenshot_20211222-170534](https://user-images.githubusercontent.com/10619102/147149545-0855db4c-2cb1-44e2-86a1-d28f767cde27.png) |
- Send a giphy 
- Expected: Check that the border is sharp
- Send another message
- Expected: Check that the border of the first giphy is no longer shard. It becomes round. 
=> Fixing border bug

docusaurus/docs/Android/04-compose/03-channel-components/02-channel-list-header.mdx, docusaurus/docs/Android/04-compose/03-channel-components/04-default-channel-item.mdx, docusaurus/docs/Android/04-compose/04-message-components/02-message-list-header.mdx, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChannelActivity.kt, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/header/ChannelListHeader.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/list/ChannelItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/selectedmessage/SelectedMessageDialog.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/selectedmessage/SelectedMessageMenu.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/selectedmessage/SelectedReactionsMenu.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/suggestions/SuggestionList.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/suggestions/commands/CommandSuggestionItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/suggestions/mentions/MentionSuggestionItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/header/MessageListHeader.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt
https://github.com/GetStream/stream-chat-android/issues/2810
Align the naming of Slot API parameters.
The parameters were aligned according to the rules below:
For 1 slot (like wrapping something): content
For 3 horizontal slots: leadingContent / centerContent / trailingContent
For 3 vertical slots: headerContent / centerContent / footerContent
For 5 slots: leadingContent / headerContent / centerContent / footerContent/ trailingContent
For 2 vertical slots: headerContent / centerContent OR centerContent / footerContent
~~- [ ] Changelog is updated with client-facing changes~~
~~- [ ] New code is covered by unit tests~~
~~- [ ] Comparison screenshots added for visual changes~~
=> [2810] Align the naming of Slot API parameters

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/avatar/UserAvatar.kt
Fixes #2821 
Had to reorder the elements in a way that we always use a box and only add the indicator if needed instead of the previous logic.
Open the ChannelsScreen, shouldn't see flickering of avatars around online status updates.
=> Minor fix of recomposition

stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/state/MessageInputState.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerDefaultTrailingContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerViewModel.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_composer_default_trailing_content.xml
https://stream-io.atlassian.net/browse/CAS-1468
Adding slow mode support to `MessageComposerView`.
1. Propagating current `coolDownTimer` value in `MessageInputState`
2. Disabling send button when `coolDownTimer` is > 0
3. Displaying remaining cooldown seconds at `coolDownBadge` `TextView` displayed in front of send button.
https://user-images.githubusercontent.com/4527432/147079587-3816c85d-1f9a-4572-87bd-0cf4b2e6c695.mp4
Run ui-components sample app on the `feature/cas-1468-composer-slow-mode` branch. Open a channel with slow mode enabled and test sending messages.
This PR is related to `MessageComposerView` development and targets the `feature/cas-1466-message-composer-attachments` working branch
=> CAS-1468 `MessageComposerView` slow mode 

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/PinnedMessagesPagination.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/ChannelApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/PinnedMessagesRequest.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/pinned/list/PinnedMessageListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/pinned/list/viewmodel/PinnedMessageListViewModel.kt
Add support for pinned messages endpoint
- Added new endpoint to `ChatApi`
- Added `getPinnedMessages` to `ChatClient` and `ChannelClient`
- Added `PinnedMessagesPagination` to simplify pagination options
- Refactor `PinnedMessagesViewModel` to use newly created endpoint
1. Change credentials
2. Run UI Components sample app
3. Go to pinned message list (ChannelInfoView -> PinnedMessages cell)
4. Play with pinning/unpinning and pagination
- [] ~PR targets the `develop` branch~ PR targets the `main` branch
=> [CAS-1505] Add support for pinned messages endpoint

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/list/SuggestionListController.kt
https://stream-io.atlassian.net/browse/CAS-1485
Fix displaying mentions after a newline
Added `Pattern.MULTILINE` to mention  patterns
Check if mentions work fine when writing a multiline message in `MessageInputView`
=> [CAS-1485] Fix displaying mentions after newline

CHANGELOG.md, stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/coil/StreamImageLoaderFactory.kt
Fixes #2913 
We had to apply minimum frame delay to our GIF loading factory so that all gifs load with the speed they should have.
Send the following Giphy link in a message, to any channel (https://giphy.com/gifs/bbc-3o6ZtbprtmmjsZzn2M), it should load as a Link attachment. Observe the GIF in the link preview.
The GIF will be much faster without these changes and it will load normally once the changes are applied.
This is ironic, so I won't do it. :]
=> Added minimum frame delay for giphies

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/internal/MessageListScrollHelper.kt
Proposed fix for #2912 
Our users have reported that long tapping on an item in the list both opens a dialog and allows them to scroll while holding the press. This shouldn't happen.
Added a check in our ScrollHelper that checks if we have any `DialogFragment`s active. If we do, it manually calls stop scrolling on the list to prevent further scroll, which releases the long tap/press.
- Open any messages screen (any channel). 
- Long tap on a message and keep holding the click.
- Attempt to scroll the list behind by holding and pulling the click up or down (while the dialog is active).
Before this change: The list kept scrolling.
After this change: The list should be static.
=> Add small fix to intercept scrolling when popups are shown

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channel/ChannelListViewModel.kt
Fix crashes caused by exceptions being thrown because of the use of `channel.id` instead `channel.cid` in `ChannelListViewModel.deleteConversation(Channel)` when deleting channels.
Replace the use of `channel.id` with `channel.cid` inside `ChannelListViewModel.deleteConversation(Channel)`.
Launch the Compose Sample app, long press on a channel item to open the bottom sheet containing channel options and delete a conversation.
Make sure the app does not throw any exceptions or crash.
=> [2941] Fix deleting channels

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/ChannelInfoDto.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/DownstreamMessageDtoAdapterTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/ChannelInfoDtoTestData.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/MessageDtoTestData.kt
https://github.com/GetStream/stream-chat-android/issues/2944
Fix the deserialization issue when searching for a message in a channel with 0 members:
```
com.squareup.moshi.JsonDataException: Required value 'member_count' missing at $.channel at $.results[0].message 
```
The `member_count` field is an optional field. It can be absent for a channel containing 0 members. This is not an issue for `ChannelDto` as the `member_count` field already defaults to 0 there. 
Added the default value to `ChannelInfoDto.member_count` so that searching for a message in a channel with 0 members completes without errors.
1. Apply the patch below to the `develop` branch
2. Ensure that searching for "abcde" returns an error
1. Apply the patch below to the `bugfix/2944-handle-absent-member-count` branch
2. …
=> [2944] Handle absent member count

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
Improve the` MessageComposer` UX by making sure that
1. Commands are disabled when text or attachments are present in the composer
2. Disable attachments button when mentions or commands popups are present
Reason for no. 2 Is that otherwise a user can create a situation where `AttachmentsPicker` and popups overlap.
Added additional logic statements to `DefaultComposerIntegrations` that make sure all conditions are satisfied.
| --- | --- |
| ![just_attachment_before](https://user-images.githubusercontent.com/37080097/150555605-4bbbffee-9f46-4e55-8799-762705fc3b15.png) | ![just_attachment_after](https://user-images.githubusercontent.com/37080097/150555603-abf72311-fb85-448c-942c-85bca6bed58b.png) |
| ![just_attachment_with_slash_before](https://user-images.githubuserconten …
=> [2816] Improve MessageComposer UX

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/usecase/MarkRead.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/usecase/MarkReadTest.kt
Fix marking read when using ChatDomain
Mark read wasn't working fine when `OfflinePlugin` is configured but we are using `ChatDomain.markRead` because we were running a precondition twice:
1. In `ChatClient.markRead` method
2. In `MarkRead` class, using `channelController.markRead()`
Introduced new internal `ChatClient.markRead` method that skips the precondition.
It'll be removed once `ChatDomain `is merged.
Test if mark read works fine when `ChatDomain` approach
=> Fix marking read when using ChatDomain

CHANGELOG.md, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventHandlerImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/logic/ChannelLogic.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/RepositoryFacade.kt
Fix clearing cache after receiving channel truncated event.
1. Replace `mutableState.messageList` with `mutableState._messages` when parsing messages to prevent propagating wrong state when updating `mutable._messages`
2. Remove `channel` from LRU cache when it was truncated
3. Fix updating `lastSyncAt` when recovery was run but there were no active channels
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/17440581/151767617-20505ab2-efda-4521-b2ff-b39b4b2eea79.mp4" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/17440581/151767600-3564f2a9-1ef0-4d20-8877-71f936dd8702.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
You will …
=> Fix clearing cache after receiving channel truncated event

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/token/CacheableTokenProvider.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/token/TokenManager.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/token/TokenManagerImpl.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/interceptor/TokenAuthInterceptorTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenConnectUser.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/token/CacheableTokenProviderTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/token/FakeTokenManager.kt
Our internal implementation was requesting new token multiple times even though it wasn't expired.
close #2966 
Create an implementation that caches a token to be used if it has not been invalidated. 
It is an internal implementation that doesn't change our public API and doesn't force our customers to create an implementation that keeps it.
Inject a custom `TokenProvider` and verify that `loadToken()` method is not called multiple times
=> Cacheable token provider

stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerSuggestionsPopup.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerViewModel.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerViewModelBinding.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerMentionSuggestionsContent.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_suggestion_list_view.xml
Ensure that dismissed mention/command suggestion dialogs don't appear after they were dismissed. 
Using `PopupWindow.setOnDismissListener` to reset the state inside ViewModel.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/151777455-204e4ee1-4404-43ee-92ff-b26d62af4b31.mp4" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/151777216-1d3f3757-41cf-43f0-8988-588340afdee0.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
1. Type "@" and observe the mentions suggestion popup
2. Dismiss the dialog with an outside click
3. Delete the input and observe that "phantom" popup doesn't appear
_Please provide a suitable …
=> [2996] Improve suggestion popup in new message composer

stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/GiphyMediaAttachmentViewStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/MediaAttachmentViewStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/GiphyMediaAttachmentView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/MediaAttachmentView.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_giphy_media_attachment_view.xml, stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_giphy_attachment.xml, stream-chat-android-ui-components/src/main/res/values/attrs_giphy_media_attachment_view.xml, stream-chat-android-ui-components/src/main/res/values/attrs_media_attachment_view.xml, stream-chat-android-ui-components/src/main/res/values/styles.xml
Continued working on resizeable Giphys.
Added:
- Styled attributes for `GiphyMediaAttachmentView`
- Additional capabilities such as constant size and giphy scaling logic
- Kdocs
Note:
Setting the following items in `StreamUi.MessageList.GiphyMediaAttachment` will result in the users seeing the UI as it was previously and visually avodiing introducing a breaking change. 
```xml
<item name="streamUiGiphyMediaAttachmentConstantSize">true</item>
<item name="streamUiGiphyMediaAttachmentGiphyMaxHeight">250dp</item>
<item name="streamUiGiphyMediaAttachmentScaleType">centerCrop</item>
```
The new system with autosizeable Giphy containers is much better however I believe this should be communicated to the users in case they want to keep the old system for some reason .
You can also keep the old …
=> Merge fork of branch `GiphyResizeAux`

CHANGELOG.md, buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt, stream-chat-android-offline/api/stream-chat-android-offline.api, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/ChannelDao.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/ChannelRepository.kt
Sync cached channels after setting the user.
Add calling sync endpoint for all cached channels after setting the user.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/17440581/152116997-2c3f62ba-3136-48ac-9e92-cca27607ec69.mp4" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/17440581/152118053-ea520f2d-f8ff-4f23-a1ab-d2d557ca1441.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
You will need two devices and apply a patch on one of them (it adds truncating channel after clicking on user avatar in `ChatFragment`).
1. Turn off `OfflinePlugin` - use `ChatDomain` instead
2. Send a message from device A and log out
2. Click on …
=> Sync cached channels after setting the user

stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/ReturnOnErrorCall.kt, stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/WithPreconditionCall.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/logic/ChannelLogic.kt
There are couple of issues like newly loaded message was not saved and callback issues in OfflinePlugin.
- Store messages locally so they can be found in subsequent queries from the database.
- Invoke callbacks on the main thread instead of the background.
**To test message not found crash:**
1. Bruised Pattern Channel.
2. Go into a pinned message, select the oldest pinned message  by Dmitri ("Check this article")
3. Select "Thread replies". It is crashing.
**To test thread exception:**
1. Follow the above steps, try to scroll in the thread page so `threadLoadMore` is triggered in VM.
=> Fix Offline Plugin Issues

CHANGELOG.md, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/ChatError.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/ChatErrorTest.kt
Add `UnknownHostException` as a non-permanent network error. If the internet is not available, the user can still regain connection and sync messages editions later. 
Refactor in the class, but the logic is the same, the only change is that `UnknownHostException` is not considered to be a permanent error and it can be the cause of a `ChatNetworkError`
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/153005698-b652de10-5b1d-45f1-bdf9-52cd0bc2686d.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/153005673-cab14867-98a9-4ebc-a0dd-7f2982526561.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Edit a message …
=> Adding UnknownHostException for not permanent network errors

stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/WithPreconditionCall.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/querychannels/logic/QueryChannelsLogic.kt
There is a bug when handling events. We use `ChatClient::state` extension function when we refresh channels after certain events but this extension function requires to have configured `OfflinePlugin` in `ChatClient` already.  OfflinePlugin is not configured in release builds.
Added a check to use `ChatDomain::channel()` when OfflinePlugin is disabled.
- Use SDK 4.28 in your application.
- Wait till you receive any events like `CidEvent` or `MarkAllReadEvent`.
- There must not be any exception and app should behave as expected.
=> Fix OfflinePlugin runtime exception

stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/querychannels/logic/QueryChannelsLogic.kt, stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt, stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
Fix OfflinePlugin.
- Keep stateless calls
- Use feature toggle to make sure that `ChatClient` is not being used at the wrong moment. 
- Reverting stateful calls to stateless
- Adding feature toggles.
Disable OfflinePlugi, don't set it in ChatInitilizer and test the app
- ~[ ] PR targets the `develop` branch~
=> Fixes for OfflinePlugin usage

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messageoptions/MessageOptions.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
It doesn't make sense to edit Giphy messages, as the BE doesn't re-process the giphy command and/or we can end up overriding the message and removing the Giphy.
It's also fairly uncommon to have this type of functionality.
Added checks if the message is a giphy, that we can't edit them.
| --- | --- |
| ![Screenshot_1644580499](https://user-images.githubusercontent.com/17215808/153587290-2606d05e-3455-415b-8925-558a344b46fe.png)  | ![Screenshot_1644580378](https://user-images.githubusercontent.com/17215808/153587320-1b2fc964-f9f9-4c64-a751-f2fff1146a92.png)  |
| --- | --- |
| ![Screenshot_1644580466](https://user-images.githubusercontent.com/17215808/153587560-cc6199d1-1870-475e-8cb1-8911dc2e1c56.png) | …
=> 3020 - Disallow editing giphy messages

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_list_view.xml
Fix setting custom empty and loading views for MessageListView
Fixed empty state and loading containers width and height
| Original | Customized |
| --- | --- |
| <img width="435" alt="Screenshot 2022-02-15 at 15 46 40" src="https://user-images.githubusercontent.com/17440581/154087506-dc47b6a0-1119-43e8-a846-34e70e211eef.png">|<img width="435" alt="Screenshot 2022-02-15 at 15 46 10" src="https://user-images.githubusercontent.com/17440581/154087490-6a5158d7-67ad-43b7-ab82-c56aea395454.png">|
1. Apply the patch and check if both original and customized versions work fine.
2. Apply the same patch on `develop` and test the customized version.
<details>
```
Index: …
```
=> Fix setting custom empty and loading views for MessageListView

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/EventMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/EventDtos.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/ChatEventHandler.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/DefaultChatEventHandler.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/Mother.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/querychannels/DefaultChatEventHandlerTest.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/utils/TestDataHelper.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/CustomEventHandler.kt
Closes #3089
Don't remove the channel from the UI if a member removal event arrives and the removed member is no the current user.
1. User1: Launch UI components sample app and create a named channel with users User2 and User3
2. User2: Observe that the channel has appeared
3. User1: Remove irrelevant User3 from the channel
Actual result:
User2: the channel disappears from the channel list even though user2 is still a member of the channel
Expected result:
User2 observes that the number of sections in the channel's avatar is reduced and the channel remains in the list
=> [3089] Fix default events handler

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageComposerViewModel.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
Closes #3099 
Exposed MessageComposer's `clearData()`.
Can be called from the ViewModel/Controller now, wasn't available before.
=> Exposed clearing of message composer

CHANGELOG.md, buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
Bump Compose version to [1.1.1](https://developer.android.com/jetpack/androidx/releases/compose-ui#version_11_2). It includes some critical issues fixes below:
Bug Fixes
- Fix NullPointerException at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList ([aosp/1947059](https://android-review.googlesource.com/c/platform/frameworks/support/+/1947059), [b/206677462](https://issuetracker.google.com/issues/206677462))
- Fix crash caused by clipboard content while reading from clipboard on Android. ([I06020](https://android-review.googlesource.com/#/q/I0602066750e3fce55deceb709f8c04ee9a71dabf), [b/197769306](https://issuetracker.google.com/issues/197769306))
- Fixed RTL in LazyVerticalGrid ([aosp/1931080](https://android-review.googlesource.com/c/platform/frameworks/support/+/1931080), …
=> Bump Compose version to 1.1.1

CHANGELOG.md, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventHandlerImpl.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/ChatDomainImplReplayEventsForActiveChannelsTest.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/event/TotalUnreadCountTest.kt
Fix updating `ChatDomain::totalUnreadCount` and `ChatDomain::channelUnreadCount`
The unread counts shouldn't be updated if the event comes from the sync endpoint or the channel doesn't have `read-events` capability.
You should test two scenarios. For both, you'll need to use `ui-components`, apply a patch and use two devices. The patch modifies `ChannelListViewModel::filter` so you should see two channels: `livestream` and `messaging`. Before testing, run the app and filter the logs by `UnreadTest` keyword.
Scenario 1:
1. Open the app on device 1 and stay on `ChannelListView`
2. Send a message to `livestream` channel from device 2
3. Observe that unread counts stay the same (are not being updated)
4. Check the same behavior on `main` - unread counts are being reset to 0
Scenario 2:
1. …
=> Fix updating ChatDomain::totalUnreadCount and ChatDomain::channelUnreadCount

stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/listeners/ShuffleGiphyListener.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/OfflinePlugin.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/factory/StreamOfflinePluginFactory.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/ShuffleGiphyListenerImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
closes #3140 
Move `shuffleGiphy` method to LLC
Converted `shuffleGiphy` extension function to a method and applied side effects.
Check if shuffling a Giphy works as expected
=> Move shuffleGiphy method to LLC

stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Android.java, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt, stream-chat-android-offline/api/stream-chat-android-offline.api, stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomain.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/usecase/LoadOldMessagesTest.kt, stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModelTest.kt
Closes #2976 
Clean the older unused `ChatDomain::loadOlderMessages` from tests and docs.
- Docs are updated to use `ChatClient::loadOlderMessages` instead of `ChatDomain::loadOlderMessages`.
- Tests are modified/removed which were using `ChatDomain::loadOlderMessages`.
- Run the sample app and it should work as expected.
=> Remove unused ChatDomain::loadOlderMessages

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/state/ChannelMutableState.kt
The typing events state is not reflected correctly in `MessageListViewHeader`. 
- Simplified the logic of populating typing events state.
- Run the samples app on two devices with different accounts. 
- Type a message in one device and you should be able to see new typing indicators in the header of the other device.
=> Fix typing state event in `ChannelMutableState`

stream-chat-android-offline/api/stream-chat-android-offline.api, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelData.kt
Fix displaying Channel's name and image.
Added `name` and `image` to `ChannelData`.
1. Open a channel with the given name
2. Go back to the `ChannelListView`
3. Observe that the `name` stays the same
4. Repeat the process on `develop`
=> Fix displaying Channel's name and image

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/LoadNotificationDataWorker.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/ChatNotificationHandler.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/MessagingStyleNotificationHandler.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/NotificationHandlerFactory.kt, stream-chat-android-client/src/main/res/values-en/strings.xml, stream-chat-android-client/src/main/res/values-es/strings.xml, stream-chat-android-client/src/main/res/values-fr/strings.xml, stream-chat-android-client/src/main/res/values-hi/strings.xml, stream-chat-android-client/src/main/res/values-id/strings.xml, stream-chat-android-client/src/main/res/values-in/strings.xml, stream-chat-android-client/src/main/res/values-it/strings.xml, stream-chat-android-client/src/main/res/values-ja/strings.xml, stream-chat-android-client/src/main/res/values-ko/strings.xml, stream-chat-android-client/src/main/res/values/strings.xml
Add possibility to customize notification channel.
- Added `notificationChannel` lambda parameter to `NotificationHandlerFactory::createNotificationHandler` which is used to create a `NotificationChannel` used for displaying notifications
- Changed the `NotificationChannel` used for displaying `Loading notification data` notification
Test push notifications on Android <= O and > O.
=> Add possibility to customize notification channel

CHANGELOG.md, stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Messages.java, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Messages.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/attachment/AttachmentFactory.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/attachment/AttachmentFactoryManager.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/attachment/InnerAttachmentViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/CustomAttachmentsViewHolder.kt
Choose a more descriptive name for the `AttachmentViewHolder`.
Renamed the class to `InnerAttachmentViewHolder` to indicate that it doesn't represent an individual ViewHolder. It represents just an inner ViewHolder delegate with the lifecycle of the outer ViewHolder.
=> [3109] Rename inner attachment ViewHolder

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/internal/SimpleChannelListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
Fixes #3175 
Some users require a way to check if the message or channel lists have been initialized (we generally check if the adapter exists for this).
This is required to let them build custom auth logic and show some info only when the data is ready.
Exposed a simple function that tells us if the adapter is initialized or not in these lists.
No real test, can just call it from the outside before and after binding the data/showing items.
=> Expose a check if the adapter has been initialized or not in Channel and Message lists

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/list/ChannelItem.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_item_foreground_view.xml
Fixing wrong behavior. Closes #2884 
We just added checks to show/remove the read status in case the last message is not from the current user.
| Before Filip | Before Amit |
| --- | --- |
| ![Screenshot_1646748750](https://user-images.githubusercontent.com/17215808/157255117-3c388c3a-a017-4748-a73e-ba2080799c35.png) | ![Screenshot_1646748749](https://user-images.githubusercontent.com/17215808/157255085-2254e96a-cac0-4658-a0d8-3d574e833753.png) |
| After Filip | After Amit |
| --- | --- |
| ![Screenshot_1646748702](https://user-images.githubusercontent.com/17215808/157254971-b840ab77-2fa2-4704-9f41-d867145b6619.png) | ![Screenshot_1646748920](https://user-images.githubusercontent.com/17215808/157255385-111b08ce-a3fd-421e-842b-7ca14f2cf9d1.png) |
1. Run the sample app on develop - all …
=> 2884 - Remove read status indicators when the last sent message is not from the current user

CHANGELOG.md, docusaurus/docs/Android/03-ui/05-components/05-message-list.mdx, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsView.kt, stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml, stream-chat-android-ui-components/src/main/res/values/styles.xml
Allow customizing retry message action
Added `streamUiRetryMessageEnabled` attribute to `MessageListView` which is `true` by defauly.
1. Apply the patch. It will disable `retry message` option and mark every message sent by the current user as failed
2. Check that option is not visible
3. Go to `fragment_chat` and change flag to `true`
4. Check that option is available
<details>
```
Index: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/viewmodel/MessageListViewModelBinding.kt
<+>UTF-8
diff --git …
```
=> Allow customizing retry message action

CHANGELOG.md, docusaurus/docs/Android/04-compose/03-general-customization/01-chat-theme.mdx, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamRippleTheme.kt
Fix ripple color in dark mode.
Providing `LocalRippleTheme` in `ChatTheme` like it is done in `MaterialTheme`. 
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/158569451-b31eb32c-fbd5-4ce0-a54e-b763e8e9abfb.mp4" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/158568741-1ee3b2cf-787c-4588-8575-adccf0f358dc.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
1. Switch to dark mode
2. Observe ripple colors
=> [3193] Improve click ripple

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/messages/list/MessageListItemState.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/list/ChannelItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/channels/MessageReadStatusIcon.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageFooter.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
Implement message delivery indicator in the message list.
https://user-images.githubusercontent.com/9600921/158708776-7ff004cc-4563-459d-8781-31c3064d2ec0.mp4
1. Send a message
2. Read the message from another client
3. Observe that the message was read
=> [3217] Add support for message delivery indicator in the message list

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Fix QueryChannels.
`QueryChannelsPostponeHelper` has to be applied only in the API call, but not in the plugins. Otherwise, the database call (and any other plugin) will be postponed too. In our current case, that stops data from being fetched from database. 
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/158478457-e5e99857-45dc-4c19-a785-bb01d55ccb21.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/158478632-e41c4839-9005-465b-ab6d-40daa24ba638.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Do the test in the video.
- ~ [] Changelog is updated …
=> Postponing API call, but not plugins apply

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/SyncStatus.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messageoptions/MessageOptions.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt, stream-chat-android-compose/src/main/res/drawable/stream_compose_ic_thread.xml, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsView.kt
Reduce the number of message actions for failed / pending messages.
**Compose: theirs message** 
| --- | --- |
| ![photo_2022-03-18 17 36 37](https://user-images.githubusercontent.com/9600921/159023075-447c4ff7-cd7e-4abe-b13f-016707dd5bb1.jpeg) | ![photo_2022-03-18 17 20 11](https://user-images.githubusercontent.com/9600921/159020078-e81752f1-4f89-488d-97e2-e8d10efcae3c.jpeg) |
**Compose: mine message** 
| --- | --- |
| ![photo_2022-03-18 17 36 08](https://user-images.githubusercontent.com/9600921/159023000-066dbbd2-727e-49e6-afea-5231839f59e7.jpeg) | ![photo_2022-03-18 17 19 29](https://user-images.githubusercontent.com/9600921/159019994-c5ceda3b-1a6e-4e5c-a0a8-9c2eaadc5a32.jpeg) |
**Compose: failed message** 
| --- | --- |
| …
=> [3188] Fix message options

docusaurus/docs/Android/02-client/06-guides/06-offline-support.mdx, docusaurus/docs/Android/02-client/06-guides/07-chatdomain-migration.mdx, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt, stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Channels.java, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Channels.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/member/GroupChatInfoMemberOptionsViewModel.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/users/GroupChatInfoAddUsersViewModel.kt
closes #3034 
Add `ChatDomain` migration guide.
1. Add migration guide.
2. Unify `addMembers` and `removeMembers` API
**NOTE: Some of the link won't work correctly before the release **
1. Checkout the branch
3. Run `npx stream-chat-docusaurus -i -s`
4. Review the migration guide page
=> Add ChatDomain migration guide

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
Remove typing related actions in MessageListViewModel
The code was pushed by accident.
=> Remove typing related actions in MessageListViewModel

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/ChatUI.kt
Fix crash when overriding `ChatUI::imageHeadersProvider`.
The crash was caused by a compiler issue introduced in Kotlin `1.6.0`. You can find more details  [here](https://youtrack.jetbrains.com/issue/KT-49793).
The issue should be fixed in Kotlin `1.6.20`.
Apply the patch and try to run the UI Components sample app. Compare with develop.
<details>
```
Index: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/ChatUIInitializer.kt
<+>UTF-8
diff --git a/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/ChatUIIniti …
```
=> Fix crash when overriding ChatUI::imageHeadersProvider

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputViewStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/attachment/AttachmentSelectionDialogFragment.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/attachment/AttachmentSelectionDialogStyle.kt, stream-chat-android-ui-components/src/main/res/values/attrs_message_input_view.xml, stream-chat-android-ui-components/src/main/res/values/styles.xml
Fixes #3241 
We exposed a way to customize the icons, but not the colors of the icons. This way our users can easily customize both.
Exposed a color state list attribute to the MessageInputView style, that's propagated to the AttachmentDialogStyle.
No UI changes per se, but testing with the given patch will produce the following:
<details>
```
Index: stream-chat-android-ui-components/src/main/res/color/stream_ui_test.xml
<+>UTF-8
diff --git a/stream-chat-android-ui-components/src/main/res/color/stream_ui_test.xml b/stream-chat-android-ui-components/src/main/res/color/stream_ui_tes …
```
=> Expose attributes and customization for tab colors

docusaurus/sidebars-android.js
Add `ChatDomain` migration guide to the sidebar.
1. Run `npx stream-chat-docusaurus -i -s`
2. Make sure `ChatDomain migration` page is visible in sidebard
=> Add ChatDomain migration guide to sidebar

CHANGELOG.md, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/channels/ChannelListHeader.kt, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/channels/ChannelListView.kt, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/general/ChatUi.kt, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageInput.kt, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageList.kt, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageListHeader.kt, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/utility/AttachmentGallery.kt, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/utility/SearchView.kt
Due to concurrent changes to the docs (code snippets, documentation structure), some of the links in the snippets are broken.
Check that the links are no longer broken.
=> [2957] Fix code snippets links

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/GiphyAttachmentViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsDialogFragment.kt
Fix bugs listed in https://github.com/GetStream/stream-chat-android/issues/3259
- `GiphyAttachmentViewHolder`
Remove `modifiedListeners()` and set the listeners upon initialization.
- `UserReactionsView` not displaying reactions properly
Do not rely on `private val currentUser: LiveData<User?> = ChatClient.instance().globalState.user.asLiveData()`. The `LiveData` is never observed, only having it's value read directly. This in turn leads to a race condition in which the `LiveData` will never emit the value before the value is read as `currentUser?.value`. Instead realy on `ChatClient.instance().globalState.user.?.value`.
| --- | --- |
| ![Screenshot_1648481759](https://user-images.githubusercontent.com/37080097/160436426-26965c0a-f83b-485c-a26a …
=> [3259] Fix reactions in UI Components

docusaurus/docs/Android/04-compose/03-general-customization/01-chat-theme.mdx
Fix wrong documentation on docusaurus for Jetpack Compose ChatTheme.
=> Fix docusaurus for Jetpack Compose ChatTheme

CHANGELOG.md, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/querychannels/internal/QueryChannelsLogic.kt
Fix NPE in client.state.
We run `QueryChannelsLogic.updateOnlineChannels` asynchronously so changes in ChatClient.state can result in unpredictable results. An example is that client.state may be null, is the user disconnects while waiting for the results of the request. 
By passing the reference in the constructor, this reference won't be lost in the middle of the request. 
Log in and out some times in the app, in different scenarios.
=> Fixing client.state NPE

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/UserMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/UserDtos.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/DownstreamUserDtoAdapterTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/UserDtoTestData.kt
#3278 
Fixed `User` model deserialization error when `User.image` is null.
Made `DownstreamUserDto.name` and `DownstreamUserDto.image` nullable. 
Run tests and check if users' images and names work as expected.
=> Fixed User deserialization error

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/FileAttachmentPreviewContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/ImageAttachmentPreviewContent.kt
Implement horizontal scrolling for file previews in the message composer.
| --- | --- |
| ![photo_2022-04-04 23 52 51](https://user-images.githubusercontent.com/9600921/161630266-f1347dfb-7728-4377-9fdc-348fcb2a1481.jpeg) | ![photo_2022-04-04 23 46 51](https://user-images.githubusercontent.com/9600921/161629401-c41c947b-6596-4231-9f2e-b2d723fcdf9d.jpeg) |
| ![photo_2022-04-04 23 52 48](https://user-images.githubusercontent.com/9600921/161630272-5867da24-d8ce-4beb-af86-14421a78a937.jpeg) | ![photo_2022-04-04 23 46 53](https://user-images.githubusercontent.com/9600921/161629396-a2a2a679-b36e-4e52-abaf-bc011b9f2e1f.jpeg) |
1. Run Compose sample app and select several file attachments
2. Verify that they can be scrolled horizontally
=> [2680] Improve message input attachments UX

CHANGELOG.md, stream-chat-android-compose/build.gradle, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/attachments/images/ImagesPicker.kt, stream-chat-android-compose/src/main/res/drawable/stream_compose_ic_video.xml
Apart from images, we should also display videos in the first tab of our attachments picker. Currently, the Compose version of the SDK shows no thumbnails for videos.
In order to support video thumbnails, we need to use `VideoFrameUriFetcher` from the `io.coil-kt:coil-video` library.
| --- | --- |
| ![photo_2022-04-07 02 44 35](https://user-images.githubusercontent.com/9600921/162092141-ffc0b955-c214-48e7-a506-3163a847c3e5.jpeg) | ![photo_2022-04-07 02 43 19](https://user-images.githubusercontent.com/9600921/162092014-31203d0b-712f-46ee-bb8e-4af93bf607d4.jpeg) |
1. Open attachment picker and scroll to a video
2. Check that the video thumbnail is displayed
=> [3295] Show video thumbnail in attachment picker

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageFooter.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/sync/internal/SyncManager.kt
issue: [3318](https://github.com/GetStream/stream-chat-android/issues/3318)
Fix editing message while offline.
Check if the message was sent to the backend before trying to update it. If the message was not sent, we shouldn't try to update it in the backend, but send it with the new text. 
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/162757769-b4ce0351-924d-46d8-b3c7-f9aea97a0369.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/162757742-df6a97b3-aa6e-4d6d-9e26-583ae5b7d8f0.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
- Use airplane mode. 
- Send a message
- Edit it
- Become online. 
In develop …
=> [ISSUE-3318] Fixing editing message while offline

stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/BaseConnectedActivity.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/ChannelsActivity.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/MessagesActivity.kt
Fix reconnection issue in Compose sample app.
Our Compose sample app doesn't handle process death gracefully. Even though, we try to keep our Compose app as clean as possible it is still necessary to add some boilerplate to handle the case when the OS kills the app in the background.
| --- | --- |
| ![photo_2022-04-12 14 23 39](https://user-images.githubusercontent.com/9600921/162949629-dd9dd598-16f2-4688-baad-9eabbb9d7ac3.jpeg) | ![photo_2022-04-12 14 23 36](https://user-images.githubusercontent.com/9600921/162949637-d4d01265-0037-4336-938d-2d0e165ff654.jpeg) |
1. Open Compose sample app and login with any user
2. On the channels screen, press home button to collapse the application
3. From Android Studio, press the "Terminate Application" button
4. Open recent …
=> [3311] Fix process death issue in Compose sample app

config/detekt/detekt-test.yml, scripts/detekt-test.gradle, stream-chat-android-test/build.gradle, stream-chat-android-test/detekt-baseline.xml
Fix the issues we had on Test Module.
On our test module, we have the `Mother` methods that receive a lot of default arguments, In our main "Detekt Rules Set" we only allow 6 arguments per method and dafault argument count on this rule. I have create a new "Detekt Rules Set" that is only applied to this module to avoid this rule that doesn't make sense on this module.
Fixes https://github.com/GetStream/android-internal-board/issues/25
- ~[ ] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui)~
=> Fix Detekt Issues on Test module

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/SupportedReactions.kt
Fix reaction drawables wrong tint.
The drawables used from resources get cached and when a change is applied it is propagated to all of the drawables. Calling `.mutate()` will make drawable mutable ensuring that it won't share its state to other instances. 
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/38032787/163400032-0b79702e-387e-48ac-bd62-9571bc8607d3.mp4" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/38032787/163400538-0f1c98f7-fac3-4dab-8668-797114a8968a.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Run develop branch on Android Nougat (7, API 28). Add reactions to a single message using at least two users. …
=> [2881] Fix wrong tint on reaction drawables

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/FullScreenDialogFragment.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/TouchInterceptingFrameLayout.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/MessageListItemViewHolderFactory.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsDialogFragment.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_dialog_message_options.xml
Custom `MessageListItemViewHolderFactory` is ignored by the message options overlay. The default factory is used instead. 
We need to ensure that in case a client provides a custom `MessageListItemViewHolderFactory`, then this factory is also used on the message options overlay.
Removed the `clone()` method, as it is impossible to clone the provided custom implementation of `MessageListItemViewHolderFactory` without reflection. And even with reflection, it is highly unlikely that we will be able to create a new instance of the class that could have constructor parameters.
So, it was decided to use the original message item factory provided by the message list.
<details>
```
Index: …
```
=> [3299] Fix custom message item factory on message options overlay

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/Call.kt
Change visibility of the retry extension to internal.
=> Change visibility of the retry extension to internal

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messageoptions/MessageOptions.kt
Fixes #3340 
Added checks for the default message options to show the Copy message option in case the message has links.
1. Open the sample app
2. Long tap on a message with a link
3. You should see the "Copy Message" option now
=> Allowed copying of messages containing links

CHANGELOG.md, stream-chat-android-core/src/main/java/io/getstream/chat/android/core/internal/coroutines/DispatcherProvider.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
Fixes #3349 
Relying on the `Dispatchers.Main.Immediate` helps us force the state/UI updates that aren't asynchronous, to be fully synchronous - i.e. to avoid dispatching events cycle.
By avoiding dispatching event cycles, the UI updates are no longer race-conditioned in Compose and things work nicely.
Lovely framework bug ^^
| --- | --- |
| https://user-images.githubusercontent.com/17215808/163799261-93ef7df9-987c-4791-9a44-c68b5221b7a2.mp4 | https://user-images.githubusercontent.com/17215808/163799308-1e6d3a52-31e2-4feb-b587-1efc473afbd7.mp4 |
1. Run the app on develop on a live device (not emulator)
2. Try typing really fast in the message input (random bashing also works)
3. Sporadically, the message input seems to clear and reset. Also, holding the delete button …
=> Add immediate dispatcher provider and apply it to MessageComposerController.kt

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/member/GroupChatInfoMemberOptionsDialogFragment.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/member/GroupChatInfoMemberOptionsViewModel.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/preview/ChatPreviewFragment.kt
closes #3316 
Fix sample app crash after clicking on message option.
1. Simplify `GroupChatInfoMemberOptionsViewModel` initialization so there is no need to call `watchChannel`
2. Hide channel info option from dialog fragment if the channel doesn't exist
3. Fix crash after clicking on user's avatar in preview fragment
**NOTE:** There is one more issue (infinite loading on `MessageListView`) that will be fixed in a separate PR
| --- | --- |
|https://user-images.githubusercontent.com/17440581/164706673-3be0bec6-a253-42b9-ad68-5f25d136437c.mp4|https://user-images.githubusercontent.com/17440581/164706660-34b13327-c440-4684-9f64-1353af7057c0.mp4|
1. Go to the group channel, press the channel's avatar and press one of the members
2. Make sure that …
=> Fix sample app crash after clicking on message option

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsDialogFragment.kt
Fix bug related to configure flag message confirmation.
Changing of style field to another
diff:
```
diff --git a/stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat.xml b/stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat.xml
index 17f5e61dc2..ef86f2c581 100644
--- a/stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat.xml
+++ b/stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat.xml
@@ -24,7 +24,7 @@
app:layout_constraintEnd_toEndOf="parent"
app:layout_constraintStart_toStartOf="parent"
app:layout_constraintTop_toBottomOf="@+id/messagesHeaderView"
-        app:streamUiFlagMessageConfirmationEnabled="true"
+        app:streamUiFlagMessageConfirmationEnabled="false" …
```
=> Changing deleteConfirmationEnabled to flagMessageConfirmationEnabled

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
Message input is unresponsive upon first entering a channel offline. 
This PR aims to make the input responsive.
Closes #3418
Set `isFocusableInTouchMode` on `MessageInputView`s inner `EditText` as well.
1. Kill app if app is open
2. Go offline
3. Open app
4. Enter a channel for the first time in this session (has to be the first)
5. Try to click on the `EditText` inside `MessageInputView`
Expected behavior: The field is clickable, responsive and you can input a message
=> [3418] fix unresponsive message input

CHANGELOG.md, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/model/channel/ChannelData.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
closes #3413 
Fix updating own capabilities after receiving events.
`Channel` object from events doesn't contain `ownCapabilities` field.
That's why we should only update `ChannelData::ownCapabilities` if the set is not empty.
1. Go to the channel and send some messages
2. Add a new user (to this channel) from another device
3. Try to send more messages
=> Fix updating own capabilities after receiving events

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/SocketFactory.kt
closes #3429 
Fix overriding User's image and name properties
Exclude `image` and `name` properties from user details JSON if they are empty.
Apply the patch:
<details>
```
Index: stream-chat-android-ui-components-sample/src/demo/kotlin/io/getstream/chat/ui/sample/application/AppConfig.kt
<+>UTF-8
diff --git a/stream-chat-android-ui-components-sample/src/demo/kotlin/io/getstream/chat/ui/sample/application/AppConfig.kt b/stream-chat-android-ui-components-sample/src/demo/kotlin/io/getstream/chat/ui/sample/application/AppConfig.kt
--- …
```
=> Fix overriding User image and name properties

CHANGELOG.md, docusaurus/docs/Android/04-compose/03-general-customization/01-chat-theme.mdx, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/DefaultStreamCoilImageLoader.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/MessagePreviewFormatter.kt
Ensure that clients are able to use `ChatTheme` without the need to add Coil dependency to their projects.
=> [3439] Don't expose Coil ImageLoader in ChatTheme

stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Closes https://github.com/GetStream/stream-chat-android/issues/3498
Make `ChatClient.Builder.build` method accessible from Java.
- cut release build using
```
./gradlew :stream-chat-android-client:assembleRelease
```
- create a separate dummy project
- inject generated `chat-client aar` as a library in the dummy project
- add the code below
```Java
ChatClient client = new ChatClient.Builder("asfdgsfgasfds", context)
.logLevel(ChatLogLevel.ALL)
.withPlugin(factory)
.build(); // <-- here
```
=> [3498] ChatClient.Builder.build method is not accessible from Java

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
Allow users to switch to command mode manually so they can create shortcuts to certain commands.
closes #3370 
closes #3371 
Exposed a public method `switchToCommandMode()` inside `MessageInputView`.
| --- | --- |
| ![output](https://user-images.githubusercontent.com/37080097/168333254-cc70ad52-9bcd-4f5d-b592-82eeced861cd.gif) | ![output0](https://user-images.githubusercontent.com/37080097/168333259-53ed5c9c-ffc7-4830-b926-df507930fc57.gif) |
1. Apply the patch provided below
2. Launch the UI Components Sample App
3. Enter a channel that allows sending Giphys (most if not all channels in the sample app)
4. Click on the Giphy command button
Expected result: The button should immediately activate command mode with Giphys in mind
<details>
<summary>Git Patch implementing …
=> [3515] Enable Command Shortcuts

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
Fix initializing `OfflinePlugin` when connecting anonymous user.
When connecting anonymous users, we were calling `initializationCoordinator.userConnected()` after receiving the first `ConnectedEvent` because we didn't have the `User` object earlier.
The problem is that with this approach, `OfflinePlugin` won't receive `ConnectingEvent` and `ConnectedEvent` because the listener won't be set yet.
Changed the approach to match regular user connection with providing "fake" anonymous user object
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/17440581/169562194-3c0747ef-cf17-422b-8992-5cfcb7f67fe7.mp4
" controls="controls" muted="muted" />
</td>
<td>
<video …
=> Fix initializing OP when connecting anonymous user

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
Fix issue after disconnecting and reconnecting as the same user.
Add clearing cached OP instance when disconnecting the user.
When the user calls `ChatClint::disconnect` we are deinitializing all OP-related classes and therefore we should create a new OP instance when connecting the same user again.
1. Sign in as a User
2. Sign out
3. Sign in as the same user
You should be able to see the channels list and interact with channels without problems.
=> Add clearing cached OP instance when disconnecting the user

.idea/codeStyles/Project.xml
Closes #3558 
Reformatting an XML file in Android Studio removes line breaks before comments:
```xml
<?xml version="1.0" encoding="utf-8"?>
```
->
```xml
<?xml version="1.0" encoding="utf-8"?>
```
As a result, the code above doesn't pass `./gradlew spotlessCheck`. We need to adjust Android Studio code style settings so that auto formatting doesn't affect the license header.
Turning on the "Keep line breaks" setting for XML files.
1. Restart Android Studio for the changes to take effect
2. Open any XML file with our license header
3. Press `Option + Command + L` to reformat the code
4. The license header should remain intact
=> [3558] Fix license header reformatting

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaPreviewActivity.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentMediaActivity.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_activity_attachment_media.xml, stream-chat-android-ui-components/src/main/res/values/attrs_media_activity.xml, stream-chat-android-ui-components/src/main/res/values/styles.xml
Closes #3539
Currently, the media preview screen remains black while the video is loading. We should provide a loading indicator not to confuse users.
<table>
<thead>
<tr>
<th>UI Components</th>
<th>Compose</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/169530400-ac94847e-7856-4dc5-bb7a-620029fd9104.mp4" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/169530409-8eda0bba-d317-4e0e-9952-ba6dfa53d311.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
1. Click on a message with video attachment
2. Ensure that a progress indicator is displayed before the playback
=> [3539] Show progress bar when a video is loading

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/MessagingStyleNotificationHandler.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/InitializationCoordinator.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/BaseChatClientTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenConnectUser.kt
Ensure `currentUser` is not init when a push notification is received.
Fix #3403 
Previously, when a push notification was received we initialized the `currentUser`. It was done because when the PN is received we need to do some calls to the API to receive the most updated data. Those calls need to be authenticated. To authenticate the calls we don't really need the current user to be initialized, but the token provider. With this PR I refactor the flow when a PN is received to be sure the token provider is already initialized.
On the other hand, a new internal method has been created to obtain info from the "stored user". This info is used on `MessagingStyleNotificationHandler` to display the user info on the notification 
-. Open the sample app and login with an user on "Device A".
-. …
=> Init `currentUser` only when `connectUser()` is called

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QuerySort.kt
Log all the available fields in a class and the one that was searched, when QuerySort can't find a property.
=> Logging when QuerySort could not find a property for a class

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/StreamLifecycleObserver.kt
Verify an observer was added before trying to remove it from the `lifecycle` owner, because on the case it wasn't added the internal implementation throws an exception.
=> Not try to remove an observer if the observer wasn't added

CHANGELOG.md, stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.kt
Improve handling reads in `MessageListItemLiveData`.
Add additional null check when updating reads.
Run UI Components sample app and make sure `MessageListView` is updated properly.
=> Improve handling reads in MessageListItemLiveData

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/FileAttachmentsView.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_file_attachment.xml
The upload progress text does not have enough space to properly unfurl and often gets ellipsized.
closes #3496
- Set the visibility of `actionButton` to gone while the file is being uploaded
- Trim the padding of stream_ui_item_file_attachment.xml so that the text has more space
| --- | --- |
| https://user-images.githubusercontent.com/37080097/170707652-a7a4eb24-e963-40f7-badc-f6feff052568.mp4 | https://user-images.githubusercontent.com/37080097/170707660-c17db614-9142-4550-8d48-4ff7e494c5a8.mp4 |
1. Upload a file
2. Observe the progress text saying " y MB / x MB"
Expected: The text should not be clipped / ellipsized.
=> [3496] Fix upload progress text getting ellipsized

stream-chat-android-ui-components-sample/src/debug/kotlin/io/getstream/chat/ui/sample/application/DebugMetricsHelper.kt
Even though it might be beneficial to leave this option enabled, looks like it produces a certain amount of false positives and the sample app crashes without a reason for that. Removing it for now.
=> Remove death penalty for violating strict mode policy

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/message/MessageUtils.kt, stream-chat-android-compose-sample/detekt-baseline.xml, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/data/PredefinedUserCredentials.kt, stream-chat-android-core/api/stream-chat-android-core.api, stream-chat-android-core/src/main/java/io/getstream/chat/android/core/utils/date/DateUtils.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventBatchUpdate.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerSequential.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/batch/SocketEventCollector.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/builder/internal/RepositoryFacade.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/ChannelEntityUtils.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/ChannelMapper.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/DatabaseChannelRepository.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/domain/channel/internal/ChannelRepositoryImplTest.kt, stream-chat-android-ui-components-sample/src/demo/kotlin/io/getstream/chat/ui/sample/application/AppConfig.kt
Closes: https://github.com/GetStream/stream-chat-android/issues/3546
Related PR: https://github.com/GetStream/stream-chat-android/pull/3524
Show the latest actual data in offline mode.
1. Open either sample app while online
2. Stay on the channel list
3. Take a screenshot of the channel list
4. Kill the app
5. Go offline
6. Re-open the app while offline and stay on the channel list
7. Take a screenshot
8. Compare screenshots
Expected: The channel list shows the latest previously seen online state.
=> [3546] Channel list loads stale data from the DB

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerImpl.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerSequential.kt
Closes: https://github.com/GetStream/stream-chat-android/issues/3635
Avoid `sync history` request being fired if `cids` list is empty.
Connect user who has no channels.
=> [3635] Sync history only when necessary

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/EmojiUtil.kt
Messages with a single file attachment and no text are missing the chat bubble
Modify the function designed to check if the message is emoji only so that it does not register messages with empty text as emoji only.
| --- | --- |
| ![emoji_before](https://user-images.githubusercontent.com/37080097/174281432-14655d71-162b-4381-a874-5eeabdb56bb6.png) | ![emoji_after](https://user-images.githubusercontent.com/37080097/174281439-064b0ac1-23d4-4576-b3fa-9f3e81178a0a.png) |
1. Check that this has the bubble correctly displayed for messages with a single file attachment
2. Check that quoting above mentioned messages produces the expected result
3. Check that the emojis are displayed as instructed in [#3665](https://github.com/GetStream/stream-chat-android/pull/3665)
=> [3692] Reinstate missing chat bubble

stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatApp.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt
The toggle service should be initialized before ChatClient otherwise components inside ChatClient are not initialized properly.
- Changed the order of initialization of toggle service.
- Do a fresh installation of the sample app or clean the storage before installation.
- Check if the socket connection is working as expected or not.
=> Initialise toggle service before ChatClient

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/socket/ws/WebSocketEventObserver.kt
Closes #3738 
When the WebSocket receives too many events and the subscriber is busy handling those events, we miss a few events. It happens because `StateFlow` only keeps the last event. We need to change the events flow type to `SharedFlow`.
- Replaced `StateFlow` with `SharedFlow` for events flow.
- Run the sample app on two devices.
- Remove a user from any channel on device A.
- On device B, you must receive 6 events inside `EventHandler`.
- You can check the logs with tag `Chat:SocketEvent` that must have those six events similar to following:
```
2022-06-22 17:57:55.168 19633-19633/io.getstream.chat.ui.sample.debug V/Chat:SocketEvent: (main:2) [onSocketEventReceived] event.type: notification.mark_read
2022-06-22 17:57:55.197 19633-19633/io.getstream.chat.ui.sample.debug …
```
=> Use SharedFlow with buffer for WebSocket events

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
Fix counting of unread messages for newly created channels.
Initializing `mutableState._read.value` if it is ready. This code: 
```
mutableState._read.value = readState.apply { this?.unreadMessages = unreadCount + 1 }
```
Was rewriting null to `mutableState._read` if it wasn't initiated. Now it initializes it when it is null. 
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/175085321-8c413c7c-af03-4e12-830e-fbd6c81a9eba.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/175085270-45c0a33a-7bf3-4403-90ac-0347b284fad0.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Test the counting for newly created …
=> Fixing nullability problems of ChannelLogic.mutableState._read.value

stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/login/UserLoginActivity.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/user_login/UserLoginViewModel.kt
Fix connecting users in sample apps.
We don't need to connect a user if they were already connected.
1. Open a sample app
2. Go to bg
3. Send a message from another device
4. Tap on push notification
5. You should be able to see messages and app should be in connected state
=> Fix connecting user in sample apps

CHANGELOG.md, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/errorhandler/internal/DeleteReactionErrorHandlerImpl.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/errorhandler/internal/DeleteReactionErrorHandlerImplTest.kt
Fixing `NullPointerException` when deleting reactions. 
Returning errors when `cid` is null. Checking the git history of this class, this was the intended behavior. This bug was inserted (by me, ops) in a code refactor.
This causes a crash in older versions of the SDK. It is not crashing anymore, but I believe this is the cause of problems of syncing messages and reactions when the connection is regained in the SDK.
- ~[ ] PR is linked to the GitHub issue it resolves~. **This is a problem found when running tests for the SDK.**
_Pointer!_
=> Fixing NullPointerException when deleting reactions

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/ChannelListFragment.kt
Closes #3760 
Remove the default channel filter from `ChannelListFragment`.
We provide a default filter in ChannelListFragment:
```
protected open fun getFilter(): FilterObject? {
return Filters.and(
Filters.eq("type", "messaging"),
Filters.`in`("members", listOf(ChatClient.instance().getCurrentUser()?.id ?: ""))
)
}
```
Unfortunately, the user is not always initialized at this point. It's better to remove the filter from ChannelListFragment and rely on the default filter in ChannelListViewModel (which is the same)
=> [3760] Remove the default filter from ChannelListFragment

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListViewStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListItemStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/TypedArray.kt
Our pending delivery icon was not rendering properly due to it not being fetched by compat methods.
Fetch the icon using compat methods.
| Before (Channels Screen) | Before (Messages Screen) | After  (Channels Screen) | After (Messages Screen) |
| --- | --- | --- | --- |
| ![before_channels_screen](https://user-images.githubusercontent.com/37080097/175541010-19f8ed75-c0a6-430a-952c-677dd636d4de.png) | ![before_messages_screen](https://user-images.githubusercontent.com/37080097/175541002-37ed48bb-62ef-494c-a018-3833531ab388.png)| ![after_channels_screen](https://user-images.githubusercontent.com/37080097/175541008-d9a1dec6-b9cd-40d7-8d8a-aa299991ae2b.png)| ![after_messages_screen](https://user-images.githubusercontent.com/37080097/175541007-99d402c0-8acf-442c-904f-4bf9afe4fd36.png) | …
=> [3763] Fix pending delivery icon not rendering properly

buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt, stream-chat-android-client/build.gradle, stream-chat-android-client/src/debug/java/io/getstream/chat/android/client/di/ChatModule.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/StreamLifecycleObserver.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/socket/lifecycle/StreamLifecyclePublisher.kt, stream-chat-android-client/src/release/java/io/getstream/chat/android/client/di/ChatModule.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChannelsApiCallsTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ConnectUserTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/DevicesApiCallsTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MessagesApiCallsTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/UsersApiCallsTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/BaseChatClientTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/DevTokenTest.kt
Inject `lifecycle` to simplify our tests and be able to test some parts of our code where we need to register/unregister `lifecycleObservers`.
For testing the `LifecycleTesting` dependency has been added
=> Inject custom Lifecycle

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/TokenUtils.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/DevTokenTest.kt
Extract `devToken()` outside of `ChatClient`. Move the implementation to `TokenUtils` and test it properly
=> Extract `devToken()` outside of `ChatClient`

CHANGELOG.md, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/interceptor/internal/SendMessageInterceptorImpl.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/interceptor/internal/SendMessageInterceptorImplTest.kt
Fix reply inside notification
When there are no attachments to be sent, return a `Result.success` instead of `Result.error`. An error doesn't make sense in this case, because nothing wrong happens, there were just no attachments to be sent. This way it is possible to send messages without attachments even when the socket is not connected. 
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/175353664-294061c6-c0ac-4da8-aef4-f3fa9a15a8b5.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/175353629-0da059c9-5792-4417-b3ea-6bc0faef7773.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table> …
=> Fixing reply inside notification

.github/workflows/localazy-download-manual.yml
Run GH-Action periodically to be up-to-date when new translations are updated on Localazy website.
The translations from Localazy don't keep the license header, so we need to run Spotless just before we create a PR with the new translations
=> Run GH-Action to download localazy translations periodically

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/Messages.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
closes #3529
closes #3770 
#3529
Extracted marking as read into a separate function that triggers a lambda when a new item is visible. 
The benefit of this is that only the newly visible item will call mark as read, where as previously any recomposed item would call mark as read.
#3770
Compare the IDs of the messages that are marked as read, marking the channel as read only when the last item is reached.
#3529 
1. Log in as Marton
2. Enter a channel named `Marton is banned here`
3. Send a few messages (you need at least two failed messages in order for compose to enter a loop)
4. Observe Logcat
Result: Compose will enter a recomposition loop and start making repeated unnecessary calls to mark read
1. Log in as Marton
2. Enter a channel named `Marton is banned here`
3. Send a few messages …
=> [3529 & 3770] Optimize calls to mark read 

stream-chat-android-offline/src/main/java/com/squareup/moshi/MultiMapJsonAdapter.kt
Closes #3829 
Sectioned avatars are different for online and offline channels.
Deserializing json with members into a map with ordered key set. 
```
internal data class ChannelEntity(
...
val members: Map<String, MemberEntity>
}    
```
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/177036455-a572362d-0825-4faa-95b7-43359fca22c8.mp4" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/177036458-bb47561b-5d1c-428e-bfc1-733f8b24fe58.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
1. Open the channels screen
2. Sectioned avatars should show first 4 members of each channel
=> [3829] Fix sectioned avatars

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Closes: https://github.com/GetStream/stream-chat-android/issues/3834
Fix the issue of PN being hidden.
When new message arrives the notification message says Loading notification data and then just disappears. No new notifications are shown after it, both sdks, while in background and killed. 
=> [3834] notification is not visible

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
Closes #3493 
Show snackbar when file size exceeds the limit.
Updated check that shows the snackbar.
| XML | Before | After |
| --- | --- | --- |
| ![Screenshot_1657198101](https://user-images.githubusercontent.com/38032787/177777804-85eba6e2-9208-4472-adb8-ca990ceaeda1.png) | ![Screenshot_1657198177](https://user-images.githubusercontent.com/38032787/177777816-e65e12c2-d4b7-44c8-b96e-1ffd623dfd6d.png) | ![Screenshot_1657198210](https://user-images.githubusercontent.com/38032787/177777836-9ca3f185-0250-4096-95bd-ada3aaf981e3.png) |
1. Run on develop and try to upload an attachment larger than 100MB
2. Run on this branch and try to upload an attachment larger than 100MB
=> Show snackbar on file to large error

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
Related PR: #3833 
Clear the cache of `StreamOfflinePluginFactory` when user disconnects. 
- Logout of the SDK
- Login again
Check that the SDK recovers the connection.
=> [3868] Socket does not reconnect on logout/login flow

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/querychannels/internal/QueryChannelsLogic.kt
closes #3758 
Fix infinite loading state when DB doesn't contain channels.
Added initializing channels state with `emptyMap()` if it's not initialized yet and the request failed.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/17440581/178481483-b0db8a6a-c385-40ad-95eb-9a9905865b06.mp4
" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/17440581/178481461-11d61a3e-1516-4d6a-a35b-e4cd1875a3bb.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
1. Turn on airplane mode
2. Sign in as a User (make sure the DB is empty)
3. You should be able to see empty state after the initial loading
=> Fix initializing channels state when DB is empty and API request fails

CHANGELOG.md, DEPRECATIONS.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/StreamLifecycleObserver.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatNotifications.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/ChannelsActivity.kt, stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/ClientAndUsers.java, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragmentViewModel.kt
Fix #3643
Ensure `disconnect()` process is completed before any other action can be run to avoid any race-condition in our `ChatClient`.
On the other hand, a new `ChatClient.disconnect()` method is created that return a `Call` instance to be run properly.
Run sample apps and verify login/logout work properly.
=> Improve disconnect method

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/SocketStateService.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/UserStateService.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/InitializationCoordinator.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenConnectUser.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/StateRegistry.kt
Don't clear Registries instances when clearing its state. If the SDK is disconnected, but `StateRegistry` or `LogicRegistry` are requested, the SDK will crash because their instance was cleared. 
The problem is hard to reproduce but happens with one customer. 
=> Not clearing instances of registries

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenConnectUser.kt
This issue is the side-effect of the following PRs:
- #3852
- #3888
Fix problem that causes offline view of ChannelListView to stuck at loading state.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/179610260-bf55a35a-dc20-4f64-ad81-b4ca83ea9330.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/179610244-606c0ca2-db82-4e84-afa0-056a5ed2b1b5.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Enter the app without internet.
- ~[ ] PR is linked to the GitHub issue it resolves~. This fixes a problem not published.
- ~[ ] Changelog is updated with client-facing changes.~ Not published yet
- ~[ ] New code is …
=> Moving user set in clientState

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/interceptor/internal/SendMessageInterceptorImpl.kt
Fix message preview off by one when sending messages offline problem.
Refreshing channels **after** message is inserted.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/180068769-f13cad7f-8c70-474f-9214-f3436039a04b.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/180067839-b8fa49f7-dbae-40f0-b8e7-0d57e7de5f4b.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Follow the videos =]
~- [ ] Affected documentation updated (KDocs, docusaurus, tutorial)~
_Don't lose the count!!_
=> Fix message preview off by 1

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/internal/Date.kt
closes #3902 
Check if `lastSyncAt` is no later than 30 days when calling the sync endpoint.
1. Run the sample apps and filter `syncHistory`logs. Make sure the channel syncs correctly
2. Apply the patch and rebuild the app. Search for the same logs which should now log an error.
<details>
```
Index: stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/sync/internal/SyncManager.kt
<+>UTF-8
diff --git a/stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/sync/internal/SyncManager.kt …
```
=> Check if lastSyncAt is no later than 30 days when calling sync endpoint

.github/workflows/release-start-test.yaml, .github/workflows/release-start.yaml
Create an automation that doesn't need to change permissions in release branch to be used.
Using the correct actor now.
I create the `release-start-test.yaml` to test this PR. We can merge this, test it by creating a branch called `release-test` and then remove this file once it is verified.
- ~[ ] PR targets the `develop` branch~. **It targets main**
_Let's use the correct actor!_
=> Release with correct actor

stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/global/internal/GlobalMutableState.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/utils/internal/ChannelUtils.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
Fix `GlobalState` initialization.
Run sample apps and make sure there are no crashes when going to `ChannelList` or `MessageList`
=> Fix GlobalState initialization

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Disconnected state is not shown in airplane mode.
**To Reproduce**
Steps to reproduce the behavior:
1. Open the channel screen / open the message list screen
2. Switch your phone into airplane mode
3. Nothing happens
**Expected behavior**
The toolbar should indicate that the connection has been lost
=> [3942] Fix the display of disconnected state

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Channel.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/models/QuerySortByFieldTest.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModelTest.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/Mother.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/integration/BaseDomainTest2.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/QueryChannelsImplRepositoryTest.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/internal/extensions/ChannelExtensionsTest.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/querychannels/QueryChannelsSortTest.kt
closes #3894 
Remove QuerySort usages from tests
Run tests.
=> Remove QuerySort usages from tests

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/CreateChannelListenerImpl.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/CreateChannelTests.kt, stream-chat-android-state/api/stream-chat-android-state.api, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/utils/internal/ChannelUtils.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/internal/StatePlugin.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/channel/CreateChannelTests.kt
Move `CreateChannelListenerImpl` to OfflinePlugin module. There's no need to separate this class into state and persistence because this is already just persistence. 
Create channels and check the persistence of it. 
- ~[ ] Comparison screenshots added for visual changes~ 
_Change the channel_
=> Moving CreateChannelListenerImpl to offline module

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/socket/ChatSocket.kt
Log when an unrecoverable error happens. 
_Logs_
=> Loging unrecoverable error

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/helpers/CallPostponeHelper.kt
closes #3896 
Postpone calls that require an active socket connection.
Added postponing the following calls:
- `ChatClient::queryChannel` and `ChatClient::createChannel` if [QueryChannelRequest.watch] or [QueryChannelRequest.presence] is enabled
- `ChatClient::queryChannels`  if [QueryChannelsRequest.watch] or [QueryChannelsRequest.presence] is enabled
- `ChatClient::queryUsers`  if [QueryUsersRequest.presence] is enabled
- `ChatClient::stopWatching` 
Smoke test the apps.
=> Postpone calls that require active socket connection

CHANGELOG.md, DEPRECATIONS.md, docusaurus/docs/Android/03-ui/04-message-components/04-message-input.mdx, docusaurus/docs/Android/04-compose/05-message-components/04-message-composer.mdx, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/compose/messages/MessageComposer.kt, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageInput.kt, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/typing/DefaultTypingUpdatesBuffer.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt, stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
Closes #3967
- Move `CoroutineScope` to the constructor
- Update the documentation
- Start the deprecation process
**Please run a docusaurus build and check the documentation changes**
Although the actual changes to the code were very slight and there is no real change in behavior expected, if you want to be thorough you can do the following on both apps.
Pre testing scenario:
1. Launch the app on two devices with two different users logged in
2. Enter the same channel
Test scenario 1:
1. On user device A start typing
2. Observe on User B that the typing update has appeared and should disappear ~3 seconds since the last keystroke on device B
Test scenario 2: 
1. Repeat the same but exist channel mid typing (the typing updates should stop)
=> [3967] Deprecate `DefaultTypingUpdatesBuffer`

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/ChannelApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/state/ClientState.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/utils/internal/ChannelMarkReadHelper.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/channel/ChannelMarkReadHelperTests.kt
closes #3984
- removed `connection_id` from `ChannelApi.mark read`
- switched from checking `clientState.isOnline` to `clientState.isNetworkAvailable` when marking channels as read
For all test scenarios, you should open the app on two different devices with the same user and check the same channel.
Test Scenario 1:
1. From device A enter a channel and send a message
2. From device B enter the same channel
Expectation: Channel should be marked as read on Device A
Test Scenario 1:
1. Put the app on device A to the background or kill it, preferably try both scenarios
2. From device B trigger a push notification by sending a message to a shared channel
3. Click on the push notification on device A
4. Go back to the channels screen and check if the channel was marked as read
=> [3984] mark channel as read when opening from push notification

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModel.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelViewModelFactory.kt
closes #3981 
Add possibility to customize `ChatEventHandler` when using `ChannelListViewModel` in compose.
Added additional `chatEventHandler` parameter to `ChannelListViewModel` and `ChannelListViewModelFactory`
1. Apply the patch. It changes the default `ChatEventHandler` in a way that the channel will be removed from the list if new message arrives.
2. Build the app on device 1 and stay on `ChannelList`
3. Open the app on device 2 and send a message in some channel
4. Observer the channel disappears from the list on device 1
<details>
```
Index: stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/ChannelsScreen.kt …
```
=> Add possibility to customize chatEventHandler in compose

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/chat/DefaultChatEventHandler.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/querychannels/DefaultChatEventHandlerTest.kt
closes #3973 
Fix updating channels list after receiving new message event.
Add handling `NewMessageEvent` in `DefaultChatEventHandler` if the message is not a system message.
We should skip `system` messages for now in order to properly handle the remove member use case, as removed member can still receive a message with information that they just left the channel.
Test 2 scenarios:
1. Apply the patch. You will need 2 devices with Compose application
2. On device 1 sign in as Rafal and go to the available channel
3. On device 2 sign in as Jaewoong, stay on `ChannelList` and click avatar (channel will be hidden)
4. Send a message from device 1 and confirm the channel on device 2 is now visible
<details>
<summary>Provide the patch …
=> Update channels list after receiving new message event

CHANGELOG.md, stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/StorageHelper.kt
Closes #3961
Fix the crash happening when processing a list of content URIs with `StorageHelper::.getAttachmentsFromUriList` and submitting the prepared attachments to `MessageInputView` (or `MessageComposerView`).
```
android.database.sqlite.SQLiteException: no such column: duration (code 1 SQLITE_ERROR): , while compiling: SELECT _id, _display_name, mime_type, _size, duration FROM images WHERE (_id=?)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
at android.content.ContentResolver.query(ContentResolver.java:802)
at android.content.ContentResolver.query(ContentResolver.java:752)
at …
```
=> [3961] Fix crash when attaching photo

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
Closes #4034 
Reaction of the current user are lost and turn grey.
Ensured that we don't lose own reactions when a new reaction event arrives.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/184386259-5bee117a-cb86-450a-9a98-303c5047d47b.mp4" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/184387103-0bf8506e-8635-4d7e-b11c-73d2f7e95a87.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Add, delete and modify reactions. Ensure that they have the correct tint.
=> [4034] Fix own reactions

stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ThreadQueryListenerFull.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ThreadQueryListenerImpl.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/thread/internal/ThreadLogic.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
Prepare ThreadQueryListenerImpl to handle both state and/or persistence accordingly with how users configure the SDK.
- `ThreadLogic` is no longer the implementation of `ThreadQueryListener`. There's already a specific class for that which is `ThreadQueryListenerImpl` (or `ThreadQueryListenerFull`) now.  `ThreadLogic` should only handle the logic of threads instead of also being a lister of ChatClient requests. This way each class becomes more specialized. 
- `ThreadQueryListenerFull` handles both state and persistence, but its properties are optional.
I don't believe this class should be separated into database and state completely because the code uses persistence to update the state if the information lives only inside the database at the moment the listener is called. Separating it …
=> [ISSUE-3710] Thread query listener impl separation

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
Let `QueryChannelsRequest` be fired on app launch
1) Launch Sample app. 
2) Login as any user.
3) Kill the app
4) Launch again
5) Repeat steps 3 & 4 until unread counts are not presented
=> [4037] fix query channels request not being fire on app launch

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/receivers/NotificationMessageReceiver.kt
Fix reply action.
There is no need to set `message.user` when sending a message. Moreover,  `ChatClient.user` always will be null as the user is not set before connecting the socket.
1. Receive push notification
2. Use reply action and make sure the message is sent
=> Fix reply action

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/MessagingStyleNotificationHandler.kt
Show user avatar on push notifications when `MessagingStyleNotificationsHandler` is in use.
Fix #4053
Android Notification doesn't provide any native option to display remote images (eg: URLs), it only allows to use resources/files/Bitmap. 
To be able to show remote images we need to download them and store them into a file or a bitmap.
| --- | --- |
| ![Screenshot from 2022-08-18 13-19-15](https://user-images.githubusercontent.com/4047514/185384012-35108943-e67f-4043-b2f8-5f807a5a5dc6.png) | ![Screenshot from 2022-08-18 13-16-16](https://user-images.githubusercontent.com/4047514/185384036-a056a390-6747-469a-af9f-3da9db84662d.png) |
To see avatar icons on MessagingStyles you need to use a device with Android Version 28+
Install the sample app, put it in the background, …
=> Show the user avatar when a PN is received and it is using `MessagingStyleNotificationHandler`

stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QueryChannelRequest.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/identifier/Identifiers.kt, stream-chat-android-core/api/stream-chat-android-core.api, stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/Call.kt, stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/DistinctCall.kt, stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/SharedCalls.kt, stream-chat-android-ui-components-sample/detekt-baseline.xml
Make side effects for DistinctCalls run once.
A new operator named `share` has been introduced to reuse the same chain of the calls as long as the real request keeps running.
- Run sample app
- Open any channel 
- Make sure there is a single `doOnStart` and `doOnResult` presented in the logs even though the `queryChannel` is invoked multiple times
```
2022-08-18 19:29:49.657 5359-5359/io.getstream.chat.ui.sample.debug D/Chat:Client: (main:2) [queryChannel] cid: messaging:sample-app-channel-109
2022-08-18 19:29:49.661 5359-5470/io.getstream.chat.ui.sample.debug V/Chat:Client: (DefaultDispatcher-worker-13:119) [queryChannel] #doOnStart; plugin: io.getstream.chat.android.offline.plugin.internal.OfflinePlugin
2022-08-18 19:29:49.668 5359-5359/io.getstream.chat.ui.sample.debug D/Chat:Client: …
```
=> [3963] Side effects for DistinctCalls run multiple times

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/QueryMembersListenerDatabase.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/QueryMembersListenerDatabaseTest.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/internal/StatePlugin.kt
Renaming QueryMembersListenerImpl to QueryMembersListenerDatabase because it only deals with persistence.
Class rename and adding unit tests
<details>
```
```
</details>
=> [ISSUE-4063] QueryMembersListenerImpl separation

CHANGELOG.md, buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/ImageAttachmentsGroupView.kt
Closes #4066 
Added and else branch wrapping the image attachment View height in case the attachment does not have fixed dimensions
| --- | --- |
| ![fixed_height_before](https://user-images.githubusercontent.com/37080097/185897974-4f02af09-387c-4a48-abe8-0e6078315e65.png) | ![fixed_height_after](https://user-images.githubusercontent.com/37080097/185898015-10fec92e-3fa8-4fa8-897e-09166d159297.png) |
<details>
<summary>Patch that logs image dimensions</summary>
```
Index: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/ImageAttachmentsGroupView.kt
<+>UTF-8 …
```
=> [4066] Fix image attachments without dimensions not loading

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/configuration/StatePluginConfig.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
Make EventHandlerSequential as a default one
- Run Sample app
- Login 
- Observe Logcat
You should see the following output:
```
D/Chat:EventHandlerSeq: (DefaultDispatcher-worker-1:186743) [handleBatchEvent] >>> id: 434514951
```
=> [4082] Make EventHandlerSequential as a default one

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/TypingEventPruner.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/util/FakeImageLoader.kt
Closes #4099 
Replaced the implementation with a simple indexing and an elvis operator where necessary
This change affects the `TypingEventPruner` on API 23 and below. After the fix, we should re-test the functionality on both lower and higher APIs while paying special attention to API 
Please test using the testing regime from the original `TypingEventPruner` PR seen here: https://github.com/GetStream/stream-chat-android/pull/3637
=> [4099] Remove usage of Kotlin's `getOrDefault()` function

stream-chat-android-ui-components-sample/src/debug/kotlin/io/getstream/chat/ui/sample/application/ApplicationConfigurator.kt
Only use Flipper on Android API 23+ because it is crashing on previous versions
=> Use Flipper only on Android API 23+

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt
Fix unread count when processing duplicate events.
Remove incrementing unread count if the message is already in the state.
Make sure unread count is stable after restoring the app from the background.
=> Remove incrementing unread count if the message is already in state

stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/notifications/StreamCoilUserIconBuilder.kt
Add a `StreamHandsOff` comment to prevent reflection errors
=> Add a `StreamHandsOff` comment to prevent reflection errors

.github/workflows/localazy-download.yml
Improve Download Translations Workflow performance by adding cache for our Gradle Dependencies
=> Add GitHub cache to download translations workflow

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/experimental/ChatSocket.kt
After the app went to the background the WebSocket wasn't properly closed, and some events could arrive through it. It is not a good approach because while the socket is connected the backend doesn't send any Push Notification. 
Now, whenever we know the SDK is not in a state that could receive WS Event, we close the connection to be sure they are not accepted.
Use any of our Sample Apps, after login, move de app to the background and with another device send some messages to your users. Messages should appear as a Notifications
</details>
=> Close StreamWebSocket on case a Disconnected Event happens

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/QuotedMessageText.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamColors.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/TextUtils.kt
Expose way to custimize own/other message text color.
Added `ownMessageText` and `otherMessageText` to `StreamColors`.
| --- | --- |
| ![Screenshot_1663664532](https://user-images.githubusercontent.com/38032787/191216073-d40bd03a-1e4e-4e49-989e-5c234eb110df.png) | ![Screenshot_1663664329](https://user-images.githubusercontent.com/38032787/191216048-42543a78-2985-4c1b-b32e-a3b1b353594e.png) |
1. Build this branch and check the text colors
2. Apply the patch and build again, the message text colors should be red for current the user and blue for other users
<details>
<summary>Test patch</summary>
```
Index: stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/MessagesActivity.kt
Subsystem: …
```
=> Exposed own/other message text color customization options

CHANGELOG.md, settings.gradle, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ThreadQueryListenerComposite.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ThreadQueryListenerDatabase.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/ThreadQueryListenerDatabaseTest.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ThreadQueryListenerState.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/ThreadQueryListenerStateTest.kt
Separate ThreadQueryListener into database and state.
In comments
Test threads in the sample app. 
_No, man, it is Thread not Threat, jesus..._
=> [ISSUE-4166] Separating ThreadQueryListenerFull

CHANGELOG.md, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/utils/GiphyInfoType.kt
#4221 
Refactored how giphy size is parsed.
1. Login as Amit and open Giphy testing
2. The sizes of giphies should fit the giphy size
3. Apply the patch and repeat, giphys should be the default size
<details>
```
Index: stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/utils/GiphyInfoType.kt
<+>UTF-8
diff --git a/stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/utils/GiphyInfoType.kt b/stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/utils/GiphyInfoType.kt
--- …
```
=> Fix parsing of giphy size

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/StreamFileUtil.kt
Closes #4224 
Switched to using Kotlin's in built function for copying file streams.
Repeat the following steps on both dev and the current branch:
1. Launch the Compose app
2. Log in as `Jc`
3. Go to channel `Skinny Secret`
4. Scroll up until you find a video attachment with a message `87 MB video`
5. Open it in the gallery
6. Click on share
Expected result:  Should throw an OOM error on dev, work fine on the current branch.
Please note two things:
- If you are uploading  your own large files for testing do so using a `release` build. Our logging causes OOMs upon upload on `debug`. (unrelated to this PR)
- If you want to re test caching with the same file, you have to exit the activity. Clearing the cache is tied to the gallery's `onDestroy`, it it's not called you won't be …
=> [4224] Write to cache in buffered chunks

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/ImageAttachmentView.kt
closes #4231
Added a fallback to `Attachment.upload`
| --- | --- |
| ![Screenshot_1664884140](https://user-images.githubusercontent.com/37080097/193820155-729573f7-712b-4431-aa5a-cd18fb437040.png) | ![Screenshot_1664884104](https://user-images.githubusercontent.com/37080097/193820264-c79be0d5-ed39-4f96-b640-9471d578a065.png) |
1. Open the XML app
2. Go to a channel
3. Send an image and kill the internet mid send
Result: You should see a failed message that will be correctly displayed.
=> [4231] Fix displaying image attachments that have failed to send V5

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/BaseMessageItemViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/CustomAttachmentsViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/FileAttachmentsViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/GiphyAttachmentViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/ImageAttachmentViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/LinkAttachmentsViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/MessagePlainTextViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/MessageOptionsDialogFragment.kt
Align reactions ballon in message options dialog even when using a custom view holder for the messages.
Now implementations of `BaseMessageItemViewHolder` can provide the message container. 
| Before (with custom ViewHolder) | After (with custom ViewHolder)|
| --- | --- |
| ![Screenshot_20221005-180745](https://user-images.githubusercontent.com/10619102/194165204-14001e53-8758-4f2f-a836-174a706644a5.png) | ![Screenshot_20221005-180822](https://user-images.githubusercontent.com/10619102/194165221-4d0d7201-43f5-491f-b7b9-49308d543a3b.png) |
| ![Screenshot_20221005-180750](https://user-images.githubusercontent.com/10619102/194165213-4c272d2f-fa7d-41ac-9a28-f8173f222ea9.png)  | ![Screenshot_20221005-180827](https://user-images.githubusercontent.com/10619102/194165229-89cca389-7bbb-4ea4-9e58-64 …
=> [V5 ISSUE-4245] Alignment for reaction with custom view holders

.github/workflows/apk-s3-distribute.yml, .github/workflows/app-distribute.yml, .github/workflows/build-and-test.yml, .github/workflows/check-entities.yml, .github/workflows/docusaurus-staging.yml, .github/workflows/pr-checks.yml, .github/workflows/publish-hotfix.yml, .github/workflows/publish-snapshot.yml, .github/workflows/publish.yml, .github/workflows/release-docs.yaml, .github/workflows/snapshot-record.yaml, .github/workflows/snapshot-tests.yaml
Update `action/setup-java` gh-action to version 3.6.0 that replace some internal methods that are deprecated in the previous version.
Related PR: #4278
Fix: #4279
=> Update actions/setup-java to version 3.6.0

.github/actions/gradle-cache/action.yml, .github/workflows/apk-s3-distribute.yml, .github/workflows/app-distribute.yml, .github/workflows/build-and-test.yml, .github/workflows/check-entities.yml, .github/workflows/clean-detekt-baseline.yaml, .github/workflows/docusaurus-staging.yml, .github/workflows/localazy-download.yml, .github/workflows/localazy-upload.yml, .github/workflows/no-response.yml, .github/workflows/pr-checks.yml, .github/workflows/publish-hotfix.yml, .github/workflows/publish-snapshot.yml, .github/workflows/publish.yml, .github/workflows/release-docs.yaml, .github/workflows/release-post.yaml, .github/workflows/release-start-test.yaml, .github/workflows/release-start.yaml, .github/workflows/snapshot-record.yaml, .github/workflows/snapshot-tests.yaml
Update Ubuntu Runners Version to 22.04, previous one will be deprecated at the end of this year.
Actions has been upgraded as well to the last version to avoid some Warning Messages:
-. actions/cache@v3.0.11
-. actions/setup-java@v3.6.0
-. actions/checkout@v3.1.0
-. actions/upload-artifact@v3.1.0
This PR cherry-pick behavior from `develop` branch to our `v5` branch
=> Upgrade runners and gh actions

stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/ApiRequestAnalyserInterceptor.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/HttpLoggingInterceptor.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Constants.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputFieldView.kt
Fix `HttpLoggingInterceptor` crash.
Added a limit for writing/reading from the buffer. Now we are not going to log request bodies of more than 1MB.
Send a big attachment (> 30MB).
=> Fix HttpLoggingInterceptor crash

stream-chat-android-ui-uitests/build.gradle, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/util/TestData.kt
https://github.com/GetStream/stream-chat-android/issues/4305
Fix compilation error in UI tests introduced after ThreeTenABP dependency was removed from the main source set. 
Execute `./gradlew stream-chat-android-ui-uitests:assembleDebugAndroidTest` and verify that the code compiles.
=> [4305] Fix UI tests

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/PushTokenUpdateHandler.kt, stream-chat-android-pushprovider-firebase/src/main/java/io/getstream/chat/android/pushprovider/firebase/ChatFirebaseMessagingService.kt
When a new token come from FirebaseMessageService we were removing the `providerName` from the device, what could cause errors on our PN Logic.
=> Fix multi-bundle feature when using Firebase as Push Provider

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/detekt-baseline.xml, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/composer/MessageInput.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageText.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/QuotedMessage.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/QuotedMessageContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/QuotedMessageText.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamColors.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/TextUtils.kt, stream-chat-android-ui-components/detekt-baseline.xml
Closes https://github.com/GetStream/stream-chat-android/issues/4326
Added some options to `StreamColors`, to make it possible to customize the appearance of quoted messages.
- `StreamColors.ownMessageQuotedBackground`
- `StreamColors.otherMessageQuotedBackground`
- `StreamColors.ownMessageQuotedText`
- `StreamColors.otherMessageQuotedText`
| --- | --- |
| ![photo_2022-11-01 16 27 11](https://user-images.githubusercontent.com/9600921/199244368-693d99e0-cc41-4b5c-8bab-bf18da6298ae.jpeg) | ![photo_2022-11-01 16 27 08](https://user-images.githubusercontent.com/9600921/199244380-ae058f28-6cf6-4c71-8240-c3cf9d1db894.jpeg) |
| ![photo_2022-11-01 16 30 39](https://user-images.githubusercontent.com/9600921/199245109-31b245e7-42ae-4722-b2bd-4ad637a690fc.jpeg)| ![photo_2022-11-01 …
=> [4326] Fix text color in quoted messages

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/state/ClientMutableState.kt
Making `ClientMutableState` as an internal interface.
Ci checks are enough in this case.
=> [ISSUE-3866] Making ClientMutableState internal interface

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
Closes #4297 
Instead of comparing the full attachment link which might differ depending on when it was loaded, fallback to comparing a shortened URL
This PR technically touches upon the compose SDK as well since they share the new `MessageListController` , however the Compose SDK uses internal logic inside `MediaGalleryPreviewViewModel.deleteCurrentMediaAttachment()` so it will not be affected in the compose sample app.
**Note**: It is important to always test freshly uploaded attachments, they must always be the latest message without navigating away from the message list in any way.
1. Checkout `develop`
2. Launch the UI Components sample app
3. Send a message with multiple image and/or video attachments
4. Open an attachment in the gallery.
5. Delete an attachment via the gallery …
=> [4297] V5 Make attachment equality comparisons based on shortened links

CHANGELOG.md, stream-chat-android-compose/detekt-baseline.xml, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/ImagePreviewActivity.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
Implements #4395 
Filtered out attachments link attachments in both XML and Compose SDKs
Please repeat the test procedure on both apps:
1. Launch the app
2. Open a channel
3. Send a message that contains multiple media attachments (image and/or video) 
4. Open the message in the gallery
5. Exert all options such as reply, show in chat, save and delete
6. Exhaust delete until the last attachment is deleted
Repeat step 3 with the following variations:
- Message contains no text (should delete the message with the last attachment deleted)
- Message contains text (should not delete the message with the last attachment deleted)
- Message contains link (should not display the link attachment in the gallery and should not delete the message with the last attachment deleted)
=> [4395] `V5` Don't show link attachments in the attachment galleries

CHANGELOG.md, buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/StateRegistry.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
Synchronize `ChatClient` initialization.
Fixed the race condition when connecting the user just after receiving the push notification when the application is killed. In both scenarios, we are calling `initializeClientWithUser` from different threads which might result in rebuilding things like plugins.
1. Apply the patch below and filter logs by `initializeClientWithUser`
2. On device1 sign in as Marton and kill the app
3. From device2 send a message to a channel in which Marton is a member
4. Receive a push notification on device1 and observe the logs. You should see two `initializeClientWithUser` synchronized invocation (there is a log at the beginning and end of the method)
<details>
<summary>Provide the patch summary …
=> Synchronize ChatClient initialization

docusaurus/docs/Android/02-client/03-messages.mdx, docusaurus/docs/Android/02-client/06-guides/02-sending-custom-attachments.mdx, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessagesViewModelFactory.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputViewStyle.kt
Closes #4446 
Search for all references to the previous 20 MB file limit and change them to 100 MB
Search phrases included:
- 20MB
- 20 MB
- MB
- 20
- Mega
- Megabyte
- Twenty
Test A:
Launch Docusaurus and check that the updated pages render correctly and that the correct text is updated
Test B: 
Only kdocs were changed and no code but you can run the sample apps for good measure
</details>
=> [4446] Correct mentions of uplaod file size limit from 20 MB to 100 MB

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/MessageOptionsDialogFragment.kt, stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml, stream-chat-android-ui-components/src/main/res/values/styles.xml
Closes https://github.com/GetStream/stream-chat-android/issues/4437
Hide reactions by default for messages that haven't been synced.
| --- | --- |
| ![photo_2022-11-18 13 57 54](https://user-images.githubusercontent.com/9600921/202689968-8a60b99a-a289-4bea-911b-e0c7574ce472.jpeg) | ![photo_2022-11-18 13 57 56](https://user-images.githubusercontent.com/9600921/202689961-af675a7d-433e-42ab-abd5-8fe85a43aaa8.jpeg) |
| ![photo_2022-11-18 14 02 40](https://user-images.githubusercontent.com/9600921/202690836-d532fe54-271e-4101-9fa1-0f95f35f947f.jpeg) | ![photo_2022-11-18 14 02 38](https://user-images.githubusercontent.com/9600921/202690841-ffe9d179-ae3d-4acb-9a60-629bff0aa8bb.jpeg) |
=> [4437] Hide reactions for unsent messages

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/message/attachments/internal/UploadAttachmentsAndroidWorker.kt
Fix `IllegalArgumentException` when upload attachments worker fails.
We cannot pass `ChatError` to the `Data` object when creating `Result.failure` because valid value types are: Boolean, Integer, Long, Float, Double, String, and their array versions.
=> Fix returning error from worker when upload attachments fails

CHANGELOG.md, buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/querychannels/internal/QueryChannelsLogic.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/querychannels/internal/QueryChannelsStateLogic.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/querychannels/internal/QueryChannelsMutableState.kt
Fix the empty placeholder blinking while loading channels.
Test 3 different scenario:
1. Try to load channels when DB is empty
2. Try to load channels when DB is empty and there is no Internet connection
3. Try to load channels when DB is not empty and there is no Internet connection
=> Fix empty placeholder blinking while loading channels

stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/global/internal/GlobalMutableState.kt
Fix a bug when chat is not loaded when logging in after a logout.
We didn't call `connectUser` properly as `GlobalState::user` was not cleared during disconnection. 
Added clearing all `GlobalState` values during disconnection.
1. Sign in
2. Sign out
3. Sign in
4. Confirm everything works as expected
=> Clear all GlobalState values during disconnection

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
When using `MessageInputView` in a Fragment, as soon as the input view gets focus, a listener is set. If the fragment gets dismissed
Issue: https://github.com/GetStream/stream-chat-android/issues/4498
Simply unregister the listener when the view is detached (it'll get reattached on the next focus event
None
- Add LeakCanary
- Add `MessageInputView` to a fragment
- Tap on the input view
- Dismiss the fragment
- 5s later, leak canary will report a leak on `main`, but shouldn't on this branch
=> Fix keyboard listener not cleared

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Attachment.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/extensions/internal/Attachment.kt
closes #4598 
Added an extension function which uses regex to find the file name from the URL in case it's missing.
Inside the channel `Giphy testing` there is an image of a pair of headphones that was sent from an iPhone device. The image does not have proper `Attachment.name` or `Attachment.title` properties.
Testing steps:
1. Open the image mentioned above in the gallery
2. Download it
Expected: Will silently fail on `v5`/ `develop` branches but will succeed downloading it here.
=> [4598] Enable Downloading Attachments Without Valid Name or Title Properties

stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageList.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
Just added checks to not trigger loading if there are no messages to load.
Test A)
1. Run Compose app on v5.
2. Open a new thread. (preferably with an image message as parent)
3. Attempt to scroll top/bottom. 
You should see a lot of requests in Logcat as well as the loading spinner freaking out.
Test B)
1. Run Compose on this branch.
2. Open a new thread. (preferably with an image message as parent)
3. Attempt to scroll top/bottom.
The scroll shouldn't trigger any unnecessary loads.
If you test it in a thread that has _many_ messages, it should work fine and load all the messages.
=> Minor optimization/fix

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/ImageAttachmentsGroupView.kt
Closes #4657
Apply `fitXY` scaling if the image height on the screen is smaller than the max container height. Otherwise `centerCrop` so scaling is not broken.
| --- | --- |
| ![Screenshot_20230207_122025_Chat Sample Android](https://user-images.githubusercontent.com/38032787/217231394-9215a6f2-1dcc-47c6-9797-efc7e5d9de41.jpg) | ![Screenshot_20230207_121935_Chat Sample Android](https://user-images.githubusercontent.com/38032787/217231416-1dd5b69f-f06b-4058-a9b2-ae8f8fb804ef.jpg) |
| Test image 1 | Test image 2 | Test image 3 |
| --- | --- | --- |
| ![Screenshot 2023-02-06 at 12 13 19](https://user-images.githubusercontent.com/38032787/217230613-0b283618-6bf1-4609-9659-87e1d18f9fbd.png) | ![216983320-179eec7b-aa7b-4e0e-9043-cbd83d0413b6](https://user-images.githubusercont …
=> Fix image scaling

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.kt, stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
Closes #4680 
Implemented a method inside `MessageListItemLiveData` which updates the date separator handler.
<details>
<summary>Patch that logs separator handler calls</summary>
```
Index: stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
<+>UTF-8
diff --git a/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt b/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
--- a/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/featu …
```
=> [4680] Fix setting date separator handler not being applied

stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
We had a potential memory leak. This PR fixes it and resolves #4694 in a different, albeit much simpler way.
Instead of passing down the basic context of the current local context instance, we pass down the app context instead.
1. Run Compose apps before/after the fix, the image loading should behave the same.
However, the potential for memory leaks should be gone, given that we're not binding a singleton instance of the StreamCoilImageLoader to the Activity context, we're doing it for the app context instead.
=> Minor memory leak fix

stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/user_login/UserLoginViewModel.kt
Sample Apps weren't checking the right argument to know if the user was connected or not.
Fix: #4718
=> Fix Sample Apps Initialization

stream-chat-android-compose-sample/src/main/AndroidManifest.xml
closes #4724 
Change the activity launch modes so that if `MessagesActivity` is active in the stack it gets recreated with new arguments.
1. Launch the Compose app
2. Receive a PN, click on the PN and then kill the app
3. Receive a PN again, click on it and background the app
4. Receive a PN again and click on it
Expected: On `develop`, every subsequent PN click will not focus on the message because the VM is in memory and not getting reinitialized. When launched from the branch contained in this PR, it should always focus the correct message.
=> [4724] Improve Sample App PN Reliability

stream-chat-android-ui-components/detekt-baseline.xml, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/MediaAttachmentView.kt
Closes #4720 
Implemented an if check which avoids parsing dimension if the thumbnail of a video is null. This action would previously result in an early return.
| --- | --- |
| ![Screenshot_1678798304](https://user-images.githubusercontent.com/37080097/225006916-cdc7a32c-7de3-41f8-b224-f4677d101386.png) | ![Screenshot_1678798274](https://user-images.githubusercontent.com/37080097/225006929-5a6bbd30-8cad-4af8-99f5-6f40a4a45295.png) |
<details>
<summary>Patch which disables video thumbnails uploading</summary>
```
Index: stream-chat-android-client/src/main/java/io/getstream/chat/android/client/attachment/AttachmentUploader.kt
<+>UTF-8 …
```
=> [4720] Fix videos without thumbnails being unclickable

stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/utils/extensions/Flow.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/detekt-baseline.xml, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/internal/MessageListScrollHelper.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/MessageListState.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/messages/MessageListViewModelTest.kt
closes #4743
Altered logic conditions around the scroll logic.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/37080097/226987093-1c05880c-11bf-48d5-af81-1a764600f02f.mp4" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/37080097/226987082-7474352c-51a3-4ed0-8855-5d62e6775caf.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/37080097/226987094-fec6e310-603f-4dca-a0c3-fa7b6dce4182.mp4" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/37080097/226987089-077aa7 …
=> [4743] Fix scrolling issues in threads

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerViewStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerCenterContent.kt, stream-chat-android-ui-components/src/main/res/values/attrs_message_composer_view.xml
Enable the control to show/hide the reply view inside the default implementation of the `MessageComposerView` center content.
Added `messageInputShowReplyView` to `MessageComposerViewStyle`.
| --- | --- |
| ![Screenshot_1679499962](https://user-images.githubusercontent.com/38032787/226964530-04222411-2a95-4339-8a57-2db0e2300ded.png)  | ![Screenshot_1679499938](https://user-images.githubusercontent.com/38032787/226964562-c7be3aca-fa46-49b0-9ef7-1c1ece8441d0.png)  |
Run this branch without patch and reply to a message. The replyView should be visible.
Run this branch with the patch and repeat. ReplyView should not be visible.
<details>
<summary>Test patch</summary>
```
Index: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/Me …
```
=> MessageComposerView show reply view

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/preview/factory/FallbackAttachmentPreviewFactory.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/DefaultQuotedAttachmentView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/attachment/FallbackQuotedAttachmentMessageFactory.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/attachment/QuotedAttachmentFactoryManager.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/attachment/UnsupportedAttachmentFactory.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_unsupported_attachment_preview.xml
Fix the preview of unsupported attachments.
Changing the view that returns in `FallbackAttachmentPreviewFactory`. 
| --- | --- |
| ![Screenshot_20230330-123230 (2)](https://user-images.githubusercontent.com/10619102/228827329-42bd5b4d-759b-40d6-afc8-df4f7882485c.png) | ![Screenshot_20230330-135029](https://user-images.githubusercontent.com/10619102/228827332-71846568-1916-4907-87b2-9105e4d44077.png) |
Make `FileAttachmentPreviewFactory.canHandle` and `MediaAttachmentPreviewFactory.canHandle` return false so no attachment is supported and you can see the behaviour. 
=> [ISSUE-4756] Creating preview of unsupported attachment

stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/detekt-baseline.xml, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/StreamAttachmentFactories.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/FileAttachmentContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/FileUploadContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/GiphyAttachmentContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/LinkAttachmentContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/MediaAttachmentContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/FileAttachmentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/GiphyAttachmentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/LinkAttachmentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/MediaAttachmentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/UploadAttachmentFactory.kt
This is the `v6` implementation of https://github.com/GetStream/stream-chat-android/pull/4754 
Exposed click lambdas throught their respective content and factory environments.
Test A - Making sure past functionality is preserved
1. Launch the compose app and open a channel
2. Upload attachments of various types (Image, Link, Giphy, File [.pdf, audio, etc.])
3. Click on all of those once uploaded, and also test clicking on those that are still uploading
Test B - Making sure new functionality works
<details>
<summary>Override clicks patch</summary>
```
Index: stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/MessagesActivity.kt
<+>UTF-8 …
```
=> [4749] [v6] Expose Attachment clicks

stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/MessageComposerViewStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/content/DefaultMessageComposerCenterContent.kt, stream-chat-android-ui-components/src/main/res/values/attrs_message_composer_view.xml
`v6` implementation of the following PR: https://github.com/GetStream/stream-chat-android/pull/4746
Enable the control to show/hide the reply view inside the default implementation of the `MessageComposerView` center content.
Added `messageInputShowReplyView` to `MessageComposerViewStyle`.
| --- | --- |
| ![Screenshot_1679499962](https://user-images.githubusercontent.com/38032787/226964530-04222411-2a95-4339-8a57-2db0e2300ded.png)  | ![Screenshot_1679499938](https://user-images.githubusercontent.com/38032787/226964562-c7be3aca-fa46-49b0-9ef7-1c1ece8441d0.png)  |
1. Run this branch without patch and reply to a message. The replyView should be visible.
2. Run this branch with the patch and repeat. ReplyView should not be visible.
<details>
<summary>Test patch</summary> …
=> [4746] [v6] Enable Removing Reply View

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/StateRegistry.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
When the user was disconnected, some instances was destroyed and could cause some error on the case the device is being used offline or with a poor network connection.
=> Remove static access

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/ChatSocket.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/experimental/ChatSocket.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/experimental/ChatSocketStateService.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/Mother.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenReconnectSocket.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/experimental/ChatSocketStateServiceTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/observable/FakeSocket.kt
Fix socket reconnection after a user performer `ChatClient.disconnectSocket()`
On `v5`we have currently 2 socket implementations and the patch has been applied to both implementations.
Fixed: https://github.com/GetStream/android-internal-board/issues/66
=> Fix socket reconnection

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/TextUtils.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/Linkify.kt, stream-chat-android-ui-utils/src/main/kotlin/io/getstream/chat/android/uiutils/extension/String.kt
Make emails clickable in messages.
Closes: https://github.com/GetStream/android-internal-board/issues/72
| --- | --- |
| ![email_before](https://github.com/GetStream/stream-chat-android/assets/1286516/d8a69f6f-05b3-4522-847e-cf91aed4c877) | ![email_after](https://github.com/GetStream/stream-chat-android/assets/1286516/22438203-1922-4c86-a620-72d4bf13011f) |
- open Compose or XML app
- go to any Channel
- post a message with email
- make sure email is highlighted 
- tap on email
- make sure you're redirected to an email app
=> [i72] make emails clickable in messages

CHANGELOG.md, stream-chat-android-client-test/src/main/java/io/getstream/chat/android/client/test/utils/TestDataHelper.kt, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/EventMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/EventDtos.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/internal/Channel.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerImpl.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerSequential.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogic.kt
Handle properly ban/unban events on ChannelState 
The `ChannelUserBannedEvent` contains a new property to let us know whether it is a shadow or a standard ban.
It has been appropriately handled on DB and State instances
=> Handle ban/unban events in ChannelState

CHANGELOG.md, stream-chat-android-client-test/src/main/java/io/getstream/chat/android/client/test/utils/TestDataHelper.kt, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/EventMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/EventDtos.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/internal/Channel.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventHandlerSequential.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelLogic.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogic.kt
Handle properly ban/unban events on ChannelState 
The `ChannelUserBannedEvent` contains a new property to let us know whether it is a shadow or a standard ban.
It has been appropriately handled on DB and State instances
=> Handle ban/unban events v6

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QueryChannelRequest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/models/QueryChannelRequestTests.kt
Closes: https://github.com/GetStream/android-internal-board/issues/82
`QueryChannelRequest.withWatchers` should set `state` as `true` to make `watchers` accessible in response
=> [i82] fix QueryChannelRequest.withWatchers setup

.idea/codeStyles/Project.xml, CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/detekt-baseline.xml, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageText.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/QuotedMessageContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/QuotedMessageText.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/MessageTheme.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamColors.kt
Closes https://github.com/GetStream/android-internal-board/issues/88
=> [i88] Make message text style customizable on Compose 

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QueryChannelRequest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/models/QueryChannelRequestTests.kt
Closes: https://github.com/GetStream/android-internal-board/issues/82
`QueryChannelRequest.withWatchers` should set `state` as `true` to make `watchers` accessible in response
=> [i82] QueryChannelRequest.withWatchers does not return watchers

CHANGELOG.md, stream-chat-android-client/detekt-baseline.xml, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/detekt-baseline.xml, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListItemViewHolderFactory.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListVisibilityContainer.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListVisibilityContainerImpl.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/internal/SimpleChannelListView.kt
Closes: https://github.com/GetStream/android-internal-board/issues/92
=> [i92] control options visibility for each channel

docusaurus/android-docusaurus-dontent-docs.plugin.js
Keep v6 as "unreleased" version
The current version will be our current v5 version and v6 will be under the `/next` path
=> Keep v6 as "unreleased" version

stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_composer_default_center_content.xml
Fix multiline support in XML message Composer.
No ticket for this.
It's a side-effect of https://github.com/GetStream/stream-chat-android/pull/4828
=> [i74] fix multiline support in XML message composer

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
Closes: https://github.com/GetStream/android-internal-board/issues/103
=> [i103] ChannelViewHolder shows invalid last message

CHANGELOG.md, docusaurus/docs/Android/04-ui/06-guides/04-enabling-audio-recording.mdx, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/detekt-baseline.xml, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/MessageComposerViewStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/content/DefaultMessageComposerCenterOverlapContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/content/DefaultMessageComposerTrailingContent.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_composer_default_center_overlap_content.xml, stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_composer_default_center_overlap_floating_hold.xml, stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_composer_default_center_overlap_floating_mic.xml, stream-chat-android-ui-components/src/main/res/values/attrs_message_composer_view.xml, stream-chat-android-ui-components/src/main/res/values/dimens.xml, stream-chat-android-ui-components/src/main/res/values/styles.xml
=> [i74] Enhance audio recording ui customization

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/content/DefaultMessageComposerTrailingContent.kt
Closes: https://github.com/GetStream/android-internal-board/issues/109
=> [i109] fix send button not being visible

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/ChatNotificationHandler.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/MessagingStyleNotificationHandler.kt, stream-chat-android-client/src/main/res/values/colors.xml
Closes: https://github.com/GetStream/android-internal-board/issues/107
=> [i107] expose notification color

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/detekt-baseline.xml, stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/ListenerDelegate.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListIconProviderContainer.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListIconProviderContainerImpl.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListItemViewHolderFactory.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/internal/SimpleChannelListView.kt
Closes: https://github.com/GetStream/android-internal-board/issues/110
=> [i110] control options icon for each channel

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/LinkAttachmentView.kt
Closes: https://github.com/GetStream/android-internal-board/issues/111
=> [i111] Link preview click opens a wrong url

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
Relates to https://github.com/GetStream/android-internal-board/issues/108
=> [i108] make itemAnimator as nullable param

stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/channels/ChannelItemTest.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/channels/ChannelListHeaderTest.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/channels/ChannelListTest.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/channels/SelectedChannelMenuTest.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/components/ChannelAvatarTest.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/components/MessageReadStatusIconTest.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/messages/MessageListHeaderTest.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/compose/messages/SelectedReactionsMenuTest.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/uicomponents/channels/ChannelListItemViewTest.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/uicomponents/channels/ChannelListViewTest.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/uicomponents/components/ChannelAvatarTest.kt, stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/util/TestData.kt, stream-chat-android-ui-utils/detekt-baseline.xml, stream-chat-android-ui-utils/src/test/kotlin/io/getstream/chat/android/uiutils/extension/ChannelKtTest.kt
UI-tests got broken due to these changes: https://github.com/GetStream/stream-chat-android/pull/4893
=> (ui-tests) fix broken ui-tests

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/StreamWebSocket.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/experimental/ws/StreamWebSocketTest.kt
Closes: https://github.com/GetStream/android-internal-board/issues/118
Corresponding PR for **v5**: https://github.com/GetStream/stream-chat-android/pull/4943
The `eventFlow` field is initialsed after the `webSocketListener`. We have seen crashes where `eventFlow` is null when accessed from onFailure() callback too early. This can probably happen because`socketCreator()` is supplied through the constructor and if there is an immediate (synchronous) failure during the socket creation then it will deliver `onFailure()` within the initialisation of the parent class (`StreamWebSocket`) before `eventFlow` was even initialised (despite that it's a `val`).
=> [i118] Fix NPE in StreamWebSocket (onFailure)

CHANGELOG.md, buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt, stream-chat-android-client/detekt-baseline.xml, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatPushDelegate.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/parser/StreamPayloadParser.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/notifications/parser/StreamPayloadParserTest.kt, stream-chat-android-core/api/stream-chat-android-core.api, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/PushMessage.kt
Closes: https://github.com/GetStream/android-internal-board/issues/116
Related PR: https://github.com/GetStream/stream-android-push/pull/9
Corresponding PR in **v5**: https://github.com/GetStream/stream-chat-android/pull/4940
=> [i116] Extend PushMessage to access extra data

stream-chat-android-client/build.gradle, stream-chat-android-offline/build.gradle
The sample project `stream-chat-android-ui-components-sample` will not compile on a default Android Studio installation with Java 17 because it uses `stream-chat-android-offline` and similarly with `stream-chat-android-client` and these one doesn't set the Kotlin jvmTarget to Java 11 to match with other modules that use Java 11. This will cause a build error:
> 'compileDebugJavaWithJavac' task (current target is 11) and 'kspDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
=> Fix build issues with JDK 17 in offline and client module

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/internal/MessageListItemViewTypeMapper.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/AudioRecordingAttachmentsGroupView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/FileAttachmentsView.kt, stream-chat-android-ui-utils/api/stream-chat-android-ui-utils.api, stream-chat-android-ui-utils/src/main/kotlin/io/getstream/chat/android/uiutils/extension/Attachment.kt
Closes: https://github.com/GetStream/android-internal-board/issues/122
=> [i122] fix crash on playing failed voice message

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugin/ThrottlingPlugin.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugin/factory/ThrottlingPluginFactory.kt
Create a plugin to throttle the number of MarkRead events the SDK sends to backend
=> Throttling MarkRead Events

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugin/ThrottlingPlugin.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugin/factory/ThrottlingPluginFactory.kt
Create a plugin to throttle the number of MarkRead events the SDK sends to backend
=> Throttling MarkRead Events (V6)

stream-chat-android-client/detekt-baseline.xml, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/adapters/DateAdapter.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/adapters/ExactDateAdapter.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/adapters/internal/StreamDateFormatter.kt
Add caching to Date parsing.
And also use Java Instant and DateTimeFormatter for >= API 26. These implemenations are considerably faster, in our use-case it's 4x faster on a Pixel 4a:
Average OLD format time 3ms ,total time spent 7948ms
Average NEW format time 0ms,total time spent 1908ms
Average OLD parse time 4ms ,total time spent 7995ms
Average NEW new parse time 1ms ,total time spent 2643ms
=> add caching to date parser

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugin/ThrottlingPlugin.kt
Disable `ThrottlingPlugin` for now, since it causes issues with read attempts when you reopen channel with unread messages within 3 seconds window.
=> disable ThrottlingPlugin

CHANGELOG.md, stream-chat-android-client/src/main/AndroidManifest.xml, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/LoadNotificationDataWorker.kt
Starting on Android 14, whenever a Background Service is started, it needs to declare which type it is.
In our case, we use it to sync data in our database and the type to be used needs to be `FOREGROUND_SERVICE_TYPE_DATA_SYNC`
Fix: #4995
=> Declare a Data Sync foreground service type for `LoadNotificationDataWorker`

CHANGELOG.md, stream-chat-android-client/src/main/AndroidManifest.xml, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/LoadNotificationDataWorker.kt
Starting on Android 14, whenever a Background Service is started, it needs to declare which type it is.
In our case, we use it to sync data in our database and the type to be used needs to be `FOREGROUND_SERVICE_TYPE_DATA_SYNC`
Fix: #4995
=> [v5] Declare a Data Sync foreground service type for `LoadNotificationDataworker`

gradle.properties
Disable full R8 Mode.
Since Gradle 8.0, R8 full mode is enabled by default, and it optimizes all source codes more aggressively. For that reason, workflows for our sample projects' release build are getting broken: https://github.com/GetStream/stream-chat-android/actions/runs/6412468811/job/17409835800
More info:
- https://developer.android.com/build/releases/gradle-plugin#default-changes
- https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md
We can add strict proguard rules, but it seems to be overkill for sample apps. Just simply disabling the R8 full mode resolves this problem.
=> Disable R8 full Mode

.github/workflows/app-distribute.yml
The Token authentication [was deprecated](https://github.com/firebase/firebase-tools#general) and we need to [migrate ](https://github.com/wzieba/Firebase-Distribution-Github-Action/wiki/FIREBASE_TOKEN-migration) to the new "Service Account Authentication".
It will fix the workflow that distribute our Sample Apps across our testers
=> Configure "Service Account Authentication" for Firebase Distribution process

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageContainer.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/MessageDateSeparatorTheme.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamColors.kt, stream-chat-android-compose/src/main/res/values/colors.xml
Closes https://github.com/GetStream/android-internal-board/issues/200
=> [i200] add MessageDateSeparatorTheme

buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
Upgrade Stream Push artifact to the [last version](https://github.com/GetStream/stream-android-push/releases/tag/v1.1.6) that fixes the race condition due to initializing the SDK after the first activity was created
=> Upgrade StreamPuhs Dependency

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/identifier/Identifiers.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/debugger/ChatClientDebuggerTest.kt
Closes: https://github.com/GetStream/android-internal-board/issues/205
<details>
<summary>Apply this patch</summary>
```
Subject: [PATCH] Test Patch
---
Index: stream-chat-android-state/src/main/java/io/getstream/chat/android/state/sync/internal/SyncManager.kt
<+>UTF-8
diff --git a/stream-chat-android-state/src/main/java/io/getstream/chat/android/state/sync/internal/SyncManager.kt b/stream-chat-android-state/src/main/java/io/getstream/chat/android/state/sync/internal/SyncManager.kt
--- a/stream-chat-android-state/src/main/java/io/getstream/chat/android/state/sync/internal/SyncManager.kt	(revision 8f53391c2381d45f79c932de72256277864b32fe)
+++ …
```
=> [i205] prevent duplicate SendMessage requests

CHANGELOG.md, buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt, stream-chat-android-client/src/main/AndroidManifest.xml, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/LoadNotificationDataWorker.kt
Starting on Android 14, whenever a Background Service is started, it needs to declare which type it is.
On #5001 a DataSync service was declared to be able to sync our DB after a PN is received. This permission requires updating Google Play Console App Content data with a video showing functionality using this permission. All our customers would need to update the Google Play Console App Content to complaint with Google Play Policy. 
To avoid it, we can use [ShortService](https://developer.android.com/about/versions/14/changes/fgs-types-required#short-service) foreground service type instead that doesn't require any new permission.
=> [V5] Use shortService instead of dataSync for our workmanager job

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
Closes: https://github.com/GetStream/android-internal-board/issues/208
Look at the **Some fancy channel** title position.
| --- | --- |
| ![before_center_title](https://github.com/GetStream/stream-chat-android/assets/1286516/a14f2b5e-e2fe-4a92-8137-130603901090) | ![after_center_title](https://github.com/GetStream/stream-chat-android/assets/1286516/240a0eb9-cbf9-4708-baef-cd78801db394) |
=> [i208] center channel title when no last message

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListVisibilityContainerImpl.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
Closes: https://github.com/GetStream/android-internal-board/issues/209
Instead having the following condition in `ChannelViewHolder`
```kotlin
channel.ownCapabilities.contains(ChannelCapabilities.DELETE_CHANNEL)
```
It now was used as a default condition for `isDeleteOptionVisible: ChannelOptionVisibilityPredicate`
=> [i209] allow override channel options visibility

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListItemStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/internal/MessageDeletedViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/background/MessageBackgroundFactoryImpl.kt
Closes: https://github.com/GetStream/android-internal-board/issues/211
=> [i211] Customize deleted message UI

CHANGELOG.md, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/composer/CustomMessageComposerLeadingContent.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerCenterContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerCommandSuggestionsContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerFooterContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerHeaderContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerLeadingContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerMentionSuggestionsContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerTrailingContent.kt
Closes: https://github.com/GetStream/android-internal-board/issues/215
=> [i215] Make default composer components extensible

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/MessageComposerViewStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/content/DefaultMessageComposerCommandSuggestionsContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/content/DefaultMessageComposerLeadingContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/content/DefaultMessageComposerMentionSuggestionsContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/content/DefaultMessageComposerTrailingContent.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListItemStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/internal/MessageDeletedViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/background/MessageBackgroundFactoryImpl.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/font/TextStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/TypedArray.kt, stream-chat-android-ui-components/src/main/res/values/attrs_message_composer_view.xml, stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml, stream-chat-android-ui-components/src/main/res/values/styles.xml
Closes: https://github.com/GetStream/android-internal-board/issues/212
=> [i212] allow composer icons customizations

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/HeadersInterceptor.kt
GZIP configuration was wrong. We were adding `application/gzip` instead of `gzip` into `Accept-Encoding`. But the best solution is to not specify this at all - because if you do, then you have to handle it on your own. OkHttp handles this transparently - we don’t need to specify it.
This is best explained by Jake Wharton here: https://github.com/square/okhttp/issues/2132 
I verified this by placing breakpoints into `GzipSource.read`  in OkHttp and also in `BridgeInterceptor` . The read function is not getting called on the `GzipSource` in develop - only if I delete our accept-encoding header it works correctly.
=> Fix Gzip compression for requests

CHANGELOG.md, stream-chat-android-client/src/androidTest/java/io/getstream/chat/android/client/poc/ClientInstrumentationTests.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/StreamFileUploader.kt
Closes: https://github.com/GetStream/android-internal-board/issues/216
=> [i216] fix audio recording uploading

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/HeadersInterceptor.kt
GZIP configuration was wrong. We were adding `application/gzip` instead of `gzip` into `Accept-Encoding`. But the best solution is to not specify this at all - because if you do, then you have to handle it on your own. OkHttp handles this transparently - we don’t need to specify it.
This is best explained by Jake Wharton here: https://github.com/square/okhttp/issues/2132 
I verified this by placing breakpoints into `GzipSource.read`  in OkHttp and also in `BridgeInterceptor` . The read function is not getting called on the `GzipSource` in develop - only if I delete our accept-encoding header it works correctly.
=> Fix Gzip compression (v5)

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Reflection in Kotlin is very slow - the KClass.members can take even hundreds of miliseconds when it's invoked the first time (subsequent calls are fast). We use this reflection when parsing the extra fields in some of the responses. And this is causing an uncessary delay when the first channels or messages are loaded. We can just eagerly warm up the reflection for each relevant class and prevent this first invocation delay. This seems to save about ~500ms when loading the first channels page.
=> Preload KClass members for our DTO classes

stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/internal/LogicRegistry.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/querychannels/internal/QueryChannelsStateLogic.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/plugin/logic/querychannels/internal/QueryChannelsStateLogicTest.kt
The `ChannelMutableState()` is rather slow to create (many `StateFlows` with `SharingStarted.Eagerly`) - we need to investigate this closer but for now we can prepare the channels in parallel. In my measurements this approach is always faster - it seems to save about 500ms on 30 channels (in the sample app).
=> Asynchronously create ChannelMutableState()

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/NotificationHandlerFactory.kt
Delaying the reflection saves ~190ms on the main thread while the SDK is being initialised (usually in the Application.onCreate() - thus delaying the whole application cold start).
=> Delay reflection in NotificationHandlerFactory

stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/helper/DateFormatter.kt
This line is executed on every channel item drawn and causes a small delay - but this small stuff quickly adds up and contributes to the janky channel list in Compose.
=> Cache dateformat used by UI

stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/ChannelCapabilities.kt, stream-chat-android-ui-common/detekt-baseline.xml, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
Same implementation as https://github.com/GetStream/stream-chat-swiftui/pull/402/files.
We need to handle the `skip-slow-mode` flag which completely disables slow mode on the client.
=> Fix skip slow mode capability not handled

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/MessageExtensions.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/channels/MessageReadStatusIcon.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessagesViewModelFactory.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/messages/MessageComposerViewModelTest.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelLogic.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/internal/LogicRegistry.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/channel/controller/WhenHandleEvent.kt, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/DateSeparatorHandler.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/utils/extensions/Message.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/utils/extensions/MessageFooterVisibility.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/shared/ChatInfoSharedAttachmentsViewModel.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/messages/MessageListViewModelFactory.kt, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/messages/MessageComposerViewModelTest.kt
Messages sent ofline weren't initializing the date when the message was created and if we didn't update the message from the one that is returned from backend, we could arrive to condition where it is not updated never causing a crash when the date of all messages is used to sort a conversation.
Apart of that, if we jump to a message in the past, it could cause a gap on the conversation due the pagination was not implemented properly.
I have created a method to be sure any gap on the conversation list is filled when the State module is used.
Fix: #5034
To test it, you will need to jump to a message in the pass within a conversation.
I have create a channel where there are an indexed list of messages to verify the list of messages is loaded properly.
Open the UI-Component sample app, login …
=> Fix empty message list

stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/header/VersionPrefixHeader.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/ChatUIInitializer.kt
Use sealed class instead of enum v5
=> Use a Sealed Class for VersionPrefixHeader (V5)

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/thread/internal/ThreadLogic.kt
This fixes an issue where in threads where the root message list of `ownReactions` was incorrect (empty).
=> Fix Message.ownReactions incorrect

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/String.kt, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/common/extensions/StringTest.kt
This function can lead to a crash if the items contain invalid Regex strings (e.g. "Ryan :)")
=> Fix Regex not escaped in getOccurrenceRanges

CHANGELOG.md, docusaurus/docs/Android/05-compose/05-message-components/05-attachments-picker.mdx, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/AttachmentsPicker.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerTabFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/StorageHelperWrapper.kt, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/compose/messages/AttachmentsPicker.kt, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/detekt-baseline.xml, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/helper/internal/StorageHelper.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/state/messages/composer/AttachmentMetaData.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/internal/AttachmentMetaDataMapper.kt
Closes: 
- https://github.com/GetStream/android-internal-board/issues/192
=> [i192] remove attachment picker limitation in compose

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messageoptions/MessageOptions.kt, stream-chat-android-compose/src/main/res/drawable/stream_compose_ic_mark_as_unread.xml, stream-chat-android-compose/src/main/res/values/strings.xml, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
Add "mark as unread" option on Compose Artifact
It was pending on #5103
The unread separator would be shown on the messages list after #5122 is merged
=> Add "mark as unread" option on Compose Artifact

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/detekt-baseline.xml, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListItemStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/internal/MessageListItemDecoratorProvider.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/FootnoteView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/decorator/internal/FootnoteDecorator.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_footnote.xml, stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml, stream-chat-android-ui-components/src/main/res/values/styles.xml
Closes:
- https://github.com/GetStream/android-internal-board/issues/230
```kotlin
TransformStyle.messageListItemStyleTransformer = StyleTransformer { defaultStyle ->
defaultStyle.copy(
textStyleReadCounter = defaultStyle.textStyleReadCounter.copy(
color = Color.RED,
style = Typeface.BOLD,
size = 16.dpToPx()
),
)
}
```
| --- | --- |
| ![READ_COUNTER_BEFORE](https://github.com/GetStream/stream-chat-android/assets/1286516/1998f44d-15af-4559-b0b6-d63b166ad486) | ![READ_COUNTER_AFTER](https://github.com/GetStream/stream-chat-android/assets/1286516/486373bb-0c29-4dd9-8ab5-c2c711b9b706) |
=> [i230] Support read count UI customizations

CHANGELOG.md, stream-chat-android-core/src/main/java/io/getstream/chat/android/core/utils/date/DateUtils.kt, stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.kt, stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/MessageListItemLiveDataTest.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/231
Related to:
- https://github.com/GetStream/stream-chat-android/pull/5132
=> [i231] Old messages are read by newly added member

CHANGELOG.md, stream-chat-android-state/api/stream-chat-android-state.api, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/extensions/ChatClient.kt
Open `ChatClient.getMessageUsingCache()` extension method
fix: https://github.com/GetStream/android-internal-board/issues/238
=> Open `ChatClient.getMessageUsingCache()` extension method

CHANGELOG.md, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/utils/AttachmentConstants.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/242
=> [i242] align max attachment count with API limits

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/TextUtils.kt
Link should be always used in lowercase.
Fix: #5162
=> Ensure the link builder always uses lowercase

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/observable/ChatEventsObservable.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/observable/Subscriptions.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/DependencyResolverTest.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/244
Fix: #5149 
=> [i244] fix crash in ChatEventsObservable.onNext

CHANGELOG.md, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessagePositionHandler.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/252
=> [i252] Add isInThread to MessagePositionHandler

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/SocketFactory.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/SocketFactoryTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/token/FakeTokenManager.kt
Our Socket Factory wasn't fetching a new token in case the reconnection state was achieved. 
Whenever a TokenProvider is used to provide a JWT token with an expiration date, when the token expires and the WS is closed, the token used to establish a new WS Connection isn't refreshed, causing an endless retry process unless the user interacts with our Rest API.
=> Ensure new token is fetch on case reconnecting WS

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugins/requests/ApiRequestsDumper.kt
Use immutable list to ensure thread-safe access
Fix: #5186
=> Use immutable list to ensure thread-safe access

stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
Fix weird behavior when a new message is sent to a channel and the "Unread Label" appears.
Fix: #5206 
Unread label should never be shown on the case last message is read, even if new messages are sent
=> Fix "Unread Label" behavior

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/266
=> [i266] SelectExtendedReactions does not work

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/preview/factory/AudioRecordAttachmentPreviewFactory.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/267
=> [i267] fix crash on editing message with recording

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/MessageTextFormatter.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/QuotedMessageTextFormatter.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/268
=> [i268] fix TextStyle mismatch in text formatters

CHANGELOG.md, docusaurus/android_versioned_docs/version-6.x.x-before-refactoring/04-ui/04-message-components/02-message-list.mdx, docusaurus/docs/Android/ui/message-components/message-list.mdx, stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ui/messages/MessageList.java, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageList.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListItemViewHolderFactory.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/internal/MessageListItemAdapter.kt
- https://github.com/GetStream/android-internal-board/issues/281
- #5219
=> [i281] fix crash with custom message view holder

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/internal/Channel.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogic.kt
Not increase unread counter when an shadowed message arrives
Fix: https://github.com/GetStream/android-internal-board/issues/277
=> Not increase unread counter when an shadowed message arrives

stream-chat-android-compose-sample/src/main/AndroidManifest.xml
Automatic backups break the login in our compose sample (autobackup is already disabled in the XML sample).
=> Remove autobackup from Compose sample 

stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/composer/InputField.kt
Closes:
- https://github.com/GetStream/android-internal-board/issues/283
Related PR:
- #2700 
=> [i283] Keyboard gets stuck when typing

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/SocketFactory.kt
Catch only `UnsupportedEncodingException` while building Websocket URL
=> Catch only `UnsupportedEncodingException` while building Websocket URL

CHANGELOG.md, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/ChannelData.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventHandlerSequential.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelLogic.kt
Ignore events with shadowed messages
Close: https://github.com/GetStream/android-internal-board/issues/282
=> Ignore events with shadowed messages

CHANGELOG.md, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModelTest.kt, stream-chat-android-state/api/stream-chat-android-state.api, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/extensions/ChatClient.kt, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListControllerTests.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListViewStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/UnreadLabelButtonStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListItemViewHolderFactory.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListListenerContainer.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/MessageListListenerContainerImpl.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/internal/UnreadSeparatorViewHolder.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/helper/TransformStyle.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/messages/MessageListViewModelBinding.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_list_view.xml, stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/messages/MessageListViewModelTest.kt
When a user goes into a channel with unread messages, the message list is automatically scrolled to the first unread message position.
Close: https://github.com/GetStream/android-internal-board/issues/199
=> Jump to first unread message

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/internal/Channel.kt, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/ChannelData.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/DatabaseChannelRepository.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/domain/channel/internal/ChannelRepositoryImplTest.kt
Filter Thread Message when LastMessageAt is calculated
=> Filter Thread Message when LastMessageAt is calculated

CHANGELOG.md, docusaurus/docs/Android/client/moderation-tools.mdx, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/FlagRequestAdapterFactory.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/ModerationApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/FlagRequest.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/MoshiChatParser.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/UsersApiCallsTests.kt, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Moderation.java, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/Moderation.kt, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/messages/MessageListViewModelBinding.kt, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/messages/MessageListViewModelTest.kt
The API allows send `reason` and `custom` data whenever a message/user is flagged, but the SDK didn't provide a way to add it.
New `reason` and `custom` fields have been added 
close: https://github.com/GetStream/android-internal-board/issues/286
=> Add reason to flag endpoints

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/internal/DistinctChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/internal/DistinctChatApiEnabler.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/identifier/Identifiers.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/MessageApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/optimisation/hash/GetNewerRepliesHash.kt
Create a Low-Level Logic to fetch reply messages from older to newer.
The "State" and UI implementation will be covered on a different PR.
=> Feature get newer replies

stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/detekt-baseline.xml, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModel.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModelTest.kt
Closes:
- https://stream-io.atlassian.net/browse/PBE-2783
=> [PBE-2783] Infinite progress bar on ChannelList screen

stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/Messages.kt
Closes:
- https://stream-io.atlassian.net/browse/PBE-2806
=> [PBE-2806] Thread replies are scrolled to bottom on any event

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/interceptor/message/internal/PrepareMessageLogicImpl.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/message/MessageUtils.kt
The LLC SDK has a preventive mechanism to not send the same message twice.
The mechanism is based on the message id, but the message id wasn't initialized in time which caused some messages to be dropped in the case multiple messages are sent at the same time.
Fix https://stream-io.atlassian.net/browse/PBE-3738
=> [PBE-3738] Ensure message has id before starting the send process

CHANGELOG.md, stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ui/general/Configuration.java, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/general/Configuration.kt, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/helper/ImageHeadersProvider.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/helper/VideoHeadersProvider.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/images/internal/CoilStreamImageLoader.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/ChatUI.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/gallery/internal/AttachmentGalleryVideoPageFragment.kt
The SDK already provided the `ImageHeadersProvider` interface to inject custom headers whenever an image URL wanted to be loaded. This interface has been updated to receive as a parameter the URL that will be fetched to be able to inject different headers depending on the URL.
In the same way, the `VideoHeadersProvider` interface has been created to use custom headers when video URLs are fetched.
=> Headers providers Interfaces to fetch image/video URLs

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/MessageRepository.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/RepositoryFacade.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/noop/NoOpMessageRepository.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/DatabaseChannelRepository.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/DatabaseMessageRepository.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/channel/controller/attachment/UploadAttachmentsIntegrationTests.kt
We have to clear cache layer when channel becomes `hidden` to avoid messages from that channel to be accessible.
Closes:
- https://stream-io.atlassian.net/browse/PBE-4081
Related PR:
- https://github.com/GetStream/stream-chat-android/pull/5189
=> [PBE-4081]  hidden channel messages are shown up

CHANGELOG.md, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/state/messages/list/MessageListState.kt, stream-chat-android-ui-components/detekt-baseline.xml, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/internal/MessageListScrollHelper.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/model/MessageListItemWrapper.kt
Resolves:
- https://stream-io.atlassian.net/browse/PBE-3881
=> [PBE-3881] message list scrolls down on reaction

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/gallery/AttachmentGalleryActivity.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/gallery/overview/MediaAttachmentGridView.kt
- https://stream-io.atlassian.net/browse/PBE-3852
- https://github.com/GetStream/stream-chat-android/pull/1960
Most likely the `AttachmentGalleryActivity` gets killed in background. Then when the activity gets restored, `setupGallery` is being called with empty items list, which triggers `onBackPressed`, which internally calls `popBackStackImmediate` and it crashes due other ongoing transaction.
- user backgrounds the app on gallery screen
- then activity gets killed in the background either due to doze mode or resources draining
I forced this scenario on my end with activity being killed in the background (can see empty list coming), however, I was unable to replicate the crash (gallery just gets closed)
I also noticed another crash while investigating …
=> [PBE-3852] fix crash on gallery screen

CHANGELOG.md, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/MessageReplyView.kt, stream-chat-android-ui-components/src/main/res/values/styles.xml
Closes: 
- https://stream-io.atlassian.net/browse/PBE-4110
We should **not** apply styling depending on both `quotedMessage.isMine` and `containerMessage.isMine` combined. 
It brings complexity in understanding and expectations on UI customizations
=> [PBE-4110] fix quoted message styling

CHANGELOG.md, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/preview/internal/MessagePreviewView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/search/internal/SearchResultListAdapter.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/search/list/SearchResultListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/search/list/SearchResultListViewStyle.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_preview_item.xml, stream-chat-android-ui-components/src/main/res/values/attrs_search_result_list_view.xml, stream-chat-android-ui-components/src/main/res/values/dimens.xml, stream-chat-android-ui-components/src/main/res/values/styles.xml
Closes:
- https://stream-io.atlassian.net/browse/PBE-4097
=> [PBE-4097] extend search result list styling

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogic.kt
Related PRs:
- https://github.com/GetStream/stream-chat-android/pull/5290
- https://github.com/GetStream/stream-chat-android/pull/5289
=> [PBE-3845] fix side-effect & add missing changelog

stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/detekt-baseline.xml, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/ChannelResponse.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelMessagesUpdateLogic.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/state/ChannelState.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/internal/Message.kt, stream-chat-android-compose-sample/detekt-baseline.xml, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/data/PredefinedUserCredentials.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModelTest.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelLogic.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogic.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/channel/internal/ChannelMutableState.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/channel/controller/WhenHandleEvent.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/plugin/listener/internal/EditMessageListenerStateTest.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogicTest.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListControllerTests.kt, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/messages/MessageListViewModelTest.kt
Closes:
- https://stream-io.atlassian.net/browse/PBE-4795
Expose `pinnedMessages` in `ChannelState`
=> [PBE-4795] add missing ChannelState.pinnedMessages

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/LoadNotificationDataWorker.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/message/MessageUtils.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelLogic.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogic.kt
Related ticket:
- https://stream-io.atlassian.net/browse/PBE-4795
Related PR:
- https://github.com/GetStream/stream-chat-android/pull/5306
=> [PBE-4795] fix pinned messages on message deletion

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/TextUtils.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/ui/util/TextUtilsKtTest.kt
Ensure only the protocol scheme is lowercase
Fix: #5294
=> Ensure only the protocol scheme is lowercase

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/QuotedMessageText.kt
Small PR to fix an issue where the quoted message doesn't have the correct style.
This PR was created initially on #5310 but was merged into `main` branch incorrectly, it should be merged into `develop` branch instead.
=> Update quoted messages composable to use the quoted text style instead

buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
Upgrade Kotlin Coroutines to version 1.8.1
This version fix an internal error happening on Android devices with version 12, 13 and/or 14 as was described [here](https://github.com/GetStream/stream-chat-android/issues/5202#issuecomment-1988644160). 
Fix: #5202
=> Upgrade Kotlin Coroutines to version 1.8.1

build.gradle, buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
After jCenter was shut down, GitVersioners was not available by any maven repository. It looks like it was working on our CI because of the cache system we have implemented, but it started to fail recently, maybe because of any cache expiration.
=> Add jitpack repository to resolve GitVersioners dependency

CHANGELOG.md, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/messages/MessageComposerViewModelTest.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerController.kt, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/messages/MessageComposerViewModelTest.kt
After a message is properly sent from the message composer, it is marked as read
Fix: https://stream-io.atlassian.net/browse/PBE-5213
=> [PBE-5213] After a message is properly sent from the message composer, it is marked as read

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventHandlerSequential.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelLogic.kt
Clean up cache on `channel.hidden` event
Relates to:
- https://stream-io.atlassian.net/browse/PBE-4081
- https://github.com/GetStream/stream-chat-android/pull/5281
=> [PBE-4081] clear cache on channel.hidden event

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/ChannelsScreen.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelViewModelFactory.kt
Enable multiple instances of `ChannelsListViewModel` to be cached with varying parameters.
https://github.com/GetStream/stream-chat-android/issues/5327
Added an optinonal viewmodel key to `ChannelViewModelFactory` that is used by `ChannelsScreen`.
Behaviour is the same when viewmodel key is not set so its backwards compatible with previous releases.
N/A
Patch contains changes to `ChannelsActivity` inside `stream-chat-android-compose-sample`, adding a horizontal pager with two tabs where each tab has a slightly different sort on the list.
In the companion object there is a boolean `UseKeys` which is currently set to false, run with false to see the issue occur and run with true to see the fix.
<details>
```
Subject: [PATCH] #5327 Add key to …
```
=> #5327 Enable Multiple Channel List ViewModels

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/channel/internal/ChannelMutableState.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/plugin/state/channel/internal/ChannelMutableStateTests.kt
Related Ticket:
- https://stream-io.atlassian.net/browse/PBE-5181
Related PR:
- https://github.com/GetStream/stream-chat-android/pull/5321
- https://github.com/GetStream/stream-chat-android/pull/5329
Ensure all expired pinned messages are filtered out from exposure.
=> [PBE-5181] filter out expired pinned messages

stream-chat-android-compose/build.gradle, stream-chat-android-previewdata/api/stream-chat-android-previewdata.api, stream-chat-android-previewdata/build.gradle.kts
Fix the R8 issue for the previewdata module. ((#5359)
=> Fix the R8 issue for the previewdata module

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/internal/Channel.kt, stream-chat-android-core/src/testFixtures/kotlin/io/getstream/chat/android/Mother.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/domain/channel/internal/ChannelRepositoryImplTest.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/querychannels/internal/QueryChannelsStateLogic.kt, stream-chat-android-ui-utils/src/main/kotlin/io/getstream/chat/android/uiutils/extension/Channel.kt
When the last message is a deleted one, there isn't any preview available for the channels list.
On the DB we are filtering deleted messages when the channel is stored to ensure the last message is a non-delated one.
On the state plugin we are merging offline messages with the new ones we are receiving querying channels.
=> [PBE-4155] Ensure last preview message is not a deleted one

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
We were building some internal components used in the MessagesScreen that would be needed by customers who want to build their customer MessagesScreen.
We can expose those components to be used by our customers.
=> [PBE-5678] Expose some components needed to build custom MessagesScreen

CHANGELOG.md, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
Hide unread messages button on the case the list of messages is empty
| --- | --- |
| ![Screenshot_20240827_141542](https://github.com/user-attachments/assets/700b1c5f-3ce3-419d-99a6-e35d6c8b191d) | ![Screenshot_20240827_141432](https://github.com/user-attachments/assets/836ae365-7ebb-4b2b-89a5-7deb6b11afda) |
=> Hide unread messages button on the case the list of messages is empty

stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/listener/internal/ThreadQueryListenerState.kt
Fix race-condition when the endOfOlderMessage/endOfNewerMessage flag was updated after the messageList is updated
=> [PBE-5781] Reorder how ThreadState Properties are updated when new messages arrieve

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/suggestions/mentions/MentionSuggestionItem.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerController.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/content/DefaultMessageComposerMentionSuggestionsContent.kt
When `user.name` is empty we have to use `user.id` in Mentions UI component to align with other SDKs.
**Related ticket**:
- https://stream-io.atlassian.net/browse/PBE-5751
**Slack**:
- https://getstream.slack.com/archives/C07EV8DFMRN/p1724790876176129?thread_ts=1724696447.660409&cid=C07EV8DFMRN
=> [PBE-0] use user.id for mentions if user.name is empty

stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaGalleryPreviewActivity.kt
=> [5148] Crash on MediaGalleryPreviewActivity

CHANGELOG.md, DEPRECATIONS.md, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/FilterObject.kt, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/Filters.kt
Deprecate `NotInFilterObject` because it is no longer supported on the backend side.
This class will be removed soon on a future release.
=> [PBE-5890] Deprecate `NotInFilterObject`

stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/AttachmentsPicker.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
Fix unnecessary padding and overlapping content in `edge-to-edge` scenario.
- Use `safeDrawingPadding` instead of existing inset padding modifiers:
- `MessagesScreen`: existing `systemBarsPadding` only accounts for the system bar, but not for the keyboard & navigation bar, leading to attachments picker being obscured.
- `MessageComposer`: existing `imePadding` only accoungs for the keyboard, so if used as a standalone component, other insets are not taken into account.
- `AttachmentsPicker`: has no inset padding, needed if used as standalone.
- Explicitly consume ime inset in `MessagesScreen` with `consumeWindowInsets(WindowInsets.ime)`, even if normally it's not needed, as a potential fix for reported cases when the `MessageComposer` has too much bottom padding (roughly the size of 2 …
=> Fix edge to edge extra padding and overlapping content

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/attachment/AttachmentUploader.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/attachment/AttachmentUploaderTests.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/StreamAttachmentFactories.kt
Async-Voice attachments weren't rendered properly on Compose SDK on some situations.
Some internal properties caused it, which we use in our attachments to track the upload process.
Apart of that, the attachments factories has been reordered to ensure Async-Voice attachments use the proper factory
=> [PBE-5896] Fix/async voice compose render

CHANGELOG.md, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
Currently, when a message is deleted, the read are updated removing them from the deleted message and adding them to the previous message. It causes that a deleted message on the last possition is always marked as unread.
Only non-deleted messages should be elegible to be marked as unread
UnreadLabel is not added on the case that only deleted messages are after the last read message
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/3bb0cbee-79c5-45a3-97e7-166b5ea8657e" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/b38b2725-9397-4f71-b484-7a24ca4e48c3" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
=> [PBE-5969] UnreadLabel shouldn't appear when only deleted messages are unread

stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/avatar/Avatar.kt
The `ChannelAvatar` component wasn't clickable when it shows 2+ user avatars (handled by `GroupAvatar` in the background)
The root cause was in a deeper layer, in the `Avatar` implementation. The `Avatar` always set the `clickable()` modifier on the `StreamImage` component (even if the `onClick` handler was null), which resulted in the `StreamImage` consuming the click events, even if its parent component had a `clickable` modifier set (in this case - `GroupAvatar`).
With this change, the `clickable` modifier is set only when the `onClick` handler is passed.
<table>
<thead>
<tr>
<th></th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Single user avatar (no changes)
</td>
<td>
<video src="https://github.com/user-attachments/assets/19f209c9-cd0c-4bca-b …
=> Fix ChannelAvatar not clickable

stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/composer/InputField.kt
Fix the input border is using wrong shape
=> Fix the input border is using wrong shape

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/identifier/Identifiers.kt
Avoid multiple ConnectUser invocations by sharing the `Call`
=> Avoid multiple ConnectUser invocations by sharing the `Call`

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/navigation/destinations/AttachmentDestination.kt
Clicking on Certain Areas of Audio Recording in Message List Displays "Invalid URL" Error
fix for this issue #5446 
basically check to make sure the attachment is unsupported before showing error message
Try tapping random places in the message bubble try to avoid buttons and the slider the toast should not appear
=> bug fix for Clicking on Certain Areas of Audio Recording in Message List Displays "Invalid URL" Error

stream-chat-android-core/src/main/java/io/getstream/chat/android/models/MessageModerationDetails.kt
A wrong literal was used for the moderation action FLAG in the code: `MESSAGE_RESPONSE_ACTION_BOUNCE` instead of `MESSAGE_RESPONSE_ACTION_FLAG`.
| --- | --- |
| img | img |
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<details>
```
```
</details>
_Please provide a suitable gif that describes your work on this pull …
=> [PBE-0] Fix moderation action FLAG literal.

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/MarkUnreadRequest.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenMarkUnreadThread.kt
Implement the ChatClient.markThreadUnread operation. It will be used as part of the whole Threads V2 implementation.
- Extend the MarkUnreadRequest with thread_id filed (as per the api documentation)
- Implement new markThreadUnread (similar to markUnread) methods on ChatClient and ChannelClient
_NA_
_Currently not used_
=> [PBE-3749] Implement ChatClient::markThreadUnread operation.

stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/DateSeparatorHandler.kt
Fix #5454
Provide a default DateSeparatorHandler adding date separator whenever two messages are from different days
=> Refactor default date separator handle to add date when messages are from different days

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/audio/StreamAudioPlayer.kt
fix issue causing users to not be able to set speed after pausing audio #5450 
allow setting speed when audio is paused
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/c8e7428d-fafa-4d31-8ba7-6d3a5f27cf69" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/ea0f3821-ddf4-4421-a582-c05e7dcc6c69" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
- Play audio recording
- pause audio recording
- Set speed
=> bug fix for "Unable to set audio speed after pausing"

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-ui-components/src/main/res/values/strings_message_list.xml
Exposes the `flagUser()` and `unflagUser()` methods on the `MessageListController` and `MessageListViewModel (xml and compose)` so that they can be invoked from the UI components, without accessing the `ChatClient` directly.
Linear: https://linear.app/stream/issue/AND-11/expose-flaguserunflaguser-on-messagelistcontrollermessagelistviewmodel
- Expose `flagUser()`/`unflagUser()` on the `MessageListController` (delegates the call to the `ChatClient`)
- Create new `ErrorEvent.FlagUserError` and `ErrorEvent.UnflagUserError` for handling errors which occurred while performing the corresponding operation
- Expose `flagUser()`/`unflagUser()` on the `MessageListViewModel(compose)`
- Create new `Event.FlagUser` and `Event.UnflagUser` for triggering the corresponding operations from the `xml` SDK. …
=> [AND-11] Expose flagUser/unflagUser on MessageListController and MessageListViewModels.

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaGalleryPreviewActivity.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaPreviewActivity.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/documents/AttachmentDocumentActivity.java, stream-chat-android-ui-common/src/main/res/layout/stream_activity_attachment_document.xml, stream-chat-android-ui-components/src/main/AndroidManifest.xml, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/ChannelListActivity.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/gallery/AttachmentActivity.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/gallery/AttachmentGalleryActivity.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/gallery/AttachmentMediaActivity.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/MessageListActivity.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_activity_attachment_gallery.xml, stream-chat-android-ui-components/src/main/res/layout/stream_ui_activity_attachment_media.xml
Any apps targeting Android 15 (`targetSdk=35`) have edge-to-edge enabled by default. This means that some screens/components could be obstructed by the system bars / keyboard, making it impossible to interact with. Therefore, we must ensure that the screens we provide from the SDK are supporting edge-to-edge, otherwise integrator apps targeting Android 15 could have issues.
**Note 1: This PR DOESN'T change the SDK / sample apps `targetSdk` value, as that might require other updates. It just makes sure that the affected screens are properly shown in apps targeting Android 15.**
**Note 2: This PR DOESN'T explicitly introduce edge-to-edge for all screens (for Android version < 15). The only screens where edge-to-edge is explicitly requested are screens which are already simulating such …
=> [AND-6] Add edge-to-edge support for apps targeting Android 15

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/internal/ExtraDataValidator.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/ChannelApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/MemberMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/MemberDtos.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/UpdateMemberPartialRequest.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/UpdateMemberPartialResponse.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/MoshiChatParser.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/adapters/MemberDtoAdapters.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenPartialUpdateMember.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/DownstreamMemberDtoAdapterTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/UpstreamMemberDtoAdapterTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/ChannelDtoTestData.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/MemberDtoTestData.kt, stream-chat-android-core/api/stream-chat-android-core.api, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/Member.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/ChatDatabase.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/member/internal/MemberEntity.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/member/internal/MemberMapper.kt
- Part 1 of the custom membership data feature
Linear: https://linear.app/stream/issue/AND-16/custom-membership-data
Implements the `partialUpdateMember` operation.
- Extend `Member`, `UpstreamMemberDto`, `DownstreamMemberDto` and `MemberEntity` with custom data.
- Write new extra data adapters for the `DTOs`
- Add custom data validation in `ExtraDataValidator` for reserved `Member` field names
- Add `partialUpdateMember` to `ChannelApi`
- Expose `partialUpdateMember` on `ChatClient` and `ChannelClient`
=> [AND-16] Implement ChatClient.partialUpdateMember()

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamKeyboardBehaviour.kt
The PR introduces a way of configuring different keyboard behaviours (at the movement it is only `closeKeyboardOnAttachmentPickerOpen`, but it can be extended in the future). The default behaviour is to close the keyboard, so the PR also addresses the issue that the keyboard wasn't closed when opening the attachments picker from the `MessagesScreen`.
- Implement new `StreamKeyboardConfiguration` class which allows customisation of different keyboard behaviours.
- Provide the `StreamKeyboardConfiguration` via the `ChatTheme`
- Ensure the keyboard is closed in the `AttachmentsPickerMenu` (if instructed by the `StreamKeyboardConfiguration`)
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/43c3c19a-0361- …
=> [AND-147] Fix keyboard not closing when opening attachment picker menu and make this behaviour customizable.

stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaGalleryPreviewActivity.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaPreviewActivity.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/documents/AttachmentDocumentActivity.java, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/ChannelListActivity.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/gallery/AttachmentActivity.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/gallery/AttachmentGalleryActivity.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/gallery/AttachmentMediaActivity.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/MessageListActivity.kt
Ensure ChatClient is initialized before internal SDK activities are started
=> [AND-159] Ensure ChatClient is initialized before internal SDK activities are started

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/channels/list/ItemState.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/list/SearchResultItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/pinned/PinnedMessageList.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/SearchResultNameFormatter.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModel.kt, stream-chat-android-compose/src/main/res/values/strings.xml, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/pinned/PinnedMessageListController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/model/MessageResult.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/pinned/PinnedMessageListControllerTest.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/internal/MessageResultDiffCallback.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/mentions/list/MentionListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/mentions/list/internal/MentionListAdapter.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/preview/internal/MessagePreviewView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/pinned/list/PinnedMessageListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/pinned/list/internal/PinnedMessageListAdapter.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/search/internal/SearchResultListAdapter.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/search/list/SearchResultListView.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/mentions/MentionListViewModel.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/pinned/PinnedMessageListViewModelBinding.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/search/SearchViewModel.kt
When searching for messages, our customers couldn't know the channel data in which this message was posted. It was a bit problematic for 1:1 channel where the data rendered on the screen could be a bit confusing for the user searching for messages.
The list of messages has been pre-processed, recovering the channel data from our internal DB before it is provided to the view.
=> [AND-13] Add channel info when searching for messages

README.md, stream-chat-android-client/README.md, stream-chat-android-compose/README.md, stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/docusaurus/GettingStarted.java, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/GettingStarted.kt, stream-chat-android-offline/README.md, stream-chat-android-ui-components/README.md
Keep the documentation healthy
Fix broken links in the `Getting Started` section of the entire repo
=> Fix broken link of Getting Started README section

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/AndroidManifest.xml, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/attachments/images/ImagesPicker.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerFilesTabFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerImagesTabFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/FilesAccess.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/NoStorageAccessContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/PermissionPermanentlyDeniedSnackBar.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/Permissions.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/VisualMediaAccess.kt, stream-chat-android-ui-common/src/main/res/values/strings.xml
Linear: https://linear.app/stream/issue/AND-12/improve-storage-access-permission-behaviour-with-limited-access
Adds support for partial media access for Android 14+.
More details: https://developer.android.com/about/versions/14/changes/partial-photo-video-access
- Add `READ_MEDIA_VISUAL_USER_SELECTED` to `AndroidManifest` to ensure media re-selection is properly handled on Android 14+.
- Add granular permission handling for `AttachmentsPickerImagesTabFactory`  based on the different android versions (12 and below, 13 and 14 and above)
- Add new UI options in the images/videos picker to initiate media re-selection on Android 14+.
- Add granular permission handling for `AttachmentsPickerFilesTabFactory`  based on the different android versions (12 and below, 13 and 14 and above)
- Add new …
=> [AND-12] Improve media storage permission handling.

CHANGELOG.md, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/internal/StatePlugin.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/listener/internal/QueryMembersListenerState.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/plugin/listener/internal/QueryMembersListenerStateTest.kt
Intercept members and add them to `ChannelState` whenever the LLC method `ChatClient.queryMembers()` is invoked.
=> [AND-170] Intercept Members and add them to ChannelState

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModelTest.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/messages/MessageComposerViewModelTest.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/extensions/ChatClientExtensionTests.kt, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/channels/ChannelListViewModelTest.kt, stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/messages/MessageComposerViewModelTest.kt
Await Depednecy Resolve process until ChatClient is properly initialized or timeout is over to avoid race-conditions in situations where the Chat Components are initialized without waiting the user is connected.
Using the following patch we can verify the `GlobalState` can be resolved requesting it even before the `connectUser()` method is invoked.
<details>
<summary>Patch</summary>
```
Subject: [PATCH] crash investigation
---
Index: stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
<+>UTF-8
diff --git a/stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sampl …
```
=> [AND-172] Await Depednecy Resolve process until ChatClient is properly initialized

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/StreamAttachmentFactories.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/MediaAttachmentContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/MediaAttachmentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaGalleryPreviewActivity.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaGalleryPreviewContract.kt
Related PR: #5490
On implementing the previous PR, the use of `DownloadAttachmentUriGenerator` and `DownloadRequestInterceptor` was obtained from the ones configured within `ChatTheme` entity.
The problem is that our internal activities don't use the `ChatTheme` that our customers configure when they initialize the SDK. There aren't any static references to it, so the default implementation was used.
With this PR the customization used on `ChatTheme` is forwarded to our internal activities
To test it, you only need to add a custom implementation of those dependencies and check it is being used when downloading attachments.
| From Message List Attachment | From Media Gallery |
| --- | --- |
| ![Screenshot from 2024-12-16 09-42-23](https://github.com/user-attachments/assets/58dd12e5-260b-4b8 …
=> [AND-176] Intercept Attachment Download Process within internal activities

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/UserApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/UserMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/UserDtos.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/BlockUserResponse.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/UnblockUserResponse.kt
Linear: https://linear.app/stream/issue/AND-188/user-blocking-feature-issue-with-android-sdk-version-680
The `queryBlockedUsers` operation had its API endpoint wrongly defined. This PR fixes that issue, and additionally ensures that the `blockUser` and `unblockUser` operation responses are correctly parsed.
- 🚨 Breaking change: The `ChatClient.unblockUser(userId: String)` operation returns `Call<Unit>` instead of `Call<UserBlock>`. this is changed because the API no longer gives us return information about the unblocked user as it can be deducted from the argument that was initially passed to the `unblockUser` method.
- Add the missing `GET` path to the `UserApi.queryBlockedUsers`
- Adjust the `BlockUserResponse` and `UnblockUserResponse` models to ensure they are properly parsed
_NA_
1. …
=> [AND-188] Fix user blocking operations.

metrics/size.json
Clear SDK sizes so we can test the changes being pushed from the workflow
=> Clear sizes so we can test changes push

.github/workflows/build-and-test.yml, .github/workflows/check-entities.yml, .github/workflows/sdk-size-checks.yml
By default, GitHub Actions permits multiple workflow runs to execute concurrently. As a result, if a second push is made to a PR branch before the CI workflow from the previous push completes, two workflow runs will execute in parallel. This is a waste of resources.
To address this, concurrency control is introduced by configuring a unique concurrency group. This ensures that only one workflow run per branch is active at a time, with any new runs automatically canceling previous ones in progress.
=> Prevent multiple PR workflows running at the same time

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/network/NetworkStateProvider.kt
Linear: https://linear.app/stream/issue/AND-205/race-condition-in-networkstateprovider-causes-the-connectionstate-to
Fixes a rare bug where turning off the network connectivity on the device doesn't update the `ConnectionState` to `Offline`.
The cause for this is that it is not safe to call `ConnectivityManager.getNetworkCapabilities(Network)` from the `ConnectivityManager.NetworkCallback.onLost` callback, as there is no guarantee that the `ConnectivityManager` state will be in the updated state from the callback. In some occasions, calling `NetworkStateProvider.isConnected()` from the `NetworkCallback.onLost` callback returns `true`, which is a false positive. See details: https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onLost(android.net.Network) …
=> [AND-205] Improve network connectivity check in the NetworkStateProvider.

CHANGELOG.md, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListControllerTests.kt
The `MessageListController` flag `showSystemMessages` was not respected, due to the `DeletedMessageVisibility` taking precedence. We now properly take this flag into consideration, if the message is not deleted.
Change the `MessageListController.filterMessagesToShow` logic to consider the `DeletedMessageVisibility` when the  message is deleted, and consider `showSystemMessages` if the message is a system one.
**Scenario where showSystemMessages = false**
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/a5ccc06a-bb88-49f9-902e-791fc92d2040" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/8ca1922a-5e27-4376-9ea4-0feabfce3622" controls="controls" …
=> [AND-203] Fix system messages not hidden if showSystemMessages=false.

CHANGELOG.md
- Fix the wrong method name in `CHANGELOG.md`: `ChatClient::queryBlockedMembers` to `ChatClient::queryBlockedUsers`.
=> [AND-0] Fix wrong method name in CHANGELOG.md.

.github/workflows/e2e-test.yml, fastlane/Fastfile, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/pages/MessageListPage.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobot.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobotChannelListAsserts.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobotMessageListAsserts.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/tests/MessageListTests.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/tests/StreamTestCase.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/factory/MessageContentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/suggestions/SuggestionList.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt, stream-chat-android-e2e-test/api/stream-chat-android-e2e-test.api, stream-chat-android-e2e-test/src/main/AndroidManifest.xml, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/mockserver/DataTypes.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/mockserver/MockServer.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/robots/BackendRobot.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/robots/ParticipantRobot.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/uiautomator/Actions.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/uiautomator/Element.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/uiautomator/Math.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/uiautomator/Wait.kt
Resolve https://linear.app/stream/issue/AND-183
Copy-paste all the `MessageList` E2E tests from iOS to Android
=> [CI] Add MessageList E2E tests

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageContainer.kt
Fixes a problem in the Compose SDK where we override each error message text with the default "Moderation failed" text.
- Update the `DefaultMessageModeratedContent` (which is also used for showing Messages with `type = error`, not only moderated messages) so that it prioritises showing `text`, and falling back to `R.string.stream_compose_message_moderated` if `text` is blank.
_Note: It is now aligned with the XML implementation: `ErrorMessageViewHolder`_
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/b0bcf6b2-ea89-4de6-a427-1efecca50096" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/9d691b24-ecc4-4518-a822-625f4e49dc57" controls="controls" …
=> [AND-216] Fix error message text being overridden by moderation message.

stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/pages/MessageListPage.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobot.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobotMessageListAsserts.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/tests/ReactionsTests.kt, stream-chat-android-e2e-test/api/stream-chat-android-e2e-test.api, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/robots/ParticipantRobot.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/uiautomator/Element.kt
Resolve https://linear.app/stream/issue/AND-185
Copy-paste all the `Reaction` E2E tests from iOS to Android
=> [CI] Add Reaction E2E tests

stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/pages/MessageListPage.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobot.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobotMessageListAsserts.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/tests/GiphyTests.kt, stream-chat-android-e2e-test/api/stream-chat-android-e2e-test.api, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/robots/ParticipantRobot.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/uiautomator/Actions.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/uiautomator/Element.kt
Resolve https://linear.app/stream/issue/AND-226
Copy-paste all the `Giphy` E2E tests from iOS to Android
=> [CI] Add Giphy E2E tests

gradle/libs.versions.toml, stream-chat-android-compose-sample/src/main/AndroidManifest.xml, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/chats/ChatsActivity.kt, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/build.gradle.kts, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/chats/ChatsScreen.kt
Make our chat screens compatible with large screens such as tablets.
A new `ChatsActivity` is introduced to the compose sample app to host the `ChatsScreen` and handle navigation between **Chats** and **Threads**
When the sample runs on a phone device, it should behave as is, rendering a single-pane screen.
When it runs on a larger device, e.g. a tablet, it should render two panels, one for channels and another one for messages of the selected channel.
⚠️ **There are a few flows that need to be revisited. For now, `ChatsScreen` is marked as experimental.**
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/b0c74c78-ed40-4888-9193-8c71a0a20a37" controls="controls" muted="muted" />
</td>
<td>
<video …
=> AND-217: Introduce ChatsScreen composable

stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobot.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobotChannelListAsserts.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobotMessageListAsserts.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/tests/ChannelListTests.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/tests/GiphyTests.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/tests/MessageListTests.kt, stream-chat-android-e2e-test/api/stream-chat-android-e2e-test.api, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/uiautomator/Actions.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/uiautomator/Element.kt
Resolve https://linear.app/stream/issue/AND-184
Copy-paste all the `ChannelList` E2E tests from iOS to Android
=> [CI] Add ChannelList E2E tests

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/poll/PollOptionList.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/poll/PollSwitchItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/poll/PollSwitchList.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/PollSwitchItemFactory.kt, stream-chat-android-compose/src/main/res/values/strings.xml, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/ui/poll/PollUITest.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/ui/util/DefaultPollSwitchItemFactoryTest.kt, stream-chat-android-ui-components/src/main/res/layout/stream_ui_poll_option.xml, stream-chat-android-ui-components/src/main/res/values/strings.xml
Resolves: https://linear.app/stream/issue/AND-250/incorrect-placeholder-in-text-fields-for-poll-options
The poll creation dialog had some wrong placeholders in the input fields:
- "Add an option" field -> "Ask a question" placeholder
- "Max number of answers" field -> "Ask a question" placeholder
This PR sets new, more appropriate placeholders to those fields 
- Add new `description` property `PollSwitchInput` to allow customisation of the description (placeholder) of the switch input fields
- Override the default `description` for the "Add option" field
- Replace hard-coded string "Option" with a localised resource in the XML SDK
**Note: For the "Add an option" placeholder, I re-used the same "Add an option" placeholder. If you think that this is not appropriate, we can update the …
=> [AND-250] Fix default poll input fields hints.

CHANGELOG.md, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobotMessageListAsserts.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/extensions/ChatClient.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/extensions/ChatClientExtensionTests.kt
There were an issue on our `getStateOnNull()` method that propagated a new state on the case any of the properties of the current user was updated, even if the user was the same one. It would invoke multiple times the same queries for previous created states (Channels, All Active Channel and/or All Activy Threads).
In our sample apps it wasn't appreciated in a normal usage of the app because the current user wasn't update frequently, but it could be a big issue on a customer integration that by some reason the user's properties are updated more frequently.
=> [AND-264] Avoid querying multiple times to WatchChannel if any property of the currentuser is updated

.github/workflows/sdk-size-checks.yml, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/HeadersInterceptor.kt
_The goal of this change is to fix a NullPointerException in the app, specifically caused by an attempt to invoke the `toString()` method on a null object. This was preventing the application from opening, causing it to crash immediately. After fixing this issue, the app is now able to open and function as expected._
_The fix involved identifying the null object reference that caused the `NullPointerException`. By adding null checks and ensuring that the object is initialized before invoking any methods, we prevented the crash. The updated code now gracefully handles null values, allowing the app to proceed without errors._
_There were no UI changes involved in this fix as it was related to backend functionality. However, the app's stability has significantly improved, leading to a better …
=> Refactor/Docs not opening fixed.

stream-chat-android-docs/proguard-rules.pro, stream-chat-android-ui-components-sample/proguard-rules.pro
Add the missing rules to fix `stream-chat-android-ui-components-sample:assembleDemoRelease` of the `App distribute CI` and `assembleRelease` of the `Build and test` pipelines
https://github.com/GetStream/stream-chat-android/actions/runs/12992168847/job/36231394030#step:6:930
https://github.com/GetStream/stream-chat-android/actions/runs/12992168852/job/36231395525#step:4:2037
=> Fix App distribute and Build and test pipelines

CHANGELOG.md, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/component/CustomChatComponentFactory.kt, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/header/ChannelListHeader.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/list/ChannelItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/list/ChannelList.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/list/Channels.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/SearchInput.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/factory/MessageContentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageContainer.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageList.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/Messages.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatComponentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
- Create message stateless component factories.
- Refactor to have a single component factory object.
=> [AND-253] Message stateless component factories

.github/workflows/build-and-test.yml
Remove `stream-chat-android-ui-uitests` from Build and test pipeline
Android tests from `stream-chat-android-ui-uitests` are not running at all, due to a bug with the screenshot library.
So, it would make sense to stop compiling it in our CI.
Besides, snapshot tests are faster with Paparazzi.
=> Remove stream-chat-android-ui-uitests from Build and test pipeline

CHANGELOG.md, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/UserId.kt
The public `Channel.currentUserUnreadCount()` extension function is using `UserId` alias as argument, what make this function unavailable to anyone that is not opt-in for `@InternalStreamChatApi`.
Exposing `UserId` alias avoid @InternalStreamChatApi issues
=> [AND-307] Expose `UserId` alias to avoid InternalStreamChatApi issues

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModel.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModelTest.kt
Add a debouncer on queryChannels to avoid multiple calls to fetch channels when typing new characters on the search input while using seach channel mode
=> [AND-308] Avoid multiple calls to fetch channels when typing new characters on search input

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageContainer.kt, stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ui/general/Configuration.java, stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ui/messages/MessageList.java, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/compose/general/ChatTheme.kt, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/general/Configuration.kt, stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageList.kt, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/helper/DateFormatter.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/helper/DefaultDateFormatterTest.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/impl/DateDividerViewHolder.kt
Expose a new method on `DateFormatter` to return a representation of relative data.
It is now used within our "Date Separator Views" on both SDKs, XML and Compose.
The default implementation continue using `DateUtils` from Android SDK, but it is customizable by our customers providing a custom implementation of `DateFormatter`
Fix: #5584
=> [AND-275] Expose a new method to return a representation of relative date

stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerMediaCaptureTabFactory.kt
Fix the default camera picker
Remember the `CaptureMediaContract` to avoid state loss.
That contract logic relies on two instance fields: `pictureFile` and `videoFile`
Every recomposition of `PickerTabContent` created a new `CaptureMediaContract` instance, hence losing those field references.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/5229a9ae-2946-40a3-8e4b-823a07df1fe0" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/8460b572-8ce6-4b9c-b3ca-bc08c3525575" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
=> [AND-325] Fix default camera photo/video picker

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListControllerTests.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/messages/MessageListViewModel.kt
Exposes the `scrollToFirstUnreadMessage` method from the `MessageListController` on the `MessageListViewModel`s.
Additionally, fixes a bug where the `chatClient.loadMessagesAroundId` wasn't called, when calling `scrollToFirstUnreadMessage` when the message wasn't already loaded.
- Expose `scrollToFirstUnreadMessage` on `MessageListViewModel`(compose)
- Expose `scrollToFirstUnreadMessage` on `MessageListViewModel`(xml)
- Fix `chatClient.loadMessagesAroundId` not called:
```kotlin
messages.firstOrNull { it.id == unreadLabel.lastReadMessageId }
?.let { messages.focusUnreadMessage(it.id) }
?: {  // <- This was never called as it is lambda that wasn't invoked
scope.launch {
chatClient.loadMessagesAroundId(cid, unreadLabel.lastReadMessageId)
.await()
.onSuccess { channel -> …
```
=> [AND-296] Expose scrollToFirstUnreadMessage on MessageListViewModel.

CHANGELOG.md, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/MessagesActivity.kt, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentPickerAction.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerPollTabFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/poll/AttachmentsPickerPollUtils.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/poll/PollSwitchItem.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/PollSwitchItemFactory.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/ui/messages/attachments/poll/AttachmentsPickerPollUtilsTest.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/ui/util/DefaultPollSwitchItemFactoryTest.kt
If a client is using the `AttachmentsPicker` component in their code, handling the creation of a poll is a bit difficult. They would need to copy-paste the whole logic for transforming the `AttachmentPickerPollCreation` into a `PollConfig`, which can be error prone, and is not something that they should know how it is done internally. They currently need to do the following:
```kotlin
AttachmentsPicker(
onAttachmentPickerAction = { action ->
if (action is AttachmentPickerPollCreation) {
composerViewModel.createPoll(
pollConfig = PollConfig(
name = action.question,
options = action.options.filter { it.title.isNotEmpty() }.map { it.title },
description = action.question,
allowUserSuggestedOptions = action.switches.any { it.key == "allowUserSuggestedOptions" && it.enabled },
votingVisibility …
```
=> [AND-319] Improve poll creation process(compose).

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/ImageUtils.kt
Fix crash when recording audio on message reply
For some reason, when starting to record audio in a message reply, `onSizeChanged` of the user avatar calculates the size as `0x0`. That's not a valid size to load an image and Coil requires any dimension to be greater than zero.
We have to check for non-zero dimensions before using the `size`.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/5b22a44e-36b9-455a-8cba-b51c365129d9" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/b265cef8-7f0a-4e6a-8f83-e10b84da2a31" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Reply to a message and start recording audio.
=> [AND-328] Fix crash when recording audio on message reply

.github/workflows/e2e-test-cron.yml, .github/workflows/e2e-test.yml, fastlane/Fastfile, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/robots/UserRobotMessageListAsserts.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/tests/ChannelListTests.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/tests/ReactionsTests.kt, stream-chat-android-compose-sample/src/androidTestE2eDebug/kotlin/io/getstream/chat/android/compose/tests/StreamTestCase.kt, stream-chat-android-e2e-test/api/stream-chat-android-e2e-test.api, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/robots/ParticipantRobot.kt, stream-chat-android-e2e-test/src/main/kotlin/io/getstream/chat/android/e2e/test/uiautomator/Actions.kt
- Make e2e tests more stable on PRs and Nightly
- Rename logs archives so they are no rewritten.
- Remove API 29 from nightly checks, it was not stable. Having 28 as a min tier should be fine.
- Add timeout to Allure upload (noticed it can get stuck)
- Grant read/write permissions for older APIs
- Implement a `retryOnStaleObjectException` workaround to wait until the message list is unstale after scrolling
- Implement an option to provide a `delay` to participants actions, so we can test offline mode properly
=> [CI] Resolve some e2e tests issues

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
The `ChatClient#deleteFile` and the `ChatClient#deleteImage` will always return `Result.Success`, even if the operation fails. The underlying problem is in the `MoshiChatApi` implementation, where in the `deleteFile` and `deleteImage` methods ignore the `FileUploader.deleteImage/File` result, and return a hard-coded `Result.Success(Unit)`.
Remove the hard-coded `Result.Success(Unit)` return, and propagate the original result of the `FileUploader.deleteImage/File` operation.
=> [AND-378] Fix deleteFile/deleteImage not propagating errors.

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageFooter.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/decorator/internal/FootnoteDecorator.kt
The message timestamp in the `MessageList` (Compose) was wrongly rendering the `updatedAt` date (if present), instead of the `createdAt` date. This means that any updates to the message such as reacting, pinning/unpinning or editing, resulted in updating the timestamp shown below the message. 
This is also different from the behaviour that we have in the XML SDK.
Additionally, in the XML SDK there was a specific case where the `updatedAt` was rendered instead of the `createdAt` - for non-ephemeral Giphy messages. This logic is now removed as well, because it had the same bug, but only present on Giphy messages. 
In this PR, the Compose and XML implementations are aligned.
- Compose: Always render the `createdAt` date as timestamp, and don't consider `updatedAt`
- XML: Remove the specific …
=> [AND-394] Fix timestamp rendering in the message footer.

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/SocketFactory.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/SocketFactoryTest.kt
Fix the placement of the `X-Stream-Client` value in the WebSocket request URL
Move the `X-Stream-Client` value from the `json` query parameter, to a dedicated query parameter in the WebSocket request URL.
=> [AND-381] Fix WS X-Stream-Client headers placement.

CHANGELOG.md, DEPRECATIONS.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser/FilterObjectToMap.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/models/FilterObjectTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/FilterObjectTypeAdapterTest.kt, stream-chat-android-core/api/stream-chat-android-core.api, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/FilterObject.kt, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/Filters.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/converter/internal/FilterObjectConverter.kt, stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/database/converter/FilterObjectConverterTest.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/utils/internal/CustomObjectFiltering.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/utils/CustomObjectFilteringTest.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/users/GroupChatInfoAddUsersViewModel.kt
Revert changes where `NotInFilterObject` was removed.
We keep it as deprecated and will be removed on a future version.
This reverts commit 7bfe302fc1c1d273df263b3ca53efc7db8501b4c.
=> [AND-390] Revert "[PBE-5891] Remove `NotInFilterObject` (#5394)"

CHANGELOG.md, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt
PR #5677  introduced a side-effect that showed the unread label after a picture/video attachment was sent using a third-party activity.
On this PR we introduce an extra flag to check if the unreadLabel State should be updated or not.
Remember that this unreadLabel should only be updated when the conversation is opened and/or when the marAsUnread feature is used by the final user.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/c0b83ff3-3a35-49c2-9aa4-d99d1572fb0a" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/acffc044-343f-4017-a060-92eb2dcb9f48" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr> …
=> [AND-396] Unread label shouldn't be shown after an own message is sent

stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/channel/ChannelInfoOptionItem.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/chats/ChatsActivity.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/chats/InfoContentMode.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/pinned/PinnedMessagesActivity.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/pinned/PinnedMessagesScreen.kt, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/chats/ChatListContentMode.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/chats/ChatsScreen.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/adaptivelayout/ThreePaneNavigator.kt, stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/ui/util/adaptivelayout/ThreePaneNavigatorTest.kt
Render pinned messages in the info pane of `ChatsScreen`
- Navigate to `PinnedMessagesScreen`
- Reuse `PinnedMessagesScreen` in `PinnedMessagesActivity`
- Add ripple effect to the `ChannelInfoOptionItem`
- Rename `ListContentMode` to `ChatListContentMode`
<table>
<thead>
<tr>
<th>Phone</th>
<th>Tablet</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/a49a5e02-313f-4819-a479-286cf4c5c887" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/7df5937f-f295-41b9-b0f6-36b441e8447d" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
- Enable Adaptive layout in the Advanced options
- Follow the video steps on tablet devices
=> [AND-388] Render pinned messages in the info pane of ChatsScreen

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/HeadersUtil.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/HeadersUtilTest.kt
The `HeadersInterceptor` takes some info from the customer app as the app name. Our customers could have special characters on their app names that are not compatible with the http request. To avoid it, headers need to be sanitized
Fix: https://linear.app/stream/issue/AND-428/
=> Ensure headers don't contain special characters

CHANGELOG.md, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/state/messages/list/NewMessageState.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListControllerTests.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/componentbrowser/messages/viewholder/BaseMessagesComponentBrowserFragment.kt
Focus on the typing item when it appears, and the scroll position is near the bottom.
Return a `NewMessageState` for the typing indicator item, so that the UI can behave properly.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/58da32e6-8aec-4460-9da9-9ccb43dffebc" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/7652a09c-66a0-4148-b975-4d5f0090f39d" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
- Create a custom typing indicator item (the default is empty)
```kotlin
public interface ChatComponentFactory {
@Composable
public fun LazyItemScope.MessageListTypingIndicatorItemContent(typingItem: TypingItemState) {
Text(modifier …
```
=> [AND-440] Fix the typing list item focus

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/observable/Subscriptions.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/observable/SubscriptionImplTest.kt
Fix #5699
The subscription is disposed concurrently when filtering, causing the listener to be null when calling onEvent.
The fix adds a safe call to onEvent.
Unit tests are introduced to cover that class.
For more context: https://github.com/GetStream/stream-chat-android/pull/1269
=> [AND-466] Fix concurrency issue on SubscriptionImpl

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/TokenAuthInterceptor.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/interceptor/TokenAuthInterceptorTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/token/FakeTokenManager.kt
The `AuthTokenInterceptor` detects when the BE returns a token expired error, and automatically calls the `TokenProvider` to fetch a new token. Afterwards, it re-performs the call, but still uses the old token, and NOT the refreshed one. This causes the re-performed call to always fail, even though we have a new valid token.
With this PR, we ensure that the newly fetched token is used for the repeated invocation of the failed call.
- Adds the newly fetched token from the `TokenProvider` as a header to the `Request` before re-performing it.
1. Use the app until the Stream token expires
2. Do some action that would trigger a BE call
3. You should observe only one failed call in the logs (the first 'Invalid token' response) instead of 2
=> [AND-498] Fix new token not sent with the request after refreshing it.

stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessageContent.kt
Fix the unused `MessageRegularContent` component factory.
The `MessageRegularContent` component factory was not being used in the `MessageContent` component.
Which made the component factory being ignored when using `ChatComponentFactory`.
The fixing makes the `MessageContent` use the `MessageRegularContent` component factory only if the deprecated `messageContentFactory` is not used.
Create a custom `ChatComponentFactory`, implement `MessageRegularContent`, and see the message regular content using the custom UI in the `MessagesScreen`
=> [AND-540] Fix MessageRegularContent component factory

CHANGELOG.md, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/picker/AttachmentsPickerDialogFragment.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/picker/factory/system/internal/AttachmentsPickerSystemFragment.kt
Fix #5760 
- `AttachmentsPickerSystemFragment`:
- Changed `config` property to be passed as fragment arguments, making it state-restorable.
- Removed the fragment in `onViewCreated` if `style` is not initialized or `savedInstanceState` is not null, preventing crashes when the fragment is recreated without necessary data.
- `AttachmentsPickerDialogFragment`:
- Added a check in `onDismiss` to ensure `style` is initialized before accessing its properties.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/20440df5-e074-4b5a-93c7-ab0758b8678b" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/1fffcdd1-07f3-47f7-b2b6-565d4ae81e8e" controls="controls" …
=> [AND-552] Fix UninitializedPropertyAccessException in AttachmentsPickerSystemFragment

README.md
This PR fixes a small typo in the README file where the phrase
"Learn the basics of the SDK by by building a simple messaging app"
contains a duplicated word **"by"**. This change removes the duplicate to improve readability.
Improve documentation clarity by fixing a minor typo.
Removed the duplicated word **"by"** in the README file.
No testing required, as this change only affects documentation.
=> fix(README): remove duplicate word 'by' in Chat Tutorial link description

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/DomainMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/EventMapping.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/Mother.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api2/mapping/DomainMappingTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageMapper.kt
Ensure `ChannelInfo` is paresed from the Channel entity when Message doesn't contains it.
Complete: AND-595
=> Ensure `ChannelInfo` is paresed from the Channel entity when Message doesn't contains it

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/ChatSocket.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/SocketFactory.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/SocketFactoryTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/token/FakeTokenManager.kt
To ensure the WS Connection is established with a non-expired token, on #5185 we force a token refresh on any reconnection process. It was fine because ensured it, but there is a corner-case where the token doesn't need to be refreshed even if it is a reconnection process, and it is in the case the app goes to the background.
On this PR, instead of refreshing the token whenever a reconnection process is started, the previous token is expired only in the case a potential token issue happened previously, and only in the case the previous token was expired, a new one is required.
Complete AND-593
=> Expire token only when it is needed

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/pinned/PinnedMessageList.kt
Avoid unnecessary coroutine scope creation inside a LaunchedEffect block and simplify the coroutine launch logic in the PinnedMessagesScreen. 
- This improves code readability and adheres to best practices in Compose.
-  Avoid manually launching nested coroutines when the outer scope already provides the structured, lifecycle-safe coroutine.
- Creating a CoroutineScope just to immediately launch one job inside another coroutine (LaunchedEffect) is unnecessary indirection and adds no value in our case.
- Keep coroutine usage minimal and clear.
Replaced the use of rememberCoroutineScope() within LaunchedEffect with a direct suspend call to collect from viewModel.errorEvents. Since LaunchedEffect already provides a lifecycle-aware coroutine scope, creating an additional scope was redundant. …
=> Remove redundant use of coroutineScope inside of LaunchedEffect.

CHANGELOG.md, stream-chat-android-compose-sample/src/main/AndroidManifest.xml, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/feature/channel/draft/DraftChannelActivity.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/feature/channel/draft/DraftChannelScreen.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/feature/channel/draft/DraftChannelViewModel.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/feature/channel/draft/DraftChannelViewModelFactory.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/channel/DirectChannelInfoActivity.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/channel/GroupChannelInfoActivity.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/chats/ChatsActivity.kt, stream-chat-android-compose-sample/src/main/res/values/strings.xml, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/info/ChannelInfoMemberInfoModalSheet.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/info/DirectChannelInfoScreen.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/info/GroupChannelInfoScreen.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channel/ChannelHeaderViewModelFactory.kt, stream-chat-android-ui-common/api/stream-chat-android-ui-common.api, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/channel/draft/DraftChannelViewAction.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/channel/draft/DraftChannelViewController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/channel/draft/DraftChannelViewEvent.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/channel/info/ChannelInfoMemberViewController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/channel/info/ChannelInfoMemberViewEvent.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/channel/info/ChannelInfoViewController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/channel/info/ChannelInfoViewEvent.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/state/channel/draft/DraftChannelViewState.kt, stream-chat-android-ui-common/src/main/res/values/strings.xml, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/channel/draft/DraftChannelViewControllerTest.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/channel/info/ChannelInfoMemberViewControllerTest.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/channel/info/ChannelInfoViewControllerTest.kt
Support messaging a member from the group channel info screen
Messaging a member from the group channel info screen can enter two possible funnels:
- When there is an existing direct channel between the current user and the clicked member, the app navigates directly to the messages screen.
- When there is no direct channel for those users, the app opens a draft channel screen, and after sending the first message, the channel is converted to a non-draft channel and navigates to the messages screen.
The draft view controller and its state, and events are part of the `ui-common`, so it can be reused by the `ui-components` SDK. The draft screens and view model are not.
<table>
<thead>
<tr>
<th>Starting a new chat</th>
<th>Messaging an existing chat</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video …
=> Message members from the member bottom sheet of channel info screen

stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerController.kt
Perform a small cleanup of the codebase for better readability and adherence to Kotlin conventions:
- Capitalize constant field names to follow naming conventions.
- Remove redundant suspend keyword where it was unnecessary.
- Simplify the constructor parameter by removing redundant class name reference.
=> Capitalize constant fields and remove redundant declarations.

CHANGELOG.md, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/AudioRecordAttachmentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/FileAttachmentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/GiphyAttachmentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/LinkAttachmentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/MediaAttachmentFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/UploadAttachmentFactory.kt
Expose `canHandle` lambda of the attachment factories: `AudioRecordAttachmentFactory`, `FileAttachmentFactory`, `GiphyAttachmentFactory`, `LinkAttachmentFactory`, `MediaAttachmentFactory`, `UploadAttachmentFactory`
=> Expose `canHandle` lambda of the attachment factories

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
Previously, the back action had a check for IME visibility that would do nothing if the IME was visible, potentially making the top bar up button useless when the keyboard was open. This check has been removed.
Related to #5824
- Navigate to a channel
- Click on the message compose input to open the keyboard
- Click on the top bar up button
- The user should navigate back to the channel list screen
- Navigate to a channel
- Click on the message compose input to open the keyboard
- Use the system back button (by gesture or navigation button)
- The keyboard should close
- Use the system back button (by gesture or navigation button)
- The user should navigate back to the channel list screen
Same when entering a thread
=> Fix the top bar up button of the messages screen

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModel.kt
Resolves: https://linear.app/stream/issue/AND-665/optimize-default-channel-search-query-on-android-compose
The default query for the channel search in the Compose SDK is way too complicated, and could cause timeouts for customers with large amounts of data. This PR simplifies the filter and ensures the `autocomplete` query is not run unless the query is at least 3 chars long. 
- Add a guard preventing the `autocomplete` query from running unless it is 3 characters long.
- Remove the `Filters.notExists("name")`
_NA_
1. Set the `ChannelsScreen#searchMode` to `SearchMode.Channels`
2. Enter a query - search should not be performed for the first 2 characters
=> Optimizations for the default channel search logic.

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/poll/PollOptionInput.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/poll/PollSwitchList.kt
Fix the poll creation button to disable when multiple answers has a wrong input.
- Validate poll switch input even on checked state change.
-Using `TextFieldValue` to manage the text input state, which allows us to set the cursor position to the end of the text when the input is first drawn.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/bb28671e-1eb1-432a-a7f2-09f4862d808a" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/211c15d5-0c11-4e14-a1c0-66f6987bbd8e" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
=> Fix Poll creation button enabling on changed change

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/MediaGalleryPreviewActivity.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/mediapreview/MediaGalleryPreviewViewModel.kt
Fixes a bug where the gallery could not always be opened (introduced in this [PR](https://github.com/GetStream/stream-chat-android/pull/5884)).
When opening the screen, if the UI is rendered before the `viewModel.message` emits the new `Message` with its attachment, the activity would be automatically closed
Resolves: https://linear.app/stream/issue/AND-695/media-gallery-not-opening-when-clicking-on-channel
- Removes the check for `message.isDeleted() || message.attachments.isEmpty()` to close the screen from the Compose code
- Introduce a new event-triggered screen closing logic, triggered only after deleting the attachments/message.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/f382ab8a-4cb6-40f …
=> Fix MediaGallery not opened (closed automatically).

CHANGELOG.md, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/DomainMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/UserDtos.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/Mother.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/UserDtoTestData.kt, stream-chat-android-compose-sample/src/main/AndroidManifest.xml, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/feature/channel/list/ChannelsActivity.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/feature/channel/list/ChannelsScreenNavigationDrawer.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/profile/UserProfileActivity.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/profile/UserProfileViewModel.kt, stream-chat-android-compose-sample/src/main/res/values/strings.xml, stream-chat-android-core/api/stream-chat-android-core.api, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/User.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/ChatDatabase.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/user/internal/DatabaseUserRepository.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/user/internal/UserEntity.kt
Support [User Average Response Time](https://www.notion.so/stream-wiki/Display-User-Average-Response-Time-2386a5d7f9f680f497a4f7346a38736b)
Introduces the `avgResponseTime` field to the `User` model and related DTOs and entities.
- Added `avg_response_time` to `DownstreamUserDto`.
- Added `avgResponseTime` to the `User` model, its `Builder`, and the `compareTo` logic.
- Added `avgResponseTime` to `UserEntity`.
- Updated database version to `89`.
- Mapped `avg_response_time` in `DomainMapping` and `DatabaseUserRepository`.
- Included `avg_response_time` in test data for `UserDtoTestData`.
Introduces the User Profile screen to the sample app, which shows the Average Response Time.
> [!IMPORTANT]
>  `User response time` must be enabled in Nessy (already enabled in the app used by the sample) …
=> Support User Average Response Time

stream-chat-android-compose-sample/src/demo/java/io/getstream/chat/android/compose/sample/ui/StartupActivity.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatApp.kt
(Demo app) Ensure that the user is connected in the application creation, not in the `StartupActivity`
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/6c808a88-aa13-46df-859a-ffdd290807e8" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/bb2db432-a9e5-4cba-a964-0ff4642f882d" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Trigger a configuration change (for example, by removing a permission), and resume the app from the recent apps.
=> (Demo app) Ensure user connection on app initialization after a configuration change

CHANGELOG.md, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/MessagesActivity.kt, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/MediaAttachmentPreviewContent.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/attachments/images/ImagesPicker.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerSystemTabFactory.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerTabFactories.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/AttachmentPickerTheme.kt
- Introduce `checkIconBackgroundColor`, `checkIconTintColor`, and `contentColor` to `AttachmentPickerTheme`.
=> Introduce more customizable colors to the `AttachmentPickerTheme`

CHANGELOG.md, stream-chat-android-client-test/src/main/java/io/getstream/chat/android/client/test/Mother.kt, stream-chat-android-client-test/src/main/java/io/getstream/chat/android/client/test/utils/TestDataHelper.kt, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/EventMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/EventDtos.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api2/mapping/EventMappingTestArguments.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/extensions/internal/ChannelExtensionsTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/chat/ChatEventHandler.kt
The `ChannelHiddenEvent` and `ChannelVisibleEvent` now contains a `Channel` entity.
When an userA block another userB, any 1:1 channel they both have are blocked and `ChannelHiddenEvent` is received. With the new change the customer can know if the channel is hidden because the "block action" or because "hide action" and configure different behavior.
Complete: AND-716
=> Add `Channel` entity to `ChannelHiddenEvent` and `ChannelVisibleEvent`

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/poll/PollOptionList.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/picker/poll/CreatePollViewModel.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/picker/poll/OptionsAdapter.kt
Filter out Poll Options differing only on whitespaces
Fix: AND-717
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/9b70b83a-69dd-431b-af26-a51b262e99cd" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/a7262bb1-ae19-4ba8-8690-873501560d23" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/211b96b7-4df2-4632-ab42-e0f427bcb2cc" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/8e86e9af-fb5f-4553-b33b-eedc783e6aae" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
=> Filter out Poll Options differing only on whitespaces

CHANGELOG.md, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/build.gradle.kts, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitCdnApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/CompletableResponse.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/FileUploader.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/StreamFileUploader.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/ProgressCallback.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientChannelFileUploaderTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientStandaloneFileUploaderTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api2/MoshiChatApiTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/uploader/StreamFileUploaderTest.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/profile/UserProfileScreen.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/profile/UserProfileUtils.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/profile/UserProfileViewEvent.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/profile/UserProfileViewModel.kt
Support upload standalone file/image endpoints as per https://github.com/GetStream/stream-chat-js/pull/1564
Introduced `ChatClient.uploadFile`, `ChatClient.deleteFile`, `ChatClient.uploadImage`, and `ChatClient.deleteImage`, to upload/delete files/images that are not related to any channel. 
```kotlin
chatClient.uploadImage(
file = anImageFile,
).enqueue()
```
Added a functionality to upload the profile picture to the Compose demo app.
> [!NOTE]
> All the updated profile pictures are reset on a new app cold launch or login, so that we keep the original avatars of the demo app.
> [!IMPORTANT]
> It was set `-Xjvm-default=all` to the Kotlin compiler of the client module, so that default implementations of interfaces are available in **Java**, e.g., using the `ProgressCallback` doesn't …
=> Support upload file/image standalone endpoints

CHANGELOG.md, stream-chat-android-client-test/src/main/java/io/getstream/chat/android/client/test/Mother.kt, stream-chat-android-client-test/src/main/java/io/getstream/chat/android/client/test/utils/TestDataHelper.kt, stream-chat-android-client/api/stream-chat-android-client.api, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/DomainMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/EventMapping.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/ChannelDtos.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/EventDtos.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/state/ChannelState.kt, stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api2/mapping/EventMappingTestArguments.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/channel/ChannelClientSubscribeTest.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/extensions/ChatEventEnrichmentsTests.kt, stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt, stream-chat-android-core/api/stream-chat-android-core.api, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/Channel.kt, stream-chat-android-core/src/main/java/io/getstream/chat/android/models/ChannelData.kt, stream-chat-android-core/src/testFixtures/kotlin/io/getstream/chat/android/Mother.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/ChatDatabase.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/ChannelEntity.kt, stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/ChannelMapper.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventHandlerSequential.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelLogic.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogic.kt, stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/channel/internal/ChannelMutableState.kt, stream-chat-android-state/src/test/java/io/getstream/chat/android/state/plugin/logic/querythreads/internal/QueryThreadsLogicTest.kt
Expose Channel Messages Count.
This property has been added to multiple entities:
- `NewMessageEvent.channelMessageCount`
-  MessageDeletedEvent.channelMessageCount`
- `ChannelState.messagesCount`
- `Channel.messagesCount`
Complete: AND-721
=> Expose Channel Messages Count

CHANGELOG.md, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/channel/attachments/ChannelMediaAttachmentsActivity.kt, stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/chats/ChatsActivity.kt, stream-chat-android-compose/api/stream-chat-android-compose.api, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channel/ChannelAttachmentsViewModel.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channel/ChannelAttachmentsViewModelFactory.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/channel/attachments/ChannelAttachmentsViewController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/utils/StreamFileUtil.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/channel/attachments/ChannelAttachmentsViewControllerTest.kt, stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/shared/media/ChatInfoSharedMediaFragment.kt, stream-chat-android-ui-components/api/stream-chat-android-ui-components.api, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/gallery/internal/AttachmentGalleryImagePageFragment.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/channel/ChannelAttachmentsViewModel.kt, stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/channel/ChannelAttachmentsViewModelFactory.kt
- XML was not showing media attachments that contain `thumbUrl` only.
- Compose was showing link attachments where it should not.
The fix creates a unified local filter in the view controller used for both SDKs.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/dba050d1-6002-4c99-8571-1e5293a8ce35" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/94cccd2f-88fd-4b4c-aa65-89a5e715409e" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
=> 6.24.0 release testing

CHANGELOG.md, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/Messages.kt, stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/state/messages/list/MessageListItemState.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/state/messages/list/MessageListItemStateTest.kt
- Add a unique identifier for `MessageListItemState`.
- Add `distinctUntilChanged` before mapping the message list state to ensure that the reversed message list is only recreated when the actual state changes, not on every emission.
Apply the provided patch and look for log entries of `alor: MessageListStartOfTheChannelItemContent` when entering a channel, scrolling to the very first sent message.
<details>
<summary>MessageListStartOfTheChannelItemContent recompositions</summary>
```
Subject: [PATCH] MessageListStartOfTheChannelItemContent recompositions
---
Index: stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatComponentFactory.kt
<+>UTF-8 …
```
=> Fix recompositions of MessageListStartOfTheChannelItemContent

CHANGELOG.md, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/MessageListController.kt, stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/UnreadLabelCalculator.kt, stream-chat-android-ui-common/src/test/kotlin/io/getstream/chat/android/ui/common/feature/messages/list/UnreadLabelCalculatorTest.kt
Fixes the following bugs related to the unread separator:
- Sending a message while offline is marked as unread after syncing
- Uncommitted pending messages are marked as unread after re-entering the channel
Resolves: https://linear.app/stream/issue/AND-720/pending-messages-arent-marked-as-read-on-backend-but-adding-them-to
And related to: https://linear.app/stream/issue/AND-729/ensure-pending-message-is-marked-as-read-after-it-was-committed-server
Extracts the unread label calculation logic from the `MessageListController` to a `UnreadLabelCalculator` class
Adds specific handling for cases where the `lastReadMessageId` from the BE doesn't reflect the local state of the unread messages (syncing a message after sending it offline or having an uncommitted pending message).
The details of …
=> Fix several unread separator bugs.
