library/src/main/java/com/getstream/sdk/chat/enums/EventType.java
library/src/main/java/com/getstream/sdk/chat/model/Channel.java
library/src/main/java/com/getstream/sdk/chat/model/Event.java
library/src/main/java/com/getstream/sdk/chat/rest/core/ChatChannelEventHandler.java
library/src/main/java/com/getstream/sdk/chat/rest/core/ChatEventHandler.java
library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelListViewModel.java
library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java

Channel events handlers include the channel as parameter; the client does all the magic and makes sure the channel is known (queuing up to solve races is left as TODO).
This should make handlers safer and remove lot of boilerplate code
Before:
```java
private void updateChannelMessage(Event event) {
Channel channel = getChannelByCid(event.getCid());
if (channel != null) {
channel.handleMessageUpdatedOrDeleted(event);
}
}
```
After:
```java
private void updateChannelMessage(Channel channel, Event event) {
channel.handleMessageUpdatedOrDeleted(event);
}
```

include channel to event handler and do the null checks in the handler

---

library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java
library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java
library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelListViewModel.java
library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java
sample/src/main/java/io/getstream/chat/example/ChannelActivity.java
sample/src/main/java/io/getstream/chat/example/CustomMessageInputView.java

For analytics and toast/UI purposes its nice if you can set a SendMessage listener on the MessageInputView. 
This pull request adds support for that by removing this line:
```
setOnSendMessageListener(viewModel);
```
That line was overwriting listeners set by users of this library.
It also simplifies the listener system from a double listener system to a single listener setup, making the code easier to read.

Message input view

---

library/src/main/java/com/getstream/sdk/chat/model/Channel.java
library/src/main/java/com/getstream/sdk/chat/rest/adapter/ChannelGsonAdapter.java
library/src/main/java/com/getstream/sdk/chat/rest/controller/APIService.java
library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
library/src/main/java/com/getstream/sdk/chat/rest/interfaces/DeleteChannelCallback.java
library/src/main/java/com/getstream/sdk/chat/rest/interfaces/DeviceCallback.java
library/src/main/java/com/getstream/sdk/chat/rest/response/DeleteChannelResponse.java
library/src/main/java/com/getstream/sdk/chat/storage/ChannelsDao.java
library/src/main/java/com/getstream/sdk/chat/storage/Storage.java
library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelListViewModel.java
sample/src/main/java/io/getstream/chat/example/BaseApplication.java

- add field `deletedAt` to Channel model. Also, add it to gson adapter.
- add API method to `Client` to delete a channel.
- add method to `Channel` to delete this channel.
- add method to `ChannelListViewModel` to delete channel. _I am not sure this method is needed. Client can call Channel.delete or Client.deleteChannel directly._
- add handling of the event `channel.deleted`. 
- add method to `Storage` to delete the channel from local DB.

Add delete channel feature

---

library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java
sample/build.gradle
sample/src/main/java/io/getstream/chat/example/CustomMessageInputView2.java

adds the prepareMessage function to the MessageInputView, solves 
https://github.com/GetStream/stream-chat-android/issues/28
example usage
```
public class CustomMessageInputView2 extends MessageInputView {
public CustomMessageInputView2(Context context) {
super(context);
}
public CustomMessageInputView2(Context context, AttributeSet attrs) {
super(context, attrs);
}
@Override
public Message prepareMessage(String input) {
Message m = super.prepareMessage(input);
// note that you typically want to use custom fields on attachments instead of messages
// attachment UI is easier to customize than the message UI
HashMap<String, Object> extraData = new HashMap<>();
extraData.put("mycustomfield", "123");
m.setExtraData(extraData);
return m;
}
}
```

made it easier to customize the message

---

library/src/main/java/com/getstream/sdk/chat/EventSubscriberRegistry.java
library/src/main/java/com/getstream/sdk/chat/model/Channel.java
library/src/main/java/com/getstream/sdk/chat/rest/EventHandler.java
library/src/main/java/com/getstream/sdk/chat/rest/EventHandlerThread.java
library/src/main/java/com/getstream/sdk/chat/rest/WebSocketService.java
library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java

We have Client, Channel, WebsocketService, ChannelState, ClientState
Threads are used for websocket events `EventHandlerThread` and the `onSetUserCompleted`
There are some possible race conditions:
- code that adds/calls event handlers (currently done using synchronized methods, which is not entirely right since it only affects the individual method)
- reading and writing on the channel/channelState objects
Looks like https://github.com/GetStream/stream-chat-android/issues/106 is related
FIXED:
- websocket events could be received before the thread was ready to receive them
-- start the thread before connecting the websocket
-- setup the handler logic on thread creation instead of thread start
(Possibly related: https://github.com/GetStream/stream-chat-android/issues/105)
- Thread safety …

Client robustness WIP

---

library/src/main/res/layout/stream_view_message_input.xml
library/src/main/res/values/colors.xml

- Maxlines 7 for Input text.
- Uploading an image + text

fix message input lines(max 7) and image select with text message

---

library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java
library/src/main/java/com/getstream/sdk/chat/rest/core/ClientState.java

Disconnection sets user to null, but NPE is not checked.

Fix disconnection NPE.

---

library/src/main/java/com/getstream/sdk/chat/rest/response/ErrorResponse.java

`ErrorResponse.parseError` might throw exception if response doesn't contain proper body. That's the case for >=4xx errors.

Catch error body parsing errors

---

library/src/main/java/com/getstream/sdk/chat/view/ChannelHeaderView.java

- Fixed the position issue of channel Header Title when Last active is hidden

Fix/Channel Header Title position issue when Last active is hidden

---

docs/ChannelHeader.md
docs/ChannelList.md
docs/MessageInput.md
docs/MessageList.md
library/src/main/java/com/getstream/sdk/chat/adapter/AttachmentViewHolderFile.java
library/src/main/java/com/getstream/sdk/chat/view/MessageListViewStyle.java
library/src/main/res/values/attrs.xml

You can set custom fonts for the entire library or for specific UI components.
1. First of all you have to put your own font file(s) (.ttf, .otf,…) in your `assets` folder or `res`.
2. Setup custom font for whole library
You can register your custom font by `StreamChat.initStyle(StreamChatStyle style)`
```
StreamChat.initStyle(
new StreamChatStyle.Builder()
.setDefaultFont(R.font.your_custom_font)                
//.setDefaultFont("fonts/your_custom_font.ttf")
.build()
``` 
3. Setup custom font to specific UI components
You can setup custom fonts specific UI components of `ChannelListView` , `ChannelHeaderView`, `MessageListView` and `MessageInputView`
For example, if you want to set custom font of message text, you can follow the code below
```xml …
```

Update/ReadMe for Custom Font

---

library/src/main/java/com/getstream/sdk/chat/adapter/AttachmentViewHolderMedia.java
library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java
library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java
library/src/main/res/layout/stream_item_attach_media.xml

https://stream-io.atlassian.net/browse/CAS-45
- add progressBar/ disable buttons while giphy send API response
- if error response, shows error message

CAS-45/Giphy: send and shuffle buttons do not work

---

CHANGELOG.md
build.gradle
library/src/main/java/com/getstream/sdk/chat/rest/adapter/ReactionGsonAdapter.java

Double can't be casted to Integer.
```
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
```

Fix score double casting error

---

library/src/main/java/com/getstream/sdk/chat/adapter/ChannelItemPayloadDiff.java

I want to have a custom implementation extended from BaseChannelListItemViewHolder
For it I need to have public ChannelItemPayloadDiff

Make ChannelItemPayloadDiff public

---

CHANGELOG.md
library/build.gradle
library/src/main/java/com/getstream/sdk/chat/utils/LlcMigrationUtils.java
library/src/main/java/com/getstream/sdk/chat/view/AvatarView.kt

When a channel or user has an empty name, the text to be rendered on the bitmap that contains the initials of the name has a size of 0. This size was used as the radio of the bitmap be center the name on it, but a bitmap can't have a size of 0, so it needs to have a default value on the case that user/channel doesn't have an associated name.
Fix #478

Fix default avatar with an empty name

---

CHANGELOG.md
build.gradle
library/build.gradle

* Updates livedata to 0.6.5 version which fixes NotificationMarkReadEvent crash
* Adds mavenLocal() repository
* Fixes: https://github.com/GetStream/stream-chat-android/issues/536

Fix / Update livedata dependency

---

sample/src/main/kotlin/io/getstream/chat/sample/feature/channels/ChannelsFragment.kt

* Using navigation component requires a manual call to `activity.finish()` in order to close the app on back press. This PR handles back press in ChannelsFragment

Close app on back press at home screen

---

library/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.java

There was a bug because we were comparing the full user object from the message and it is keeping some status (`online`, `lastActive`...) that are not properly sync with the `currentUser` stored on the app. Maybe we should split the user object in the future to be consistent about those attributes.
So, now to decide if a message is mine or not, we only check the `user.id` that should be unique

Fix UI of messages of the current user

---

CHANGELOG.md
library/build.gradle
library/src/main/java/com/getstream/sdk/chat/view/channels/ChannelsView.kt

Jira link: 
https://stream-io.atlassian.net/browse/CAS-176
Adds missing `ChannelsView.setViewHolderFactory(factory: ChannelViewHolderFactory)` function to `ChannelsView`.
Related: https://github.com/GetStream/stream-chat-android/issues/571

[CAS-176] Add ChannelsView.setViewHolderFactory() function

---

library/src/main/AndroidManifest.xml
library/src/main/java/com/getstream/sdk/chat/utils/frescoimageviewer/FrescoContentProvider.kt
versions.gradle

Fresco library needs to be initialized before starting to use the views they provide.
I'm using a ContentProvider to start it because it is instantiated before any other part of the code

Init Fresco library

---

library/src/main/java/com/getstream/sdk/chat/adapter/ReactionDialogAdapter.java

The cid property of Message entity is not initialized sometimes, we need to standardize the structure of our entities to be sure we are working always with the right data. In the meantime we need to add this kind of check to our code

Use proper CID from message when add/remove reactions

---

library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.kt

Setting KeyboardEventListener inside `init` block is not safe, because it's initialization looks for host Activity under the hood and `init` is being called before Activity `onCreate` method.

Move KeyboardEventListener initialization to onFocusChangeListener

---

library/build.gradle

Adding RecyclerView with `implementation` configuration results  crash in `MessageView`  unless RecyclerView dependency is manually added to the project

Change RecyclerView dependency configuration to api

---

library/src/main/java/com/getstream/sdk/chat/view/ChannelHeaderViewStyle.kt

Some of the default values were set directly to the appropriate fields during initialization and some of them were available only when using `get*()` methods. This was misleading because some of the fields had `internal` modifier which makes them accessible inside the library code. Using those fields through `internal` property led to missing drawables and strings.

Change the way of setting default values in ChannelHeaderViewStyle

---

library/build.gradle

Missing fragmentKtx library causes `java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode` crash on some Android devices when trying to open the camera from MessageInputView

Add missing fragment ktx dependency

---

library/src/main/java/com/getstream/sdk/chat/ChatSocketListener.kt
library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItem.kt
library/src/main/java/com/getstream/sdk/chat/utils/MessageInputController.kt
library/src/main/java/com/getstream/sdk/chat/utils/UploadManager.kt
library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.kt
library/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModel.kt
library/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
library/src/main/kotlinX/Primitives.kt

`Primitives` file already exists on LiveData module and it was giving an error when it is used into this project.
Moving it to an internal package fixes it.
Fixes: #603

Move Primives files to another package to avoid duplicate class error

---

library/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModel.kt

Adding @JvmField annotation improves UX when using SDK in Java because user can get those values directly from `ChannelListViewModel` instead of `ChannelListViewModel.Companion`

Add JvmField annotation to default filter and sort type inside ChannelListViewModel

---

library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItem.kt

The task was to extract hardcoded text from this class, but these strings are not displayed on the UI. They are only being used to calculate a checksum, which then in turn is used to provide a unique stable ID for `RecyclerView` items.
The changes made here simplify this ID generation, removing the very long `this.toString()` prefix from the checksum calculation, and adding more obvious hardcoded IDs for the _typing_ and _thread separator_ items. IDs will still stay unique as before, but their generation is simpler and quicker.
---
Note: In the long term, this stable ID mechanism will be made obsolete anyway, as using `DiffUtil` and [`RecyclerView.ListAdapter`](https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter) will replace it.

[CAS-230] Revise hardcoded string IDs in MessageListItem, simplify checksum calculation

---

CHANGELOG.md
library/src/main/java/com/getstream/sdk/chat/adapter/AttachmentListItem.kt
library/src/main/java/com/getstream/sdk/chat/adapter/AttachmentListItemAdapter.java
library/src/main/java/com/getstream/sdk/chat/adapter/AttachmentViewHolder.java
library/src/main/java/com/getstream/sdk/chat/adapter/AttachmentViewHolderFile.java
library/src/main/java/com/getstream/sdk/chat/adapter/AttachmentViewHolderMedia.java
library/src/main/java/com/getstream/sdk/chat/adapter/BaseAttachmentViewHolder.java
library/src/main/java/com/getstream/sdk/chat/adapter/MessageViewHolderFactory.kt

Wraps the `Attachment` network model into the `AttachmentListItem` class, so that it's not used directly in `AttachmentListItemAdapter`. This allows us to add extra properties to the list item later, if needed.
See previous discussion in https://github.com/GetStream/stream-chat-android/pull/614#discussion_r484452890

Introduce AttachmentListItem wrapper class

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/getstream/sdk/chat/Dependencies.kt
library/src/main/java/com/getstream/sdk/chat/ChatImpl.java
library/src/main/java/com/getstream/sdk/chat/ChatSocketListener.kt

Shouldn't be merged before the release of LiveData which will contain events changes in LLC (https://github.com/GetStream/stream-chat-android-client/pull/75)

Adjust ChatSocketListener to new events(NewMessageEvent, NotificationMarkReadEvent, NotificationMessageNewEvent) properties

---

library/src/main/java/com/getstream/sdk/chat/adapter/AttachmentViewHolderFactory.kt
library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java

https://github.com/GetStream/stream-chat-android/pull/640 merged yesterday has introduced a crash when trying to render any attachment, as a `lateinit var` was not injected. This PR fixes the issue. 
(+ a style inconsistency compared to the message factory)

[Bugfix] Set ListenerContainer in AttachmentViewHolderFactory

---

library/src/main/java/com/getstream/sdk/chat/adapter/BaseMessageListItemViewHolder.kt
library/src/main/java/com/getstream/sdk/chat/adapter/DateSeparatorViewHolder.kt
library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemAdapter.kt
library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemViewHolder.kt
library/src/main/java/com/getstream/sdk/chat/adapter/ThreadSeparatorViewHolder.kt
library/src/main/java/com/getstream/sdk/chat/adapter/TypingIndicatorViewHolder.kt

Removes the last unnecessary parameter from the ViewHolder binding methods, leaving just the `MessageItem` itself.

[CAS-231] Remove position parameter from ViewHolder binding method

---

library/src/main/java/com/getstream/sdk/chat/ChatImpl.java

Forgot to check for nullability of the handler in Java code, added a check now. If `null` handler is passed in from the builder, the default one is used internally instead.

Check for null values of navigationHandler

---

library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemAdapter.kt
library/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemDiffCallback.kt
library/src/test/java/com/getstream/sdk/chat/adapter/MessageListItemDiffCallbackTest.kt

https://stream-io.atlassian.net/browse/CAS-282
The [`ListAdapter`](https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter) class manages the list of items for us, and it uses [`AsyncListDiffer`](https://developer.android.com/reference/androidx/recyclerview/widget/AsyncListDiffer) internally, so the diff is calculated on a background thread.

[CAS-282] Use ListAdapter in MessageListItemAdapter instead of using DiffUtil directly

---

library/src/test/java/com/getstream/sdk/chat/utils/StartStopBufferTest.kt
library/src/test/java/com/getstream/sdk/chat/utils/TestCoroutineExtension.kt
library/src/test/java/com/getstream/sdk/chat/viewmodel/CreateChannelViewModelTest.kt

Introduces a new `TestCoroutineExtension` class that can be used to easily use test coroutine constructs (dispatchers and scopes) in unit tests.
Also moves some of the mocking logic to different methods than where we used them before: setting and reseting the Main dispatcher now only happens once for each test class, and coroutines are cleaned up after every individual test.
Usage example (note that `@JvmField` is required to make the field storing the extension public for JUnit):
```kotlin
class MyTestThatNeedsCoroutines {
@JvmField
@RegisterExtension
val testCoroutines = TestCoroutineExtension()
@Test
fun `I should be able to run coroutines`() {
testCoroutines.scope.runBlockingTest { 
withContext(testCoroutines.dispatcher) {
}
}
}
}
```

Create JUnit5 extension for coroutine tests

---

CHANGELOG.md
library/src/main/java/com/getstream/sdk/chat/ChatImpl.java

Clean up `ChatDomain` initialization in `ChatImpl.setUser()` function. 
Initialize `ChatDomain` instance only after user was set in `ChatClient` successfully.

Improve chat builder

---

library/src/main/java/com/getstream/sdk/chat/utils/Utils.java
library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java
library/src/main/java/com/getstream/sdk/chat/view/dialog/MessageMoreActionDialog.kt
library/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputView.kt

Changed the keyboard utility methods taking an `Activity` as a parameter to take a `Context` instead, as it's often enough to perform the action.
Added two new utilities that take `View` instances as parameters, as we usually invoke these methods from our custom Views.
This fixes some crashes where our custom Views are used in Fragments that have non-Activity `Context`s.
- [] ~Changelog updated with client-facing changes~
- [] ~Comparison screenshots added for visual changes~

Fix keyboard utility methods

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/getstream/sdk/chat/Dependencies.kt
library/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputView.kt

Bugfix for issue #694 
The `registerForActivityResult` method had a behaviour change in recent Activity / Fragment KTX versions (in ``, specifically) where callbacks can no longer be registered after the Activity got into a `STARTED` state. Instead of relying on the Activity's lifecycle, we can register and unregister our callbacks dynamically, by accessing the underlying ActivityResultRegistry directly.

Fix crash caused by registering for Activity results too late

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/getstream/sdk/chat/Dependencies.kt
library/build.gradle
library/src/main/java/com/getstream/sdk/chat/ImageLoader.kt
library/src/main/java/com/getstream/sdk/chat/adapter/viewholder/attachment/AttachmentViewHolderMedia.kt

- Replace Glide with Coil in AttachmentViewHolderMedia
- Improve showing loading indicator on media
Glide sometimes has problems with GIFs loading (probably it cannot decode them) and it doesn't provide any helpful exception. On the other hand, Coil renders everything correctly and its performance is much better comparing to Glide
Describe what this PR changes, why we're making the change, how it should be tested...

[CAS-292] Fix GIFs loading issues

---

library/src/main/java/com/getstream/sdk/chat/view/common/Extensions.kt
library/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputView.kt

Found more crashes happening when using Hilt & MessageInputView. Hilt makes the view's context a FragmentContextWrapper, so casting to an activity causes a crash.
~- [ ] Changelog updated with client-facing changes~
~- [ ] Comparison screenshots added for visual changes~

Message input context wrapper

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/getstream/sdk/chat/Dependencies.kt

Update Offline Support to the [last version](https://github.com/GetStream/stream-chat-android-livedata/releases/tag/0.8.6)
~- [ ] Comparison screenshots added for visual changes~

Update Offline Support version

---

library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelHeaderViewModel.kt
library/src/main/java/com/getstream/sdk/chat/viewmodel/CreateChannelViewModel.kt
library/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
library/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
library/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt

https://stream-io.atlassian.net/browse/CAS-272
- Verified that viewmodel's constructors are not doing any heavy lifting
- Removed redundant `GlobalScope.launch` and `viewModelScope.launch` invocation from the viewmodels
- Replaced `execute()` with `enqueue()` in `MessageListViewModel.onThreadModeEntered()` not to block the main thread

CAS-272 Review viewmodels

---

CHANGELOG.md
library/src/main/java/com/getstream/sdk/chat/model/ModelType.kt
library/src/main/java/com/getstream/sdk/chat/utils/GifEditText.java
library/src/main/java/com/getstream/sdk/chat/utils/StorageHelper.kt
library/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputView.kt

- Fix selecting gifs from the keyboard
- Add missing file extension when creating cached files (some files (e.g. GIFs selected from keyboard) don't have proper extension in its title so we need to add it manually otherwise, they will be sent as files instead of images)
- Add milliseconds to the cached file name to prevent files from overriding
- [] New code is covered by unit tests

[CAS-295] Fix sending gifs from keyboard

---

CHANGELOG.md
library/src/main/java/com/getstream/sdk/chat/view/common/Extensions.kt
library/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputView.kt

The `ensure` extension introduced in https://github.com/GetStream/stream-chat-android/pull/699 was meant to make sure that we always fetch an `Activity` in our Views through `context`, even if it returns a wrapper around the `Activity` first (e.g. when using Dagger Hilt). Its implementation checked if the current View `Context` is a `ContextWrapper`, and if it is, it used its base context instead.
The issue is that `AppCompatActivity` itself is a `ContextWrapper`, so in this case, we used its base, a `ContextThemeWrapper` instead, which we then proceeded to cast to `Activity` types.
We already removed another usage of `ensure`, as it was causing crashes, see here https://github.com/GetStream/stream-chat-android/pull/703#pullrequestreview-510736883
This PR replaces its remaining usage with …

Replace ensure extension with recursive search for Activity

---

library/src/main/java/com/getstream/sdk/chat/view/MessageListView.kt

`MessageListItem` wasn't being casted properly. In the case that it was different than `MessageItem` it would crash

Fix wrong casting

---

stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/CommandMentionListItemAdapter.java

https://stream-io.atlassian.net/browse/CAS-324
This was an incorrect cast to a supertype of databinding bindings instead of viewbinding bindings, which produced a crash

[CAS-324] Remove leftover reference to a databinding type

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImpl.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplTest.kt
stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/feature/channels/ChannelsFragment.kt
stream-chat-android-sample/src/main/res/values/strings.xml
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
stream-chat-android/src/test/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModelTest.kt

[CAS-303](https://stream-io.atlassian.net/browse/CAS-303)
Removing hide channel from list when user requests it. Like this:
If a new message is send to this channel and the channel is listening to it, the channel will reaper. **But there's still a problem that I need some changes in the backend to solve**:
The back end does not return the hidden channels, so the app doesn't listen for hidden channels because they are not returned in the query. So, if a user hides the channel and leaves the app, the channel won't be revealed when new messages come because this channel will not be returned by the new query. To solve this the backend should return **all the channels to the user, including the hidden ones.** Anyways I think this PR can be merged while we wait for the backend to change this …

CAS-303/hide channel fix2

---

CHANGELOG.md
stream-chat-android-client-CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatClientConfig.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientImplTest.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/Chat.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/ChatImpl.java

- Add fileUploader method to ChatClient.Builder
- Add fileUploader property to Chat.Builder
- Fix setting Nullable Logger
There is no need to provide builder methods to `ChatDomain.Builder` because it takes `ChatClient` as a parameter

[CAS-312] Add possibility to replace default FileUploader:

---

stream-chat-android-client/src/test/java/io/getstream/chat/android/client/helpers/AttachmentHelperTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/ChatParserImplTest.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventAdapterTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/PaginationTest.kt
stream-chat-android/src/test/java/com/getstream/sdk/chat/utils/LlcMigrationUtilsTest.kt
stream-chat-android/src/test/java/com/getstream/sdk/chat/viewmodel/ChannelHeaderViewModelTest.kt
stream-chat-android/src/test/java/com/getstream/sdk/chat/viewmodel/CreateChannelViewModelTest.kt

Referencing the method name in a comment
- Makes it available for navigation in the IDE (it doesn't resolve the methods in the string parameter of `@MethodSource`)
- Prevents the source methods from being marked as unused, so we don't attempt removing them

Add method links for parameterized tests

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/service/sync/OfflineSyncFirebaseMessagingService.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/ChatImpl.java

https://github.com/GetStream/stream-chat-android/pull/764 changed `lateinit` `instance` properties to nullable. Turns out we were relying on `lateinit` sometimes throwing an `UninitializedPropertyAccessException`.
This PR adds a new method for checking whether the `ChatClient` or `ChatDomain` is already set. (This API could be marked internal or opt-in later, for now, it's probably fine for it to be `public`.)

Fix crash caused by relying on UninitializedPropertyAccessException

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/AnonymousApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/AuthenticatedApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitAnonymousApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitCdnApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt

Introduces the `AnonymousApi` and `AuthenticatedApi` annotations for deciding whether a Retrofit API requires authentication.

Add AnonymousApi and AuthenticatedApi annotations

---

CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/GetChannelControllerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/GetChannelImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/UseCaseHelper.kt

Adding a separate use case for getting `ChannelController`. We shouldn't use `watchChannel` use case for that because it triggers unneeded calls to API and offline storage.

[CAS-350] Add GetChannelController use case

---

CHANGELOG.md
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/EndlessScrollListener.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/MessageListView.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModelBinding.kt
stream-chat-android/src/main/res/values/attrs.xml
stream-chat-android/src/main/res/values/values.xml

Added load more threshold. As a consequence, if the user scrolls message list up at a reasonable speed, the scrolling experience will be seamless.
Load more LiveData does not contribute to the state of `MessageListItemWrapper` for performance reasons. We don't want the diff to be calculated too often.

Improve message list pagination

---

CHANGELOG.md
stream-chat-android/src/main/java/com/getstream/sdk/chat/style/TextStyle.kt

https://stream-io.atlassian.net/browse/CAS-383
This PR fixes fetching color value from TypedArray.

[Bug] Fix fetching color value from TypedArray

---

CHANGELOG.md
stream-chat-android/src/main/java/com/getstream/sdk/chat/DefaultBubbleHelper.java
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/viewholder/message/configurators/IndicatorConfigurator.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/BaseStyle.java
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/MessageListView.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/MessageListViewStyle.java
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/ReadStateView.java
stream-chat-android/src/main/res/values/attrs.xml

Read state indicator visibility attr was not handled in the code. This PR fixes the setting of its visibility.

[Bug] Fix read state indicator visibility attr handling

---

.github/workflows/automerge.yml
.github/workflows/build-lint-test.yml

Adds a new GitHub actions workflow using [pascalgn/automerge-action](https://github.com/pascalgn/automerge-action), and changes the existing build/lint/test workflow so that it only runs on `push` events. 
This will do two things in the repo:
- Keep all PR branches up-to-date by rebasing them on the target branch when it changes (can be prevented by adding a `no-autorebase` label, if necessary for some reason).
- Automatically merge PRs that have passed the pipeline checks and got the required review, if they're labeled with `automerge`.
See the config in the modified file for more details.

Add automerge GitHub Actions workflow

---

stream-chat-android/src/main/java/com/getstream/sdk/chat/view/channels/ChannelListView.java
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/channels/ChannelsView.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModelBinding.kt

Steps to reproduce the issue:
1. Scroll channel list to the end
2. Navigate to any channel
3. Go back to the channel list and observe that the list is empty
This happens because the last state we receive on the channel list page is `EndPageReached`. When going back to that page, the UI is recreated with `EndPageReached` state and we observe an empty screen.
The root of the problem is that we try to implement our ViewModels in MVI/Redux style with a single `State` which is enough to recreate the whole UI at any point of time. Unfortunately, some of the `State` classes are more like events (e.g. `NavigateToLoginScreen`, `EndPageReached`) and they lack important bits of information to recreate the UI (e.g. when going back to the previous screen).
We have 2 options:
- Implement `State` …

Fix empty screen when returning back to channels

---

CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImpl.kt

When manual checking I noticed that if we didn't query online at startup and ran query when connection was recovered, then we didn't store channel query. That's why after rerun of app we don't get channels from local repo.

Store query entity in run query online flow.

---

.github/workflows/build-and-test.yml
.github/workflows/pr-checks.yml

- Supposedly fixes our problems with the automerge plugin, where it doesn't re-trigger PR workflows after it auto-rebases a branch (by changing the `push` trigger to `pull_request`)
- Adds a new workflow that builds both debug and release variants and executes tests, only on the `develop` and `master` branch, so we always see an up-to-date build status for those branches

Revise GitHub actions workflows

---

stream-chat-android-sample/src/release/kotlin/io/getstream/chat/sample/application/ExtraDependenciesImpl.kt

Fixes release builds (was failing before due to different method names in the `debug` and `release` source set)

Fix release build

---

stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/application/App.kt

We were initializing our SDK twice. The one from `App` class is not needed, because at this time we doesn't know which APIKey is going to be used

[CAS-381] Remove initialization from App::onCreate

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseConnectedIntegrationTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDisconnectedIntegrationTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDomainTest.kt

Some of our LiveData was been used from a background thread when calling `setValue()`, and it is not allowed.
There were other race-conditions with our eventListeners and the properties that should be initialized but weren't. All Listener Initialization has been moved after the user is set

[CAS-382] [CAS-388] Fix livedata updated in background thread

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDatabase.kt

Speed up of messages fetching from DB. 
I noticed that sometimes message queries from DB for channel takes some long time. At my slow device _(1 CPU, 750 MB RAM_) for one channel it takes **246.570539 ms** in average. And also I see we have already added indices for table for its' selection params.
I looked at SQLite manual and found very important setup parameter `PRAGMA synchronous` (docs available [here](https://www.sqlite.org/pragma.html#pragma_synchronous)). It defines how DB ensures its' sync via multithreaded transactional environment (it needs for critical situations as OS crashes). Since Lollipop SQLite uses `WAL mode` for journaling (faster then the previous `PERSIST mode`). And with `WAL` we don't need `FULL synchronous mode` it's too strict. We can apply `NORMAL synchronous …

Add NORMAL synchronous mode for SQLite

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitCallAdapterFactory.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/call/RetrofitCall.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/RetroError.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/RetroSuccess.kt

Our custom call class was invoking callbacks without switching to the main thread. This meant if you used `.enqueue { ... }` and tried to touch the UI, your app would have a very bad time. This fix specifies a default main thread executor and uses it to invoke callbacks on the main thread. It also allows one to specify a callback executor when creating the call adapter factory.

Callback threading

---

CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/utils/LlcMigrationUtils.java

https://stream-io.atlassian.net/browse/CAS-358
Issues:
- Our logic for visually indicating as read in the channel list only renders as read if the last read date is newer than the last message date, but the API marks reads with the message's createdAt date. This makes the comparison EQUAL, especially from online query results.
- Additionally, if we got into the state where last read & last message dates are equal, we don't send markRead updates to the UI or the API because the logic indicates we only do that if the last read date is AFTER the last message date. So, we end up stuck in an unread state.
- We execute several concurrent data fetches for offline & online. The mark read usecase gets executed immediately when a message list view loads, even before the viewmodel has a chance to …

fix: CAS-358 fix channels being stuck in the unread state

---

CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/User.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventBatchUpdate.kt

Fixes #802 
`totalUnreadCount` and `channelUnreadCount` weren't being updated when the user is connected and the proper value was not assigned until a new message arrived.

Fix unread counters

---

stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/application/ChatInitializer.kt
stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/feature/startup/StartupFragment.kt
stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/feature/user_login/UserLoginFragment.kt
stream-chat-android-sample/src/main/res/navigation/main_navigation.xml
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/startup/StartupFragment.kt
stream-chat-android-ui-components-sample/src/main/res/navigation/main_nav_graph.xml

Add startup fragment to prevent multiple ChatClient initializations.
Previous implementation allowed creating multiple ChatClient instances without deinitializing old ones.
This was happening when user was on channels fragment, clicked the back button and reopened the app which
was kept in memory.
That was causing multiple socket connections to be opened because socket connection is automatically restored
after resuming the app.
Moreover, back button wasn't working correctly after logging out (Activity wasn't destroyed).

Fix navigation in sample apps.

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/avatarview/ComponentBrowserAvatarViewFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/home/ComponentBrowserHomeFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/user_login/UserLoginFragment.kt
stream-chat-android-ui-components-sample/src/main/res/drawable/shape_component_browser_item_background.xml
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_component_browser_avatar_view.xml
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_component_browser_home.xml
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_user_login.xml
stream-chat-android-ui-components-sample/src/main/res/layout/item_user.xml
stream-chat-android-ui-components-sample/src/main/res/navigation/main_nav_graph.xml
stream-chat-android-ui-components-sample/src/main/res/values/styles.xml

Adds a Component Browser screen where we can try our new UI components in different configurations. Accessible via a long tap of the version number.
<p float="left">
</p>

Create component browser in new UI sample app, add AvatarView screen

---

stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/ChannelListDiffCallback.java

https://stream-io.atlassian.net/browse/CAS-395
Correctly display last messages in channel list when:
- user observes channel list
- somebody modifies the last message in the channel

CAS-395 Editing the last message doesn’t update the channel preview

---

CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt

[CAS-401](https://stream-io.atlassian.net/browse/CAS-401?atlOrigin=eyJpIjoiM2IyNzc1OWU5OTNiNGU4ZjhjMWQ1NjQxMWEwNzJlNjQiLCJwIjoiaiJ9)
We have an issue when local channels weren't sorted correctly. 
It happened because only for showing channels we extracted them from DB without messages. But sorting was based on last message date. So it was null and the channels list wasn't sorted correctly. I added a cache for lastMessageAt field of the Channel class via a liveData source in ChannelController. So when `ChannelController::toChannel` is invoked the lastMessageField is set.

Cache in live data of ChannelController value of Channel::lastMessageAt

---

CHANGELOG.md
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputController.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputStyle.kt
stream-chat-android/src/main/res/values/attrs.xml

This PR adds `streamShowSendAlsoToChannelCheckbox` attr to `MessageInputStyle` controlling visibility of "send also to channel" checkbox

[CAS-404] Add streamShowSendAlsoToChannelCheckbox attr to MessageInputStyle 

---

CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitApi.kt

`ChatClient::UpdateUsers` wasn't working fine because we didn't add the `api_key` to our query and backend was rejecting this call

[CAS-434] Hotfix/update users endpoint

---

stream-chat-android/src/main/java/com/getstream/sdk/chat/view/MessageListView.kt

Fix ScrollButtonBehavior when a thread is started/closed
- ~[ ] Reviewers added~

Fix ScrollButtonBehavior when a thread is started/closed

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/StreamLifecycleObserver.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/LifecycleHandler.java

`LifecycleObserver` instances only are able to be registered on MainThread. We had a crash previously because our `ChatClient` (That was a LifecycleObserver) was registered from a background thread when it was started by a push notification.
Reviewing our previous implementation, I could see we were registering it into the constructor, but we don't need to do it there if a user has not been set. I have refactored that logic to only observe when the user is set properly.
On the other hand, we had a previous implementation of `StreamLifecycleObserver` that prevented to be called immediately after we register our observer and removing an unnecessary call to reconnect that was been done previously
- …

[CAS-439] Hotfix subscribe client on main thread

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListItemViewHolder.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java
stream-chat-android/src/main/java/com/getstream/sdk/chat/utils/DateFormatter.kt
stream-chat-android/src/test/java/com/getstream/sdk/chat/utils/DateFormatterTest.kt

Extracts the date formatting logic that we already had duplicated in two places for the list of channel items (and we'll use in at least two more places in the new design) into a helper class + adds tests.

Extract formatting of channel dates into DateFormatter

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt

To be consistent with the majority of modern apps, do not reload current page when the current bottom navigation item is reselected.

Disable reselection of the same item in bottom navigation

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/search/ComponentBrowserSearchViewFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/Debouncer.kt

https://stream-io.atlassian.net/browse/CAS-369
Adds a listener that only notifies after debouncing test input for 300ms. Debouncing logic is contained in a reusable utility class.

Debounce search input events

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseConnectedIntegrationTest.kt

Use StateFlow to fix the error triggered by calling clearState from the IO thread:
https://console.firebase.google.com/project/stream-chat-internal/crashlytics/app/android:io.getstream.chat.sample.debug/issues/3d76c3f580802cc57d67fa27be437dcf?time=last-seven-days&sessionEventKey=5FB681280016000139B4D82C531C700B_1475287504195377751
Remove unused typingEvents implementation, design is dropping this feature request.

use stateflow to fix chatDomainImpl.clearState

---

CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/controllers/ChannelController.kt

Accept Invite Message is now optional, if null value is sent, no message will be sent to the rest of members about this action
Fixes #909 

[CAS-448] Set "Acept Invite Message" optional

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/entity/ReactionEntity.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemAdapter.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemDiffCallback.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemPayloadDiff.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/viewholder/message/BaseMessageListItemViewHolder.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/viewholder/message/DateSeparatorViewHolder.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/viewholder/message/LoadingMoreViewHolder.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/viewholder/message/MessageListItemViewHolder.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/viewholder/message/ThreadSeparatorViewHolder.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/viewholder/message/TypingIndicatorViewHolder.kt
stream-chat-android/src/test/java/com/getstream/sdk/chat/adapter/MessageListItemDiffCallbackTest.kt

We were previously triggering many rerenders of the message list item. Here's a list of the most common causes for rerendering the message:
```
- Message.user can have
-- different unread counts, we shouldn't rerender when that happens
-- different last online values, again shouldn't trigger a rerender
- The user objects on message.latestReactions and message.ownReactions have the same issue with last online and unread counts values on the user object
- messageReadBy returns a list of channel user read objects, the problem is that they contain unread message counts which can trigger a diff
- reaction.updated at wasn't stored in the reaction entity, so the offline & online version were always different
```
**Solutions:**
- MessageListItemDiffCallback implements areContentsTheSame focused …

Message diff

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ClientExtensions.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClientExtensions.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/controllers/ChannelController.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/FileUploader.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/textinput/MessageInputViewModelBinding.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/utils/exomedia/ui/widget/VideoControls.java
stream-chat-android/src/main/java/com/getstream/sdk/chat/utils/exomedia/util/DeviceUtil.java
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/ChannelHeaderView.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelHeaderViewModelBinding.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModelBinding.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModelBinding.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModelBinding.kt

Fixes doc comments, having an extra `*` causes them to render incorrectly, as it's interpreted as an empty list item

Fix documentation comment styles

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/add/AddChannelFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/ChannelListFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/mentions/MentionsFragment.kt
stream-chat-android-ui-components-sample/src/main/res/navigation/main_nav_graph.xml
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mentions/MentionsListViewModel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchViewModel.kt

Add a new parameter for `ChatFragment` to specify which message we're navigating to. This is provided when navigating to the screen from Search or Mentions, for example.

Add a message ID parameter for ChatFragment

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/textinput/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/textinput/MessageInputViewModelBinding.kt

Add message edit feature the message using `io.getstream.chat.android.ui.textinput.MessageInputView` with `sdk.chat.viewmodel.MessageInputViewModel`.

Message edit feature

---

CHANGELOG.md
stream-chat-android/src/main/AndroidManifest.xml
stream-chat-android/src/main/java/com/getstream/sdk/chat/CaptureMediaContract.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/StreamFileProvider.kt

Updates some usages of FileProvider after reviewing it due to https://github.com/GetStream/stream-chat-android/issues/925
- Use separate `StreamFileProvider` class instead of the androidx `FileProvider` ([as described here](https://commonsware.com/blog/2017/06/27/fileprovider-libraries.html))
- Update the way we create the authority string, fetch it from `PackageManager` instead of assembling it ourselves

FileProvider updates

---

CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Channel.kt

< Jira issue link, if applicable >
This PR fixes NPE at `Channel.lastMessageByCurrentUserWasRead()`
~- [ ] Comparison screenshots added for visual changes~

[Fix] NPE at Channel.lastMessageByCurrentUserWasRead()

---

stream-chat-android-sample/src/debug/kotlin/io/getstream/chat/sample/application/AppConfig.kt
stream-chat-android-ui-components-sample/src/debug/kotlin/io/getstream/chat/ui/sample/application/AppConfig.kt

As cleartext support is disabled, we need to use `https` scheme for user avatars.

Change avatar url schema to https

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/ChannelListFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchInputView.kt

Currently, pressing "back" while in a search closes the entire app. This change clears the input field (and therefore closes search) on a back button press instead, effectively navigating back to the channel list.

Clear search input on back button press before closing Activity

---

CHANGELOG.md
UNRELEASED_CHANGELOG.md

Hides mentions of the new `ui-components` module, as it's WIP and customers shouldn't be using it yet anyway.

Remove mentions of the ui-components module from the CHANGELOG

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/header/ComponentBrowserMessagesHeaderViewFragment.kt
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_component_browser_messages_header_view.xml
stream-chat-android-ui-components/src/main/res/drawable/stream_ui_badge_bg.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_messages_header_view.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_typing_indicator_view.xml
stream-chat-android-ui-components/src/main/res/values/styles.xml

Small changes to the `MessageHeaderView`:
- Adjusted clickable area so that it is easier to click on back button
- Added support for long badges
- Properly configured `AvatarView` (renders without white border, supports online status)
- Increased typing animation speed
- Fixed typing indicator and text position 
| --- | --- |
|![photo_2020-12-08 19 06 10](https://user-images.githubusercontent.com/9600921/101508245-7834e500-3988-11eb-8b5e-129379aeec5a.jpeg)| ![photo_2020-12-08 19 06 33](https://user-images.githubusercontent.com/9600921/101508286-8420a700-3988-11eb-99c4-afb6978cc7f1.jpeg) |

MessageHeaderView amendments

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ErrorCall.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/call/RetrofitCall.kt
stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/Call.kt
stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/CoroutineCall.kt
stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/MapCall.kt
stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/ZipCall.kt
stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Channels.java
stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ClientAndUsers.java
stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Events.java
stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Messages.java
stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/TypingIndicators.java
stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/UserPresence.java
stream-chat-android-test/src/main/java/io/getstream/chat/android/test/TestCall.kt
stream-chat-android/src/test/java/com/getstream/sdk/chat/viewmodel/channels/ChannelListViewModelTest.kt

Using the `Call` class from Java is inconvenient, as evidenced by our documentation snippets. Using a Kotlin function type as the parameter of `enqueue` (the preferred way of running a `Call` from Java) means that we're forcing our clients to return `kotlin.Unit` explicitly in their implementations, and/or to implement an ugly `Function1<Result<T>, Unit>()` type.
This PR replaces the function type with a `fun interface`, which lets Java clients use a more natural API. The old `enqueue` signature is kept around to keep source compatibility for Java clients, but it's hidden from Kotlin clients.

Update the API of the Call class

---

stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/KeystrokeImplTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/MarkAllReadImplTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/MarkReadImplTest.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/ChannelListItemAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/BaseChannelListItemViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListItemViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Any.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Channel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Message.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/String.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/User.kt
stream-chat-android-ui-components/src/main/res/values/strings.xml

- Noticed there was no direction on handling attachments for channel list items & their previews, so asked design to provide some direction and implemented what they decided on.
- Only bold mentions of the current user
- Fixed user's last message status not updating when read
- Also updates the tests that were using `yield()` to use `advanceUntilIdle()`

[CAS-364] last message attachments

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/textinput/MessageInputView.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputController.kt

`toString` never returns `null`, so these calls simply didn't make sense

Clean up some incorrect usages of isNullOrBlank

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/OnlyAttachmentsMessagesComponentBrowserFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/PlainTextMessagesComponentBrowserFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewHolderFactory.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/MessagePlainTextViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyMediaAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt

Adding click listeners for the new `MessageListItemViewHolderFactory`. Now the plain text messages and the attachment messages are working. 
Those listeners are needed to I can properly test the PR #991

Long click listener for messages

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Member.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDatabase.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/entity/MemberEntity.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoViewModel.kt

Currently, the only way to determine whether a channel member is shadow banned is to query members and check `shadowBan` flag. Unfortunately, we don't receive any event when a member is banned/unbanned so we need to get fresh data every time we enter `ChatInfo` screen

[CAS-467] Integrate shadow ban in sample app

---

stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/CommandMentionListItemAdapter.java
stream-chat-android/src/main/res/layout/stream_item_mention.xml

Fixes the binding logic in `CommandMentionListItemAdapter`, removes an unused TextView.
| --- | --- |
| ![Screenshot_1608039968](https://user-images.githubusercontent.com/12054216/102223824-7cf81c80-3ee5-11eb-93d2-35f7e9060128.png) | ![Screenshot_1608040391](https://user-images.githubusercontent.com/12054216/102223864-87b2b180-3ee5-11eb-8362-db39203ded3b.png) |

Fix binding of data in ReadUsersDialog

---

stream-chat-android-ui-components-sample/src/main/res/color/bottom_nav_item_color.xml
stream-chat-android-ui-components-sample/src/main/res/drawable/ic_new_direct_message.xml
stream-chat-android-ui-components-sample/src/main/res/drawable/ic_sign_out.xml
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_home.xml
stream-chat-android-ui-components-sample/src/main/res/layout/item_options.xml
stream-chat-android-ui-components-sample/src/main/res/layout/item_user.xml
stream-chat-android-ui-components-sample/src/main/res/layout/nav_header.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_header_view.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_item_foreground_view.xml
stream-chat-android-ui-components/src/main/res/values/colors.xml

[CAS-370](https://stream-io.atlassian.net/browse/CAS-370)
Fixing a margin in the menu drawer. Now the profile picture is aligned with the other icons.

[CAS-370] Profile drawer layout

---

.github/workflows/pr-checks.yml

Without this, modules without any tests in them could pass PR checks even if they had broken code in them. This adds an explicit build job that builds all modules (only the debug variant still).

Add a build step to our PR checks

---

stream-chat-android-ui-components/src/main/AndroidManifest.xml

Previously we were relying on the permissions from the `stream-chat-android` module, but since we no longer depend on it, this module was now lacking these permissions.

Add permissions to the new UI module

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/add/AddChannelFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/add/group/AddGroupChannelFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/GroupChatInfoFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/user_login/UserLoginFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/util/extensions/Fragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/attachments/file/FileAttachmentFragment.kt

We need different window handling behaviour depending on which Fragment we're in. Sometimes we want to resize the window so that it all fits above the keyboard, and sometimes we want to cover its bottom half with the keyboard.
This PR removes adds extensions for `Fragment` to dynamically set this for each screen.
https://user-images.githubusercontent.com/12054216/102590365-beb8db00-4110-11eb-9626-51437c4ffbed.mov

Add extensions for setting soft input mode in Fragments

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ErrorCall.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/call/RetrofitCall.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser/ChatParserImpl.kt
stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/MapCall.kt
stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/ZipCall.kt
stream-chat-android-core/src/main/java/io/getstream/chat/android/client/utils/Result.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ThreadControllerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/GetChannelControllerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/GetThreadImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/GetTotalUnreadCountImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/GetUnreadChannelCountImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/MarkAllReadImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/MarkReadImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/QueryChannelsImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/WatchChannelImpl.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDomainTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/BaseDomainTest2.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/SendMessageWithFilesTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/utils/TestDataHelper.kt

This constructor allowed its users to create a Result that had both a result and an error in it, or neither of them. Both of these cases are misusing the Result type.
There is still a single usage of the old constructor, because we rely on both the result and the error being returned there 😞

Deprecate two parameter Result ctor

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/LegacyDateFormatter.kt
stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/utils/LegacyDateFormatterTest.kt

Removes calls to the `Date()` constructor, which returns a `Date` representing the current time. Use a blank `Date` instead, which then has its hour/minute/second values set.

Do not rely on current time in LegacyDateFormatter

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/GravityDecorator.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_media_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_media_attachments.xml

This PR fixes the lost `layout_width` and `layout_height` params of footnote include. When including a layout there are basically 2 options:
- Not override any layout params
- Override all layout parameters, otherwise they will be lost
| --- | --- |
| ![photo_2020-12-23 01 42 32](https://user-images.githubusercontent.com/9600921/102939894-2b8cf600-44c0-11eb-9176-52a4448e8d6a.jpeg) | ![photo_2020-12-23 01 42 35](https://user-images.githubusercontent.com/9600921/102939883-26c84200-44c0-11eb-9e57-a5ae11b911d3.jpeg) |

Fix footnote positioning

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/ChannelHeaderViewModel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/header/MessagesHeaderView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/header/MessagesHeaderViewBinding.kt

Show typing users in message list header. Had to introduce some state as we need to show previous subtitle state when a user stops typing.
https://user-images.githubusercontent.com/9600921/102976124-26f12d80-4512-11eb-8630-744f8da3117f.mov

Show typing indicator

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/BaseMessageItemViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/FailedIndicatorDecorator.kt
stream-chat-android-ui-components/src/main/res/drawable/stream_ui_ic_warning.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_media_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_media_attachments.xml

https://stream-io.atlassian.net/browse/CAS-488
_[Interior Crocodile Alligator](https://www.youtube.com/watch?v=kZwhNFOn4ik)_
Adds the Failure indicator to ViewHolders for messages that failed to send with a permanent error.

Failure Indicator Decorator

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelsView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelsViewModelBinding.kt

This PR prevent channel list loading indicator from displaying over channel list received from cache. This is just a temp solution. We need to completely get rid of sealed classes in our view models and controllers:
```
data class State(
val contentState: ContentState,
val channels: List<Channel>,
val loadingMore: Boolean,
val hasMore: Boolean
)
enum class ContentState {
CONTENT, LOADING, ERROR
}
```
https://user-images.githubusercontent.com/9600921/102942457-6d209f80-44c6-11eb-9646-aad1e06f9334.mov
https://user-images.githubusercontent.com/9600921/102942452-6a25af00-44c6-11eb-8ffc-8bef3644bec9.mov

Don't display loading indicator over channels from cache

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/AvatarDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/DeliveryStatusDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/GravityDecorator.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_giphy.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_media_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_media_attachments.xml
stream-chat-android-ui-components/src/main/res/values/dimens.xml

Various fixes around ViewHolder margins and similar things:
- Fix start/end margins on ViewHolders
- Use `tools` namespace in ViewHolder layouts for guideline positioning, as setting those values does nothing (overridden at runtime by a decorator)
- Hides the delivery status on Giphy ViewHolders
- Fix incorrect spacing of ViewHolder content when avatars are hidden
| --- | --- |
| ![Screenshot_1608039968](https://user-images.githubusercontent.com/12054216/102981934-00c78f80-450a-11eb-917b-22bc79f22220.png) | ![Screenshot_1608040391](https://user-images.githubusercontent.com/12054216/102993361-56596780-451d-11eb-9774-6fe2e90a37fc.png) |

ViewHolder margin fixes

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/ReactionsDecorator.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_media_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_media_attachments.xml

This PR fixes the horizontal position of `ReactionsView` in the message list. As we had to revert the most recent `ConstraintLayout` version to the stable one, negative margins stopped working. Had to implement it with the help of extra `Space` view.
| --- | --- |
|![photo_2020-12-23 17 22 31](https://user-images.githubusercontent.com/9600921/103006849-7439c300-4543-11eb-9bc8-04c405cf499b.jpeg) | ![photo_2020-12-23 17 22 46](https://user-images.githubusercontent.com/9600921/103006884-7bf96780-4543-11eb-8be6-759dc106c887.jpeg) |

Fix ReactionsView position in the message list

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListViewModelBinding.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/options/MessageOptionsOverlayDialogFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/options/MessageOptionsView.kt
stream-chat-android-ui-components/src/main/res/drawable/stream_ui_ic_edit.xml
stream-chat-android-ui-components/src/main/res/drawable/stream_ui_ic_flag.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_options_view.xml
stream-chat-android-ui-components/src/main/res/values/attrs.xml
stream-chat-android-ui-components/src/main/res/values/strings.xml

[CAS-428](https://stream-io.atlassian.net/browse/CAS-428)
Adding the implementation for the message option. 
Is this PR I'm just binding the implementation that already exists to the list. We still need to create the behaviour for **reply**. Which is hidden.
This version: 
New version:

[CAS-428] Behaviour for Message Options

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/adapter/MessageListItem.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemDiffCallback.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewHolderFactory.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/DateDividerViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/GiphyViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/MessageDeletedViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/MessagePlainTextViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyMediaAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithMediaAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/ThreadSeparatorViewHolder.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_thread_divider.xml
stream-chat-android-ui-components/src/main/res/values/strings.xml

https://stream-io.atlassian.net/browse/CAS-490
Adds the separator item for Threads showing the number of replies
| Light | Dark |
| --- | --- |
| ![Screenshot_1608039968](https://user-images.githubusercontent.com/12054216/103014455-11dec380-453f-11eb-8438-ab9346d94dab.png) | ![Screenshot_1608040391](https://user-images.githubusercontent.com/12054216/103014469-14411d80-453f-11eb-889c-51e556d69b5e.png) |

[CAS-490] Thread separator ViewHolder

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/textinput/MessageInputFieldView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/textinput/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/textinput/MessageInputViewModelBinding.kt
stream-chat-android-ui-components/src/main/res/values/strings.xml

This PR migrates the logic of limiting maximum message length from the old UI components to the new ones.

Add max message length limit

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/ThreadRepliesDecorator.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text.xml

Hide thread replies container by default, so that it remains hidden if the Decorator is not applied to a ViewHolder
| --- | --- |
|![Screenshot_20201229_132240](https://user-images.githubusercontent.com/12054216/103283871-01649800-49da-11eb-91ac-56c0d289107e.png) | ![Screenshot_20201229_132401](https://user-images.githubusercontent.com/12054216/103283887-09bcd300-49da-11eb-9b70-b54d14e979df.png) |

Fix some visibility handling in ThreadRepliesDecorator

---

UNRELEASED_CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChannelData.kt

`ChannelData` is being propagated through `MutableStateFlow` which doesn't update its value when the new one is equal to the previous:
>      The current value of this state flow.
>     Setting a value that is [equal][Any.equals] to the previous one does nothing.
That's why our `MessagesHeaderView` (which shows member count and relies on `ChannelHeaderViewModel::channelState`) wasn't updated properly after adding or removing a channel member. 
Adding `memberCount` to `ChannelData` solves that issue but we should review our `ChannelHeaderViewModel::channelState` implementation because it exposes `Channel` based on `ChannelData` updates so it might not contain proper data (for example when channel watchers change).
I think that there are two possible solutions for that problem:
1. Add …

[CAS-494] Add member count to ChannelData

---

stream-chat-android-ui-components-sample/src/main/res/layout/add_channel_view.xml
stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_option_item.xml
stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_separator_item.xml
stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_shared_file_date_divider.xml
stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_shared_file_item.xml
stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_stateful_option_item.xml
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat_info_shared_files.xml
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat_info_shared_media.xml
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/images/AttachmentGallery.kt
stream-chat-android-ui-components/src/main/res/drawable/stream_ui_shape_message_options_background.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_activity_attachment_gallery.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_attachment_gallery.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_messages_header_view.xml
stream-chat-android-ui-components/src/main/res/values/styles.xml

[CAS-229](https://stream-io.atlassian.net/browse/CAS-229)
Some screens got the wrong colours in some PR and some others were not covered by the Dark theme ticket. This PR fixes the colours for the screens that doesn't show the correct colours for the dark theme. 
- Changelog updated with client-facing changes. **no need.**
- New code is covered by unit tests. **no need.**

[CAS-229] Fixing colours for many screens

---

.idea/compiler.xml
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/BackgroundDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/ThreadRepliesDecorator.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_footnote.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_giphy.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_media_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_media_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_threads_footnote.xml
stream-chat-android-ui-components/src/main/res/values/dimens.xml

https://stream-io.atlassian.net/browse/CAS-484
Adding thread replies count label for all of the available message types. 

[cas-484] Thread replies footnote for different message types

---

stream-chat-android-ui-components-sample/src/main/res/layout/add_channel_view.xml
stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_group_add_users_dialog_fragment.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_fragment_attachment_file.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_attachment_media.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_deleted.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_giphy.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_media_attachments.xml

[CAS-229](https://stream-io.atlassian.net/browse/CAS-229)
Fixing the colour for a small check. 
| --- | --- |
| ![Screenshot_20210104-174404](https://user-images.githubusercontent.com/10619102/103558521-14cda280-4eb5-11eb-92b7-2d7dcbfb43a0.png) | ![Screenshot_20210104-174053](https://user-images.githubusercontent.com/10619102/103558584-2f078080-4eb5-11eb-82cd-331efe81c041.png) |
| ![Screenshot_20210104-183631](https://user-images.githubusercontent.com/10619102/103563273-cb815100-4ebc-11eb-92ac-113746c2bd33.png) | ![Screenshot_20210104-183757](https://user-images.githubusercontent.com/10619102/103563297-d936d680-4ebc-11eb-90c8-ae36dd92294f.png) |
| ![Screenshot_20210104-183521](https://user-images.githubusercontent.com/10619102/103563469-1c914500-4ebd-11eb-9d7d-abb908d06d …

[CAS-219] Fixing tint few screens

---

stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/application/ChatInitializer.kt
stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/application/FirebaseLogger.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/FirebaseLogger.kt

- Set log level to `ChatLogLevel.NOTHING` for release builds
- Filtered out internal log events with tags starting with "Chat" from `FirebaseLogger` (Mostly https requests, websocket events, etc.)
- [] Comparison screenshots added for visual changes

Disable logging in release build

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListListenerContainer.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListListenerContainerImpl.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/MessagePlainTextViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyMediaAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithMediaAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/options/MessageOptionsView.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_thread_divider.xml

https://stream-io.atlassian.net/browse/CAS-496
A batch of thread handling implementation bits / improvements. See commit messages for details.
Opening and closing threads is now connected to listeners correctly, albeit still very glitchy. Fixes to follow up later on, in separate PRs.

[CAS-496] Thread opening logic, thread listeners

---

stream-chat-android-ui-components/src/main/res/layout/stream_ui_mentions_list_view.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_search_result_list_view.xml

Just a small correction in the XML. The text for "No results found for [search here]" and "No mentions exist yet…" was aligned to the left, not the center.  💅 
- Changelog updated with client-facing changes. **No need**
- New code is covered by unit tests. **No need**

Fixing text alignment

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt

Don't show Thread reply option if a message is in a thread and was "also sent to channel"

Thread reply options improvement

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/utils/TestDataHelper.kt

Start parsing the `channel` inside `notification.message_new` events, as it's included in the event we receive, as a fix for #1045

Add channel property to notification.message_new events

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/BaseMessageItemViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/AttachmentClickListener.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/FileAttachmentsView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/MediaAttachmentView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/MediaAttachmentsGroupView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/MessagePlainTextViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyMediaAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithMediaAttachmentsViewHolder.kt

https://stream-io.atlassian.net/browse/CAS-493
This PR ensures that options overlay is shown on long press regardless of the touch area in message bubble (text, file/media attachment).

CAS-493 Show options overlay on long press for all view holders

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser/MapAdapter.kt

`delegateMapAdapter ` can return `null` during JSON reading.
Fixes #1127 
- [] New code is covered by unit tests

Fix deleting channel error

---

stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_giphy.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_media_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_file_attachments.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_plain_text_with_media_attachments.xml

By default replies footnote should be hidden, so that it works on message options screen without corresponding decorator.
| --- | --- |
| ![photo_2021-01-05 23 48 40](https://user-images.githubusercontent.com/9600921/103697137-8d655980-4fb0-11eb-80b9-b3654bcfc85a.jpeg) | ![photo_2021-01-05 23 48 37](https://user-images.githubusercontent.com/9600921/103697149-90f8e080-4fb0-11eb-8df6-2362ebace0cd.jpeg) |

Hide replies footer by default

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/shared/media/ChatInfoSharedMediaFragment.kt
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat_info_shared_media.xml
stream-chat-android-ui-components/src/main/res/drawable/stream_ui_date_divider_background.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_date_divider.xml
stream-chat-android-ui-components/src/main/res/values-night/colors.xml
stream-chat-android-ui-components/src/main/res/values/colors.xml

- Add elevation when showing loading or empty state on SharedMedia screen
- Improve date divider colors in both day and night modes
| --- | --- |
|<img width="312" alt="Screenshot 2021-01-06 at 12 51 51" src="https://user-images.githubusercontent.com/17440581/103766430-1e731980-501f-11eb-85c8-8703bffa4fa9.png">|<img width="312" alt="Screenshot 2021-01-06 at 12 54 40" src="https://user-images.githubusercontent.com/17440581/103766444-23d06400-501f-11eb-8f33-183c9322f0dd.png">|
|<img width="310" alt="Screenshot 2021-01-06 at 12 52 17" src="https://user-images.githubusercontent.com/17440581/103766432-203cdd00-501f-11eb-8009-96377f3b4001.png">|<img width="313" alt="Screenshot 2021-01-06 at 12 55 01" src="https://user-images.githubusercontent.com/17440581/103766446-23d06400-50 …

[CAS-508] Improve shared media screen

---

stream-chat-android-ui-components-sample/src/main/res/layout/item_options.xml

[CAS-505](https://stream-io.atlassian.net/browse/CAS-505)
Tinting the icon with white in the dark mode. Before it was black in a black background, impossible to see the icon. 

[CAS-505] Fixing icon tint for advanced options

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/GiphyMessageComponentBrowserFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/attachments/file/FileAttachmentAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/attachments/media/MediaAttachmentAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/attachments/selected/SelectedFileAttachmentAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/attachments/selected/SelectedMediaAttachmentAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/actions/ChannelMembersAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mentions/MentionsListAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/FileAttachmentsView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/GiphyViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/reactions/ReactionsAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchResultListAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestions/CommandsAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestions/MentionsAdapter.kt

https://stream-io.atlassian.net/browse/CAS-498
Refactors our ViewHolders so that they create all listeners when initialized, and store the current model in a property so that listeners can reference it.
Also adjusts some code style so that all ViewHolders use inflaters and `binding.apply` calls in the same way.

[CAS-498] ViewHolder listeners

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelViewHolder.kt

Fixes a bug I introduced in https://github.com/GetStream/stream-chat-android/pull/1140, where the click and long click listeners for channel items were applied to the root of their entire layout, instead of the root of the foreground layer.

Apply channel click listeners to foreground view only

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/DownloadAttachment.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/UseCaseHelper.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListListenerContainer.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListListenerContainerImpl.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/AttachmentClickListener.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/FileAttachmentsView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListViewModelBinding.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_file_attachment.xml
stream-chat-android-ui-components/src/main/res/values/strings.xml

https://stream-io.atlassian.net/browse/CAS-515
This PR adds a possibility to download a file from the message list.
What's covered:
- User is able to download any file from the message list via standard Android `DownloadManager`
What's not covered (almost everything):
- Persistent storage for downloads with download status (started/completed/failed) and download progress
- Possibility to observe download state in `ChannelController`. 
- UI that reflects the current state of particular download (able to download / downloading is in progress / downloading completed)
- Possibility to cancel ongoing downloads
- Possibility to navigate to downloaded file directly from the message list
https://user-images.githubusercontent.com/9600921/103778724-b682fa00-5043-11eb-820d-4510b590f6d2.mov

[CAS-515] Basic download functionality

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/DownloadAttachment.kt

Making `DownloadAttachment` use case `internal` as its implementation is not complete.

Make download attachment user case internal

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/controllers/ChannelController.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/UsersApiCallsTests.kt

Unmuting user was causing a crash because of the wrong return type.
We are getting `{"duration":"10.63ms"}` response instead of `Mute` class.
It was working "fine" before fixing `Result` class in #1069 just because we were able to create `Result` with both `data` and `error` as nulls

[CAS-513] Change unmuting user related methods return type to Call<Unit>

---

stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveDataBenchmark.kt

This test currently measures the performance of GitHub Actions instead of our `MessageListItemLiveData` class, as it breaks randomly on CI, without us making any relevant changes to it at all. This PR ignores the test for now (can still be checked locally after making changes to the LiveData).

Ignore benchmark test

---

.idea/codeStyles/Project.xml

This changes the IDE behaviour so that running auto-formatting on a file will add trailing commas to appropriate places. I didn't want to reformat the entire project and touch all files this PR, but hopefully we'll have more and more trailing commas in the project with this change over time, as we format the files that we touch (please run IDE formatting before commits!).
ktlint, unfortunately, doesn't pick this up yet (see https://github.com/pinterest/ktlint/issues/709).
| --- | --- |
| ![Screenshot 2021-01-07 at 16 18 50](https://user-images.githubusercontent.com/12054216/103909626-3bcde380-5104-11eb-8295-287fb9e5d62f.png) | ![Screenshot 2021-01-07 at 16 18 40](https://user-images.githubusercontent.com/12054216/103909634-3cff1080-5104-11eb-9c40-ccaef517d603.png) |

Enable trailing commas in code style

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/custom_login/CustomLoginViewModel.kt

In this PR the app disconnects from the chat if the connection fails. The app was crashing because a wrong token was persisted in the app. 
- Comparison screenshots added for visual changes. **no need**

Fixing error when connection doesn't work

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelsView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListItemViewHolderFactory.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListListenerContainer.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelViewHolder.kt

Disabled long press effect (vibration) when there is a long press on channel item and custom long press listener has not been set.

Prevent long press consumption in channel list when using default long press listener

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/StorageHelper.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/StringUtils.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/AttachmentExtension.kt
stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/utils/StringUtilsTest.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/FileAttachmentsView.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_file_attachment.xml

[CAS-512](https://stream-io.atlassian.net/browse/CAS-512)
This PR removes the timestamp and the STREAM from the name of the attachment file. This way the user sees the original name, instead of just STREAM_202... 
Edit:
Removing `STREAM_` from the prefix and removing the maxline=1 from the textview. Now the item can show files with title with multiple lines. 
_The last one is the name with the change in the code._ 

[CAS-512] Original name for attachments

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/adapter/MessageListItem.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemDiffCallback.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewHolderFactory.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewType.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewTypeMapper.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/MessageListItemDiffCallback.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/MessageViewHolderFactory.kt

We never created instances of this class, we just had a bunch of code handling its diffing. In the old UI, having one in the list would've resulted in a crash in the ViewModel factory, in the new UI, we were using a blank View to display it.

Remove unused ReadStateItem message type

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/options/MessageOptionsDialogFragment.kt

Initializes `listenerContainer` so we avoid not initialised property exception.
- Changelog updated with client-facing changes
- New code is covered by unit tests
- Comparison screenshots added for visual changes

Initializating listenerContainer

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/EmptyMessageListListenerContainer.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/GiphyMessageComponentBrowserFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/OnlyFileAttachmentsMessagesComponentBrowserFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/OnlyMediaAttachmentsMessagesComponentBrowserFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/PlainTextMessagesComponentBrowserFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/PlainTextWithFileAttachmentsMessagesComponentBrowserFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/PlainTextWithMediaAttachmentsMessagesComponentBrowserFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/GiphyViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/MessagePlainTextViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyMediaAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithMediaAttachmentsViewHolder.kt

Removes some `null` handling we were only doing to support using message ViewHolders in the component browser.

Make message listener container non-nullable

---

stream-chat-android-ui-components/src/main/res/values-night/colors.xml
stream-chat-android-ui-components/src/main/res/values/colors.xml

Deleted messages have the same background color of normal messages. Only the text color changes (from black to grey).
| --- | --- |
|  ![photo_2021-01-08_17-36-01](https://user-images.githubusercontent.com/4047514/104040531-0abee300-51d8-11eb-8e4e-cb95acad6900.jpg) |  ![photo_2021-01-08_17-36-04](https://user-images.githubusercontent.com/4047514/104040516-0692c580-51d8-11eb-836d-0ac6d2eae69b.jpg)  |

Update delete message background

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/images/AttachmentGalleryActivity.kt

`resources.configuration.locales` is only available prior to 24 API, we support 21+
- Changelog updated with client-facing changes
- New code is covered by unit tests
- Comparison screenshots added for visual changes

fixing locale compatibility problem

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/header/ChannelListHeaderView.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_header_view.xml
stream-chat-android-ui-components/src/main/res/values/styles.xml

This PR fixes channels header style
| --- | --- |
| <img width="496" alt="Screenshot 2021-01-12 at 11 22 38" src="https://user-images.githubusercontent.com/9600921/104289788-9ed7c580-54ca-11eb-9cee-81b8ce3b9a88.png"> |<img width="495" alt="Screenshot 2021-01-12 at 11 34 57" src="https://user-images.githubusercontent.com/9600921/104289801-a1d2b600-54ca-11eb-8552-380cd951939e.png"> |

Fix channels header

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/options/MessageOptionsDialogFragment.kt

Lets users close the message options dialog by clicking to the side of the selected message. This was previously consumed by the ViewHolder's root click listener, and would do nothing.

Dismiss message options when the message container is clicked

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/BackgroundDecorator.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_giphy.xml

[CAS-525](https://stream-io.atlassian.net/browse/CAS-525?atlOrigin=eyJpIjoiMWE2YTJiZjkzNDk1NDBmMWJhNDVjZjA4OTExMTEwZGYiLCJwIjoiaiJ9)
Fix crash with MaterialCardView for old android versions, by using `app:cardBackgroundColor` instead of `android:background`. Also fix the colour being used for the background.

Fix CardView related crash in Giphy ViewHolder

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/MessageReplyView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/AvatarDecorator.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_reply_view.xml

Was surprised to find out that `findViewById` performs DFS and not BFS. Therefore, for most of our message list view holders, `AvatarDecorator` was updating invisible avatar in inner `ReplyView` layout instead of message avatar.
| --- | --- |
| ![photo_2021-01-13 00 31 23](https://user-images.githubusercontent.com/9600921/104376885-b056b700-5536-11eb-9c4d-72609eb6e1de.jpeg) | ![photo_2021-01-13 00 31 19](https://user-images.githubusercontent.com/9600921/104376890-b2207a80-5536-11eb-8178-299986fb05da.jpeg) |

Fix duplicate AvatarView layout ID in ReplyView

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/images/AttachmentGallery.kt

Share actions needs to generated a file before the intent is generated, and it could spend some time. We need to disable the button during this process to prevent multiple share-process to be executed

[CAS-534] Feature/debounce share icon

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/MediaAttachmentsGroupView.kt

Fix corner size apply to MediaAttachmentsGroupView
| --- | --- |
| ![photo_2021-01-13_13-36-08](https://user-images.githubusercontent.com/4047514/104453271-715f4a80-55a4-11eb-82ee-10a6e69f35c8.jpg)  | ![photo_2021-01-13_13-36-09](https://user-images.githubusercontent.com/4047514/104453279-745a3b00-55a4-11eb-8eff-9afca4df5d36.jpg) |

Fix corner size apply to MediaAttachmentsGroupView

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/view/activity/AttachmentActivity.java
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/view/activity/AttachmentMediaActivity.java
stream-chat-android-ui-common/src/main/res/values/strings.xml

Better error message when we can't display attachment. Logging added. 
| --- | --- |
| ![Screenshot_20210113-145030](https://user-images.githubusercontent.com/10619102/104461749-087dcf80-55b0-11eb-8808-cea0a83624bc.png) | ![Screenshot_20210113-134831](https://user-images.githubusercontent.com/10619102/104461797-13386480-55b0-11eb-8315-1f8499f37727.png) | 

Improve error handling for attachments

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelViewHolder.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_item_foreground_view.xml

Fixes a bunch of things around the unread count badges on the channel list:
- Vertically aligns them to the _end_ of the timestamp instead of the _center_ of it
- Doesn't let the channel name and the badge overlap
- Fixes vertical alignment of timestamp and vadge
- Uses "99+" for large unread counts as per the design
| --- | --- |
|  ![Screenshot_20210115_095347](https://user-images.githubusercontent.com/12054216/104706498-772b6c00-571b-11eb-800c-37dc6989cc31.png) | ![Screenshot_20210115_101141](https://user-images.githubusercontent.com/12054216/104706515-7db9e380-571b-11eb-9797-91be9db630b5.png) |

Fix channel list badges

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/User.kt

See title & screenshots
| --- | --- |
| ![Screenshot_20210115_154416](https://user-images.githubusercontent.com/12054216/104744811-9e029600-574d-11eb-878a-0d5b02a93a37.png) | ![Screenshot_20210115_161822](https://user-images.githubusercontent.com/12054216/104744885-b5418380-574d-11eb-9674-8f34ac0162c9.png)|

Use User.createdAt in last seen text if lastActive is not available

---

stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/ChannelItemPayloadDiff.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/ChannelListDiffCallback.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemAdapter.java
stream-chat-android/src/test/java/com/getstream/sdk/chat/adapter/ChannelListDiffCallbackTest.kt

https://stream-io.atlassian.net/browse/CAS-545
https://github.com/GetStream/stream-chat-android/issues/1226
`ChannelListDiffCallback` was not taking into account `unreadCount` field. As a result, unread counts could be stale in the channel list.

[CAS-545] Incorrect unread counts in channel list

---

stream-chat-android-ui-components/src/main/res/drawable/stream_ui_attachment_cancel_background.xml
stream-chat-android-ui-components/src/main/res/drawable/stream_ui_circle_white_attachment_check.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_attachment_media.xml
stream-chat-android-ui-components/src/main/res/values-night/colors.xml
stream-chat-android-ui-components/src/main/res/values/colors.xml

This PR creates a small colour fix related to attachments. 
|---|---|
| ![Untitled3](https://user-images.githubusercontent.com/10619102/104957382-5b032580-59ce-11eb-849f-4edd0fc36f87.png) | ![Untitled](https://user-images.githubusercontent.com/10619102/104957412-68201480-59ce-11eb-8ca9-9ba1e7718330.png) | 
| ![Untitled2](https://user-images.githubusercontent.com/10619102/104957517-9998e000-59ce-11eb-92a2-97520ed34c72.png) | ![Untitled4](https://user-images.githubusercontent.com/10619102/104957582-b503eb00-59ce-11eb-8c9f-66f139e0a762.png) | 

Fixing some colours related to attachments

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/ChannelListItemType.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/ChannelListItemViewType.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelListItemViewHolderFactory.kt

Changes channel list view types from internal enum using ordinals to public, constant integers with offsets for better QOL for clients implementing custom channel view holders.

Channel list view types

---

stream-chat-android-client/build.gradle
stream-chat-android-offline/build.gradle

Users who include only our client dependency and don't include `couroutines-android` themselves would get a crash when performing calls with our SDK, as the platform specific Main dispatcher wouldn't be found at runtime 😢

Move coroutines-android dependency to client module

---

stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/Channel.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelsView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/ChannelViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/coil/AvatarFetcher.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/header/MessagesHeaderViewBinding.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/textinput/MessageInputViewModelBinding.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Channel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/User.kt

Expose `isDirectMessage` about current channel from `MessageInputViewModel`, and set the `chatMode` in `MessageInputView` based on it.
This affects what copy we show next to the "Also send" checkbox:
| Group | Direct message |
| --- | --- |
| ![Screenshot_20210121_093909](https://user-images.githubusercontent.com/12054216/105325170-95d2ac80-5bcc-11eb-92db-0225e1ab6bc8.png) | ![Screenshot_20210121_093933](https://user-images.githubusercontent.com/12054216/105325178-979c7000-5bcc-11eb-84db-bde7365f36a5.png) |
The PR moves some utility methods to the `common` module as that's where the ViewModel lives.

Set ChatMode in MessageInputView

---

stream-chat-android-offline/api/stream-chat-android-offline.api
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/SendMessageImpl.kt

Default parameter values don't work in Java by default, and interfaces can't have `@JvmOverloads` methods. This PR adds a manual single-param overload, so that Java clients are not forced to always provide the second parameter.

Add 1-param overload of SendMessage#invoke for Java clients

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ClientExtensions.kt

Adds a `setUserAndAwait` extension so that coroutine users can easily wait for `setUser` to complete, and don't need to use a callback

Add suspending setUserAndAwait extensions for ChatClient

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/common/Extensions.kt

This PR fixes the position of badge in bottom navigation bar. The logic which alters the position of the badge has stopped working recently. I didn't find the reason, but I suspect that the version of the material library has be updated and as a result the behavior changed. I was relying on a fact that badges are allocated lazily in `BottomNavigationView`. Now, this is obviously not the case.
| Our design | Our app |
| --- | --- |
|<img width="382" alt="Screenshot 2021-01-22 at 15 50 46" src="https://user-images.githubusercontent.com/9600921/105492857-a026a080-5cc9-11eb-9938-0f0e5dcae877.png"> |<img width="380" alt="Screenshot 2021-01-22 at 15 49 40" src="https://user-images.githubusercontent.com/9600921/105492823-913fee00-5cc9-11eb-9be8-7c3028a503e7.png"> |

Fix badge position in bottom menu

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/header/ChannelListHeaderView.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_header_view.xml

https://stream-io.atlassian.net/browse/CAS-579
Fixes button colour in dark mode, fixes icon size, changes underlying implementation to use `ImageView` like other similar buttons we have
| --- | --- |
| ![Screenshot_20210122_152226](https://user-images.githubusercontent.com/12054216/105502762-12958180-5cc6-11eb-9c5c-02ba0b5c355e.png) | ![Screenshot_20210122_151759](https://user-images.githubusercontent.com/12054216/105502764-132e1800-5cc6-11eb-9f77-7d3fe7b635af.png) |
| ![Screenshot_20210122_152230](https://user-images.githubusercontent.com/12054216/105502752-10332780-5cc6-11eb-911a-9d278308d7cc.png) | ![Screenshot_20210122_151754](https://user-images.githubusercontent.com/12054216/105502768-13c6ae80-5cc6-11eb-8005-ea42fb9fc7a7.png) |

[CAS-579] Rework new chat button design

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/adapter/MessageListItem.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.kt
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/BaseMessageItemViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/DecoratedBaseMessageItemViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemDiffCallback.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/MessageListItemViewHolderFactory.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/DateDividerViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/GiphyViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/MessagePlainTextViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/OnlyMediaAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithFileAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/PlainTextWithMediaAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/ThreadSeparatorViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/AvatarDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/BackgroundDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/BaseDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/Decorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/FailedIndicatorDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/FootnoteDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/GapDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/LinkAttachmentDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/MaxPossibleWidthDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/ReactionsDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/ReplyDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/options/MessageOptionsDialogFragment.kt

Threadfootnote didn't get shown when writing thread reply to the latest message. 
It happens because VH didn't get redrawn since `MessageListItemDiffCallback::areContentsTheSame` returned true. So we need to make messages different when in `ThreadMode` and when in `NormalMode`.  So:
1) Introduce the new field `isThreadMode` to `MessageListItem.MessageItem`
2) Remove from VHs' binding logic the `isThread`flag and use `isThreadMode` from `MessageItem`
3) Add this new flag into comparison logic of `MessageListItemDiffCallback`

[CAS-632] Thread footnote fix

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt

| --- | --- |
|<img width="326" alt="Screenshot 2021-01-25 at 14 21 48" src="https://user-images.githubusercontent.com/17440581/105711477-e32a8300-5f18-11eb-8940-7f23f862b526.png">|<img width="326" alt="Screenshot 2021-01-25 at 14 20 34" src="https://user-images.githubusercontent.com/17440581/105711472-e1f95600-5f18-11eb-9e21-bfbf1ecf07c7.png">|
1. Add possibility to configure when to add date separator through `DateSeparatorHandler`. We should reconsider the way we are passing it to `MessageListItemLiveData` because it won't work fine if the handler will be set after presenting results to the user. Maybe we should add an extra rerender?
2. Add missing TOP position to Message which has `DateSeparator` above

Fix adding date separators

---

stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/textinput/MessageInputFieldView.kt

Fix bug:
When replied the second time and send or dismiss reply then you saw reply mode from the first time
Before:
https://user-images.githubusercontent.com/11807573/105827442-4ae8d880-5fc2-11eb-9371-d4a4ebfd5291.mov
After:
https://user-images.githubusercontent.com/11807573/105827483-589e5e00-5fc2-11eb-93a6-c7fc2593e875.mov

Do not keep previous mode in ReplyMode

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListViewModelBinding.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/options/MessageOptionsDialogFragment.kt

Minor API cleanup: removes "On" prefixes from listener names, unifies order of words in the handler names to `NounVerbHandler`.

Fix consistency of MessageListView handler names and setters

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/view/LinkAttachmentView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/LinkAttachmentDecorator.kt

https://stream-io.atlassian.net/browse/CAS-576
Added enough room for the messages with links to render properly.

[CAS-576] Fix incorrect dimensions of messages with links

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser/GsonChatParser.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser/JsonUtils.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser/StreamGson.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt

This PR creates a default gson instance. As the instace of `gson` of `ChatDomainImpl` doesn't have a exclusion strategy, annotations like `@IgnoreDeserialisation` don't work with this instance. This create problems when setting the update state of an `Attachment` inside a `Message` so it can be upserted with this information. Without the correct exclusing strategy the app breaks with serialization/desarialization expcetion. 
- Comparison screenshots added for visual changes. **no need**

Creating a default gson instance

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/extensions/ClientExtensions.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/extensions/MessageReactionExtensions.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplReactionsTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/utils/TestDataHelper.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt

Motivation:
- `Message.addReaction` in `ClientExtensions` is flawed. For instance, user sends a reaction and `addReaction` method is invoked. In a moment, we receive `reaction.created` event and invoke this method for the second time. As a result, `ownReacitons` contains duplicate entries and counters don't show correct values. Basically this method should "upsert" reactions, which makes its implementation more complex.
- When reaction is sent to the server with `enforce_unique=true` flag, we receive `reaction.updated` event. However, the `enforce_unique=true` flag is not present in the event. Therefore, it is impossible to choose the right strategy to modify reactions of existing message (whether to remove other user reactions or not).
Prerequisites:
According to Mia and Ferhat, messages …

Fix duplicate reactions

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoItem.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/header/MessagesHeaderView.kt

- Change icons tint color on *ChatInfo screens
- Fix title position in MessagesHeaderView when avatar is hidden
| --- | --- |
|<img width="321" alt="Screenshot 2021-01-29 at 14 44 29" src="https://user-images.githubusercontent.com/17440581/106283849-ba6cfb00-6242-11eb-9ffc-2b2c624bf86c.png">|<img width="329" alt="Screenshot 2021-01-29 at 14 56 45" src="https://user-images.githubusercontent.com/17440581/106283856-bb9e2800-6242-11eb-82dd-fc15b3264274.png">|

Fix colors and positions on ChatInfo screen

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/overview/MediaAttachmentGridView.kt
stream-chat-android-ui-components/src/main/res/values/attrs.xml

Fix name of styleable to match name of custom view

Fix name of MediaAttachmentGridView styleable

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/SendMessagesTest.kt

[CAS-245](https://stream-io.atlassian.net/browse/CAS-245)
Fixing crash in the progress attachment. If the `uploadState` for the `attachments` if set after the `getMessageType`, it doesn't become ephemeral and then it can't be canceled. 
-  ~Changelog updated with client-facing changes~
-  ~New code is covered by unit tests~

[CAS-245] Adding InProgress as status before view type is requested

---

stream-chat-android-offline/api/stream-chat-android-offline.api
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDatabase.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/dao/ChannelDao.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/entity/ChannelEntity.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/entity/ChannelEntityPair.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/ChannelRepository.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryFactory.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/RepositoryHelper.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/mapper/ChannelMapper.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/ChatDomainEventDomainImplTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/ExampleBaseDomainTest2.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/Mother.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/RecoveryTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplInsertDomainTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/ChannelRepositoryTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/RepositoryHelperTests.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/BaseRepositoryHelperTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/RepositoryHelperTests.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/WhenEnrichChannel.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/WhenUpdateLastMessage.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/HideChannelImplTest.kt

**Goal:** "Isolate ChannelEntity usage in ChannelDao/ChannelRepository only"
**What done:**
1) Remove usage ChannelEntity from business logic
2) Rewrite ChannelRepository methods in order to use only models
3) Move logic from ChannelEntity to RepositoryHelper
4) Add update methods to DAO 
5) Refactor ChannelEntity structure. Remove unused field `mutedTill`
6) Add several tests to cover new logic in RepositoryHelper

[CAS-552] Channel entity isolation

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/navigation/destinations/AttachmentDestination.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/roundedImageView/PorterImageView.java

GIFs weren't appropriately rendered because `PorterImageView` usage. It turned out that `PorterImageView` renders drawable only if the view needs to be [invalidated](https://github.com/GetStream/stream-chat-android/blob/develop/stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/roundedImageView/PorterImageView.java#L129) (based on `invalidate` flag). The flag is changed to [false](https://github.com/GetStream/stream-chat-android/blob/develop/stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/roundedImageView/PorterImageView.java#L109) when drawable to render is non-null, but the main problem is that the flag can be changed during `onDraw` method invocation (that happens every time when …

Fix showing GIFs

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/SendMessagesTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/SendMessageWithFilesTest.kt

We removed methods that silently and asynchronously (no result or error handling possible) uploaded files and images in https://github.com/GetStream/stream-chat-android/pull/1265
We left out a `sendImage` method in `ChatClient`, which was now calling into a `ChatApi` method that returned a `Call`, essentially making it a no-op. This PR removes that method (merging it with the proper one that also itself returns a `Call`), and updates the changelog to reflect this.

Fix sendImage being a no-op

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/options/message/MessageOptionsView.kt

Making edit message gone when the message is not mine. 
-  ~Changelog updated with client-facing changes~
-  ~New code is covered by unit tests~

Hiding edit message for theirs

---

stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat_info_shared_media.xml

The toolbar in this screen to darker then it should.
| --- | --- | 
| ![Screenshot_20210204-093752](https://user-images.githubusercontent.com/10619102/106894274-7f007f80-66cd-11eb-845e-249c2e50c764.png) | ![Screenshot_20210204-093545](https://user-images.githubusercontent.com/10619102/106894294-858ef700-66cd-11eb-86d4-a727753a942b.png) | 

Fixing toolbar colour for Photos & VIdeos screen

---

stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat_info_shared_groups.xml

Fixing the toolbar colour for Shared Groups.
| --- | --- | 
| ![Screenshot_20210204-095528](https://user-images.githubusercontent.com/10619102/106895648-41045b00-66cf-11eb-804a-56d57f762a6f.png) | ![Screenshot_20210204-095406](https://user-images.githubusercontent.com/10619102/106895681-4792d280-66cf-11eb-8015-3174ff1c4774.png) | 
- ~changelog updated with client-facing changes~

Fixing toolbar colour for shared groups

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Events.java
stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Events.kt

Minor updates to the Events docs + a surprise bugfix for a `ChannelClient#subscribeForSingle` method which was recursively calling itself in an infinite loop instead of calling into `ChatClient`.

Update Events docs snippets

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/service/sync/OfflineSyncFirebaseMessagingService.kt

~1. Don't connect to the socket when doing bg data sync API call~
_This is not possible at the moment without modifying LLC API client. Added task to allow setting user without opening WS connection https://stream-io.atlassian.net/browse/CAS-681_
2. Fix storing the bg sync data. Previously, data was persisted before the user was set into `ChatClient` resulting in missing userToken value. Now we are waiting for the first event which is emitted after user is connected to WS, we persist sync config and unsubscribe the listener to make sure it's not invoked on every event.

[CAS-672] Push sync service fixes

---

stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/HiddenMessageListItemFilter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/view/MessageListView.kt

[CAS-658](https://stream-io.atlassian.net/browse/CAS-658)
Suggestion for the `MessageListItemFilter`. A predicate looks better than a method with `(MessageList) -> MessageList`, where any transformation can be applied in the list. 
It also simplies the use, instead of:
```
messageListView.setMessageListItemFilter { messageList ->
messageList.filter { messageListItem ->
// Filter logic here
true
}
}
```
We can have:
```
messageListView.setMessageListItemFilter { messageItem ->
// Boolean logic here
true
}
```

Message list filter

---

stream-chat-android-ui-components/src/main/res/layout/stream_ui_dialog_media_attachment.xml

[CAS-642](https://stream-io.atlassian.net/browse/CAS-642)
Part of the last row of `MediaAttachmentDialogFragment` was cropped. Removing `ConstraintLayout` fixes the issue. Items in the grid are recycled on scroll as expected. 
| --- | --- |
| ![device-2021-02-09-115419](https://user-images.githubusercontent.com/9600921/107340719-22d39c00-6acf-11eb-9bec-776db76d15c0.png)| ![device-2021-02-09-115317](https://user-images.githubusercontent.com/9600921/107340741-2bc46d80-6acf-11eb-8710-b98f98af39d3.png)|

[CAS-642] Fix cropped MediaAttachmentDialogFragment

---

scripts/publish-mavencentral.gradle

Some of our modules (`ui-common`, `ui-components`) use `src/main/kotlin` instead of `src/main/java`, and for these, we've been shipping empty `sources.jar` artifacts so far, because only the `src/main/java` folder's contents were included in those. This PR fixes that.

Add kotlin source folder to sources jar configuration

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/adapter/viewholder/decorator/ReactionsDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/reactions/user/UserReactionsView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/messages/reactions/view/ViewReactionsView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/UiUtils.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Message.kt

According to https://getstream.slack.com/archives/G01DU3XSWM7/p1609507461260100 it was agreed that reaction type names should be aligned across all platforms, and the names are:
```
{
Icon: LoveReaction,
type: 'love',
},
{
Icon: ThumbsUpReaction,
type: 'like',
},
{
Icon: ThumbsDownReaction,
type: 'sad',
},
{
Icon: LOLReaction,
type: 'haha',
},
{
Icon: WutReaction,
type: 'wow',
},
```
Also, some extra effort to filter out unsupported reactions, to prevent such corner cases as on the screenshots below (mixed supported/unsupported reactions, reaction bubble offset was calculated incorrectly):
| --- | --- |
| ![device-2021-02-09-191725](https://user-images.githubusercontent.com/9600921/107394052-7fa17780-6b0c-11eb-8670-3ed907398510.png) | …

Align reaction type names with other sdks

---

UNRELEASED_CHANGELOG.md
stream-chat-android/api/stream-chat-android.api
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/ChannelViewHolderFactory.java
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/channels/ChannelListViewStyle.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/channels/ChannelsView.kt
stream-chat-android/src/main/res/drawable/stream_ic_channel_divider.xml
stream-chat-android/src/main/res/layout/stream_item_channel.xml

Bugfix for #1371 
Parses the attribute into `ChannelListViewStyle`, and then overrides the default divider drawable with the custom value if it's present.
| No attr | Custom attr - Stream logo |
| --- | --- |
| ![Screenshot_20210210_115713](https://user-images.githubusercontent.com/12054216/107501641-f899e100-6b97-11eb-8c7a-07ed72e9872f.png) | ![Screenshot_20210210_115644](https://user-images.githubusercontent.com/12054216/107501651-fafc3b00-6b97-11eb-8cb0-7ff33241bd30.png) |

Use channel separator attribute in ChannelListViewStyle

---

UNRELEASED_CHANGELOG.md
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/channels/ChannelListViewStyle.kt

Bugfix for #1370 
Uses the `streamLastMessageDateUnreadTextColor` for colouring unread message dates instead of the regular attribute's value.
| --- | --- |
|![Screenshot_20210210_121639](https://user-images.githubusercontent.com/12054216/107503622-77901900-6b9a-11eb-8628-c9ddf680f5ea.png) | ![Screenshot_20210210_121610](https://user-images.githubusercontent.com/12054216/107503615-765eec00-6b9a-11eb-8fd0-22528f8781a4.png) |

Fix streamLastMessageDateUnreadTextColor not being used

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Channel.kt

Shadow banned uses are unable to observe their sent messages. When shadow banned user tries to send a message, it disappears as soon as it is delivered to the server.
According to the docs
```
Shadow Ban
Users can be shadow banned from an app entirely or from a channel. When a user is shadow banned, it will still be allowed to post messages, but any message sent during, will have shadowed: true field. However, this will be invisible from the author of the message.
```
Therefore modified some conditions so that:
- Shadow banned users are able see their sent messages on the chat screen
- Shadow banned users are able to observe their last sent message on the channel list screen
Other users still:
- Don't see messages from shadow banned users on the chat screen
- Don't see last sent message …

Fix sending messages with shadow ban

---

stream-chat-android-ui-components/src/main/res/layout/stream_ui_typing_indicator_view.xml

Removed unnecessary background from typing indicator view
| --- | --- |
| ![device-2021-02-11-150821](https://user-images.githubusercontent.com/9600921/107634856-40456900-6c7b-11eb-8a1c-fc7887d67ae1.png) | ![device-2021-02-11-150739](https://user-images.githubusercontent.com/9600921/107634874-45a2b380-6c7b-11eb-81c3-77a1c39106f5.png)|

Fix typing indicator in dark mode

---

stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_item_foreground_view.xml

When the timestamp is hidden in `ChannelListView`, the end constraint of the unread badge got invalid and it fell back to no margin being added. Constrained the badge to the end of the parent instead.
| --- | --- |
| ![Screenshot_20210215_165242](https://user-images.githubusercontent.com/12054216/107968450-ae0cd000-6fae-11eb-98b5-0e63f63f5a13.png) | ![Screenshot_20210215_165259](https://user-images.githubusercontent.com/12054216/107968447-ac430c80-6fae-11eb-86b2-fc4bfd0f9b8c.png)|

Fix end margin of unread badge when timestamp is missing

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/Chat.kt

The following `val client = ChatClient.Builder(apiKey, context).build()` creates a logger internally with `ChatLogLevel.ALL` level. Changing the default log level to `ChatLogLevel.NOTHING`

Do not show logs by default

---

UNRELEASED_CHANGELOG.md
stream-chat-android/api/stream-chat-android.api
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/MessageListViewStyle.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/dialog/MessageMoreActionDialog.kt
stream-chat-android/src/main/res/layout/stream_dialog_message_moreaction.xml
stream-chat-android/src/main/res/values/attrs.xml
stream-chat-android/src/main/res/values/colors.xml
stream-chat-android/src/main/res/values/dimens.xml
stream-chat-android/src/main/res/values/styles.xml

Add attributes that allow configuring  action buttons text style and icon tint in message action view
| --- | --- |
closes #1406

[CAS-711] Add attributes for configuring text style and icon tint in message actions view

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/BaseMessageListHeaderViewModel.kt

activeThread LiveData should be immutable, otherwise calling `messageListHeaderViewModel.setActiveThread()` from Java shows following error:
_Ambiguous method call. Both
setActiveThread
(LiveData<Message>)
in BaseMessageListHeaderViewModel and
setActiveThread
(Message)
in BaseMessageListHeaderViewModel match_

Make activeThread LiveData immutable

---

stream-chat-android-ui-components/src/main/res/layout/stream_ui_media_attachment_view.xml

Fix `MoreCountLabel` color for dark theme

[CAS-725] Fix `MoreCountLabel` color for dark theme

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/BaseMessageListHeaderViewModel.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt

Introduce `BaseMessageListHeaderViewModel::resetThread`method to match thread handling in MessageInputView. Make `BaseMessageListHeaderViewModel::setActiveThread` message parameter non-nullable

Introduce BaseMessageListHeaderViewModel::resetThread to make it consistent with thread handling in MessageInputViewModel

---

stream-chat-android-ui-components/src/main/res/drawable/stream_ui_base_channel_list_item.xml
stream-chat-android-ui-components/src/main/res/drawable/stream_ui_foreground_channel_list.xml
stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_item_foreground_view.xml

https://stream-io.atlassian.net/browse/CAS-726
Fix transparent channel item background on API 21
API 21 / API 22 / API 29
https://user-images.githubusercontent.com/9600921/108197703-cc4c0a80-712b-11eb-8e49-5b4880e2d187.mov

[CAS-726] Fix channel item background on API 21

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt

[CAS-695](https://stream-io.atlassian.net/browse/CAS-695)
Clearing the intent after the navigation happened. 
It is necessary to clear this intent otherwise the app always go back to the chat when trying to navigate back. The intent is still there and it keeps sending the user back to the chat. 

[CAS-695] Navigation from notification

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/CaptureMediaContract.kt

Fix `CaptureMediaContract` chooser on Android API 21
IntentChooser doesn't show anything on Android API 21 if there isn't any intent matching with the intent that is passing to the `createChooser()` method.
To fix it I am getting one intent from the list of valid intent that we already created, and the rest are added to the extras. 
The last Intent is the one chosen because the method `Intent.createChooser()` add the one that receives by param as the last one of the list
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/4047514/108378255-2076ed80-7205-11eb-8515-7c31798c90b5.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/4047514/108378115-02a98 …

[CAS-733] Fix `CaptureMediaContract` chooser on Android API 21

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt

Fix some typos in our deprecation messages

---

stream-chat-android-ui-components-sample/src/main/res/layout/chat_info_shared_groups_item.xml

A small fix for the title in the shared groups list item. 
| Before | After |  
| --- | --- |  
| ![Screenshot_20210219-155116](https://user-images.githubusercontent.com/10619102/108549257-a78e9900-72cb-11eb-9473-9b5c9b4dc5fa.png) | ![Screenshot_20210219-155539](https://user-images.githubusercontent.com/10619102/108549274-aeb5a700-72cb-11eb-801e-58994c2dec48.png) | 

Small fix for channel title in shared channels

---

UNRELEASED_CHANGELOG.md
stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/FileAttachmentSelectedAdapter.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messageinput/AttachmentsController.kt
stream-chat-android/src/main/res/layout/stream_item_attach_file.xml
stream-chat-android/src/test/java/com/getstream/sdk/chat/view/messageinput/attachments/WhenCancelAttachmentTests.kt

Increase touchable area on the button to remove an attachment
Fixes #1450 
Update logic to remove attachments that depended on the type of files, instead on the adapter where it was added.
| --- | --- |
| ![device-2021-02-22-133230](https://user-images.githubusercontent.com/4047514/108713981-3d6b3380-7519-11eb-8079-ec682fd04955.png) | ![device-2021-02-22-135646](https://user-images.githubusercontent.com/4047514/108714001-46f49b80-7519-11eb-95fb-7c933f31f32a.png)  |
- ~[ ] New code is covered by unit tests

Increase touchable area on the button to remove an attachment

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt

https://stream-io.atlassian.net/browse/CAS-748
Firebase token needs to be registered on the backend after the `ConnectedEvent` is received, after `api::setConnection` is called. Otherwise, the registration call may fail occasionally.

Bugfix cas-748 token registration

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/add/header/AddChannelHeaderView.kt
stream-chat-android-ui-components-sample/src/main/res/layout/add_channel_header_view.xml

This PR fixes the following issues on "Create Channel" screen:
- "Type a name" label top padding when the screen is just opened
- After we type a user name and click on a user in the results list, `EditText` should be cleared so that next user input starts with an empty search term. Also, after user has beed selected, the list should show all available users (and not only users matching the old search term).
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/109504258-69a02a80-7aac-11eb-8f15-d6918aa69f2a.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/109504281-6f960b80-7aac-11eb-9567-67f1f9fd3b8b.mov" controls="controls" …

Fix user search on the "Create Channel" screen

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt

[CAS-749](https://stream-io.atlassian.net/browse/CAS-749)
Adding `replyTo` using `replyMessageId` when handling `MessageUpdatedEvent` inside `ChannelControllerImpl`. This avoid that the reply message redraws itself in a wrong way inside a thread.
Before
https://user-images.githubusercontent.com/10619102/109515412-cd632d00-7a85-11eb-832f-5c2757ce78b7.mov
After
https://user-images.githubusercontent.com/10619102/109515196-955bea00-7a85-11eb-9479-0fc1387118cd.mov

[CAS-749] Adding replyTo message inside MessageUpdatedEvent handling

---

UNRELEASED_CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImpl.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImplTest.kt

Fixes #1473 
`QueryChannelsControllerImpl::refreshChannels` wasn't checking if the current user is still a member of the channel. 
I've added an additional check to ensure that we skip channels to which the current user doesn't belong to.

[CAS-751] Fix refreshing channel list after removing member

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt

If `MessageListView` is created with a plain constructor call passing in just a `Context`, i.e. `MessageListView(context)`, we skipped running some of its initialization code parsing attributes. With this code skipped, multiple `lateinit` variables remain uninitialized (`style`, `loadMoreListener`), leading to crashes during usage.
These changes make it so that attribute parsing always runs (no matter now the instance is created), falling back to default if needed.

Fix MessageListView attr parsing

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/User.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Channel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/header/viewmodel/MessageListHeaderViewBinding.kt

[CAS-700](https://stream-io.atlassian.net/browse/CAS-700)
This PR propagates online/offline status of the user in our Message List Header View. This PR doesn't fix the online/offline status in the whole app, more PRs will come to fix the other screens.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/109827134-3c718a80-7c1a-11eb-8dec-50e37890dd51.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/109827287-5a3eef80-7c1a-11eb-98c7-ef994c6047b0.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
_It is hard to see... but take a look at the subtitle of the channel_
- ~[] Changelog updated with client-facing …

[CAS-700] Fix - online status propagation

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoViewModel.kt

[CAS-700](https://stream-io.atlassian.net/browse/CAS-700)
This PR creates the propagation of the online/offline status in the chat info screen.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/109856915-d2b4a900-7c38-11eb-9ecb-c9a8f5f52f7e.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/109856962-e06a2e80-7c38-11eb-9871-3386edafd1b4.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
- ~[] Changelog updated with client-facing changes~

[CAS-700] Fix - Propagating online status in chat info

---

stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Messages.java
stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Messages.kt
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/attachment/AttachmentViewFactory.kt

Changes the parameter from `View` to `ViewGroup` to better represent what it is + match similar APIs like RecyclerView.

Update parameter type of createAttachmentView

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt

[CAS-582](https://stream-io.atlassian.net/browse/CAS-582)
MessageHelper should not be constructor inside the constructor of `ChannelControllerImpl`, it binds both logic together and makes impossible to unit tests one class without the other. It makes tests for message update impossible to mock. 

[CAS-582] Refactor - Moving message helper to constructor

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt

Fixes uppercase property names in two events.

Fix channelId property names in ChannelDeletedEvents

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/RecoveryTest.kt

Fixes #1497
`ChatDomainImpl.initJob` property was wrongly declared as `lateinit var`. This was causing `UnitializedProperty` crashes.

Make initJob nullable instead of lateinit

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/service/sync/PushMessageSyncHandler.kt

Fixes #1498
1. Set foreground sync service notification channel importance to `NotificationManager.IMPORTANCE_LOW`. This prevents the notification from popping over the app which is currently opened.
2. Stop using deprecated `ChatDomain.Builder` constructor

Make sync notification not pop up over the app

---

stream-chat-android/src/main/java/com/getstream/sdk/chat/adapter/viewholder/message/configurators/IndicatorConfigurator.kt

[CAS-782](https://stream-io.atlassian.net/browse/CAS-782)
Moving the "message sent" icon to correct position
| --- | --- | 
|![Screenshot_20210311-145723](https://user-images.githubusercontent.com/10619102/110832768-7118be00-827a-11eb-8334-bf2c745fa1cb.png)| ![Screenshot_20210311-145649](https://user-images.githubusercontent.com/10619102/110832723-65c59280-827a-11eb-9f3b-92eb358b74b5.png) | 

[CAS-782] Fix - Fixing sent icon

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/StringExtensions.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/GroupChatInfoFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/member/GroupChatInfoMemberOptionsDialogFragment.kt

[CAS-762](https://stream-io.atlassian.net/browse/CAS-762)
Fixing my last PR... it didn't fix the problem and the option to remove users were still appearing. 
- ~[] Changelog updated with client-facing changes~

[CAS-762] Fix - Fixing errors with anonymous channel

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/GsonChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/ModerationApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Moderation.java
stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Moderation.kt

https://stream-io.atlassian.net/browse/CAS-785
Added `unFlagMessage(messageId)` and `unFlagUser(userId)` methods to `ChatClient`.

[CAS-785] Add unflag message and unflag user methods

---

UNRELEASED_CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/extensions/Message.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/Mother.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/repository/helper/RepositoryFacadeTests.kt

Store all participants of a message into our DB

[CAS-764] Feature/store all participants of a message

---

DEPRECATIONS.md
UNRELEASED_CHANGELOG.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/GsonChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/ModerationApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/controllers/ChannelController.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/UsersApiCallsTests.kt
stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Moderation.java
stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Moderation.kt

- Renamed `unBanUser` to `unbanUser`
- Renamed `unMuteChannel` to `unmuteChannel`
- Renamed `unFlagMessage` to `unflagMessage`
- Renamed `unFlagUser` to `unflagUser`
Note: `unflagMessage` and `unflagUser` were not added to the deprecations file as these methods have not been release yet.

Fix the spelling of unmute, unban and unflag

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChannelsApiCallsTests.kt
stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/Call.kt

```
@Deprecated(
message = "Use the unbanUser(targetId, channelType, channelId) method instead",
replaceWith = ReplaceWith("this.unbanUser(targetId, channelType, channelId)")
)
public fun unBanUser(
targetId: String,
channelType: String,
channelId: String,
): Call<Unit> = api.unbanUser(
targetId = targetId,
channelType = channelType,
channelId = channelId,
shadow = false
).map {
Unit
}
@CheckResult
public fun unbanUser(
targetId: String,
channelType: String,
channelId: String,
): Call<Unit> = api.unbanUser(
targetId = targetId,
channelType = channelType,
channelId = channelId,
shadow = false
).map {
Unit
}
```
The unit test for `ChatClient.unbanUser()` was not working on my machine (works fine on our CI). Lambdas generated from `map { Unit }` class have different names, but on …

Fix NoClassDefFound error when using ChatClient.unbanUser() method

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsView.kt
stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml

https://stream-io.atlassian.net/browse/CAS-796
- Added `streamUiEditMessageEnabled` attribute to `MessageListView` and `MessageListView::setEditMessageEnabled` method to enable/disable the message editing feature.

[CAS-796] Enable/disable the message editing feature

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/navigation/destinations/AttachmentDestination.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/view/activity/AttachmentActivity.kt
stream-chat-android-ui-common/src/main/res/layout/stream_activity_attachment.xml
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt

Support of all attachment types. Previously we supported only images with gallery preview. 
1) Change default attachment click listener
2) Show `AttachmentMediaActivity` for video files. Fix logic in AttachmentDestination
https://user-images.githubusercontent.com/11807573/111455910-a871e980-8716-11eb-8f13-82761edb1589.mov

[CAS-786] Video support to attachment activity

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/SuggestionListController.kt
stream-chat-android-ui-components/src/main/res/values/attrs_message_input_view.xml

https://stream-io.atlassian.net/browse/CAS-795
With our UI, disabling mentions means only disabling mention suggestions. User will still be able to type `@someuser` from his/her keyboard and send such message with a mention.
- Added `streamUiMentionsEnabled` attribute to `MessageInputView`
- Added `MessageInputView::setMentionsEnabled` method

[CAS-795] Enable/disable mentions

---

build.gradle
buildSrc/src/main/kotlin/com/getstream/sdk/chat/Dependencies.kt
stream-chat-android-client/build.gradle
stream-chat-android-offline/build.gradle
stream-chat-android-ui-common/build.gradle
stream-chat-android-ui-components/build.gradle
stream-chat-android/build.gradle

Jacoco pollutes our test logs with numerous exceptions and shows zero test coverage in `jacoco.exec` files. Decided to remove it completely.
```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting io/getstream/chat/android/livedata/usecase/SendMessageWithAttachments$DefaultImpls.
at org.jacoco.agent.rt.internal_f3994fa.CoverageTransformer.transform(CoverageTransformer.java:94)
at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
...
```

Remove Jacoco

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/internal/MessageListItemDecoratorProvider.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/FootnoteDecorator.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/internal/MessageListItemStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/internal/MessageListViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsView.kt
stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml

Add support for thread enable/disable attributes, provide methods for setting it
1) Add flag to message options in order to show/hide the thread option
2) Provide attribute to `MessageListItemStyle` in order to not show thread footnotes in `MessageListView`

[CAS-793] Thread attribute for MessageListView

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/GsonChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/QueryParams.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitAnonymousApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitCdnApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/ChannelApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/DeviceApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/GeneralApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/GuestApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MessageApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/ModerationApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/UserApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/StreamFileUploader.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChannelsApiCallsTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/DevicesApiCallsTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MessageIdGenerationTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MessagesApiCallsTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/UsersApiCallsTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/uploader/StreamFileUploaderTest.kt

https://stream-io.atlassian.net/browse/CAS-747
- Removed `user_id` parameter which is currently sent as in a query with is not required anymore (`user_token` which is sent in the header is actually used by backend).
- Replaced `client_id` parameter with `connection_id`, as `client_id` parameter in deprecated on the backend.
Introduced `api_key` and `connection_id` constants not to make a typo. These two query parameters are used in almost every request, therefore I will move them later to the corresponding interceptor.

[CAS-747] Update REST client to the latest backend specs

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/internal/SimpleChannelListView.kt

Add `ChannelListItemPredicate` to our `channelListView` to allow filter `ChannelListItem` before they are rendered
Fixes #1549 

Add `ChannelListItemPredicate` to our `ChannelListView`

---

DEPRECATIONS.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/usecase/GetTotalUnreadCountImpl.kt

[CAS-769](https://stream-io.atlassian.net/browse/CAS-769)
Deprecated GetTotalUnreadCount.

[CAS-769] Deprecation - Get total unread count impl

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/AttachmentUtils.kt

[CAS-798](https://stream-io.atlassian.net/browse/CAS-798)
Using default icon instead of (unsuccessfully) trying to load the thumbUrl if it is `null`. It is still necessary to understand why we are getting this values as null, but that can be done in another PR. 
| --- | --- | 
| ![Screenshot_20210319-165041](https://user-images.githubusercontent.com/10619102/111835367-a43efb00-88d3-11eb-8f50-98543a7b3c3a.png) | ![Screenshot_20210319-164046](https://user-images.githubusercontent.com/10619102/111835300-8c677700-88d3-11eb-9d77-daec2bcf8c0c.png) | 

[CAS-798] Fix - Default icon for null thumbnail

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/LinkAttachmentView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/attachment/AttachmentViewFactory.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/TextAndAttachmentsViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/internal/MessageListItemStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/internal/MessageListViewStyle.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_link_attachments_view.xml
stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml

[CAS-775](https://stream-io.atlassian.net/browse/CAS-775)
Adding max lines for link description, so we don't have extremely long link descriptions. The max lines can be configured. 
| --- | --- |
| ![Screenshot_20210319-150316](https://user-images.githubusercontent.com/10619102/111824117-88802880-88c4-11eb-867a-ca70eac82a2c.png) | ![Screenshot_20210319-145911](https://user-images.githubusercontent.com/10619102/111824100-8027ed80-88c4-11eb-8d71-228e60754905.png)| 
_It is a nice game, by the way..._

[CAS-775] Fix - Max lines for link description

---

stream-chat-android-docs/build.gradle
stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt

Our docs work with the new UI module, removing the old module as a dependency here to prevent accidental usages of it in the docs.

Remove docs module dependency on old UI module

---

stream-chat-android-ui-components-sample/src/demo/kotlin/io/getstream/chat/ui/sample/application/AppConfig.kt
stream-chat-android-ui-components-sample/src/full/kotlin/io/getstream/chat/ui/sample/application/AppConfig.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/data/user/SampleUser.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/data/user/UserRepository.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/custom_login/CustomLoginViewModel.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/user_login/UserLoginViewModel.kt
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api

Setting a custom user in the sample app didn't save the custom API key, which is one of the custom details provided. Therefore, after restarting the app, reloading a custom user would fail, since we try to log them in with the hardcoded sample API key.
These changes add an `apiKey` property to `SampleUser` and persist/restore it.

Fix restoring custom user in sample app

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/ConfigMapping.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/ConfigDto.kt

Moshi impl bug: this field isn't always present in Channel objects, crashing our serialization logic in some cases

Make channel config blocklist optional

---

stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/ChatUI.kt

Move old ChatUI class to the proper package

Move old ChatUI class to the proper package

---

stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/ChatUI.kt

1. Clean up code
2. Add `replaceWith` param to `@Deprecated`

Clean up chat UI deprecation params

---

UNRELEASED_CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/controller/QueryChannelsController.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImplTest.kt

fixes #1585 
We shouldn't assume that we don't want to display channels in which the current user is not a member - the assumption is correct only for messaging channels.
`refreshChannels` method should be refactored after the channel's filtering is done.

[CAS-808] Fix refreshing not messaging channels which don't contain current user as a member

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/internal/SimpleChannelListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/internal/SimpleVerticalListDivider.kt

https://stream-io.atlassian.net/browse/CAS-810
- Fixed `channelListView.setItemSeparator()` method.
- Left `channelListView::setShouldDrawItemSeparatorOnLastItem` as is as it is not clear what is the expected behavior. We have channel list item `ViewHolder` and loading `ViewHolder`, both of them extend from `BaseChannelListItemViewHolder`. In case of custom `ViewHolders` it is impossible to distinguish them without introducing additional method to `BaseChannelListItemViewHolder` (e.g. `BaseChannelListItemViewHolder::shouldShowDivider`) and forcing clients to override it.

[CAS-810] Fix customization of channel dividers

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/application/ChatInitializer.kt
stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/feature/user_login/UserLoginViewModel.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/user_login/UserLoginViewModel.kt

- Lifecycle observer which is responsible for connecting/disconnecting to/from the WS was never disposed. Disposing it on `ChatClient.disconnect()`.
- We were using the deprecated `ChatDomain.Builder` constructor with user overwrite in our sample app. But we didn't call `ChatDomain.disonnect()` on log out. As a consequence, `ChatDomain` was never disposed. Using the new constructor without user overwrite.
Only one instance of `ChatCllient` and `ChatDomain` exists in memory now. Checked with weak references.

Avoid memory leaks

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputFieldView.kt

`app:streamUiAttachButtonEnabled` attribute is not working when external `SuggestionListView` is not attached. Ensured that controls state is refreshed after initialization.

Fix initial controls state in MessageInputView

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/model/AttachmentMetaData.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputView.kt

closes #1550 
The crash was caused because of the wrong `title`. Unfortunately, we cannot rely on the value returned by `inputContentInfo.description.label` because Samsung keyboard doesn't set the correct value (mime type instead of label).
Replacing that with the last `contentUri`'s path segment and adding default value just in case it's null.

[CAS-789] Fix crash when sending GIF from Samsung keyboard

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/SwipeViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
stream-chat-android-ui-components/src/main/res/values/attrs_channel_list_view.xml

https://stream-io.atlassian.net/browse/CAS-812
Added the possibility to customize the following attributes for `ChannelListView`:
- Option Icon Drawable
- Delete Icon Drawable
- Hide Delete Icon
- Hide Option Icon
- Disable swipe action
- Background color of "background layout"
- TextStyle for channelName
- TextStyle for lastMessage
- TextStyle for Date
- Drawable indicator for sent
- Drawable indicator for read
- Drawable indicator for Pending Sync
- Background color of "foreground layout"
- Background color for “Unread message counter”
- TextStyle for “Unread message counter”
The customization can be done using `TransformStyle` class:
```
TransformStyle.channelListStyleTransformer = StyleTransformer {
it.copy(
optionsIcon = getDrawable(R.drawable.stream_ui_arrow_left_rounded)!!, …
```

[CAS-812] Add missing attributes on ChannelListViewStyle

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-common/src/main/res/values/strings.xml
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/TextStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputFieldView.kt
stream-chat-android-ui-components/src/main/res/values/attrs_message_input_view.xml

[CAS-813](https://stream-io.atlassian.net/browse/CAS-813)
Adding configuration for divider and making TextStyle the default for hint and text input.

[CAS-813] Feature - Divider configuration for message input view

---

stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChannelsApiCallsTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/DevicesApiCallsTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MessageIdGenerationTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MessagesApiCallsTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/UsersApiCallsTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/ChatSocketServiceImplTest.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/DevTokenTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/ChatDomainImplCreateChannelTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/ChatDomainImplReplayEventsForActiveChannelsTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/ChatDomainImplTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplReactionsTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplTypingTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/QueryChannelsControllerImplTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/SendMessageOfflineTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/event/TotalUnreadCountTest.kt
stream-chat-android-test/src/main/java/io/getstream/chat/android/test/TestCoroutineExtension.kt
stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/utils/StartStopBufferTest.kt
stream-chat-android/src/test/java/com/getstream/sdk/chat/view/messageinput/attachments/BaseAttachmentsControllerTests.kt
stream-chat-android/src/test/java/com/getstream/sdk/chat/viewmodel/CreateChannelViewModelTest.kt

https://stream-io.atlassian.net/browse/CAS-827
Since`TestCoroutineExtension` extension implements `BeforeAllCallback` and `AfterAllCallback`, they have to be in static fields instead of instance fields, i.e. it should always be put in the companion object. Otherwise these callbacks are ignored, and it won't mock/reset the dispatchers in `CoroutineDispatchers`.
- Moved all the JUnit extensions to companion objects
- Updated `ChannelsApiCallsTests`, `MessageIdGenerationTests`, `DevicesApiCallsTests`, `MessagesApiCallsTests` `UsersApiCallsTests`, `ClientConnectionTests` to JUnit5 so that they are able to run extensions
- Removed `TestCoroutineExtension` from `MockClientBuilder`. Moved `TestCoroutineExtension` registration to corresponding tests which use `MockClientBuilder`
- Added a check …

[CAS-827] Fix usages of RegisterExtension in unit tests

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/header/ChannelListHeaderView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/TextStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListItemStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/header/MessageListHeaderView.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_command.xml

- Fixed incorrect values passed to the `TextStyle.Build::size()` method
- Ensured that this won't happen again by providing  `@StyleableRes`, `@ColorInt` and `@Px` hints to the compiler
| --- | --- |
| ![photo_2021-03-28 19 39 45](https://user-images.githubusercontent.com/9600921/112759822-63469500-8ffd-11eb-8b5b-ee027dec2ba6.jpeg) | ![photo_2021-03-28 19 39 49](https://user-images.githubusercontent.com/9600921/112759820-60e43b00-8ffd-11eb-9742-85eb6ec170af.jpeg) |
| --- | --- |
| ![photo_2021-03-28 19 39 43](https://user-images.githubusercontent.com/9600921/112759823-63469500-8ffd-11eb-8262-c94b69069807.jpeg) | ![photo_2021-03-28 19 39 46](https://user-images.githubusercontent.com/9600921/112759821-62adfe80-8ffd-11eb-9d49-b01891c06fa4.jpeg) |

Fix mentions and commands text style

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/ChatUI.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarBitmapFactory.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/AvatarFetcher.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/ImageLoaderFactoryInitializer.kt

Our `AvatarFetcher` use a `key` for the cache and it is generated from our `AvatarBitmapFactory` now to allow our customers to implement it by themselves.
The `AvatarBitmapFactory` used now is the one from `ChatUI` and any reference to the singleton one used inside of `AvatarBitmapFactory` has been removed

[CAS-832] Feature/allow custom key cache for avatar bitmap factory

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/ScrollButtonViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/internal/ScrollButtonView.kt
stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml

https://stream-io.atlassian.net/browse/CAS-831
Added the possibility to customize the `TextStyle` of the "Unread count" label of the button. Used the same approach as in `MessageListItemStyle`, but eventually style classes which use builders need to be refactored.
No customization applied
| --- | --- |
| ![photo_2021-03-29 19 07 51](https://user-images.githubusercontent.com/9600921/112866125-1aa4df80-90c2-11eb-9cda-d8cf5192db45.jpeg) | ![photo_2021-03-29 19 07 53](https://user-images.githubusercontent.com/9600921/112866123-1a0c4900-90c2-11eb-85cc-6c1acf766215.jpeg) |
Custom transformer
```
TransformStyle.scrollButtonStyleTransformer = StyleTransformer {
it.copy(
scrollButtonBadgeTextStyle = it.scrollButtonBadgeTextStyle.copy(
style = Typeface.ITALIC,
color = …
```

[CAS-831] Add customization of unread count badge test style

---

stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/ChatErrorTest.kt

[CAS-585](https://stream-io.atlassian.net/browse/CAS-585)
Refactoring `ChatErrorTest`  so it is no longer a integration test. No need to test chatClient with 2 message of the same ID, that test was only testing the API. 

[CAS-585] Feature - Refactor chat error

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/avatarview/ComponentBrowserAvatarViewFragment.kt
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_component_browser_avatar_view.xml
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarView.kt
stream-chat-android-ui-components/src/main/res/values/attrs_avatar_view.xml

https://stream-io.atlassian.net/browse/CAS-830
Allowing to customize avatar's online indicator color.
Added  `AvatarView.streamUiAvatarOnlineIndicatorColor` and `AvatarView.streamUiAvatarOnlineIndicatorBorderColor` xml attrs.

cas-830 custom online indicator colors

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListItemStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/BackgroundDecorator.kt
stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml

Message stroke attributes for color and width

[CAS-836] Message borders attributes

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/internal/ScrollButtonView.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_scroll_button_view.xml

Fix ScrollButtonStyles.
We are using internally Material FAB Button and for some reason, it applies a tint to any Drawable that has been previously tinted, the only way I have found "not to apply this tint" is by adding it as `null` on the xml as suggested [this comment](https://github.com/material-components/material-components-android/issues/1106#issuecomment-764739409)
Now, you can edit the ScrollButtonStyle in runtime by something like:
```
TransformStyle.scrollButtonStyleTransformer = StyleTransformer {
scrollButtonViewStyle ->
scrollButtonViewStyle.copy(
scrollButtonColor = getColor(android.R.color.holo_green_light),
scrollButtonIcon = scrollButtonViewStyle.scrollButtonIcon
?.mutate()?.apply {
DrawableCompat.setTint(this, getColor(android.R.color.holo_red_dark))
}, …
```

Fix ScrollButtonStyles

---

stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/usecase/KeystrokeImplTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/BaseChannelControllerTests.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/WhenHide.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/WhenKeystroke.kt

Rewrite keystroke tests:
1) Rewrite tests for use case (later we can move them to `ChatDomain` when use cases are deprecated)
2) Write tests for `ChannelController::keystroke`
3) Create base class with dependencies for `BaseChannelControllerTests`
4) Refactor `ChannelController::hide` tests rebasing them on the base class

[CAS-594] Keystroke tests

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/header/MessageListHeaderView.kt
stream-chat-android-ui-components/src/main/res/values/attrs_message_list_header_view.xml

[CAS-845](https://stream-io.atlassian.net/browse/CAS-845)
Making a way to change the back button of `MessageListHeaderView`.
Adding the customisation with XML styles. 
Now you can do this: 
I know, right? =D
Change the icon using: `app:streamUiMessageListHeaderBackButtonIcon`
- ~[ ] Affected documentation updated (CMS, cookbooks, tutorial)~~
_Paint it the way you prefer_

[CAS-845] Fix - Customise back button for message list header view

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/header/MessageListHeaderView.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_list_header_view.xml

[CAS-839](https://stream-io.atlassian.net/browse/CAS-839)
Make `MessageListHeaderView` background customisable. Now it is possible to customise the background when declaring the view. using `android:background` field. 
This problem was pointed in this issue: #1656
Now we use <merge> instead of `ConstraintLayout` as the root view of the `StreamUiMessageListHeaderViewBinding` which is correct since `MessageListHeaderView` is already a `ConstraintLayout`
Now you can change the background of the header view:
_Red is probably not a good color for this o.O_
- ~[ ] Affected documentation updated (CMS, cookbooks, tutorial)~~

[CAS-839] Fix - Customise background for message list header view

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/UserMapping.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/UserDtos.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/MoshiChatParser.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/MoshiErrorLogging.kt
stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/MapCall.kt

We currently have no logs when Moshi parsing fails, and in some cases this means they'll fail silently and produce odd behaviour. This PR makes it easier to notice and fix Moshi serialization related problems.
Also fixes a specific problem with `channel_mutes` occasionally being `null` in responses.
The `MoshiConverterFactory` that integrates Moshi parsing with Retrofit is wrapped with a new implementation that delegates to the old one, but logs errors when they happen.

Improve Moshi error logging

---

DEPRECATIONS.md
UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModelBinding.kt

https://stream-io.atlassian.net/browse/CAS-853
Two related GitHub issues: #1658 #1673  
Bugs in how ChannelListView is displaying its empty view.
Our binding code for ChannelListView was handling when the empty view on it should be shown. This didn't take into account the internal filtering that ChannelListView performs with the predicate, and also had a bug where it didn't submit the new list to ChannelListView if it was empty.
Can be tested by setting a predicate that filters out all channels (`{ false }`), or by removing the last channel in a channel list.

[CAS-853] Move empty view handling from binding to ChannelListView

---

UNRELEASED_CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/service/sync/EncryptedBackgroundSyncConfigStore.kt

Some emulators and some Android devices are not able to created an Encrypted Shared Preferences throwing an error that is not handled. On case we are not able to generated an Encrypted Shared Preferences we fallback to a normal Shared Preferences instance

[CAS-846] Create a fallback SharedPreferences in case the Encrypted one is not available

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/header/ChannelListHeaderView.kt

Fix ChannelListHeaderView's title position when user avatar or action button is invisible
Making both views invisible instead of gone
| --- | --- |
|<img width="325" alt="Screenshot 2021-04-06 at 09 51 49" src="https://user-images.githubusercontent.com/17440581/113678001-753fcc00-96be-11eb-8bc7-b541ec991ca9.png">|<img width="325" alt="Screenshot 2021-04-06 at 09 47 36" src="https://user-images.githubusercontent.com/17440581/113677996-73760880-96be-11eb-83ad-29f8e5bd502f.png">|
|<img width="325" alt="Screenshot 2021-04-06 at 09 49 54" src="https://user-images.githubusercontent.com/17440581/113678000-74a73580-96be-11eb-9a17-c49f364e16fc.png">|<img width="325" alt="Screenshot 2021-04-06 at 09 48 21" src="https://user-images.githubusercontent.com/17440581/113677998-74a73580- …

Fix ChannelListHeaderView's title position when user avatar or action button is invisible

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/AndroidManifest.xml
stream-chat-android-ui-components/src/main/res/values/styles.xml

https://stream-io.atlassian.net/browse/CAS-851
Add default themes to all activities of the SDK, which can be overwritten by the client app. Fixes #1661. 
Because we don't set default theme for all activities, it will use the theme from the app tag from the client app manifest. Using the wrong theme can cause runtime problems when using libraries from `com.google.android.material:material` like `BottomSheetDialog`. 
No change. 
1 - Go in the StreamUiAttachmentGalleryActivityStyle and remove the `parent="Theme.Design.Light.NoActionBar"` part
2 - Go to the app and click in some attachment (a picture, for example)
3 - Crash. I'll see that the logs are very similar to the one of #1661 
_Fixed now_

[CAS- 851] Fix - Attachment gallery crash

---

UNRELEASED_CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt

https://stream-io.atlassian.net/browse/CAS-842
This PR fixes the message read indicator in the message list.
Incoming reads from other users were ignored. Ensured that all the incoming reads (including the reads from other users) are propagated via corresponding `StateFlow` field.
GIVEN user_1 is reading a channel
AND user_2 is reading the same channel
WHEN user_1 sends a message
AND user_2 receives the message
THEN user_1 should observe that the message was read (double tick mark)

[CAS-842] Fix read indicator

---

stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Android.java
stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/cookbook/ui/MessageListView.kt
stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputViewStyle.kt

[CAS-817](https://stream-io.atlassian.net/browse/CAS-817)
Documentation for `MessageInputViewStyle` and how to change `MessageInputView` layout programatically.
See https://getstream.io/nessy/docs/chat_docs/android_chat_ux/message_input_view

[CAS-817] Docs - Documenting message input view style

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/StorageHelper.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/AttachmentExtension.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/AttachmentUtils.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/FileAttachmentsView.kt

Fixes odd UI behaviour around file uploads, namely:
- Blank names for files while they're being uploaded
- Failed indicator being displayed for in-progress file uploads (#1689)
- `.pdf.pdf` extension stacking for files with spaces in their names
- In-progress files having no file type icons displayed
Please see commit messages and descriptions for the details of the changes.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/12054216/113725247-69bac800-96f3-11eb-8033-2b30e5d730ee.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/12054216/113730241-01bab080-96f8-11eb-9268-6053194e31fa.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody> …

File upload fixes

---

UNRELEASED_CHANGELOG.md
stream-chat-android-offline/api/stream-chat-android-offline.api
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChannelData.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/database/ChatDatabase.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/domain/channel/ChannelEntity.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/domain/channel/ChannelMapper.kt

Fix filtering channel based on `Channel::team` property.
Filtering wasn't working properly because `Channel::team` was always empty. In [`QueryChannelsController::refreshChannels` ](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/controller/QueryChannelsController.kt#L221) we are creating `Channel` from `ChannelController` which internally uses `ChannelData`. `Team` property was missing in both `ChannelData` and `ChannelEntity` and that's why filtering wasn't working properly (the property was always empty (default value) even if it was present in API response)
1. Add `Filters.eq("team", "someTeam")` filter to `ChannelListViewModelFactory` and ensure that API returns at least one channel
2. …

[CAS-867] Add missing team field to ChannelEntity and ChannelData

---

UNRELEASED_CHANGELOG.md
stream-chat-android-offline/api/stream-chat-android-offline.api
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/member/GroupChatInfoMemberOptionsViewModel.kt

https://stream-io.atlassian.net/browse/CAS-648
Be able to remove members using `ChatDomain`
To be consistent with other use cases, wrapping the call into `ChatDomain` scope. The call will not be interrupted even if user leaves corresponding fragment/activity.
https://user-images.githubusercontent.com/9600921/113755923-8538c980-9719-11eb-9408-f860348db0d1.mov
Given we are on the channel info screen
When user is removed from the channel
Then the user should disappear from the members list

[CAS-648] Implement remove member use case

---

DEPRECATIONS.md
UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/Debouncer.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/viewmodel/MessageInputViewModelBinding.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/SuggestionListController.kt

Read requirements in [Jira task](https://stream-io.atlassian.net/browse/CAS-866?atlOrigin=eyJpIjoiYTEyMGVhNzY1YjZkNDdiMTkzMTY0ZjZlYTk2MDE2YjUiLCJwIjoiaiJ9)
We want to provide an abstract mechanism for the user suggested list in `MessageInputView`. Some customers want to do it using network requests for their live stream channels (such channels usually don't have members).
- Add new `UserLookupHandler` with suspend function to execute lookups
- Deprecate `MessageInputView::setMembers`
UX doesn't get changed
Put delay in `SuggestionListController`, here:
and play a little bit

[CAS-866] Suspend user lookup

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/internal/SimpleChannelListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/SnapToTopDataObserver.kt

Scroll channel list to the top if:
- we are at the top prior to the update
- user is added to a new channel or existing channel is updated and bumped to the top
Custom `RecyclerView.AdapterDataObserver` which automatically scrolls channel list to the top when necessary.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/114022253-42423780-987a-11eb-8de9-f90943fd487a.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/114022266-453d2800-987a-11eb-8146-b588593b3590.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
GIVEN channel list is scrolled to the top
WHEN a message is sent to any channel other that the first …

Automatically scroll channel list to the top

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/HostActivity.kt

https://stream-io.atlassian.net/browse/CAS-857
Ensure that sample app doesn't crash when:
- starting in offline mode
- restarting the app after it was killed
- detecting when the app was killed and restarting from launcher activity
- `lateinit` properties in `MoshiChatApi` can be accessed before they are initialized (e.g. login without network connection and proceed to the chat screen), so assigning default values to them
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/114000611-d48b1100-9863-11eb-816b-606b3f87dc79.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/114000646-d94fc500-9863-11eb-8fa1-3981be8bb63e.mov" …

[CAS-857] Fix crash when recovering from process death

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/AvatarFetcher.kt

https://github.com/GetStream/stream-chat-android/issues/1692 
https://stream-io.atlassian.net/browse/CAS-871
Fix slightly cropped avatars
Ensured that padding of `AvatarView` is not negative
| --- | --- |
| ![Screenshot 2021-04-12 at 01 18 05](https://user-images.githubusercontent.com/9600921/114323236-f834ac80-9b2c-11eb-9939-7c02a42e18ff.png) | ![Screenshot 2021-04-12 at 01 08 24](https://user-images.githubusercontent.com/9600921/114323241-fb2f9d00-9b2c-11eb-8b03-971861e13022.png) |

[CAS-871] Fix cropped avatar

---

stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/TextStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/ScrollButtonViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsDialogFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsView.kt

Refactor xml attributes applying, `MessageOptionsView.Config` and feature flags logic in `MessageListView`
Firstly we want to support dynamic updates of channel::config updates, but currently it isn't supported by BE.
We should correctly define available options in the message options screen. Their availability is logical `AND` between XML attributes and channel config.
1. Remove all UI attributes from `MessageOptionsView.Config` to `MessageListViewStyle`
2. Keep in `MessageOptionsView.Config` only feature flags and create instance only when message options is being shown
3. Add logic of feature flag calculation to operator `MessageOptionsView.Config::invoke`
1. Update dashboard channel config
2. Reload channel
3. Check options are updated accordingly

[CAS-855] Refactor MessageOptionsConfig

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/common/Extensions.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Context.kt

Using Dagger Hilt makes our `getFragmentManager` method fail. In previous versions, the `Context` that Hilt wrapped Activities with used to be a `ContextThemeWrapper`, so we checked for that specifically, but it's now just a `ContextWrapper` (see [here](https://github.com/google/dagger/blob/41c4e04da79b5edc6f4f2dff485f10896cb31849/java/dagger/hilt/android/internal/managers/ViewComponentManager.java#L171)).
Tested by locally publishing with the changes and importing it into a Dagger Hilt app.

Fix Context wrapper handling

---

DEPRECATIONS.md
UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_chat.xml
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/SuggestionListPopupWindow.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/CommandsAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/MentionsAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/SuggestionListController.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/SuggestionListUi.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/list/SuggestionListView.kt

https://stream-io.atlassian.net/browse/CAS-870
Make `SugestionListView` should an internal part of `MessageInputView`.
Displaying suggesting list in `PopupWindow`
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/114547356-0555b680-9c67-11eb-8e29-2c9f34fc96d1.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/114547249-e0614380-9c66-11eb-8749-74321f39b611.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>

[CAS-870] Make suggestion list an internal part of MessageInputView

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt

https://stream-io.atlassian.net/browse/CAS-870
Ensure that popup is hidden when `MessageInputView` becomes detached

[CAS-870] Hide suggestion list when leaving screen

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/SuggestionListController.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/internal/SuggestionListPopupWindow.kt

https://stream-io.atlassian.net/browse/CAS-870
Dismiss suggestions popup on touch outside. Otherwise there can be potential situations when popup is not dismissed. E.g. when using `ViewPager` and the adjacent tab is in "resumed" state.

[CAS-870] Dismiss suggestion list on touch outside

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/viewmodel/MessageInputViewModelBinding.kt

Don't override the UserLookupHandler every time that the members livedata is updated
`DefaultUserLookupHandler` has a mutable property for users that can be updated every time members' livedata is updated but keeping the previous `UserLookupHandler` instance. With this implementation, we keep the previous behavior but allow our customers to use their own implementation without overriding it
Add your custom `UserLookupHandler` implementation just after the binding method is called and your instance should be the one used anytime a mentions suggestion want to be shown

[CAS-872] Hotfix/user lookup handler

---

UNRELEASED_CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt

Fix based on [Github Issue](https://github.com/GetStream/stream-chat-android/issues/1716)
Local cached hidden channels don't get updated even new message was received.
Update `Channel::hidden` to false when receive `NewMessageEvent`, `NotificationMessageNewEvent`
Given two users
1) User1 creates a unique channel with User2
2) User1 hides this channel and clear history
3) User2 sends new message in the channel
4) User1 sees the channel in the list with the new message
5) User1 reads it and returns to the channel list
Channel must be in the list.

[CAS-898] Update hidden flag for a channel if new message is received

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsView.kt

According to the inner discussion, the block user feature should be better specified and supported on BE side. As an immediate action, we should disable it
1. Make `visibility = View.GONE` in the `MessageOptionsView`
2. Do not add this option in the adapter of `ChatInfoFragment`

Disable block user

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/User.kt
stream-chat-android-ui-components/src/main/res/values/strings.xml

Fix incorrect "last seen" text.
We must rely primarily on `lastActive` field for the "last seen" text to be correct. 
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/114744766-b5561d00-9d56-11eb-9e19-9923143a50b1.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/114744795-bc7d2b00-9d56-11eb-897e-23b07a8afc04.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>

Fix last seen text

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/SocketErrorMapping.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser/ChatParser.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/MoshiChatParser.kt

https://stream-io.atlassian.net/browse/CAS-902
When `ChatParser` attempts to deserialize the Gson-based `ErrorResponse` class, it calls into `MoshiChatParser` which can't handle this type.
This PR adds special handling so that Moshi recognizes this query, parses its own `ErrorResponse`, and then converts it into the Gson-based / domain model.
Bonus: added logging to whenever there's a failure in event parsing.
Tested by creating duplicate flag requests for a message, which cause these kinds of errors to be returned by the server.

[CAS-902] Moshi ErrorResponse handling

---

stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/feature/startup/StartupFragment.kt

Making sure that nobody accidentally runs the old sample instead of the new one.
Self-explanatory code.
Open old sample.

Add a warning dialog when opening the old sample app

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/GroupChatInfoFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/GroupChatInfoViewModel.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/member/GroupChatInfoMemberOptionsDialogFragment.kt

[CAS-955](https://stream-io.atlassian.net/browse/CAS-955)
Remove the option to remove users when a member is not an admin of the channel
I added the field `isOwnerOrAdmin` to the `state` of `GroupChatInfoViewModel`
| --- | --- |
| ![Screenshot_20210423-104304](https://user-images.githubusercontent.com/10619102/115880462-249bd300-a421-11eb-8eb2-2bb42d4cd0da.png) | ![Screenshot_20210423-104326](https://user-images.githubusercontent.com/10619102/115880523-341b1c00-a421-11eb-982f-f931552304f7.png) |

[CAS-955] Fix - Only admins or owner can delete users

---

UNRELEASED_CHANGELOG.md
stream-chat-android-offline/api/stream-chat-android-offline.api
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/domain/message/MessageDao.kt

https://stream-io.atlassian.net/browse/CAS-953
Fix offline reaction sync
Room treats `@Insert(onConflict = OnConflictStrategy.REPLACE)` as two separate operations and destroys child constraints. Specifying `deferred = true` doesn't help. Therefore, implemented as "upsert" to keep the existing reactions.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/115870085-6d668280-a447-11eb-8357-869ff9506db9.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/9600921/115869840-21b3d900-a447-11eb-8ea8-0a74adae4d45.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
Steps to reproduce:
-. Open a chat
-. Disable network connection …

[CAS-953] Fix oofline reaction sync

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/QueryChannelsController.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/Mother.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/querychannels/QueryChannelsControllerTest.kt

https://stream-io.atlassian.net/browse/CAS-954
Fix showing new channels.
There might be a case when a channel is not added to `queryChannelsSpec.cids` when `NotificationAddedToChannelEvent` arrives (because it doesn't match filter) but it should be added after receiving `ChannelUpdated` or `ChannelUpdatedByUser` events (because now it matches the filter).
1. Create a new channel based on members
2. Go back to the channel's list view
3. New channel should be visible

[CAS-954] Add refreshing channels after receiving update event

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/builder/RepositoryFacadeBuilder.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/builder/RepositoryFactory.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/repository/domain/user/UserRepository.kt

Create a NoOp RepositoryFacade that is used whenever an user is not set into our `ChatDomain`.
The same RepositoryFacade is used when an user is disconnected to avoid wrong data from another user
The NoOp RepositoryFacade use an InMemory implementation with empty data, with this implementation we don't need null-checking before to use it anymore.
This PR remove the Workaround added on the PR #1767 

[CAS-959] Feature/repository facade null object pattern

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt

Fix _MessageListView_ initialization.
#1767 introduced a _MessageListView_ initialization bug. The view was reinitialized every time when `channelData` changes. This PR fixes it by unsubscribing from `channelData` after receiving the first value.
1. Open a channel
2. Send a message
3. Send a message to this channel from another device
4. Chat shouldn't flash and auto-scroll should be working

Add unsubscribing from channelData when first value is received

---

documentation/docs/client/invites/_category_.json
documentation/docs/client/invites/accepting_invite.md
documentation/docs/client/invites/inviting_user.md
documentation/docs/client/invites/querying_accepted_invites.md
documentation/docs/client/invites/querying_rejected_invites.md
documentation/docs/client/invites/rejecting_invite.md

https://stream-io.atlassian.net/browse/CAS-926
Move `client/invites` cookbook to docusaurus
1. Go to `documentation` folder
3. Check out Client -> Invites section

CAS-926 Move `client/invites` cookbook to docusaurus

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/controller/ChannelControllerImplEventTest.kt
stream-chat-android-test/src/main/java/io/getstream/chat/android/test/Mother.kt

The message looked like it wasn't removed because it wasn't refreshed on the recyclerView. After debuged the DiffUtil I could see it was working fine and at the end I found the issue was taht we were mutating the same `Message` instance and because that the recyclerView didn't get update.
The different methods where a message was updated has been refactored to not mutate the same instance but a copy of it

[CAS-960] Hotfix/delete message

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt

Quickfix: fix attachment button, remove code pushed by mistake
Attachment button should not be inactive

Quickfix: fix attachment button, remove code pushed by mistake

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatViewModel.kt

New offline chat domain converts flow to livedata. But livedata doesn't get any values until it is active (has at least one observer). We used the member live data value inappropriate before, we invoke `LiveData::value` without setting any observer. It leads to null default live data value with new `Flow::asLiveData`.
Fix this issue as observing changes in livedata and setup listener every time when members get changed
1. Open chat group screen
2. Click on users' avatar
Expected behaviour: should open the group chat info screen.

[CAS-965] Fix click listener in the header view

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoViewModel.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/users/GroupChatInfoAddUsersViewModel.kt

In `GroupChatInfoAddUsersViewModel` there was direct invocation of `LiveData::value`. Now it is null by default. 
I added observer for members in VM which is removed `::onCleared`. It receives all updates propagated to this members value
1. Open group chat screen
2. Click on users' avatar
3. Click on add member
Expected behaviour: see the list of possible members
Actual: infinite loader

Fix add users in group chat infinite loader

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/shared/ChatInfoSharedGroupsFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/factory/ChannelListViewModelFactory.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/factory/ChannelsViewModelFactory.kt

Fix filtering channels with empty extra data.
`Filters.ne` doesn't work correctly when `extraData` is null. The issue is already reported to the backend team, but I've updated the filter just to make sure that the channel response contains proper data.
1. Create a channel that matches the filter but has empty extra data
2. Channel should be visible in the lix

Fix filtering channels with empty extra data

---

stream-chat-android-offline/src/test/java/io/getstream/chat/android/livedata/utils/CustomObjectFilteringTest.kt

Stop random PR pipeline failures
Our tests for custom object filters use random values. The ranges in which are generated were incorrect for the lesser-than and greater-than filters.
For example, the greater-than filter generated the expected values in the [-80, 300] range, and the value of the filter in the [-100, -80] range. When some values ended up being -80 and the filter also got the -80 random value, the filter would (correctly) filter out the -80 values present in the expected list. The PR adjusts the upper bound of the filter value to -81 to avoid this in the future.
Screenshot of this failure state:
Verified by running the tests in an endless loop for a while, and no failures happening. Previously a failure would show up every couple seconds.

Fix flaky custom object tests

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/factory/ChannelListViewModelFactory.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/factory/ChannelsViewModelFactory.kt

Fix the filter for hidden and draft channels. Until so far, it was not possible to make those channels appear. Now if the users don't use our default filter and don't ask for hidden and draft channels to be removed, they will appear. 
This will fix the filter problem of issue #1773.
**Important: This may cause some apps to include many channels that they may not want to, although this fixes a wrong behaviour.**
Removing the filter of those channels from `queryChannelsController.channelsState` and adding then in the default filter of `ChannelsViewModel` and `ChannelListViewModel`.
Ask for draft and hidden channels with and without this PR, you will see the difference =P.
- ~[ ] Affected …

Fixing filter for draft and hidden channels

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/factory/ChannelListViewModelFactory.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModel.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/factory/ChannelsViewModelFactory.kt

Fix empty channel list with default filter
Reverting "hidden" field filter condition as it was not working due to:
- "hidden" is a reserved field which is always present and the server can't handle the `Filters.notExists("hidden")` part
- "hidden" field is not present in the query channels response, therefore filtering the results from offline storage failed

Fix channels not displayed

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/BannedUserMapping.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/response/BannedUserResponse.kt

#1864 
Fix `BannedUserResponse` deserialization
1. Ban user
2. Call `queryBannedUser`

Make BannedUserResponse::shadow optional

---

stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/coil/StreamImageLoaderFactory.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/ImageLoaderFactoryInitializer.kt

Stop using a constructor that deprecated. A small change that I saw while reading our code. 
Just adding the context to the constructor of that `ImageDecoderDecoder` 
Just use a image are vefiry that nothing gets broken. 
_Tiny change_

Adding context in constructor for ImageDecoderDecoder

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QuerySort.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Channel.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/querychannels/QueryChannelsSortTest.kt

https://stream-io.atlassian.net/browse/CAS-993
https://getstream.zendesk.com/agent/tickets/11634
Fix channel list sorting
The following screenshots were taken with this query sort:
```
private val sort: QuerySort<Channel> = QuerySort<Channel>()
.desc("has_unread")
.asc("name"),
```
| --- | --- |
| ![photo_2021-05-17 19 02 03](https://user-images.githubusercontent.com/9600921/118520145-772b8f00-b742-11eb-9f25-e4e0ddd06aa8.jpeg) | ![photo_2021-05-17 19 02 06](https://user-images.githubusercontent.com/9600921/118520107-6aa73680-b742-11eb-8859-09e340ffc622.jpeg) |

[CAS-993] Fix channel sorting

---

UNRELEASED_CHANGELOG.md
docusaurus/docs/Android/client/uploading_files.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/GsonChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/FileUploader.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/StreamFileUploader.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/uploader/StreamFileUploaderTest.kt
stream-chat-android-core/api/stream-chat-android-core.api
stream-chat-android-core/src/main/java/io/getstream/chat/android/client/utils/Result.kt
stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/helpers/MyFileUploader.java
stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/helpers/MyFileUploader.kt

https://stream-io.atlassian.net/browse/CAS-975
Allow clients to receive meaningful information about the cause of the failure when calling `ChatClient::sendImage` and `ChatClient::sendFile` methods.
According to the poll in Slack, the solution with `Result` got more votes. Therefore, changed `FileUploader` methods to return `Result` objects instead of nullable strings. 
1. Update `ChannelController` to send every attachment as images (`client.sendImage(channelType, channelId, file)`)
2. Try to upload a file
3. Observe that the `Result` object contains meaningful error (`Result<String> = sendImage(file)`)

[CAS-975] Provide error description if upload fails

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/SnapToTopDataObserver.kt

When the first element was visible the auto-scroll didn't push the list down, making the new updated first element not visible.
Delete the first element visible condition
| --- | --- |
| img | img |
Don't scroll, make a change on a chat, now the chat is visible on the top

Fix auto scroll not pushing if first element was visible

---

scripts/publish-module.gradle

The original publishing script gave me good pom.xml for aar artifacts, but jar ones had no `<dependencies>` blocks. So here's a fix borrowed from Gradle docs.

Fix publishing of jar artifacts

---

DEPRECATIONS.md
UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/avatarview/ComponentBrowserAvatarViewFragment.kt
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_component_browser_avatar_view.xml
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarView.kt
stream-chat-android-ui-components/src/main/res/values/attrs_avatar_view.xml
stream-chat-android-ui-components/src/main/res/values/styles.xml

https://stream-io.atlassian.net/browse/CAS-1021
Allow horizontal alignment of online indicator
Using separate constants for each case: `topLeft`, `topRight`, `bottomLeft` and `bottomRight`. Alternative solution was to use a bit mask for that (e.g. `top|left`), but this approach increases the complexity of handling online indicator alignment programmatically.

[CAS-1021] Allow horizontal alignment of online indicator

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/RepositoryFacade.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/facade/WhenEnrichChannel.kt

Fix displaying messages in the channel
`Channel.messages` and `messageMap` can contain messages with the same id but different data.
We should distinct concatenated list by `Message::id` in order to remove duplicated messages.
1. Send `?!@@$$^^$$` - you should see "Automod blocked your message"
2. Press back and open the channel again
3. You should see the same message

Fix enriching channel with messages

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/ChannelListFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModelBinding.kt

Add default implementation of "leave channel" click listener so that clients have this functionality working out of the box

Add default implementation of leave channel click listener

---

.github/workflows/docusaurus.yml
build.gradle
scripts/merge-dokkasaurus-outputs.sh
stream-chat-android-client/build.gradle
stream-chat-android-offline/build.gradle
stream-chat-android-ui-components/build.gradle

I saw a way to customize the output folder for each dokkasaurus task. This way we don't need an extra script just to move the files to correct place. 
The output folder was added to the configuration of dokka tasks.
run: 
```
./gradlew stream-chat-android-client:dokkaDokkasaurus \
stream-chat-android-offline:dokkaDokkasaurus \
stream-chat-android-ui-components:dokkaDokkasaurus
```
And see where the files were generated. 

Docusaurus - Removing merge script

---

UNRELEASED_CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/attachment/AttachmentUploader.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputFieldView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/viewmodel/MessageInputViewModelBinding.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputController.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messageinput/MessageInputView.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/MessageInputViewModelBinding.kt

[CAS-1056](https://stream-io.atlassian.net/browse/CAS-1056)
Fixing mime type for files when they don't have file extension in its name. 
Propagating mime type from AttachmentMetaData instead of throwing it away and then relying in the name to figure out the mime type. Some files may not have the extension in its name, so we can't rely om that (some audio files may be only "track 8" without .mp3 in the end)
Before:
https://user-images.githubusercontent.com/10619102/120698199-12cc3780-c485-11eb-9b57-25e0f5b8bcb3.mov
After: 
https://user-images.githubusercontent.com/10619102/120698417-6a6aa300-c485-11eb-91a6-bded2ad495cd.mov
Upload an audio file without extension in its name.
- ~[ ] Changelog is updated with client-facing changes todo~
- ~[ ] …

[CAS-1056] Fix - Mime type fix

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt

#1943 
Fix crash when the push notification is received or token is updated and `ChatClient` is not initialized yet
Replaced `require` (which throws `IllegalArgumentException`) with `check` (which throws `IllegalStateException`)
1. Check that app doesn't crash after opening for the first time
2. Check that app doesn't crash after receiving push notification without initialized ChatClient

Fix thrown exception type while checking if ChatClient is initialized

---

docusaurus/docs/Android/01-basics/02-dependencies.md
docusaurus/docs/Android/01-basics/03-initializing-sdk.md
docusaurus/docs/Android/02-client/01-users.md
docusaurus/docs/Android/02-client/02-channels.md
docusaurus/docs/Android/02-client/03-messages.md
docusaurus/docs/Android/02-client/05-moderation-tools.md
docusaurus/docs/Android/02-client/06-push-notifications.md
docusaurus/docs/Android/03-ui/02-global-styling.md
docusaurus/docs/Android/03-ui/04-components/01-channel-list.md
docusaurus/docs/Android/03-ui/04-components/06-mention-list-view.md
docusaurus/docs/Android/03-ui/04-components/07-search-view.md
docusaurus/docs/Android/04-guides/01-building-channel-list-screen.md
docusaurus/docs/Android/04-guides/02-building-message-list-screen.md
docusaurus/docs/Android/04-guides/03-custom-message-input.md

https://stream-io.atlassian.net/browse/CAS-1073
Use Docusaurus admonitions https://docusaurus.io/docs/next/markdown-features/admonitions
| --- | --- |
| ![Screenshot 2021-06-11 at 16 24 28](https://user-images.githubusercontent.com/9600921/121693174-8c8da200-cad1-11eb-935e-2ee5946e8c2f.png) | <img width="1041" alt="Screenshot 2021-06-11 at 16 19 36" src="https://user-images.githubusercontent.com/9600921/121692891-3b7dae00-cad1-11eb-86a7-74bf92e2412b.png"> |
`npx stream-chat-docusaurus -i -s `

[CAS-1073] Use Docusaurus admonitions

---

stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/CaptureMediaContract.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/StreamFileProvider.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/StreamFileUtil.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/model/AttachmentMetaData.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/AttachmentUtils.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt

Simplify our FileProvider class to hopefully make Samsung happy
Removes the companion object, leaving just an empty subclass of `FileProvider`.

Remove companion from StreamFileProvider

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/actions/internal/ChannelActionsDialogFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelActionsDialogViewStyle.kt
stream-chat-android-ui-components/src/main/res/layout/stream_ui_fragment_channel_actions.xml
stream-chat-android-ui-components/src/main/res/values/attrs_channel_actions_dialog.xml

#1935 
Add possibility to configure `ChannelActionsDialogFragment` background
| --- | --- |
|<img width="271" alt="Screenshot 2021-06-14 at 13 12 17" src="https://user-images.githubusercontent.com/17440581/121907868-9d2d5a80-cd13-11eb-9575-59a591d35b77.png">|<img width="273" alt="Screenshot 2021-06-14 at 13 16 48" src="https://user-images.githubusercontent.com/17440581/121907897-a3233b80-cd13-11eb-8948-0d16da21a95d.png">|

[CAS-1075] Add possibility to configure channel actions background

---

.github/workflows/docusaurus.yml

Add the possibility to run docusaurus workflow manually so we don't need to do nasty hacks to push docs to staging without making a release.
Added `workflow_dispatch` as described [here](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#configuring-a-workflow-to-run-manually)

Add possibility to run docusaurus workflow manually

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/build.gradle
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputFieldView.kt

https://stream-io.atlassian.net/browse/CAS-1090
Hide suggestion list popup when keyboard is hidden
Currently, the popup window is dismissed 
- When the user makes a touch outside
- When the anchor view is detached from the view hierarchy
But there are certain cases when this is not enough. Therefore, hiding the popup window when a keyboard is hidden. As the last resort, this PR makes it possible to hide the suggestion list popup manually with the help of `MessageInputView::hideSuggestionList` method.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/9600921/122950342-0bfa5b80-d385-11eb-8a93-b6dd494b9758.mov" controls="controls" muted="muted" />
</td>
<td>
<video …

[CAS-1090] Hide suggestion list popup when keyboard is hidden

---

stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/add/AddChannelViewModel.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/add/group/select_name/AddGroupChannelSelectNameViewModel.kt

Prevent cases when current user isn't initialized yet in ChatDoman when VM got initialized
User current user in the point of logic, do not cache it

Do not cache current user as a class field in VM

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt

Fix the attachment sending in the background.
Removing the filter for only `InProgress` attachments. It is possible that the attachment is sent, but the message still wasn't sent. This is the case of this bug, the attachments were send by out Worker, but the message is not sent yet.
Case 1  - 
Send the attachment without internet.
Enabled the internet
Check that the message it sent.
Case 2 - 
Send the attachment without internet.
Close and kill the app
Enabled the internet
Come back to the app and the same channel.
Check that the message it sent.

Fix - Stop filtering messages with sent attachments

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/attachment/UploadAttachmentsAndroidWorker.kt

Avoid the creation of a second Worker if the attachments for a certain message are being uploaded already
Enqueueing a unique a unique worker instead of simply enqueueing a worker. 
Use the attachments upload feature
- ~[] Changelog is updated with client-facing changes~

Unique worker for attachment upload

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/GsonChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/PartialUpdateUsersRequest.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/UserApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/UserDtos.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/PartialUpdateUsersRequest.kt

https://stream-io.atlassian.net/browse/CAS-1113
Add possibility for partial user updates
Added `ChatClient::partialUserUpdate`.
NOTE: You can only partially update `currentUser` using client-side API.
Try to partially update a user.

[CAS-1113] Add ChatClient::partialUserUpdate for partial user updates

---

stream-chat-android-ui-components/src/main/res/values/styles.xml

[CAS-991](https://stream-io.atlassian.net/browse/CAS-991)
Add all the styles to the default one so the SDK doesn't crash if a style is not overridden. 
Delete the themes from sample app and check that nothing crashes.

[CAS-991] Fix - Adding all styles to default one

---

.github/workflows/publish.yml
scripts/publish-module.gradle
scripts/publish-root.gradle

Simplify publishing setup.
Eliminate the need for creating a separate file in CI to contain the GPG key, use an in-memory key instead.
⚠ Our GitHub CI secrets need to be updated:
- We can remove `SIGNING_SECRET_KEY_RING_FILE ` 
- We can remove `GPG_KEY_CONTENTS ` and have to add `SIGNING_KEY ` instead that contains the base64 encoded key contents (can be generated with `gpg --armor --export-secret-keys GPGKEYID | base64`)
Merge this and then create a release 😉
... or run `publishReleasePublicationToMavenLocal` locally with values set up in `local.properties`.

Use in memory GPG key for signing artifacts

---

UNRELEASED_CHANGELOG.md
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/MessageListView.kt

Scroll listener in the old MessageListView produces an exception related to index out of bound.
Use lastIndex instead of List::size

Fix crash in old MessageListView::onScrolled

---

UNRELEASED_CHANGELOG.md
stream-chat-android/api/stream-chat-android.api
stream-chat-android/src/main/java/com/getstream/sdk/chat/view/MessageListView.kt

Some of our customers would like to reuse `AttachmentViewFactory` manually.  `AttachmentViewFactory::createAttachmentView` requires `MessageListItemStyle` as an argument. But `MessageListView` doesn't have public method/field for that
1. Make style nullable
2. Expose it via `requireStyle()`

Expose MessageListViewStyle

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/header/MessageListHeaderView.kt

Fix title/subtitle alignment
Follow-up on https://github.com/GetStream/stream-chat-android/pull/1731
Set the view to invisible instead of gone (same as when it's hidden via attributes).
| --- | --- |
| ![Screenshot_20210712-194502](https://user-images.githubusercontent.com/12054216/125333263-5189c300-e34a-11eb-9200-5c5bfb57ff54.jpg) | ![Screenshot_20210712-194608](https://user-images.githubusercontent.com/12054216/125333262-50f12c80-e34a-11eb-8432-1156e92747b0.jpg) |
Call `hideAvatar` on a message list header.

Fix header alignment when MessageListHeaderView avatar is hidden

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/ChannelExtension.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Channel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Channel.kt

Remove Channel::isMuted extension
We are using `Channel::isMuted` and updating it locally for channels displayed in `ChannelListView`, so it doesn't work well for other channels (for example returned by `chatClient.queryChannels`).
It can be misleading, so I moved the property to ui module and made it internal

Remove Channel::isMuted extension

---

stream-chat-android-ui-components-sample/src/main/res/layout/fragment_home.xml
stream-chat-android-ui-components-sample/src/main/res/layout/fragment_mentions.xml
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/header/ChannelListHeaderView.kt

Removing the application of explicit style from some views so the global style is applied.
Change the theme and check is gets applied, even thought it is not added to the view.
- ~[] Changelog is updated with client-facing changes~

Removing style from some views and letting the global style be applied

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components-sample/src/main/res/values-v23/themes.xml
stream-chat-android-ui-components-sample/src/main/res/values-v29/themes.xml
stream-chat-android-ui-components-sample/src/main/res/values/themes.xml
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelActionsDialogViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/header/ChannelListHeaderView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/header/MessageListHeaderViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchInputViewStyle.kt
stream-chat-android-ui-components/src/main/res/values/styles.xml

https://stream-io.atlassian.net/browse/CAS-1127
Fix crash caused by missing `streamUiReplyAvatarStyle`
- Removed overriding default styles in the sample app (except for `streamUiChannelActionsDialogStyle ` that is needed) so we can discover such bugs faster
- Added default `streamUiReplyAvatarStyle`
- Removed redundant default styles from `StreamUiTheme `. They are applied when we are obtaining attributes (for example: `            context.obtainStyledAttributes(
attrs,
R.styleable.MessageListHeaderView,
R.attr.streamUiMessageListHeaderStyle,
R.style.StreamUi_MessageListHeader,
)`), so there is no need to have them doubled. `AvatarView` is an exception - none of them has the default style
Play with the app and check everything works fine

[CAS-1127] Add missing default streamUiReplyAvatarStyle

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsView.kt

https://stream-io.atlassian.net/browse/CAS-1124
Hide the copy option on messages only containing attachments or gifs.
| --- | --- |
| ![Screenshot_1626683648](https://user-images.githubusercontent.com/12054216/126129319-cdfa7377-ebf5-4619-9939-99d551528438.png) | ![Screenshot_1626683559](https://user-images.githubusercontent.com/12054216/126129323-75adb7bd-88be-4149-8e9f-b579daf4f7ca.png)|
Send messages with attachments only. Open message options dialog.

[CAS-1124] Only show Copy Message option if the message contains text

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/res/values/styles.xml

Fixed crash caused by missing `streamUiMessageOptionsAvatarStyle `
1. Got to channel fragment -> open reactions view
2. Go to mentions view

Fix crash caused by missing streamUiMessageOptionsAvatarStyle

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/internal/SimpleChannelListView.kt
stream-chat-android-ui-components/src/main/res/values/attrs_channel_list_view.xml

https://stream-io.atlassian.net/browse/CAS-1121
Add possibility to configure ChannelListView's edge effect color
Added attribute and nullable `edgeEffectColor` property to `ChannelListViewStyle`. By default (when `edgeEffectColor` is null), `ChannelListView` applies `android.R.attr.colorEdgeEffect` as edge effect color.
Try to apply custom `edgeEffectColor`

[CAS-1121] Add possibility to configure ChannelListView's edge effect color

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/Filters.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/shared/ChatInfoSharedGroupsFragment.kt

Fix "operator $ne is not supported for custom fields" error when querying channels in new apps
$ne operator shouldn't be used for custom fields and it was deprecated in new apps.

Replace ne operator with eq for custom fields filtering

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/Channel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Channel.kt

Simplify getting the channel's last message. 
I've made `Channel::getLastMessage` extension function public so it can be reused in custom view holders.

Make Channel::getLastMessage public

---

stream-chat-android-ui-components/src/main/res/values/attrs_message_list_header_view.xml

To keep similar attributes together for better clarity.

Move streamUiMessageListHeaderBackButtonIcon attribute next to other back button related attrs

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.kt

https://stream-io.atlassian.net/browse/CAS-1148
Fix adding typing item to message list
We were comparing the wrong `typingUsers` list
1. Add custom typing indicator view holder
2. It should be visible when someone is typing in the channel

[CAS-1148] Fix adding typing item to message list

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListItemStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/internal/MessageListItemDecoratorProvider.kt

We need to remove redundant doubling of the same flag

[CAS-1125] Remove MessageListItemStyle::reactionsEnabled

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/MediaAttachmentViewStyle.kt
stream-chat-android-ui-components/src/main/res/values/styles.xml

https://stream-io.atlassian.net/browse/CAS-1038
Review the theme attribute `streamUiMessageListMediaAttachmentStyle` which is used to customize the appearance of `MediaAttachmentView`.
The corresponding theme attribute and the style were already present. Just minor changes.
Override `streamUiMessageListMediaAttachmentStyle` theme attribute:
```xml
<style name="StreamTheme" parent="@style/StreamUiTheme">
...
<item name="streamUiMessageListMediaAttachmentStyle">@style/MediaAttachmentTheme</item>
</style>
<style name="MediaAttachmentTheme" parent="StreamUi.MessageList.MediaAttachment">
...
<item name="streamUiMediaAttachmentMoreCountTextColor">@color/stream_ui_accent_red</item>
</style>
```

[CAS-1038] Review theme attribute to customize MediaAttachmentView

---

docusaurus/docs/Android/03-ui/05-guides/04-custom-translations.md

https://stream-io.atlassian.net/browse/CAS-1137
Create a guide showing how to provide SDK strings localization.
1. Run docs:`npx stream-chat-docusaurus -i -s` 
2. Explore `/chat/docs/sdk/android/ui/guides/custom-translations/` page
[![Joe tries hard speaking french](https://img.youtube.com/vi/kujMmdwGPoo/0.jpg)](https://youtu.be/kujMmdwGPoo)

CAS-1137 [docs] Strings localization guide

---

docusaurus/docs/Android/01-basics/02-dependencies.md

Doesn't really follow convention, but it's an important small update.
Changed the docusaurus dependency to point to compose i/o ui components.

Updated dependencies for the documentation

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt

Fix the position of the default view of empty state for ChannelListView. 
I just added the `LayoutParams` =].
| --- | --- |
| ![Screenshot_20210804-114409](https://user-images.githubusercontent.com/10619102/128202573-f4b224e5-4586-4e34-b559-44253fd33911.png) | ![Screenshot_20210804-114046](https://user-images.githubusercontent.com/10619102/128202469-fb94d478-1d5c-455b-8599-c21a60d82b3b.png) |
Much better, right? =]
Comment this: 
```
val emptyView = layoutInflater.inflate(
R.layout.channels_empty_view,
view,
false,
)
emptyView.findViewById<TextView>(R.id.startChatButton).setOnClickListener {
requireActivity().findNavController(R.id.hostFragmentContainer)
.navigateSafely(HomeFragmentDirections.actionHomeFragmentToAddChannelFragment())
}
setEmptyStateView(emptyView, …
```

Fixing position of default empty view

---

stream-chat-android-ui-components/src/main/res/values-night/colors.xml
stream-chat-android-ui-components/src/main/res/values/colors.xml
stream-chat-android-ui-components/src/main/res/values/styles.xml

https://stream-io.atlassian.net/browse/CAS-1159
To have correct UI as per the mockups
Added correct colors for message reply as mentioned in the mockups 
| --- | --- |
| <img width="400" src="https://user-images.githubusercontent.com/13432025/128317726-94125436-b1d9-488b-854d-b9b476f9cb71.png"/> | <img width="400" src="https://user-images.githubusercontent.com/13432025/128317775-e4ab9f8c-3593-4a9c-935f-009b9ff785e8.png"/> |
| <img width="400" src="https://user-images.githubusercontent.com/13432025/128318246-efa83003-3d05-43eb-8636-f45e6d68cf82.png" /> | <img width="400" src="https://user-images.githubusercontent.com/13432025/128318258-df081a40-15d0-4c80-a65a-2468424b0013.png" /> |

[CAS-1159] Use correct color for message reply background

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/RecyclerView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/AttachmentUtils.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/BaseMessageItemViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/internal/MessageListItemAdapter.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/FileAttachmentsView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/TextAndAttachmentsViewHolder.kt

[Issue on github](https://github.com/GetStream/stream-chat-android/issues/1936)
Fix memory leaks when using `FileAttachmentsView`
We called `VH::unbind` when `Adapter::onViewRecycled`, but when whole `RecyclerView` was detached from window we didn't get this invocation. So Idea is calling callback for VHs when recycler is detached
1. Add dependency of canary leak
2. Go to `ChatFragment`
3. Upload heavy files (e.g. video)
4. Go back to `ChannelList` immediately

[CAS-1136] Fix FileAttachmentsView memory leaks

---

stream-chat-android-client/src/main/res/values-fr/strings.xml
stream-chat-android-ui-common/src/main/res/values-fr/strings.xml
stream-chat-android-ui-components/src/main/res/values-fr/strings_attachment_gallery.xml
stream-chat-android-ui-components/src/main/res/values-fr/strings_channel_list.xml
stream-chat-android-ui-components/src/main/res/values-fr/strings_channel_list_header.xml
stream-chat-android-ui-components/src/main/res/values-fr/strings_common.xml
stream-chat-android-ui-components/src/main/res/values-fr/strings_mention_list.xml
stream-chat-android-ui-components/src/main/res/values-fr/strings_message_input.xml
stream-chat-android-ui-components/src/main/res/values-fr/strings_message_list.xml
stream-chat-android-ui-components/src/main/res/values-fr/strings_message_list_header.xml
stream-chat-android-ui-components/src/main/res/values-fr/strings_search.xml

https://stream-io.atlassian.net/browse/CAS-1170
Add French translations
Added French translations based on Flutter SDK and Google Translate.
You can find English strings here:
- [Client](https://github.com/GetStream/stream-chat-android/blob/develop/stream-chat-android-client/src/main/res/values/strings.xml)
- [Common](https://github.com/GetStream/stream-chat-android/blob/develop/stream-chat-android-ui-common/src/main/res/values/strings.xml)
- [UI Components](https://github.com/GetStream/stream-chat-android/tree/develop/stream-chat-android-ui-components/src/main/res/values)

[CAS-1170] Add support for French

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/ChatFragment.kt
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/DeletedMessageListItemPredicate.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/internal/HiddenMessageListItemPredicate.kt

https://stream-io.atlassian.net/browse/CAS-1117
Allow customization of deleted `MessageListItem.MessageItem` visibility. 
1. It should be possible to choose from predefined parameters
2. By default deleted `MessageListItem.MessageItem` should be visible for everyone. This is how other SDKs behave so we needed to change this for consistency (breaking change).
3. It should be possible to define a custom condition for the visibility of the deleted `MessageListItem.MessageItem`
* `MessageListView::setDeletedMessageListItemPredicate` is introduced, by default set to `DeletedMessageListItemPredicate.VisibleToEveryone`
* `MessageListView` filters messages which are deleted based on the `MessageListView.deletedMessageListItemPredicate` property inside `MessageListView::handleNewWrapper` method.
* …

CAS-1117 Deleted message visibility customization

---

jitpack.yml

Fix Jitpack compilation.
We don't officially deploy our artifacts by this server, but sometimes we ask our customers to use a concreted version from a commit, and it is the easier way to provide it, so keep it working would help them
Some stuff have been updated on our SDK and Jitpack didn't use them.
As an example the JDK version or the configuration to sign the artifact.
All of that has been configured on the `jitpack.yml` file that is loaded by jitpack before the compilation is done.
You can check build result [here](https://jitpack.io/com/github/getStream/stream-chat-android/c133dd0b35/build.log)
- ~[ ] Affected documentation updated …

Configure jitpack with JDK11

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/list/SuggestionListView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/list/SuggestionListViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/list/adapter/SuggestionListItemViewHolderFactory.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/list/adapter/viewholder/internal/CommandViewHolder.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/list/adapter/viewholder/internal/MentionViewHolder.kt

https://stream-io.atlassian.net/browse/CAS-1195
Fix setting SuggestionListView's style when using it as a standalone component
`SuggestionListViewStyle` resolves attributes based on `MessageInputView` attrs. That's why `SuggestionListViewStyle` was nullable and set only when we were creating it inside `MessageInputView`.
I've changed that and created a `default` style during view initialization that allows overriding different attributes either by using `suggestionListViewTheme` or `suggestionListStyleTransformer `
1. Create a sample that uses `SuggestionListView` as a standalone components
2. Override `suggestionListViewTheme` and check if the style is applied

[CAS-1195] Fix setting SuggestionListView's style when using it as a standalone component

---

stream-chat-android-compose-sample/build.gradle
stream-chat-android-ui-components-sample/build.gradle
stream-chat-android/build.gradle

Disable missing translation inspection for sample apps not to get annoying warnings in the IDE.

Disable missing translation inspection for sample apps

---

stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/style/ChatFontsImpl.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/style/ChatFontsImpl.kt

Fix #2171 
Remove usage of SparseArray into our `ChatFontsImpl`, the benefits are only involved on the memory efficiency, but it is almost despicable compared with a `HashMap`, and this one is faster
https://developer.android.com/reference/android/util/SparseArray.html

[CAS-1189] Use Map instead of SparseArray for fonts

---

docusaurus/docs/Android/04-compose/02-general-customization/02-attachment-factory.md
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/PlainTextMessagesComponentBrowserFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/PlainTextWithFileAttachmentsMessagesComponentBrowserFragment.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/component_browser/messages/viewholder/PlainTextWithMediaAttachmentsMessagesComponentBrowserFragment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Attachment.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/navigation/destinations/AttachmentDestination.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/LinkAttachmentView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/MediaAttachmentView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/MessageReplyView.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/navigation/destinations/AttachmentDestination.kt

This reverts commit 8fa897245bdcbb3da4e1143192cf96ec218399ba, reversing
changes made to 61660c6373af901ef5d0529077093ebd859e3a23.
Fix Giphy
Giphy attachments don't work with this change
Try to send Giphy

Revert "Merge pull request #2168 from GetStream/refac/CAS-1164/TitleLinkInsteadOfOgUrl

---

UNRELEASED_CHANGELOG.md
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageList.kt

Fixes #2221 
We had missed consuming `loading` and `empty` composable view's from the `MessageList`  into the inner child components, this MR fixes it.
- [ x Affected documentation updated (docusaurus, tutorial, CMS (task created))

2221 - Added missing MessageList loading and empty views from public API

---

UNRELEASED_CHANGELOG.md
buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
stream-chat-android-ui-common/src/main/AndroidManifest.xml

Update to Targect SDK Version 30 and check that all our integrations with the new version keep working
Android 11 [added some new rules](https://developer.android.com/training/package-visibility/use-cases) to improve user privacy and if you want to query about apps installed into the device, you need to declare the query into your manifest, in other case you will get an empty list of get an exception when you query is run 
You will need to use a device/emulator running Android 11
-. Try to send pictures
-. Try to send Videos
-. Try to send files
-. Try to take a picture
-. Try to record a Video
-. Try to share an attachment
-. Try to open a file
-. Try to open a link
- ~[ ] Affected …

[CAS-1154] [CAS-1183] Use target version 30

---

UNRELEASED_CHANGELOG.md
docusaurus/docs/Android/02-client/02-channels.md
docusaurus/docs/Android/02-client/05-moderation-tools.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/GsonChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/MuteChannelRequest.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/MuteUserRequest.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/ChannelMuteMapping.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/MuteMapping.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/DownstreamChannelMuteDto.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/MuteDtos.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/MuteChannelRequest.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/requests/MuteUserRequest.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/ChannelMute.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Mute.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChannelsApiCallsTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/UsersApiCallsTests.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/UserDtoTestData.kt
stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Channels.kt
stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Moderation.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/utils/TestDataHelper.kt

https://stream-io.atlassian.net/browse/CAS-1224
Add an option to mute channel with timeout:
https://getstream.io/chat/docs/react/moderation/?language=javascript#mutes
- Added the `expiration` parameter to `ChatClient::muteChannel`, `ChannelClient:mute` methods
- Added the `timeout` parameter to `ChatClient::muteUser`, `ChannelClient:mute::muteUser` methods
Notes:
- `expiration` is in milliseconds, `timeout` is in minutes
- leaving suspicious `muteCurrentUser` method as is

[CAS-1224] Muting a channel with timeout

---

stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/header/VersionPrefixHeader.kt
stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChannelActivity.kt
stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatApp.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/ChatUIInitializer.kt
stream-chat-android/src/main/java/com/getstream/sdk/chat/ChatUI.kt

Closes #2223.
We need a way to track if our customers use the Compose SDK or the core SDK to keep tabs on how many people use which SDK.
Exposed the `VERSION_PREFIX` property as public, but `@InternalStreamChatApi`. Also added an enum that describes which version headers we support.
Internally, we don't allow for header changes to values that we don't support - using `Delegates.vetoable()`.
We can test it by tracking out headers and using the Compose SDK. We should have the `X-Stream-Client` show up as `stream-chat-compose-4.16.0`

2223 - Added SDK-specific version header

---

.github/workflows/pr-checks.yml
settings.gradle

Add Gradle Remote Build Cache to improve buil-time on our PR pipeline
We are using a [custom implementation](https://github.com/burrunan/gradle-s3-build-cache) of Remote Build Cache that uses an AWS S3 Bucket to store the cache. The access to it should be really fast and it needs less maintaining

[CAS-1233] Configure S3 Build Cache

---

docusaurus/docs/Android/03-ui/03-chatui.md
docusaurus/docs/Android/03-ui/04-components/03-message-list.md

https://stream-io.atlassian.net/browse/CAS-1210
If the user sets `autolink` property on textview, android internal implementation of Linkify removes markdown link URLSpan. So it should be specified in the docs to not use the autolink property. 
- [] Changelog is updated with client-facing changes

[CAS-1210] Add doc note about autolink property in case of markdown text

---

stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/BaseMessageListHeaderViewModel.kt

Remove warnings when clients use the `setActiveThread` and `resetThread` methods of this ViewModel via its subclasses.
Moving the warning to the constructor will still show the warning if someone attempts to create their own subclass of the base ViewModel.

Move internal annotation to ViewModel constructor

---

DEPRECATIONS.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/StringExtensions.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomain.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt

Deprecate ChatDomain::removeMembers and use ChatClient::removeMembers directly
Some additional clean ups for unused private and internal methods
Useful extension `String::cidToTypeAndId(): Pair<String, String>` is provided
- ~~[ ] New code is covered by unit tests~~
- ~~[ ] Comparison screenshots added for visual changes~~
- ~~[ ] Affected documentation updated (docusaurus, tutorial, CMS (task created))~~

[CAS-1262] Deprecate ChatDomain::removeMembers

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/UserStateService.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/clientstate/UserStateServiceTests.kt

Fix for invalid state. We believe that an event of `userUpated` may arrive after a logout happens in our app, so that state would be UserNotSet. 
- ~[ ] PR targets the `develop` branch~. No it targets `main`, which is what is needed for a hotfix.

Staying when user is updated, but is not set

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/ChannelExtension.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/ChatNotificationHandler.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/ChannelUtils.kt
stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/Channel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarBitmapFactory.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/avatar/AvatarView.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/Channel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Channel.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/AvatarFetcher.kt

https://stream-io.atlassian.net/browse/CAS-1213
Fix notifications' grouping
Grouping wasn't working fine when `contentTitle` (== `Channel.name`) was empty
| --- | --- |
|<img width="322" alt="Screenshot 2021-09-03 at 15 31 50" src="https://user-images.githubusercontent.com/17440581/132184139-feec1974-4f3e-4f16-90db-1de0cdc4416b.png">|<img width="322" alt="Screenshot 2021-09-03 at 15 30 24" src="https://user-images.githubusercontent.com/17440581/132184131-8f1ca061-cdb2-4590-84b1-8f3424f716b4.png">|
Check push notifications in 1-1 conversation

[CAS-1213] Fix setting notification's contentTitle when a Channel doesn't have the name

---

docusaurus/docs/Android/04-compose/02-general-customization/02-attachment-factory.mdx
stream-chat-android-compose/api/stream-chat-android-compose.api
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/StreamAttachmentFactories.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/FileAttachmentFactory.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/GiphyAttachmentFactory.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/ImageAttachmentFactory.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/LinkAttachmentFactory.kt

Add a workaround for weird compiler crashes related to AttachmentFactory subclasses.
Run the Compose app. Shouldn't crash on launch.

Use factory functions instead of subclasses for AttachmentFactories

---

UNRELEASED_CHANGELOG.md
stream-chat-android-ui-common/build.gradle
stream-chat-android-ui-common/src/main/AndroidManifest.xml

Fix theme break for `AttachmentDocumentActivity`
Adding a theme for `AttachmentDocumentActivity` in manifest file.
Open `AttachmentDocumentActivity` and check that it does not break anymore. 

Fixing theme for AttachmentDocumentActivity

---

UNRELEASED_CHANGELOG.md
stream-chat-android-compose/api/stream-chat-android-compose.api
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/StreamAttachmentFactories.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/FileAttachmentContent.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/FileUploadContent.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/ImageAttachmentContent.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/FileAttachmentFactory.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/UploadAttachmentFactory.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/AttachmentsUtils.kt

Fixes #2339 
Built a new factory that takes responsibility of uploading attachments. Added an AttachmentUtils check for uploading attachments.
Changed the way we find File attachments.
Attachments should work like before, upload attachments should still work fine even though it's using another factory.
~~- [ ] Affected documentation updated (docusaurus, tutorial, CMS (task created))~~ Will update with the tutorial.

[Compose] - Add UploadAttachmentFactory to list of factories we provide

---

UNRELEASED_CHANGELOG.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/MessageMapping.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/MessageDtos.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/MessageDtoTestData.kt

https://stream-io.atlassian.net/browse/CAS-1319
An authenticated user is able to send a message using the code snippet below without encountering the `SendMessage failed with error: "message.user.id is a required field"` error:
```kotlin
ChatClient.instance().channel(cid).sendMessage(
Message(text = "message text")).enqueue {
// handle message sending result
}
}
```
According to this [PR](https://github.com/GetStream/stream-chat-android/commit/f205cc04e57ba8a9acb0202896c025650544319f#diff-fc111330781f084c311d0475a0e328674c11f27ac633ae684ca46fe573f8806c), user was not sent with message object. 
```kotlin
@IgnoreSerialisation
var user: User = User()
```
Therefore, removing it from the upstream message DTO.
The list of affected methods which should be tested:
- `ChatClient::sendMessage`
- …

[CAS-1319] Fix sending messages via ChatClient::sendMessage

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MessageApi.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt

https://getstream.slack.com/archives/CE5N802GP/p1632075397158100
Fix soft message delete
The following error is returned from the backend when trying to delete a message with `hard=false`:
```json
{
"code":4,
"message":"DeleteMessage failed with error: \"false is an invalid value for the hard parameter. please specify either true or 1\"",
"StatusCode":400,
"duration":"0.00ms",
"more_info":"https://getstream.io/chat/docs/api_errors_response"
}
```
Therefore, omitting the parameter if it is false.

Fix soft delete

---

CHANGELOG.md
docusaurus/docs/Android/02-client/06-guides/02-sending-custom-attachments.mdx
docusaurus/sidebars-android.js
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Attachment.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/MessageSendingService.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/attachment/AttachmentUploader.kt

Fix the problem where attachments with no files to upload get stuck forever without syncing to the backend.
Check whether an attachment has a file to upload (based on its `upload` property), and mark it synced immediately if there's no upload required.
Here's test code for non-file attachments (can be added in `ChatFragment`):
```kotlin
// Call in some listener
val attachment = Attachment(
type = "location",
extraData = mutableMapOf(
"lat" to 111.1111,
"lon" to -105.280184,
),
)
val message = Message(
cid = args.cid,
text = "Look at this attachment!",
attachments = mutableListOf(attachment),
)
ChatDomain.instance().sendMessage(message).enqueue()
// Call on the MessageList
setAttachmentViewFactory(object:AttachmentViewFactory() {
override fun createAttachmentView(
data: …
```

Handle attachments with and without files separately

---

.github/workflows/no-response.yml

Add script for closing issues without response
Added a Github action for closing issues marked with `waiting for response` label that didn't receive any response from the author for at least 7 days.
If the original author comes back and gives more information, the label is removed and the issue is reopened, if necessary

Add script for closing issues without response

---

CHANGELOG.md
DEPRECATIONS.md
stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/TypedArray.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListItemStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/view/ViewReactionsViewStyle.kt
stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/reactions/view/internal/ViewReactionsBubbleDrawer.kt
stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml
stream-chat-android-ui-components/src/main/res/values/attrs_view_reactions_view.xml

https://stream-io.atlassian.net/browse/CAS-1333
[CAS-1333] Add missing border-related attributes to `ViewReactionsView`
- Added `bubbleBorderColorMine`, `bubbleBorderColorTheirs`, `bubbleBorderWidthMine`, `bubbleBorderWidthTheirs` attributes
- Deprecated `bubbleBorderColor`
- Fixed small bubble size when border is applied
| --- | --- |
|<img width="320" alt="before_3" src="https://user-images.githubusercontent.com/17440581/134505771-f3408961-736b-41ba-8fc5-22ed7ea67a89.png">|<img width="320" alt="after_3" src="https://user-images.githubusercontent.com/17440581/134505758-e9b24552-6711-4f19-a108-32816aa347a1.png">
|<img width="320" alt="before_1" src="https://user-images.githubusercontent.com/17440581/134505763-c2bc65f2-7c42-42cc-98e4-c0b1f32935 …

[CAS-1333] Add missing border related attributes to ViewReactionsView

---

stream-chat-android-compose/api/stream-chat-android-compose.api
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/common/MessageBubble.kt

Make the border removable from a `MessageBubble` without modifying it at the theme level.

Add a border parameter to MessageBubble

---

CHANGELOG.md
stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/MessagesActivity.kt
stream-chat-android-compose/api/stream-chat-android-compose.api
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessagesViewModelFactory.kt

Fixes #2395 
We wanted to improve the experience when creating Messages screen ViewModels.
Made most of the parameters optional by supplying default arguments. Removed the `ClipboardManager` as a parameter and created it internally

[Compose] - Improve MessagesViewModelFactory constructor

---

CHANGELOG.md
DEPRECATIONS.md
stream-chat-android-client/api/stream-chat-android-client.api
stream-chat-android-client/src/debug/java/io/getstream/chat/android/client/di/ChatModule.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatClientConfig.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
stream-chat-android-client/src/release/java/io/getstream/chat/android/client/di/ChatModule.kt

[CAS-1310](https://stream-io.atlassian.net/browse/CAS-1310)
Add a custom interceptor for our API calls. This way a customer can choose to log the API calls the way he/she prefers. 
Adding a `Interceptor` for the builder of `ChatClient`. If a customer sets him/her own interceptor, it substitutes our `HttpLoggingInterceptor` to avoid two interceptors for loggin.
Use a different logging interceptor and check if it works for you.

[CAS-1310] Adding custom api call logger interceptor

---

CHANGELOG.md
stream-chat-android-compose/api/stream-chat-android-compose.api
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/messages/attachments/AttachmentState.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/StreamAttachmentFactories.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/FileAttachmentContent.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/FileUploadContent.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/GiphyAttachmentContent.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/ImageAttachmentContent.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/LinkAttachmentContent.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/MessageAttachmentsContent.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/FileAttachmentFactory.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/GiphyAttachmentFactory.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/ImageAttachmentFactory.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/LinkAttachmentFactory.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/UploadAttachmentFactory.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/components/MessageInput.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/overlay/SelectedMessageOverlay.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageComposerViewModel.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt

Fixes #2237.
Also covers more general improvements that we planned around attachments.
We wanted to make the Attachments API as easy and intuitive to use, so we removed multiple instances where attachments required extra structure or weren't exposing parameters/properties in a way that suits Composable functions.
We also had to fix bugs with editing messages, where the user would be able to "add/remove" attachments from a given message, which ultimately is not yet supported in our API.
- Removed integrations when the user is editing messages
- Fixed a bug where editing a message with attachments causes it to lose attachments
- Improved various smaller parts of AttachmentsState and AttachmentFactory API
| --- | --- |
| …

[Compose] - Overall Attachments API improvements and cleanup

---

CHANGELOG.md
DEPRECATIONS.md
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt

Make `ChatClient.Builder` methods more obvious.
More info on `cdnUrl` deprecation: [Slack discussion](https://getstream.slack.com/archives/CE5N802GP/p1633338690250200)

 Add Kdocs on `ChatClient.Builder` methods, deprecate `cdnUrl`

---

stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/message/input/mention/DefaultUserLookupHandlerTest.kt

Fix a flaky test
The test was looking for just a single result out of the [expected, random, random] array of users. However, the random-generated usernames occasionally match our search query...
For example, with `Leandro` being the expected user result for `Le`, a random generated `UWIyFTQ3HtKrLemsciqp` also matches, and breaks the test.
```
org.amshove.kluent.internal.ComparisonFailedException: Expected: 
<[User(id=5WDFBH3U4tA3uh19c6uG, role=cLxBqLSePLUMWHjFAMl9, invisible=true, banned=false, devices=[], online=true, createdAt=Sat Jul 24 16:37:24 UTC 161846962, updatedAt=Thu Apr 09 00:23:46 UTC 85880809, lastActive=Thu Nov 16 07:21:54 UTC 105965284, totalUnreadCount=2110445997, unreadChannels=137497568, mutes=[], teams=[], channelMutes=[], extraData={name=Leandro})]>
but was: …
```

Fix flaky random data generation in username test

---

.github/workflows/build-and-test.yml

`github.head_ref` only works on PRs, but if we want to use it into a no PR Workflow, we need to use `github.ref` instead
- ~[ ] PR targets the `develop` branch~

Fix `cancel-in-progress` option

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventHandlerImpl.kt

This pr makes an improvement for the query channels flow when recovery happens.
It fixes two cases:
1) We don't make recovery after logout-login
2) We do a recovery with the same sort that injected in `QueryChannelsController`

Fix recovery flow for query channels request

---

stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/attachment/AttachmentUploader.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/usecase/SendMessage.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/SendMessageOfflineTest.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/WhenSendMessage.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/attachment/AttachmentUploaderTests.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/message/attachment/UploadAttachmentsWorkerTest.kt

Follow-up to https://github.com/GetStream/stream-chat-android/commit/1a31426dae24b8b8c0d2800a879798792060ca08 originally added in https://github.com/GetStream/stream-chat-android/pull/2260
Removes internal methods that were only being used in code removed in the commit above.

Clean up remains of removed attachmentTransformer API

---

CHANGELOG.md
stream-chat-android-ui-components/src/main/res/values-ko/strings_message_list.xml

Improved Korean translation related to the flagging.

Improve Korean translation related to the flagging

---

CHANGELOG.md
stream-chat-android-compose/api/stream-chat-android-compose.api
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/info/ChannelInfo.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/ChannelUtils.kt

Fix the conditions under which the "leave group" and "delete conversation" channel actions are displayed.

[Compose] Fix the display of channel options in the ChannelInfo component

---

CHANGELOG.md
stream-chat-android-offline/api/stream-chat-android-offline.api
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt

https://stream-io.atlassian.net/browse/CAS-1296
The goal is to make it easy to request members without the need for ChatDomain for end users.
Added an extension function `ChatClient::requestMembers`.

[CAS-1296] Add extension requestMembers in ChatClient

---

stream-chat-android-offline/api/stream-chat-android-offline.api
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/MessageDao.kt
stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/integration/MessageRepositoryTest.kt

https://stream-io.atlassian.net/browse/CAS-1443
#2580 
Fix SqliteException when selecting/inserting more than 999 messages
Add chunking messages before making SQL queries
- Run tests
- Check if messages are loading correctly
- Check if attachments are uploaded correctly

[CAS-1443] Fix SqliteException when selecting/inserting more than 999 messages

---

CHANGELOG.md
docusaurus/docs/Android/04-compose/06-utility-components/03-search-input.mdx
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channel/ChannelListViewModel.kt

https://github.com/GetStream/stream-chat-android/issues/2582
Implement channels search by either channel name (for named channels) or member name (for distinct channels).
There is no easy way to check if the channel is distinct. As a workaround, I treat distinct channels as channels without name (which is not always the case).
```json
{
"$or":[
{
"$and":[
{
"member.user.name":{
"$autocomplete":"Leandro"
}
},
{
"name":{
"$exists":false
}
}
]
},
{
"name":{
"$autocomplete":"Leandro"
}
}
]
}
```
https://user-images.githubusercontent.com/9600921/140742358-aeb94efa-6f32-46ff-b585-4d9fd21b1b09.mov

[Compose] - 2582 - Implement search channels by name and participants

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/internal/toggle/ToggleService.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/internal/toggle/dialog/ToggleAdapter.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/logic/ChannelLogic.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/state/ChannelMutableState.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/state/ChannelState.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/OfflinePlugin.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/querychannels/logic/QueryChannelsLogic.kt
stream-chat-android-ui-common/build.gradle
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
stream-chat-android-ui-components-sample/src/debug/kotlin/io/getstream/chat/ui/sample/application/ApplicationConfigurator.kt

#2530 introduced new approach to init `ChannelState`. This PR adopts it in `MessageListViewModel`
1. Add toggle for `OfflinePlugin`. Which is `false` by default and `true` in debug version of the sample app
2. Init `LiveData`s of `MessageListViewModel` by OfflinePlugin and it's `ChannelState`
Run sample app and be sure you don't have changed experience of the chat screen

MessageListViewModel initialization using OfflinePlugin

---

CHANGELOG.md
stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Android.java
stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt
stream-chat-android-offline/api/stream-chat-android-offline.api
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomain.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/Config.kt
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/OfflinePlugin.kt

https://stream-io.atlassian.net/browse/CAS-1303
The goal of this PR is to make `retryPolicy` immutable and that should be set only with the Builder.
All mutable vars of `retryPolicy` are converted into `val`. A new function `retryPolicy()` is added to Builders to customize the retry policy while creating ChatDomain instance.

[CAS-1303] Make retryPolicy immutable and set via Builder

---

stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/internal/toggle/ToggleService.kt
stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt

Avoid NPE when SDK users don't init ToggleService
Init by default in ChatClient.Builder

Init ToggleService by default in ChatClient.Builder

---

CHANGELOG.md
stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt

https://stream-io.atlassian.net/browse/CAS-1445
Fix inserting messages with empty cid
Fixed enriching message with cid.
1. Freeze the channel - you can call:
```kotlin
ChatClient.instance().channel(cid).updatePartial(mapOf("frozen" to true)).await()
```
2. Try to send a message - app shouldn't crash
3. Unfreeze the channel - call:
```kotlin
ChatClient.instance().channel(cid).updatePartial(mapOf("frozen" to false)).await()
```

[CAS-1445] Fix inserting messages with empty cid

---

CHANGELOG.md
stream-chat-android-compose/api/stream-chat-android-compose.api
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamColors.kt

https://github.com/GetStream/stream-chat-android/issues/2468
https://github.com/GetStream/stream-chat-android/issues/2500
Add the following props to `StreamColors` to allow granular customization of the message bubble color:
- ownMessagesBackgroundColor
- otherMessagesBackgroundColor
- deletedMessagesBackgroundColor
```kotlin
setContent {
ChatTheme(
colors = StreamColors.defaultColors().copy(
ownMessagesBackground = colorResource(R.color.stream_compose_avatar_gradient_red),
otherMessagesBackground = colorResource(R.color.stream_compose_avatar_gradient_yellow),
deletedMessagesBackgroundColor = colorResource(R.color.stream_compose_avatar_gradient_blue),
)
) {
MessagesScreen(...)
}
}
```

[Compose] - 2468 - Add possibility to customize the message bubble color

---

docusaurus/docs/Android/04-compose/03-channel-components/03-channel-list.mdx
docusaurus/docs/Android/04-compose/03-channel-components/04-default-channel-item.mdx

Fixed docusaurus docs for a removed extension. (I missed this in #2573)
`Channel.getDisplayName()` extension has been replaced to `ChatTheme.channelNameFormatter.format(channel)`.

Fix docusaurus docs for removed extension

---

CHANGELOG.md
stream-chat-android-compose/api/stream-chat-android-compose.api
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/messages/items/MessageItem.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageItem.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamColors.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamDimens.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
stream-chat-android-compose/src/main/res/values-en/strings.xml
stream-chat-android-compose/src/main/res/values-es/strings.xml
stream-chat-android-compose/src/main/res/values-fr/strings.xml
stream-chat-android-compose/src/main/res/values-hi/strings.xml
stream-chat-android-compose/src/main/res/values-it/strings.xml
stream-chat-android-compose/src/main/res/values-ja/strings.xml
stream-chat-android-compose/src/main/res/values-ko/strings.xml
stream-chat-android-compose/src/main/res/values/strings.xml

https://github.com/GetStream/stream-chat-android/issues/2624
Improve thread design
- Added thread separator between parent message and replies
- Improved the footnote text shown in "normal" mode 
- Removed unnecessary thread footnote in "thread" mode
| --- | --- |
| ![photo_2021-11-17 13 37 21](https://user-images.githubusercontent.com/9600921/142185109-3a0cc854-4933-4f16-9690-229cb87e7889.jpeg) | ![photo_2021-11-17 13 37 23](https://user-images.githubusercontent.com/9600921/142185103-448adee7-dc0e-4c64-a58d-2e390375533c.jpeg) |

[Compose] - 2624 - Improve thread design

---

CHANGELOG.md
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channel/info/ChannelInfo.kt
stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/ChannelUtils.kt
stream-chat-android-compose/src/main/res/values-en/strings.xml
stream-chat-android-compose/src/main/res/values-es/strings.xml
stream-chat-android-compose/src/main/res/values-fr/strings.xml
stream-chat-android-compose/src/main/res/values-hi/strings.xml
stream-chat-android-compose/src/main/res/values-it/strings.xml
stream-chat-android-compose/src/main/res/values-ja/strings.xml
stream-chat-android-compose/src/main/res/values-ko/strings.xml
stream-chat-android-compose/src/main/res/values/strings.xml

https://github.com/GetStream/stream-chat-android/issues/2656
We rely on the `Channel.members` field to show the number of members in a channel. Also, we use it to count and display the number online users. But the `Channel.members` is unreliable as it only contains the first 30 members of a channel, that's why we need to find another way.
We need to use `Channel.member_count` and `Channel.watcher_count` fields to display the `MessageListHeader` subtitle.

[Compose] - 2656 - Do not rely on channel members to display message list header subtitle

---

CHANGELOG.md
stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt

https://github.com/GetStream/stream-chat-android/issues/2647
Currently, we only handle incoming typing events. We need also to send typing events from the Compose SDK.

[Compose] - 2647 - Send typing events when the current user is typing
